// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char surfel_trace_ptx[] =
R"PTX_CHUNK(//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__miss__surfel_trace
.const .align 8 .b8 params[352] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 129, 128, 128, 59, 164, 112, 125, 63, 111, 18, 131, 58, 32, 188, 190, 76, 8, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8};

.visible .entry __miss__surfel_trace()
{



	ret;

}
	// .globl	__anyhit__surfel_composite
.visible .entry __anyhit__surfel_composite()
{
	.reg .pred 	%p<50>;
	.reg .f32 	%f<143>;
	.reg .b32 	%r<30>;
	.reg .b64 	%rd<73>;


	// begin inline asm
	call (%r17), _optix_get_launch_index_x, ();
	// end inline asm
	// begin inline asm
	call (%r18), _optix_read_primitive_idx, ();
	// end inline asm
	ld.const.u32 	%r19, [params+72];
	setp.ge.u32 	%p1, %r17, %r19;
	ld.const.u32 	%r20, [params+88];
	setp.ge.u32 	%p2, %r18, %r20;
	or.pred  	%p3, %p1, %p2;
	ld.const.u64 	%rd1, [params+80];
	setp.eq.s64 	%p4, %rd1, 0;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB1_34;
	bra.uni 	$L__BB1_1;

$L__BB1_34:
	// begin inline asm
	call _optix_ignore_intersection, ();
	// end inline asm
	bra.uni 	$L__BB1_35;

$L__BB1_1:
	cvta.to.global.u64 	%rd16, %rd1;
	mul.wide.u32 	%rd17, %r18, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.u32 	%r3, [%rd18];
	cvt.s64.s32 	%rd2, %r3;
	// begin inline asm
	call (%f57), _optix_get_world_ray_origin_x, ();
	// end inline asm
	// begin inline asm
	call (%f58), _optix_get_world_ray_origin_y, ();
	// end inline asm
	// begin inline asm
	call (%f59), _optix_get_world_ray_origin_z, ();
	// end inline asm
	// begin inline asm
	call (%f60), _optix_get_world_ray_direction_x, ();
	// end inline asm
	// begin inline asm
	call (%f61), _optix_get_world_ray_direction_y, ();
	// end inline asm
	// begin inline asm
	call (%f62), _optix_get_world_ray_direction_z, ();
	// end inline asm
	ld.const.u64 	%rd3, [params+56];
	setp.eq.s64 	%p6, %rd3, 0;
	@%p6 bra 	$L__BB1_3;

	cvta.to.global.u64 	%rd19, %rd3;
	mul.wide.u32 	%rd20, %r17, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.f32 	%f137, [%rd21];
	bra.uni 	$L__BB1_4;

$L__BB1_3:
	ld.const.f32 	%f137, [params+236];

$L__BB1_4:
	setp.leu.ftz.f32 	%p7, %f137, 0f00000000;
	@%p7 bra 	$L__BB1_6;

	abs.ftz.f32 	%f63, %f137;
	setp.lt.ftz.f32 	%p8, %f63, 0f7F800000;
	@%p8 bra 	$L__BB1_7;

$L__BB1_6:
	ld.const.f32 	%f137, [params+236];

$L__BB1_7:
	ld.const.u32 	%r21, [params+92];
	setp.le.s32 	%p9, %r21, %r3;
	setp.lt.s32 	%p10, %r3, 0;
	or.pred  	%p11, %p10, %p9;
	@%p11 bra 	$L__BB1_33;

	ld.const.u64 	%rd22, [params+96];
	cvta.to.global.u64 	%rd23, %rd22;
	shl.b64 	%rd24, %rd2, 2;
	add.s64 	%rd25, %rd23, %rd24;
	ld.global.f32 	%f12, [%rd25];
	ld.const.u64 	%rd26, [params+104];
	cvta.to.global.u64 	%rd27, %rd26;
	add.s64 	%rd28, %rd27, %rd24;
	ld.global.f32 	%f13, [%rd28];
	ld.const.u64 	%rd29, [params+112];
	cvta.to.global.u64 	%rd30, %rd29;
	add.s64 	%rd31, %rd30, %rd24;
	ld.global.f32 	%f14, [%rd31];
	ld.const.u64 	%rd32, [params+120];
	cvta.to.global.u64 	%rd33, %rd32;
	add.s64 	%rd34, %rd33, %rd24;
	ld.const.u64 	%rd35, [params+128];
	cvta.to.global.u64 	%rd36, %rd35;
	add.s64 	%rd37, %rd36, %rd24;
	ld.const.u64 	%rd38, [params+136];
	cvta.to.global.u64 	%rd39, %rd38;
	add.s64 	%rd40, %rd39, %rd24;
	ld.const.u64 	%rd41, [params+144];
	cvta.to.global.u64 	%rd42, %rd41;
	add.s64 	%rd43, %rd42, %rd24;
	ld.const.u64 	%rd44, [params+152];
	cvta.to.global.u64 	%rd45, %rd44;
	add.s64 	%rd46, %rd45, %rd24;
	ld.const.u64 	%rd47, [params+160];
	cvta.to.global.u64 	%rd48, %rd47;
	add.s64 	%rd49, %rd48, %rd24;
	ld.global.f32 	%f15, [%rd49];
	ld.global.f32 	%f16, [%rd37];
	mul.ftz.f32 	%f64, %f16, %f15;
	ld.global.f32 	%f17, [%rd46];
	ld.global.f32 	%f18, [%rd40];
	mul.ftz.f32 	%f65, %f18, %f17;
	sub.ftz.f32 	%f19, %f64, %f65;
	ld.global.f32 	%f20, [%rd43];
	mul.ftz.f32 	%f66, %f18, %f20;
	ld.global.f32 	%f21, [%rd34];
	mul.ftz.f32 	%f67, %f21, %f15;
	sub.ftz.f32 	%f22, %f66, %f67;
	mul.ftz.f32 	%f68, %f21, %f17;
	mul.ftz.f32 	%f69, %f16, %f20;
	sub.ftz.f32 	%f23, %f68, %f69;
	mul.ftz.f32 	%f70, %f22, %f22;
	fma.rn.ftz.f32 	%f71, %f19, %f19, %f70;
	fma.rn.ftz.f32 	%f24, %f23, %f23, %f71;
	setp.leu.ftz.f32 	%p12, %f24, 0f24E69595;
	@%p12 bra 	$L__BB1_33;

	rsqrt.approx.ftz.f32 	%f72, %f24;
	mul.ftz.f32 	%f138, %f19, %f72;
	mul.ftz.f32 	%f139, %f22, %f72;
	mul.ftz.f32 	%f140, %f23, %f72;
	ld.const.u32 	%r22, [params+244];
	setp.eq.s32 	%p13, %r22, 0;
	@%p13 bra 	$L__BB1_12;

	mul.ftz.f32 	%f73, %f61, %f139;
	fma.rn.ftz.f32 	%f74, %f60, %f138, %f73;
	fma.rn.ftz.f32 	%f75, %f62, %f140, %f74;
	setp.leu.ftz.f32 	%p14, %f75, 0f00000000;
	@%p14 bra 	$L__BB1_12;

	neg.ftz.f32 	%f140, %f140;
	neg.ftz.f32 	%f139, %f139;
	neg.ftz.f32 	%f138, %f138;

$L__BB1_12:
	mul.ftz.f32 	%f76, %f61, %f139;
	fma.rn.ftz.f32 	%f77, %f60, %f138, %f76;
	fma.rn.ftz.f32 	%f40, %f62, %f140, %f77;
	abs.ftz.f32 	%f78, %f40;
	setp.leu.ftz.f32 	%p15, %f78, 0f322BCC77;
	@%p15 bra 	$L__BB1_33;

	sub.ftz.f32 	%f79, %f12, %f57;
	sub.ftz.f32 	%f80, %f13, %f58;
	mul.ftz.f32 	%f81, %f80, %f139;
	fma.rn.ftz.f32 	%f82, %f79, %f138, %f81;
	sub.ftz.f32 	%f83, %f14, %f59;
	fma.rn.ftz.f32 	%f84, %f83, %f140, %f82;
	div.approx.ftz.f32 	%f41, %f84, %f40;
	abs.ftz.f32 	%f85, %f41;
	setp.geu.ftz.f32 	%p16, %f85, 0f7F800000;
	ld.const.f32 	%f86, [params+232];
	setp.leu.ftz.f32 	%p17, %f41, %f86;
	or.pred  	%p18, %p16, %p17;
	setp.geu.ftz.f32 	%p19, %f41, %f137;
	or.pred  	%p20, %p19, %p18;
	@%p20 bra 	$L__BB1_33;

	fma.rn.ftz.f32 	%f87, %f60, %f41, %f57;
	fma.rn.ftz.f32 	%f88, %f61, %f41, %f58;
	fma.rn.ftz.f32 	%f89, %f62, %f41, %f59;
	sub.ftz.f32 	%f90, %f87, %f12;
	sub.ftz.f32 	%f91, %f88, %f13;
	sub.ftz.f32 	%f92, %f89, %f14;
	mul.ftz.f32 	%f93, %f16, %f16;
	fma.rn.ftz.f32 	%f94, %f21, %f21, %f93;
	fma.rn.ftz.f32 	%f42, %f18, %f18, %f94;
	mul.ftz.f32 	%f95, %f16, %f17;
	fma.rn.ftz.f32 	%f96, %f21, %f20, %f95;
	fma.rn.ftz.f32 	%f43, %f18, %f15, %f96;
	mul.ftz.f32 	%f97, %f17, %f17;
	fma.rn.ftz.f32 	%f98, %f20, %f20, %f97;
	fma.rn.ftz.f32 	%f44, %f15, %f15, %f98;
	mul.ftz.f32 	%f99, %f16, %f91;
	fma.rn.ftz.f32 	%f100, %f21, %f90, %f99;
	fma.rn.ftz.f32 	%f45, %f18, %f92, %f100;
	mul.ftz.f32 	%f101, %f17, %f91;
	fma.rn.ftz.f32 	%f102, %f20, %f90, %f101;
	fma.rn.ftz.f32 	%f46, %f15, %f92, %f102;
	mul.ftz.f32 	%f103, %f42, %f44;
	mul.ftz.f32 	%f104, %f43, %f43;
	sub.ftz.f32 	%f47, %f103, %f104;
	abs.ftz.f32 	%f105, %f47;
	setp.leu.ftz.f32 	%p21, %f105, 0f24E69595;
	@%p21 bra 	$L__BB1_33;

	mul.ftz.f32 	%f107, %f44, %f45;
	mul.ftz.f32 	%f108, %f43, %f46;
	sub.ftz.f32 	%f109, %f107, %f108;
	div.approx.ftz.f32 	%f110, %f109, %f47;
	mul.ftz.f32 	%f111, %f43, %f45;
	mul.ftz.f32 	%f112, %f42, %f46;
	sub.ftz.f32 	%f113, %f112, %f111;
	div.approx.ftz.f32 	%f114, %f113, %f47;
	mul.ftz.f32 	%f115, %f114, %f114;
	fma.rn.ftz.f32 	%f116, %f110, %f110, %f115;
	ld.const.u64 	%rd50, [params+168];
	cvta.to.global.u64 	%rd51, %rd50;
	add.s64 	%rd53, %rd51, %rd24;
	mul.ftz.f32 	%f117, %f116, 0fBF000000;
	mul.ftz.f32 	%f118, %f117, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f119, %f118;
	ld.global.f32 	%f120, [%rd53];
	mul.ftz.f32 	%f48, %f120, %f119;
	ld.const.f32 	%f49, [params+224];
	mov.f32 	%f121, 0f3F800000;
	max.ftz.f32 	%f122, %f121, %f49;
	fma.rn.ftz.f32 	%f50, %f122, 0f358637BD, %f48;
	setp.ltu.ftz.f32 	%p22, %f50, %f49;
	mov.f32 	%f141, 0f00000000;
	@%p22 bra 	$L__BB1_17;

	ld.const.f32 	%f123, [params+228];
	mov.f32 	%f124, 0f00000000;
	max.ftz.f32 	%f125, %f124, %f48;
	min.ftz.f32 	%f141, %f123, %f125;

$L__BB1_17:
	@%p22 bra 	$L__BB1_33;

	ld.const.u64 	%rd4, [params+176];
	setp.eq.s64 	%p24, %rd4, 0;
	mov.f32 	%f142, 0f3F800000;
	@%p24 bra 	$L__BB1_20;

	cvta.to.global.u64 	%rd54, %rd4;
	add.s64 	%rd56, %rd54, %rd24;
	ld.global.f32 	%f142, [%rd56];

$L__BB1_20:
	ld.const.u32 	%r4, [params+272];
	setp.lt.s32 	%p25, %r4, 1;
	ld.const.u64 	%rd5, [params+280];
	setp.eq.s64 	%p26, %rd5, 0;
	or.pred  	%p27, %p25, %p26;
	ld.const.u64 	%rd6, [params+288];
	setp.eq.s64 	%p28, %rd6, 0;
	or.pred  	%p29, %p27, %p28;
	ld.const.u64 	%rd7, [params+296];
	setp.eq.s64 	%p30, %rd7, 0;
	or.pred  	%p31, %p29, %p30;
	ld.const.u64 	%rd8, [params+304];
	setp.eq.s64 	%p32, %rd8, 0;
	or.pred  	%p33, %p31, %p32;
	@%p33 bra 	$L__BB1_33;

	mul.lo.s32 	%r5, %r4, %r17;
	cvta.to.global.u64 	%rd9, %rd5;
	mov.u32 	%r27, 0;

$L__BB1_22:
	add.s32 	%r24, %r27, %r5;
	mul.wide.s32 	%rd57, %r24, 4;
	add.s64 	%rd58, %rd9, %rd57;
	ld.global.u32 	%r25, [%rd58];
	setp.eq.s32 	%p34, %r25, %r3;
	add.s32 	%r27, %r27, 1;
	@%p34 bra 	$L__BB1_33;

	setp.lt.s32 	%p35, %r27, %r4;
	@%p35 bra 	$L__BB1_22;

	add.s32 	%r28, %r4, -1;
	add.s32 	%r29, %r28, %r5;
	mul.wide.s32 	%rd59, %r29, 4;
	add.s64 	%rd60, %rd9, %rd59;
	cvta.to.global.u64 	%rd10, %rd6;
	add.s64 	%rd61, %rd10, %rd59;
	ld.global.u32 	%r10, [%rd60];
	setp.lt.s32 	%p36, %r10, 0;
	ld.global.f32 	%f55, [%rd61];
	add.ftz.f32 	%f127, %f55, 0fB58637BD;
	setp.gt.ftz.f32 	%p37, %f127, %f41;
	or.pred  	%p38, %p36, %p37;
	@%p38 bra 	$L__BB1_26;

	sub.ftz.f32 	%f128, %f41, %f55;
	abs.ftz.f32 	%f129, %f128;
	setp.gtu.ftz.f32 	%p39, %f129, 0f358637BD;
	setp.le.s32 	%p40, %r10, %r3;
	or.pred  	%p41, %p40, %p39;
	@%p41 bra 	$L__BB1_33;

$L__BB1_26:
	setp.gt.s32 	%p42, %r4, 1;
	@%p42 bra 	$L__BB1_27;
	bra.uni 	$L__BB1_32;

$L__BB1_27:
	cvta.to.global.u64 	%rd11, %rd7;
	cvta.to.global.u64 	%rd12, %rd8;

$L__BB1_28:
	add.s32 	%r29, %r28, %r5;
	add.s32 	%r26, %r29, -1;
	cvt.s64.s32 	%rd13, %r26;
	mul.wide.s32 	%rd62, %r26, 4;
	add.s64 	%rd14, %rd9, %rd62;
	add.s64 	%rd15, %rd10, %rd62;
	ld.global.u32 	%r13, [%rd14];
	setp.lt.s32 	%p43, %r13, 0;
	ld.global.f32 	%f56, [%rd15];
	add.ftz.f32 	%f130, %f56, 0fB58637BD;
	setp.gt.ftz.f32 	%p44, %f130, %f41;
	or.pred  	%p45, %p43, %p44;
	@%p45 bra 	$L__BB1_30;

	sub.ftz.f32 	%f131, %f41, %f56;
	abs.ftz.f32 	%f132, %f131;
	setp.gtu.ftz.f32 	%p46, %f132, 0f358637BD;
	setp.le.s32 	%p47, %r13, %r3;
	or.pred  	%p48, %p47, %p46;
	@%p48 bra 	$L__BB1_32;

$L__BB1_30:
	st.global.u32 	[%rd14+4], %r13;
	ld.global.f32 	%f133, [%rd15];
	shl.b64 	%rd63, %rd13, 2;
	add.s64 	%rd64, %rd11, %rd63;
	st.global.f32 	[%rd15+4], %f133;
	ld.global.f32 	%f134, [%rd64];
	add.s64 	%rd65, %rd12, %rd63;
	st.global.f32 	[%rd64+4], %f134;
	ld.global.f32 	%f135, [%rd65];
	st.global.f32 	[%rd65+4], %f135;
	add.s32 	%r14, %r28, -1;
	setp.gt.s32 	%p49, %r28, 1;
	mov.u32 	%r28, %r14;
	@%p49 bra 	$L__BB1_28;

	add.s32 	%r29, %r14, %r5;

$L__BB1_32:
	mul.wide.s32 	%rd66, %r29, 4;
	add.s64 	%rd67, %rd9, %rd66;
	st.global.u32 	[%rd67], %r3;
	add.s64 	%rd68, %rd10, %rd66;
	st.global.f32 	[%rd68], %f41;
	cvta.to.global.u64 	%rd69, %rd7;
	add.s64 	%rd70, %rd69, %rd66;
	st.global.f32 	[%rd70], %f141;
	cvta.to.global.u64 	%rd71, %rd8;
	add.s64 	%rd72, %rd71, %rd66;
	st.global.f32 	[%rd72], %f142;

$L__BB1_33:
	// begin inline asm
	call _optix_ignore_intersection, ();
	// end inline asm

$L__BB1_35:
	ret;

}
	// .globl	__anyhit__surfel_intersect
.visible .entry __anyhit__surfel_intersect()
{
	.reg .pred 	%p<41>;
	.reg .f32 	%f<125>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<52>;


	// begin inline asm
	call (%r6), _optix_get_launch_index_x, ();
	// end inline asm
	// begin inline asm
	call (%r7), _optix_read_primitive_idx, ();
	// end inline asm
	ld.const.u32 	%r8, [params+72];
	setp.ge.u32 	%p1, %r6, %r8;
	ld.const.u32 	%r3, [params+88];
	setp.ge.u32 	%p2, %r7, %r3;
	or.pred  	%p3, %p1, %p2;
	ld.const.u64 	%rd1, [params+80];
	setp.eq.s64 	%p4, %rd1, 0;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB2_24;
	bra.uni 	$L__BB2_1;

$L__BB2_24:
	// begin inline asm
	call _optix_ignore_intersection, ();
	// end inline asm
	bra.uni 	$L__BB2_25;

$L__BB2_1:
	cvta.to.global.u64 	%rd2, %rd1;
	mul.wide.s32 	%rd10, %r7, 4;
	add.s64 	%rd11, %rd2, %rd10;
	ld.global.s32 	%rd3, [%rd11];
	// begin inline asm
	call (%f49), _optix_get_world_ray_origin_x, ();
	// end inline asm
	// begin inline asm
	call (%f50), _optix_get_world_ray_origin_y, ();
	// end inline asm
	// begin inline asm
	call (%f51), _optix_get_world_ray_origin_z, ();
	// end inline asm
	// begin inline asm
	call (%f52), _optix_get_world_ray_direction_x, ();
	// end inline asm
	// begin inline asm
	call (%f53), _optix_get_world_ray_direction_y, ();
	// end inline asm
	// begin inline asm
	call (%f54), _optix_get_world_ray_direction_z, ();
	// end inline asm
	ld.const.u64 	%rd4, [params+56];
	setp.eq.s64 	%p6, %rd4, 0;
	@%p6 bra 	$L__BB2_3;

	cvta.to.global.u64 	%rd12, %rd4;
	mul.wide.u32 	%rd13, %r6, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.f32 	%f121, [%rd14];
	bra.uni 	$L__BB2_4;

$L__BB2_3:
	ld.const.f32 	%f121, [params+236];

$L__BB2_4:
	setp.leu.ftz.f32 	%p7, %f121, 0f00000000;
	@%p7 bra 	$L__BB2_6;

	abs.ftz.f32 	%f55, %f121;
	setp.lt.ftz.f32 	%p8, %f55, 0f7F800000;
	@%p8 bra 	$L__BB2_7;

$L__BB2_6:
	ld.const.f32 	%f121, [params+236];

$L__BB2_7:
	cvt.u32.u64 	%r9, %rd3;
	setp.lt.s32 	%p9, %r9, 0;
	ld.const.u32 	%r10, [params+92];
	setp.le.s32 	%p10, %r10, %r9;
	or.pred  	%p11, %p9, %p10;
	@%p11 bra 	$L__BB2_23;

	ld.const.u64 	%rd15, [params+96];
	cvta.to.global.u64 	%rd16, %rd15;
	shl.b64 	%rd17, %rd3, 2;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.f32 	%f12, [%rd18];
	ld.const.u64 	%rd19, [params+104];
	cvta.to.global.u64 	%rd20, %rd19;
	add.s64 	%rd21, %rd20, %rd17;
	ld.global.f32 	%f13, [%rd21];
	ld.const.u64 	%rd22, [params+112];
	cvta.to.global.u64 	%rd23, %rd22;
	add.s64 	%rd24, %rd23, %rd17;
	ld.global.f32 	%f14, [%rd24];
	ld.const.u64 	%rd25, [params+120];
	cvta.to.global.u64 	%rd26, %rd25;
	add.s64 	%rd27, %rd26, %rd17;
	ld.const.u64 	%rd28, [params+128];
	cvta.to.global.u64 	%rd29, %rd28;
	add.s64 	%rd30, %rd29, %rd17;
	ld.const.u64 	%rd31, [params+136];
	cvta.to.global.u64 	%rd32, %rd31;
	add.s64 	%rd33, %rd32, %rd17;
	ld.const.u64 	%rd34, [params+144];
	cvta.to.global.u64 	%rd35, %rd34;
	add.s64 	%rd36, %rd35, %rd17;
	ld.const.u64 	%rd37, [params+152];
	cvta.to.global.u64 	%rd38, %rd37;
	add.s64 	%rd39, %rd38, %rd17;
	ld.const.u64 	%rd40, [params+160];
	cvta.to.global.u64 	%rd41, %rd40;
	add.s64 	%rd42, %rd41, %rd17;
	ld.global.f32 	%f15, [%rd42];
	ld.global.f32 	%f16, [%rd30];
	mul.ftz.f32 	%f56, %f16, %f15;
	ld.global.f32 	%f17, [%rd39];
	ld.global.f32 	%f18, [%rd33];
	mul.ftz.f32 	%f57, %f18, %f17;
	sub.ftz.f32 	%f19, %f56, %f57;
	ld.global.f32 	%f20, [%rd36];
	mul.ftz.f32 	%f58, %f18, %f20;
	ld.global.f32 	%f21, [%rd27];
	mul.ftz.f32 	%f59, %f21, %f15;
	sub.ftz.f32 	%f22, %f58, %f59;
	mul.ftz.f32 	%f60, %f21, %f17;
	mul.ftz.f32 	%f61, %f16, %f20;
	sub.ftz.f32 	%f23, %f60, %f61;
	mul.ftz.f32 	%f62, %f22, %f22;
	fma.rn.ftz.f32 	%f63, %f19, %f19, %f62;
	fma.rn.ftz.f32 	%f24, %f23, %f23, %f63;
	setp.leu.ftz.f32 	%p12, %f24, 0f24E69595;
	@%p12 bra 	$L__BB2_23;

	rsqrt.approx.ftz.f32 	%f64, %f24;
	mul.ftz.f32 	%f122, %f19, %f64;
	mul.ftz.f32 	%f123, %f22, %f64;
	mul.ftz.f32 	%f124, %f23, %f64;
	ld.const.u32 	%r11, [params+244];
	setp.eq.s32 	%p13, %r11, 0;
	@%p13 bra 	$L__BB2_12;

	mul.ftz.f32 	%f65, %f53, %f123;
	fma.rn.ftz.f32 	%f66, %f52, %f122, %f65;
	fma.rn.ftz.f32 	%f67, %f54, %f124, %f66;
	setp.leu.ftz.f32 	%p14, %f67, 0f00000000;
	@%p14 bra 	$L__BB2_12;

	neg.ftz.f32 	%f124, %f124;
	neg.ftz.f32 	%f123, %f123;
	neg.ftz.f32 	%f122, %f122;

$L__BB2_12:
	mul.ftz.f32 	%f68, %f53, %f123;
	fma.rn.ftz.f32 	%f69, %f52, %f122, %f68;
	fma.rn.ftz.f32 	%f40, %f54, %f124, %f69;
	abs.ftz.f32 	%f70, %f40;
	setp.leu)PTX_CHUNK"
R"PTX_CHUNK(.ftz.f32 	%p15, %f70, 0f322BCC77;
	@%p15 bra 	$L__BB2_23;

	sub.ftz.f32 	%f71, %f12, %f49;
	sub.ftz.f32 	%f72, %f13, %f50;
	mul.ftz.f32 	%f73, %f72, %f123;
	fma.rn.ftz.f32 	%f74, %f71, %f122, %f73;
	sub.ftz.f32 	%f75, %f14, %f51;
	fma.rn.ftz.f32 	%f76, %f75, %f124, %f74;
	div.approx.ftz.f32 	%f41, %f76, %f40;
	abs.ftz.f32 	%f77, %f41;
	setp.geu.ftz.f32 	%p16, %f77, 0f7F800000;
	ld.const.f32 	%f78, [params+232];
	setp.leu.ftz.f32 	%p17, %f41, %f78;
	or.pred  	%p18, %p17, %p16;
	setp.geu.ftz.f32 	%p19, %f41, %f121;
	or.pred  	%p20, %p19, %p18;
	@%p20 bra 	$L__BB2_23;

	fma.rn.ftz.f32 	%f79, %f52, %f41, %f49;
	fma.rn.ftz.f32 	%f80, %f53, %f41, %f50;
	fma.rn.ftz.f32 	%f81, %f54, %f41, %f51;
	sub.ftz.f32 	%f82, %f79, %f12;
	sub.ftz.f32 	%f83, %f80, %f13;
	sub.ftz.f32 	%f84, %f81, %f14;
	mul.ftz.f32 	%f85, %f16, %f16;
	fma.rn.ftz.f32 	%f86, %f21, %f21, %f85;
	fma.rn.ftz.f32 	%f42, %f18, %f18, %f86;
	mul.ftz.f32 	%f87, %f16, %f17;
	fma.rn.ftz.f32 	%f88, %f21, %f20, %f87;
	fma.rn.ftz.f32 	%f43, %f18, %f15, %f88;
	mul.ftz.f32 	%f89, %f17, %f17;
	fma.rn.ftz.f32 	%f90, %f20, %f20, %f89;
	fma.rn.ftz.f32 	%f44, %f15, %f15, %f90;
	mul.ftz.f32 	%f91, %f16, %f83;
	fma.rn.ftz.f32 	%f92, %f21, %f82, %f91;
	fma.rn.ftz.f32 	%f45, %f18, %f84, %f92;
	mul.ftz.f32 	%f93, %f17, %f83;
	fma.rn.ftz.f32 	%f94, %f20, %f82, %f93;
	fma.rn.ftz.f32 	%f46, %f15, %f84, %f94;
	mul.ftz.f32 	%f95, %f42, %f44;
	mul.ftz.f32 	%f96, %f43, %f43;
	sub.ftz.f32 	%f47, %f95, %f96;
	abs.ftz.f32 	%f97, %f47;
	setp.leu.ftz.f32 	%p21, %f97, 0f24E69595;
	@%p21 bra 	$L__BB2_23;

	mul.ftz.f32 	%f98, %f44, %f45;
	mul.ftz.f32 	%f99, %f43, %f46;
	sub.ftz.f32 	%f100, %f98, %f99;
	div.approx.ftz.f32 	%f101, %f100, %f47;
	mul.ftz.f32 	%f102, %f43, %f45;
	mul.ftz.f32 	%f103, %f42, %f46;
	sub.ftz.f32 	%f104, %f103, %f102;
	div.approx.ftz.f32 	%f105, %f104, %f47;
	mul.ftz.f32 	%f106, %f105, %f105;
	fma.rn.ftz.f32 	%f107, %f101, %f101, %f106;
	ld.const.u64 	%rd43, [params+168];
	cvta.to.global.u64 	%rd44, %rd43;
	add.s64 	%rd46, %rd44, %rd17;
	mul.ftz.f32 	%f108, %f107, 0fBF000000;
	mul.ftz.f32 	%f109, %f108, 0f3FB8AA3B;
	ex2.approx.ftz.f32 	%f110, %f109;
	ld.global.f32 	%f111, [%rd46];
	ld.const.f32 	%f112, [params+224];
	mov.f32 	%f113, 0f3F800000;
	max.ftz.f32 	%f114, %f113, %f112;
	mul.ftz.f32 	%f115, %f114, 0f358637BD;
	fma.rn.ftz.f32 	%f116, %f111, %f110, %f115;
	setp.ltu.ftz.f32 	%p22, %f116, %f112;
	@%p22 bra 	$L__BB2_23;

	ld.const.u64 	%rd5, [params+248];
	setp.eq.s64 	%p23, %rd5, 0;
	ld.const.u64 	%rd6, [params+256];
	setp.eq.s64 	%p24, %rd6, 0;
	or.pred  	%p25, %p23, %p24;
	@%p25 bra 	$L__BB2_23;

	cvta.to.global.u64 	%rd47, %rd5;
	mul.wide.u32 	%rd48, %r6, 4;
	add.s64 	%rd7, %rd47, %rd48;
	ld.global.u32 	%r13, [%rd7];
	cvt.s64.s32 	%rd8, %r13;
	cvta.to.global.u64 	%rd49, %rd6;
	add.s64 	%rd9, %rd49, %rd48;
	ld.global.f32 	%f48, [%rd9];
	setp.lt.s32 	%p26, %r13, 0;
	mov.u32 	%r17, -1;
	setp.ge.s32 	%p27, %r13, %r3;
	or.pred  	%p28, %p26, %p27;
	@%p28 bra 	$L__BB2_19;

	shl.b64 	%rd50, %rd8, 2;
	add.s64 	%rd51, %rd2, %rd50;
	ld.global.u32 	%r17, [%rd51];

$L__BB2_19:
	cvt.u32.u64 	%r14, %rd8;
	setp.lt.s32 	%p29, %r14, 0;
	add.ftz.f32 	%f117, %f48, 0fB58637BD;
	setp.gt.ftz.f32 	%p30, %f117, %f41;
	or.pred  	%p31, %p29, %p30;
	@%p31 bra 	$L__BB2_22;

	sub.ftz.f32 	%f118, %f41, %f48;
	abs.ftz.f32 	%f119, %f118;
	setp.gtu.ftz.f32 	%p32, %f119, 0f358637BD;
	@%p32 bra 	$L__BB2_23;

	setp.gt.s32 	%p33, %r17, %r9;
	setp.lt.s32 	%p34, %r17, 0;
	or.pred  	%p35, %p34, %p33;
	setp.eq.s32 	%p36, %r17, %r9;
	setp.gt.s32 	%p37, %r14, %r7;
	and.pred  	%p38, %p37, %p36;
	or.pred  	%p39, %p35, %p38;
	not.pred 	%p40, %p39;
	@%p40 bra 	$L__BB2_23;

$L__BB2_22:
	st.global.u32 	[%rd7], %r7;
	st.global.f32 	[%rd9], %f41;

$L__BB2_23:
	// begin inline asm
	call _optix_ignore_intersection, ();
	// end inline asm

$L__BB2_25:
	ret;

}
	// .globl	__raygen__surfel_trace
.visible .entry __raygen__surfel_trace()
{
	.reg .pred 	%p<35>;
	.reg .b16 	%rs<10>;
	.reg .f32 	%f<23>;
	.reg .b32 	%r<87>;
	.reg .b64 	%rd<61>;


	// begin inline asm
	call (%r3), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r4, [params+72];
	setp.lt.u32 	%p3, %r3, %r4;
	@%p3 bra 	$L__BB3_8;
	bra.uni 	$L__BB3_1;

$L__BB3_8:
	ld.const.u64 	%rd2, [params+64];
	setp.eq.s64 	%p5, %rd2, 0;
	mov.pred 	%p34, 0;
	@%p5 bra 	$L__BB3_10;

	cvta.to.global.u64 	%rd15, %rd2;
	cvt.u64.u32 	%rd16, %r3;
	add.s64 	%rd17, %rd15, %rd16;
	ld.global.u8 	%rs3, [%rd17];
	setp.eq.s16 	%p34, %rs3, 0;

$L__BB3_10:
	ld.const.u64 	%rd3, [params];
	setp.eq.s64 	%p6, %rd3, 0;
	or.pred  	%p7, %p34, %p6;
	ld.const.v2.u32 	{%r5, %r6}, [params+88];
	setp.lt.s32 	%p8, %r5, 1;
	or.pred  	%p9, %p7, %p8;
	setp.lt.s32 	%p10, %r6, 1;
	or.pred  	%p11, %p9, %p10;
	ld.const.u64 	%rd18, [params+80];
	setp.eq.s64 	%p12, %rd18, 0;
	or.pred  	%p13, %p11, %p12;
	ld.const.u64 	%rd60, [params+248];
	setp.eq.s64 	%p14, %rd60, 0;
	or.pred  	%p15, %p13, %p14;
	ld.const.u64 	%rd5, [params+256];
	setp.eq.s64 	%p16, %rd5, 0;
	or.pred  	%p17, %p15, %p16;
	@%p17 bra 	$L__BB3_2;

	ld.const.u64 	%rd6, [params+56];
	setp.eq.s64 	%p18, %rd6, 0;
	@%p18 bra 	$L__BB3_13;

	cvta.to.global.u64 	%rd19, %rd6;
	mul.wide.u32 	%rd20, %r3, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.f32 	%f22, [%rd21];
	bra.uni 	$L__BB3_14;

$L__BB3_1:
	ld.const.u64 	%rd60, [params+248];

$L__BB3_2:
	setp.eq.s64 	%p31, %rd60, 0;
	@%p31 bra 	$L__BB3_4;

	cvta.to.global.u64 	%rd51, %rd60;
	mul.wide.u32 	%rd52, %r3, 4;
	add.s64 	%rd53, %rd51, %rd52;
	mov.u32 	%r85, -1;
	st.global.u32 	[%rd53], %r85;

$L__BB3_4:
	ld.const.u64 	%rd13, [params+256];
	setp.eq.s64 	%p32, %rd13, 0;
	@%p32 bra 	$L__BB3_6;

	cvta.to.global.u64 	%rd54, %rd13;
	mul.wide.u32 	%rd55, %r3, 4;
	add.s64 	%rd56, %rd54, %rd55;
	mov.u32 	%r86, 2139095039;
	st.global.u32 	[%rd56], %r86;

$L__BB3_6:
	ld.const.u64 	%rd14, [params+264];
	setp.eq.s64 	%p33, %rd14, 0;
	@%p33 bra 	$L__BB3_29;

	cvta.to.global.u64 	%rd57, %rd14;
	cvt.u64.u32 	%rd58, %r3;
	add.s64 	%rd59, %rd57, %rd58;
	mov.u16 	%rs8, 0;
	st.global.u8 	[%rd59], %rs8;

$L__BB3_29:
	ret;

$L__BB3_13:
	ld.const.f32 	%f22, [params+236];

$L__BB3_14:
	setp.leu.ftz.f32 	%p19, %f22, 0f00000000;
	@%p19 bra 	$L__BB3_16;

	abs.ftz.f32 	%f8, %f22;
	setp.lt.ftz.f32 	%p20, %f8, 0f7F800000;
	@%p20 bra 	$L__BB3_17;

$L__BB3_16:
	ld.const.f32 	%f22, [params+236];

$L__BB3_17:
	ld.const.f32 	%f9, [params+232];
	mov.f32 	%f10, 0f00000000;
	max.ftz.f32 	%f6, %f9, %f10;
	setp.geu.ftz.f32 	%p21, %f6, %f22;
	cvt.u64.u32 	%rd7, %r3;
	cvta.to.global.u64 	%rd22, %rd60;
	mul.wide.u32 	%rd23, %r3, 4;
	add.s64 	%rd8, %rd22, %rd23;
	mov.u32 	%r8, -1;
	st.global.u32 	[%rd8], %r8;
	cvta.to.global.u64 	%rd24, %rd5;
	add.s64 	%rd9, %rd24, %rd23;
	@%p21 bra 	$L__BB3_27;
	bra.uni 	$L__BB3_18;

$L__BB3_27:
	mov.u32 	%r84, 2139095039;
	st.global.u32 	[%rd9], %r84;
	ld.const.u64 	%rd11, [params+264];
	setp.eq.s64 	%p30, %rd11, 0;
	@%p30 bra 	$L__BB3_29;

	cvta.to.global.u64 	%rd49, %rd11;
	add.s64 	%rd50, %rd49, %rd7;
	mov.u16 	%rs7, 0;
	st.global.u8 	[%rd50], %rs7;
	bra.uni 	$L__BB3_29;

$L__BB3_18:
	mov.u32 	%r9, 2139095039;
	st.global.u32 	[%rd9], %r9;
	ld.const.u64 	%rd10, [params+264];
	setp.eq.s64 	%p22, %rd10, 0;
	@%p22 bra 	$L__BB3_20;

	cvta.to.global.u64 	%rd25, %rd10;
	add.s64 	%rd26, %rd25, %rd7;
	mov.u16 	%rs4, 0;
	st.global.u8 	[%rd26], %rs4;

$L__BB3_20:
	ld.const.u64 	%rd28, [params+8];
	cvta.to.global.u64 	%rd29, %rd28;
	shl.b64 	%rd30, %rd7, 2;
	add.s64 	%rd31, %rd29, %rd30;
	ld.global.f32 	%f11, [%rd31];
	ld.const.u64 	%rd32, [params+16];
	cvta.to.global.u64 	%rd33, %rd32;
	add.s64 	%rd34, %rd33, %rd30;
	ld.global.f32 	%f12, [%rd34];
	ld.const.u64 	%rd35, [params+24];
	cvta.to.global.u64 	%rd36, %rd35;
	add.s64 	%rd37, %rd36, %rd30;
	ld.global.f32 	%f13, [%rd37];
	ld.const.u64 	%rd38, [params+32];
	cvta.to.global.u64 	%rd39, %rd38;
	add.s64 	%rd40, %rd39, %rd30;
	ld.global.f32 	%f14, [%rd40];
	ld.const.u64 	%rd41, [params+40];
	cvta.to.global.u64 	%rd42, %rd41;
	add.s64 	%rd43, %rd42, %rd30;
	ld.global.f32 	%f15, [%rd43];
	ld.const.u64 	%rd44, [params+48];
	cvta.to.global.u64 	%rd45, %rd44;
	add.s64 	%rd46, %rd45, %rd30;
	ld.global.f32 	%f16, [%rd46];
	mov.f32 	%f19, 0f00000000;
	mov.u32 	%r43, 255;
	mov.u32 	%r44, 10;
	mov.u32 	%r48, 1;
	mov.u32 	%r80, 0;
	// begin inline asm
	call(%r10,%r11,%r12,%r13,%r14,%r15,%r16,%r17,%r18,%r19,%r20,%r21,%r22,%r23,%r24,%r25,%r26,%r27,%r28,%r29,%r30,%r31,%r32,%r33,%r34,%r35,%r36,%r37,%r38,%r39,%r40,%r41),_optix_trace_typed_32,(%r80,%rd3,%f11,%f12,%f13,%f14,%f15,%f16,%f6,%f22,%f19,%r43,%r44,%r48,%r48,%r80,%r48,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80,%r80);
	// end inline asm
	ld.global.u32 	%r81, [%rd8];
	setp.lt.s32 	%p23, %r81, 0;
	setp.ge.s32 	%p24, %r81, %r5;
	mov.u16 	%rs9, 0;
	or.pred  	%p25, %p23, %p24;
	@%p25 bra 	$L__BB3_23;

	ld.global.f32 	%f7, [%rd9];
	abs.ftz.f32 	%f20, %f7;
	setp.geu.ftz.f32 	%p26, %f20, 0f7F800000;
	@%p26 bra 	$L__BB3_23;

	setp.lt.ftz.f32 	%p27, %f7, %f22;
	selp.u16 	%rs9, 1, 0, %p27;

$L__BB3_23:
	@%p22 bra 	$L__BB3_25;

	cvta.to.global.u64 	%rd47, %rd10;
	add.s64 	%rd48, %rd47, %rd7;
	st.global.u8 	[%rd48], %rs9;

$L__BB3_25:
	setp.ne.s16 	%p29, %rs9, 0;
	@%p29 bra 	$L__BB3_29;

	mov.u32 	%r82, -1;
	st.global.u32 	[%rd8], %r82;
	mov.u32 	%r83, 2139095039;
	st.global.u32 	[%rd9], %r83;
	bra.uni 	$L__BB3_29;

}
	// .globl	__raygen__surfel_composite
.visible .entry __raygen__surfel_composite()
{
	.reg .pred 	%p<266>;
	.reg .b16 	%rs<4>;
	.reg .f32 	%f<275>;
	.reg .b32 	%r<246>;
	.reg .b64 	%rd<124>;


	// begin inline asm
	call (%r79), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r80, [params+72];
	setp.ge.u32 	%p5, %r79, %r80;
	ld.const.u32 	%r2, [params+272];
	setp.lt.s32 	%p6, %r2, 1;
	or.pred  	%p7, %p6, %p5;
	@%p7 bra 	$L__BB4_263;

	mul.lo.s32 	%r3, %r2, %r79;
	ld.const.u64 	%rd24, [params+280];
	cvta.to.global.u64 	%rd1, %rd24;
	ld.const.u64 	%rd25, [params+288];
	cvta.to.global.u64 	%rd2, %rd25;
	ld.const.u64 	%rd26, [params+296];
	cvta.to.global.u64 	%rd3, %rd26;
	ld.const.u64 	%rd27, [params+304];
	cvta.to.global.u64 	%rd4, %rd27;
	and.b32  	%r226, %r2, 3;
	add.s32 	%r82, %r2, -1;
	setp.lt.u32 	%p8, %r82, 3;
	mov.u32 	%r224, 0;
	@%p8 bra 	$L__BB4_4;

	sub.s32 	%r223, %r2, %r226;
	mov.u32 	%r83, 0;
	mov.u32 	%r224, %r83;

$L__BB4_3:
	add.s32 	%r84, %r224, %r3;
	mul.wide.s32 	%rd28, %r84, 4;
	add.s64 	%rd29, %rd1, %rd28;
	mov.u32 	%r85, -1;
	st.global.u32 	[%rd29], %r85;
	add.s64 	%rd30, %rd2, %rd28;
	mov.u32 	%r86, 2139095039;
	st.global.u32 	[%rd30], %r86;
	add.s64 	%rd31, %rd3, %rd28;
	st.global.u32 	[%rd31], %r83;
	add.s64 	%rd32, %rd4, %rd28;
	st.global.u32 	[%rd32], %r83;
	st.global.u32 	[%rd29+4], %r85;
	st.global.u32 	[%rd30+4], %r86;
	st.global.u32 	[%rd31+4], %r83;
	st.global.u32 	[%rd32+4], %r83;
	st.global.u32 	[%rd29+8], %r85;
	st.global.u32 	[%rd30+8], %r86;
	st.global.u32 	[%rd31+8], %r83;
	st.global.u32 	[%rd32+8], %r83;
	st.global.u32 	[%rd29+12], %r85;
	st.global.u32 	[%rd30+12], %r86;
	st.global.u32 	[%rd31+12], %r83;
	st.global.u32 	[%rd32+12], %r83;
	add.s32 	%r224, %r224, 4;
	add.s32 	%r223, %r223, -4;
	setp.ne.s32 	%p9, %r223, 0;
	@%p9 bra 	$L__BB4_3;

$L__BB4_4:
	setp.eq.s32 	%p10, %r226, 0;
	@%p10 bra 	$L__BB4_6;

$L__BB4_5:
	.pragma "nounroll";
	add.s32 	%r88, %r224, %r3;
	mul.wide.s32 	%rd33, %r88, 4;
	add.s64 	%rd34, %rd1, %rd33;
	mov.u32 	%r89, -1;
	st.global.u32 	[%rd34], %r89;
	add.s64 	%rd35, %rd2, %rd33;
	mov.u32 	%r90, 2139095039;
	st.global.u32 	[%rd35], %r90;
	add.s64 	%rd36, %rd3, %rd33;
	mov.u32 	%r91, 0;
	st.global.u32 	[%rd36], %r91;
	add.s64 	%rd37, %rd4, %rd33;
	st.global.u32 	[%rd37], %r91;
	add.s32 	%r224, %r224, 1;
	add.s32 	%r226, %r226, -1;
	setp.ne.s32 	%p11, %r226, 0;
	@%p11 bra 	$L__BB4_5;

$L__BB4_6:
	ld.const.u32 	%r15, [params+208];
	setp.gt.s32 	%p12, %r15, 0;
	selp.b32 	%r16, %r15, 0, %p12;
	mul.lo.s32 	%r17, %r16, %r79;
	ld.const.u64 	%rd5, [params+320];
	setp.eq.s64 	%p13, %rd5, 0;
	setp.lt.s32 	%p14, %r15, 1;
	or.pred  	%p1, %p13, %p14;
	@%p1 bra 	$L__BB4_12;

	cvta.to.global.u64 	%rd6, %rd5;
	max.s32 	%r18, %r15, 1;
	add.s32 	%r93, %r18, -1;
	and.b32  	%r231, %r18, 3;
	setp.lt.u32 	%p15, %r93, 3;
	mov.u32 	%r229, 0;
	@%p15 bra 	$L__BB4_10;

	sub.s32 	%r228, %r18, %r231;
	mov.u32 	%r94, 0;
	mov.u32 	%r229, %r94;

$L__BB4_9:
	add.s32 	%r95, %r229, %r17;
	mul.wide.s32 	%rd38, %r95, 4;
	add.s64 	%rd39, %rd6, %rd38;
	st.global.u32 	[%rd39], %r94;
	st.global.u32 	[%rd39+4], %r94;
	st.global.u32 	[%rd39+8], %r94;
	st.global.u32 	[%rd39+12], %r94;
	add.s32 	%r229, %r229, 4;
	add.s32 	%r228, %r228, -4;
	setp.ne.s32 	%p16, %r228, 0;
	@%p16 bra 	$L__BB4_9;

$L__BB4_10:
	setp.eq.s32 	%p17, %r231, 0;
	@%p17 bra 	$L__BB4_12;

$L__BB4_11:
	.pragma "nounroll";
	add.s32 	%r97, %r229, %r17;
	mul.wide.s32 	%rd40, %r97, 4;
	add.s64 	%rd41, %rd6, %rd40;
	mov.u32 	%r98, 0;
	st.global.u32 	[%rd41], %r98;
	add.s32 	%r229, %r229, 1;
	add.s32 	%r231, %r231, -1;
	setp.ne.s32 	%p18, %r231, 0;
	@%p18 bra 	$L__BB4_11;

$L__BB4_12:
	ld.const.u64 	%rd7, [params+64];
	setp.eq.s64 	%p19, %rd7, 0;
	@%p19 bra 	$L__BB4_14;

	cvta.to.global.u64 	%rd42, %rd7;
	cvt.u64.u32 	%rd43, %r79;
	add.s64 	%rd44, %rd42, %rd43;
	ld.global.u8 	%rs1, [%rd44];
	setp.ne.s16 	%p21, %rs1, 0;
	ld.const.u64 	%rd123, [params];
	setp.ne.s64 	%p22, %rd123, 0;
	and.pred  	%p23, %p21, %p22;
	ld.const.v2.u32 	{%r99, %r233}, [params+88];
	setp.gt.s32 	%p24, %r99, 0;
	and.pred  	%p25, %p23, %p24;
	setp.gt.s32 	%p26, %r233, 0;
	and.pred  	%p27, %p25, %p26;
	mov.pred 	%p265, 0;
	@%p27 bra 	$L__BB4_15;
	bra.uni 	$L__BB4_16;

$L__BB4_15:
	ld.const.u64 	%rd45, [params+80];
	setp.ne.s64 	%p265, %rd45, 0;

$L__BB4_16:
	ld.const.u64 	%rd46, [params+32];
	cvta.to.global.u64 	%rd47, %rd46;
	cvt.u64.u32 	%rd12, %r79;
	mul.wide.u32 	%rd48, %r79, 4;
	add.s64 	%rd49, %rd47, %rd48;
	ld.const.u64 	%rd50, [params+40];
	cvta.to.global.u64 	%rd51, %rd50;
	add.s64 	%rd52, %rd51, %rd48;
	ld.const.u64 	%rd53, [params+48];
	cvta.to.global.u64 	%rd54, %rd53;
	add.s64 	%rd55, %rd54, %rd48;
	ld.global.f32 	%f1, [%rd49];
	ld.global.f32 	%f2, [%rd52];
	mul.ftz.f32 	%f108, %f2, %f2;
	fma.rn.ftz.f32 	%f109, %f1, %f1, %f108;
	ld.global.f32 	%f3, [%rd55];
	fma.rn.ftz.f32 	%f4, %f3, %f3, %f109;
	setp.leu.ftz.f32 	%p34, %f4, 0f24E69595;
	mov.f32 	%f268, 0f3F800000;
	mov.f32 	%f266, 0f00000000;
	mov.f32 	%f235, %f266;
	mov.f32 	%f236, %f266;
	mov.f32 	%f237, %f268;
	@%p34 bra 	$L__BB4_18;

	rsqrt.approx.ftz.f32 	%f110, %f4;
	mul.ftz.f32 	%f111, %f1, %f110;
	mul.ftz.f32 	%f112, %f2, %f110;
	mul.ftz.f32 	%f113, %f3, %f110;
	neg.ftz.f32 	%f237, %f113;
	neg.ftz.f32 	%f236, %f112;
	neg.ftz.f32 	%f235, %f111;

$L__BB4_18:
	not.pred 	%p35, %p265;
	mov.f32 	%f267, %f266;
	mov.f32 	%f269, %f266;
	@%p35 bra 	$L__BB4_255;

	ld.const.u64 	%rd13, [params+56];
	setp.eq.s64 	%p36, %rd13, 0;
	@%p36 bra 	$L__BB4_21;

	cvta.to.global.u64 	%rd56, %rd13;
	shl.b64 	%rd57, %rd12, 2;
	add.s64 	%rd58, %rd56, %rd57;
	ld.global.f32 	%f239, [%rd58];
	bra.uni 	$L__BB4_22;

$L__BB4_14:
	ld.const.u64 	%rd123, [params];
	setp.eq.s64 	%p29, %rd123, 0;
	ld.const.v2.u32 	{%r102, %r233}, [params+88];
	setp.lt.s32 	%p30, %r102, 1;
	or.pred  	%p31, %p29, %p30;
	setp.lt.s32 	%p32, %r233, 1;
	mov.pred 	%p265, 0;
	or.pred  	%p33, %p31, %p32;
	@%p33 bra 	$L__BB4_16;
	bra.uni 	$L__BB4_15;

$L__BB4_21:
	ld.const.f32 	%f239, [params+236];

$L__BB4_22:
	setp.leu.ftz.f32 	%p37, %f239, 0f00000000;
	@%p37 bra 	$L__BB4_24;

	abs.ftz.f32 	%f118, %f239;
	setp.lt.ftz.f32 	%p38, %f118, 0f7F800000;
	@%p38 bra 	$L__BB4_25;

$L__BB4_24:
	ld.const.f32 	%f239, [params+236];

$L__BB4_25:
	ld.const.u64 	%rd60, [params+8];
	cvta.to.global.u64 	%rd61, %rd60;
	shl.b64 	%rd62, %rd12, 2;
	add.s64 	%rd63, %rd61, %rd62;
	ld.global.f32 	%f119, [%rd63];
	ld.const.u64 	%rd64, [params+16];
	cvta.to.global.u64 	%rd65, %rd64;
	add.s64 	%rd66, %rd65, %rd62;
	ld.global.f32 	%f120, [%rd66];
	ld.const.u64 	%rd67, [params+24];
	cvta.to.global.u64 	%rd68, %rd67;
	add.s64 	%rd69, %r)PTX_CHUNK"
R"PTX_CHUNK(d68, %rd62;
	ld.global.f32 	%f121, [%rd69];
	ld.const.f32 	%f132, [params+232];
	mov.f32 	%f266, 0f00000000;
	max.ftz.f32 	%f125, %f132, %f266;
	mov.u32 	%r138, 255;
	mov.u32 	%r139, 10;
	mov.u32 	%r143, 1;
	mov.u32 	%r234, 0;
	// begin inline asm
	call(%r105,%r106,%r107,%r108,%r109,%r110,%r111,%r112,%r113,%r114,%r115,%r116,%r117,%r118,%r119,%r120,%r121,%r122,%r123,%r124,%r125,%r126,%r127,%r128,%r129,%r130,%r131,%r132,%r133,%r134,%r135,%r136),_optix_trace_typed_32,(%r234,%rd123,%f119,%f120,%f121,%f1,%f2,%f3,%f125,%f239,%f266,%r138,%r139,%r234,%r143,%r234,%r143,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234,%r234);
	// end inline asm
	mov.f32 	%f267, %f266;
	mov.f32 	%f269, %f266;
	@%p6 bra 	$L__BB4_255;

	ld.const.u64 	%rd14, [params+184];
	ld.const.v2.u32 	{%r177, %r178}, [params+192];
	ld.const.v2.u32 	{%r180, %r181}, [params+200];
	setp.lt.s32 	%p40, %r181, 0;
	max.s32 	%r35, %r177, 1;
	setp.gt.s32 	%p41, %r35, 0;
	add.s32 	%r36, %r35, -1;
	selp.b32 	%r37, 0, %r36, %p41;
	cvta.to.global.u64 	%rd15, %rd14;
	cvta.to.global.u64 	%rd16, %rd5;
	setp.lt.s32 	%p42, %r180, 0;
	setp.gt.s32 	%p43, %r181, 3;
	setp.gt.s32 	%p44, %r180, 3;
	add.s32 	%r184, %r181, 1;
	mul.ftz.f32 	%f16, %f236, 0f3EFA2A1C;
	mul.ftz.f32 	%f17, %f237, 0f3EFA2A1C;
	mul.ftz.f32 	%f18, %f235, 0f3EFA2A1C;
	mul.ftz.f32 	%f137, %f235, 0f3F8BD8A1;
	mul.ftz.f32 	%f19, %f236, %f137;
	mul.ftz.f32 	%f138, %f236, 0f3F8BD8A1;
	mul.ftz.f32 	%f20, %f237, %f138;
	mul.ftz.f32 	%f139, %f237, 0f40400000;
	fma.rn.ftz.f32 	%f140, %f237, %f139, 0fBF800000;
	mul.ftz.f32 	%f21, %f140, 0f3EA17B01;
	mul.ftz.f32 	%f22, %f237, %f137;
	mul.ftz.f32 	%f141, %f236, %f236;
	mul.ftz.f32 	%f142, %f235, %f235;
	sub.ftz.f32 	%f143, %f142, %f141;
	mul.ftz.f32 	%f23, %f143, 0f3F0BD8A1;
	mul.ftz.f32 	%f144, %f235, 0f40400000;
	mul.ftz.f32 	%f145, %f235, %f144;
	sub.ftz.f32 	%f146, %f145, %f141;
	mul.ftz.f32 	%f147, %f236, 0f3F170D19;
	mul.ftz.f32 	%f24, %f147, %f146;
	mul.ftz.f32 	%f148, %f235, 0f4038FFC7;
	mul.ftz.f32 	%f149, %f236, %f148;
	mul.ftz.f32 	%f25, %f237, %f149;
	mul.ftz.f32 	%f150, %f237, 0f40A00000;
	fma.rn.ftz.f32 	%f151, %f237, %f150, 0fBF800000;
	mul.ftz.f32 	%f152, %f236, 0f3EEA01E8;
	mul.ftz.f32 	%f26, %f152, %f151;
	fma.rn.ftz.f32 	%f153, %f237, %f150, 0fC0400000;
	mul.ftz.f32 	%f154, %f237, 0f3EBF10F8;
	mul.ftz.f32 	%f27, %f154, %f153;
	mul.ftz.f32 	%f155, %f235, 0f3EEA01E8;
	mul.ftz.f32 	%f28, %f155, %f151;
	mul.ftz.f32 	%f156, %f237, 0f3FB8FFC7;
	mul.ftz.f32 	%f29, %f156, %f143;
	mul.ftz.f32 	%f157, %f236, 0f40400000;
	mul.ftz.f32 	%f158, %f236, %f157;
	sub.ftz.f32 	%f159, %f142, %f158;
	mul.ftz.f32 	%f160, %f235, 0f3F170D19;
	mul.ftz.f32 	%f30, %f160, %f159;
	add.s32 	%r185, %r180, 1;
	max.s32 	%r186, %r15, 1;
	add.s32 	%r38, %r186, -1;
	selp.b32 	%r187, 4, %r184, %p43;
	selp.b32 	%r188, 1, %r187, %p40;
	mul.lo.s32 	%r39, %r188, %r188;
	selp.b32 	%r189, 4, %r185, %p44;
	selp.b32 	%r40, 1, %r189, %p42;
	add.s32 	%r41, %r39, -1;
	and.b32  	%r42, %r39, 3;
	and.b32  	%r43, %r186, 3;
	sub.s32 	%r44, %r39, %r42;
	sub.s32 	%r45, %r186, %r43;
	mul.lo.s32 	%r190, %r40, %r40;
	mul.lo.s32 	%r46, %r190, 3;
	mov.f32 	%f269, 0f00000000;
	mov.f32 	%f268, 0f3F800000;
	mov.f32 	%f267, %f269;
	mov.f32 	%f266, %f269;
	bra.uni 	$L__BB4_27;

$L__BB4_73:
	setp.gt.s32 	%p76, %r56, 11;
	@%p76 bra 	$L__BB4_79;

	setp.gt.s32 	%p82, %r56, 9;
	@%p82 bra 	$L__BB4_77;

	setp.eq.s32 	%p85, %r56, 8;
	mov.f32 	%f251, %f23;
	@%p85 bra 	$L__BB4_85;

	setp.eq.s32 	%p86, %r56, 9;
	mov.f32 	%f251, %f24;
	@%p86 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_68:
	setp.gt.s32 	%p88, %r56, 5;
	@%p88 bra 	$L__BB4_71;

	setp.eq.s32 	%p91, %r56, 4;
	mov.f32 	%f251, %f19;
	@%p91 bra 	$L__BB4_85;

	setp.eq.s32 	%p92, %r56, 5;
	mov.f32 	%f251, %f20;
	@%p92 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_79:
	setp.gt.s32 	%p77, %r56, 13;
	@%p77 bra 	$L__BB4_82;

	setp.eq.s32 	%p80, %r56, 12;
	mov.f32 	%f251, %f27;
	@%p80 bra 	$L__BB4_85;

	setp.eq.s32 	%p81, %r56, 13;
	mov.f32 	%f251, %f28;
	@%p81 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_66:
	setp.eq.s32 	%p94, %r56, 2;
	mov.f32 	%f251, %f17;
	@%p94 bra 	$L__BB4_85;

	setp.eq.s32 	%p95, %r56, 3;
	mov.f32 	%f251, %f18;
	@%p95 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_77:
	setp.eq.s32 	%p83, %r56, 10;
	mov.f32 	%f251, %f25;
	@%p83 bra 	$L__BB4_85;

	setp.eq.s32 	%p84, %r56, 11;
	mov.f32 	%f251, %f26;
	@%p84 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_71:
	setp.eq.s32 	%p89, %r56, 6;
	mov.f32 	%f251, %f21;
	@%p89 bra 	$L__BB4_85;

	setp.eq.s32 	%p90, %r56, 7;
	mov.f32 	%f251, %f22;
	@%p90 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_82:
	setp.eq.s32 	%p78, %r56, 14;
	mov.f32 	%f251, %f29;
	@%p78 bra 	$L__BB4_85;

	setp.ne.s32 	%p79, %r56, 15;
	mov.f32 	%f251, %f30;
	@%p79 bra 	$L__BB4_84;
	bra.uni 	$L__BB4_85;

$L__BB4_84:
	mov.f32 	%f251, 0f00000000;

$L__BB4_85:
	fma.rn.ftz.f32 	%f254, %f53, %f251, %f254;
	setp.eq.s32 	%p98, %r42, 1;
	@%p98 bra 	$L__BB4_136;

	mad.lo.s32 	%r199, %r57, 3, 3;
	mul.wide.s32 	%rd79, %r199, 4;
	add.s64 	%rd19, %rd15, %rd79;
	ld.global.f32 	%f56, [%rd19];
	setp.gt.s32 	%p99, %r56, 6;
	@%p99 bra 	$L__BB4_98;

	setp.gt.s32 	%p111, %r56, 2;
	@%p111 bra 	$L__BB4_93;

	setp.gt.s32 	%p117, %r56, 0;
	@%p117 bra 	$L__BB4_91;

	mov.f32 	%f252, 0f3E906EBB;
	setp.eq.s32 	%p120, %r56, -1;
	@%p120 bra 	$L__BB4_110;

	setp.eq.s32 	%p121, %r56, 0;
	mov.f32 	%f252, %f16;
	@%p121 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_98:
	setp.gt.s32 	%p100, %r56, 10;
	@%p100 bra 	$L__BB4_104;

	setp.gt.s32 	%p106, %r56, 8;
	@%p106 bra 	$L__BB4_102;

	setp.eq.s32 	%p109, %r56, 7;
	mov.f32 	%f252, %f23;
	@%p109 bra 	$L__BB4_110;

	setp.eq.s32 	%p110, %r56, 8;
	mov.f32 	%f252, %f24;
	@%p110 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_93:
	setp.gt.s32 	%p112, %r56, 4;
	@%p112 bra 	$L__BB4_96;

	setp.eq.s32 	%p115, %r56, 3;
	mov.f32 	%f252, %f19;
	@%p115 bra 	$L__BB4_110;

	setp.eq.s32 	%p116, %r56, 4;
	mov.f32 	%f252, %f20;
	@%p116 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_104:
	setp.gt.s32 	%p101, %r56, 12;
	@%p101 bra 	$L__BB4_107;

	setp.eq.s32 	%p104, %r56, 11;
	mov.f32 	%f252, %f27;
	@%p104 bra 	$L__BB4_110;

	setp.eq.s32 	%p105, %r56, 12;
	mov.f32 	%f252, %f28;
	@%p105 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_91:
	setp.eq.s32 	%p118, %r56, 1;
	mov.f32 	%f252, %f17;
	@%p118 bra 	$L__BB4_110;

	setp.eq.s32 	%p119, %r56, 2;
	mov.f32 	%f252, %f18;
	@%p119 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_102:
	setp.eq.s32 	%p107, %r56, 9;
	mov.f32 	%f252, %f25;
	@%p107 bra 	$L__BB4_110;

	setp.eq.s32 	%p108, %r56, 10;
	mov.f32 	%f252, %f26;
	@%p108 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_96:
	setp.eq.s32 	%p113, %r56, 5;
	mov.f32 	%f252, %f21;
	@%p113 bra 	$L__BB4_110;

	setp.eq.s32 	%p114, %r56, 6;
	mov.f32 	%f252, %f22;
	@%p114 bra 	$L__BB4_110;
	bra.uni 	$L__BB4_109;

$L__BB4_107:
	setp.eq.s32 	%p102, %r56, 13;
	mov.f32 	%f252, %f29;
	@%p102 bra 	$L__BB4_110;

	setp.ne.s32 	%p103, %r56, 14;
	mov.f32 	%f252, %f30;
	@%p103 bra 	$L__BB4_109;
	bra.uni 	$L__BB4_110;

$L__BB4_109:
	mov.f32 	%f252, 0f00000000;

$L__BB4_110:
	fma.rn.ftz.f32 	%f254, %f56, %f252, %f254;
	setp.eq.s32 	%p122, %r42, 2;
	@%p122 bra 	$L__BB4_136;

	ld.global.f32 	%f59, [%rd19+12];
	setp.gt.s32 	%p123, %r56, 5;
	@%p123 bra 	$L__BB4_123;

	setp.gt.s32 	%p135, %r56, 1;
	@%p135 bra 	$L__BB4_118;

	setp.gt.s32 	%p141, %r56, -1;
	@%p141 bra 	$L__BB4_116;

	mov.f32 	%f253, 0f3E906EBB;
	setp.eq.s32 	%p144, %r56, -2;
	@%p144 bra 	$L__BB4_135;

	setp.eq.s32 	%p145, %r56, -1;
	mov.f32 	%f253, %f16;
	@%p145 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_123:
	setp.gt.s32 	%p124, %r56, 9;
	@%p124 bra 	$L__BB4_129;

	setp.gt.s32 	%p263, %r56, 7;
	@%p263 bra 	$L__BB4_127;

	setp.eq.s32 	%p133, %r56, 6;
	mov.f32 	%f253, %f23;
	@%p133 bra 	$L__BB4_135;

	setp.eq.s32 	%p134, %r56, 7;
	mov.f32 	%f253, %f24;
	@%p134 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_118:
	setp.gt.s32 	%p136, %r56, 3;
	@%p136 bra 	$L__BB4_121;

	setp.eq.s32 	%p139, %r56, 2;
	mov.f32 	%f253, %f19;
	@%p139 bra 	$L__BB4_135;

	setp.eq.s32 	%p140, %r56, 3;
	mov.f32 	%f253, %f20;
	@%p140 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_129:
	setp.gt.s32 	%p125, %r56, 11;
	@%p125 bra 	$L__BB4_132;

	setp.eq.s32 	%p128, %r56, 10;
	mov.f32 	%f253, %f27;
	@%p128 bra 	$L__BB4_135;

	setp.eq.s32 	%p129, %r56, 11;
	mov.f32 	%f253, %f28;
	@%p129 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_116:
	setp.eq.s32 	%p142, %r56, 0;
	mov.f32 	%f253, %f17;
	@%p142 bra 	$L__BB4_135;

	setp.eq.s32 	%p143, %r56, 1;
	mov.f32 	%f253, %f18;
	@%p143 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_127:
	setp.eq.s32 	%p131, %r56, 8;
	mov.f32 	%f253, %f25;
	@%p131 bra 	$L__BB4_135;

	setp.eq.s32 	%p132, %r56, 9;
	mov.f32 	%f253, %f26;
	@%p132 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_121:
	setp.eq.s32 	%p137, %r56, 4;
	mov.f32 	%f253, %f21;
	@%p137 bra 	$L__BB4_135;

	setp.eq.s32 	%p138, %r56, 5;
	mov.f32 	%f253, %f22;
	@%p138 bra 	$L__BB4_135;
	bra.uni 	$L__BB4_134;

$L__BB4_132:
	setp.eq.s32 	%p126, %r56, 12;
	mov.f32 	%f253, %f29;
	@%p126 bra 	$L__BB4_135;

	setp.ne.s32 	%p127, %r56, 13;
	mov.f32 	%f253, %f30;
	@%p127 bra 	$L__BB4_134;
	bra.uni 	$L__BB4_135;

$L__BB4_134:
	mov.f32 	%f253, 0f00000000;

$L__BB4_135:
	fma.rn.ftz.f32 	%f254, %f59, %f253, %f254;
	bra.uni 	$L__BB4_136;

$L__BB4_27:
	add.s32 	%r191, %r234, %r3;
	cvt.s64.s32 	%rd17, %r191;
	mul.wide.s32 	%rd70, %r191, 4;
	add.s64 	%rd71, %rd1, %rd70;
	ld.global.u32 	%r49, [%rd71];
	setp.lt.s32 	%p45, %r49, 0;
	@%p45 bra 	$L__BB4_254;

	add.s32 	%r219, %r234, %r3;
	cvt.s64.s32 	%rd120, %r219;
	shl.b64 	%rd72, %rd120, 2;
	add.s64 	%rd73, %rd3, %rd72;
	ld.global.f32 	%f35, [%rd73];
	setp.leu.ftz.f32 	%p46, %f35, 0f00000000;
	@%p46 bra 	$L__BB4_254;

	ld.const.u64 	%rd121, [params+184];
	setp.ne.s64 	%p47, %rd121, 0;
	mul.ftz.f32 	%f36, %f268, %f35;
	setp.gt.s32 	%p48, %r233, %r49;
	and.pred  	%p4, %p47, %p48;
	mov.f32 	%f254, 0f3F800000;
	not.pred 	%p49, %p4;
	@%p49 bra 	$L__BB4_136;

	setp.eq.s32 	%p50, %r178, 1;
	@%p50 bra 	$L__BB4_32;
	bra.uni 	$L__BB4_31;

$L__BB4_32:
	setp.eq.s32 	%p51, %r39, 0;
	mul.lo.s32 	%r193, %r40, %r49;
	mul.lo.s32 	%r50, %r193, %r40;
	mov.f32 	%f254, 0f00000000;
	@%p51 bra 	$L__BB4_136;

	setp.lt.u32 	%p52, %r41, 3;
	mov.f32 	%f254, 0f00000000;
	mov.u32 	%r56, 0;
	@%p52 bra 	$L__BB4_60;

	mov.f32 	%f254, 0f00000000;
	mov.u32 	%r56, 0;
	mov.u32 	%r236, %r44;

$L__BB4_35:
	add.s32 	%r196, %r56, %r50;
	mul.lo.s32 	%r197, %r196, 3;
	mul.wide.s32 	%rd76, %r197, 4;
	add.s64 	%rd18, %rd15, %rd76;
	ld.global.f32 	%f39, [%rd18];
	shr.u32 	%r53, %r56, 2;
	setp.gt.s32 	%p53, %r53, 1;
	@%p53 bra 	$L__BB4_38;

	mov.f32 	%f245, 0f3E906EBB;
	setp.eq.s32 	%p56, %r53, 0;
	@%p56 bra 	$L__BB4_41;

	setp.eq.s32 	%p57, %r53, 1;
	mov.f32 	%f245, %f19;
	@%p57 bra 	$L__BB4_41;
	bra.uni 	$L__BB4_40;

$L__BB4_38:
	setp.eq.s32 	%p54, %r53, 3;
	mov.f32 	%f245, %f27;
	@%p54 bra 	$L__BB4_41;

	setp.ne.s32 	%p55, %r53, 2;
	mov.f32 	%f245, %f23;
	@%p55 bra 	$L__BB4_40;
	bra.uni 	$L__BB4_41;

$L__BB4_40:
	mov.f32 	%f245, 0f00000000;

$L__BB4_41:
	fma.rn.ftz.f32 	%f41, %f39, %f245, %f254;
	ld.global.f32 	%f42, [%rd18+12];
	@%p53 bra 	$L__BB4_44;

	setp.eq.s32 	%p61, %r53, 0;
	mov.f32 	%f246, %f16;
	@%p61 bra 	$L__BB4_47;

	setp.eq.s32 	%p62, %r53, 1;
	mov.f32 	%f246, %f20;
	@%p62 bra 	$L__BB4_47;
	bra.uni 	$L__BB4_46;

$L__BB4_44:
	setp.eq.s32 	%p59, %r53, 2;
	mov.f32 	%f246, %f24;
	@%p59 bra 	$L__BB4_47;

	setp.eq.s32 	%p60, %r53, 3;
	mov.f32 	%f246, %f28;
	@%p60 bra 	$L__BB4_47;

$L__BB4_46:
	mov.f32 	%f246, 0f00000000;

$L__BB4_47:
	fma.rn.ftz.f32 	%f44, %f42, %f246, %f41;
	ld.global.f32 	%f45, [%rd18+24];
	@%p53 bra 	$L__BB4_50;

	setp.eq.s32 	%p66, %r53, 0;
	mov.f32 	%f247, %f17;
	@%p66 bra 	$L__BB4_53;

	setp.eq.s32 	%p67, %r53, 1;
	mov.f32 	%f247, %f21;
	@%p67 bra 	$L__BB4_53;
	bra.uni 	$L__BB4_52;

$L__BB4_50:
	setp.eq.s32 	%p64, %r53, 3;
	mov.f32 	%f247, %f29;
	@%p64 bra 	$L__BB4_53;

	setp.ne.s32 	%p65, %r53, 2;
	mov.f32 	%f247, %f25;
	@%p65 bra 	$L__BB4_52;
	bra.uni 	$L__BB4_53;

$L__BB4_52:
	mov.f32 	%f247, 0f00000000;

$L__BB4_53:
	fma.rn.ftz.f32 	%f47, %f45, %f247, %f44;
	ld.global.f32 	%f48, [%rd18+36];
	@%p53 bra 	$L__BB4_56;

	setp.eq.s32 	%p71, %r53, 0;
	mov.f32 	%f248, %f18;
	@%p71 bra 	$L__BB4_59;

	setp.eq.s32 	%p72, %r53, 1;
	mov.f32 	%f248, %f22;
	@%p72 bra 	$L__BB4_59;
	bra.uni 	$L__BB4_58;

$L__BB4_56:
	setp.eq.s32 	%p69, %r53, 2;
	mov.f32 	%f248, %f26;
	@%p69 bra 	$L__BB4_59;

	setp.eq.s32 	%p70, %r53, 3;
	mov.f32 	%f248, %f30;
	@%p70 bra 	$L__BB4_59;

$L__BB4_58:
	mov.f32 	%f248, 0f00000000;

$L__BB4_59:
	fma.rn.ftz.f32 	%f254, %f48, %f248, %f47;
	add.s32 	%r56, %r56, 4;
	add.s32 	%r236, %r236, -4;
	setp.ne.s32 	%p73, %r236, 0;
	@%p73 bra 	$L__BB4_35;

$L__BB4_60:
	setp.eq.s32 	%p74, %r42, 0;
	@%p74 bra 	$L__BB4_136;

	add.s32 	%r57, %r56, %r50;
	mul.lo.s32 	%r198, %r57, 3;
	mul.wide.s32 	%rd77, %r198, 4;
	add.s64 	%rd78, %rd15, %rd77;
	ld.global.f32 	%f53, [%rd78];
	setp.gt.s32 	%p75, %r56, 7;
	@%p75 bra 	$L__BB4_73;

	setp.gt.s32 	%p87, %r56, 3;
	@%p87 bra 	$L__BB4_68;

	setp.gt.s32 	%p93, %r56, 1;
	@%p93 bra 	$L__BB4_66;

	mov.f32 	%f251, 0f3E906EBB;
	setp.eq.s32 	%p96, %r56, 0;
	@%p96 bra 	$L__BB4_85;

	setp.eq.s32 	%p97, %r56, 1;
	mov.f32 	%f251, %f16;
	@%p97 bra 	$L__BB4_85;
	bra.uni 	$L__BB4_84;

$L__BB4_31:
	mad.lo.s32 	%r192, %r35, %r49, %r37;
	mul.wide.s32 	%rd74, %r192, 4;
	add.s64 	%rd75, %rd15, %rd74;
	ld.global.f32 	%f254, [%rd75];

$L__BB4_136:
	fma.rn.ftz.f32 	%f266, %f36, %f254, %f266;
	@%p1 bra 	$L__BB4_253;

	@%p4 bra 	$L__BB4_145;
	bra.uni 	$L__BB4_138;

$L__BB4_145:
	mul.lo.s32 	%r205, %r40, %r49;
	mul.lo.s32 	%r63, %r205, %r40;
	mad.lo.s32 	%r64, %r46, %r49, 9;
	mul.lo.s32 	%r65, %r35, %r49;
	mov.u32 	%r241, 0;
	bra.uni 	$L__BB4_146;

$L__BB4_189:
	setp.gt.s32 	%p181, %r75, 11;
	@%p181 bra 	$L__BB4_195;

	setp.gt.s32 	%p187, %r75, 9;
	@%p187 bra 	$L__BB4_193;

	setp.eq.s32 	%p190, %r75, 8;
	mov.f32 	%f262, %f23;
	@%p190 bra 	$L__BB4_201;

	setp.eq.s32 	%p191, %r75, 9;
	mov.f32 	%f262, %f24;
	@%p191 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_184:
	setp.gt.s32 	%p193, %r75, 5;
	@%p193 bra 	$L__BB4_187;

	setp.eq.s32 	%p196, %r75, 4;
	mov.f32 	%f262, %f19;
	@%p196 bra 	$L__BB4_201;

	setp.eq.s32 	%p197, %r75, 5;
	mov.f32 	%f262, %f20;
	@%p197 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_195:
	setp.gt.s32 	%p182, %r75, 13;
	@%p182 bra 	$L__BB4_198;

	setp.eq.s32 	%p185, %r75, 12;
	mov.f32 	%f262, %f27;
	@%p185 bra 	$L__BB4_201;

	setp.eq.s32 	%p186, %r75, 13;
	mov.f32 	%f262, %f28;
	@%p186 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_182:
	setp.eq.s32 	%p199, %r75, 2;
	mov.f32 	%f262, %f17;
	@%p199 bra 	$L__BB4_201;

	setp.eq.s32 	%p200, %r75, 3;
	mov.f32 	%f262, %f18;
	@%p200 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_193:
	setp.eq.s32 	%p188, %r75, 10;
	mov.f32 	%f262, %f25;
	@%p188 bra 	$L__BB4_201;

	setp.eq.s32 	%p189, %r75, 11;
	mov.f32 	%f262, %f26;
	@%p189 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_187:
	setp.eq.s32 	%p194, %r75, 6;
	mov.f32 	%f262, %f21;
	@%p194 bra 	$L__BB4_201;

	setp.eq.s32 	%p195, %r75, 7;
	mov.f32 	%f262, %f22;
	@%p195 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_198:
	setp.eq.s32 	%p183, %r75, 14;
	mov.f32 	%f262, %f29;
	@%p183 bra 	$L__BB4_201;

	setp.ne.s32 	%p184, %r75, 15;
	mov.f32 	%f262, %f30;
	@%p184 bra 	$L__BB4_200;
	bra.uni 	$L__BB4_201;

$L__BB4_200:
	mov.f32 	%f262, 0f00000000;

$L__BB4_201:
	fma.rn.ftz.f32 	%f265, %f82, %f262, %f265;
	setp.eq.s32 	%p203, %r42, 1;
	@%p203 bra 	$L__BB4_252;

	add.s32 	%r214, %r76, 1;
	mad.lo.s32 	%r215, %r214, 3, %r67;
	mul.wide.s32 	%rd88, %r215, 4;
	add.s64 	%rd22, %rd15, %rd88;
	ld.global.f32 	%f85, [%rd22];
	setp.gt.s32 	%p204, %r75, 6;
	@%p204 bra 	$L__BB4_214;

	setp.gt.s32 	%p216, %r75, 2;
	@%p216 bra 	$L__BB4_209;

	setp.gt.s32 	%p222, %r75, 0;
	@%p222 bra 	$L__BB4_207;

	mov.f32 	%f263, 0f3E906EBB;
	setp)PTX_CHUNK"
R"PTX_CHUNK(.eq.s32 	%p225, %r75, -1;
	@%p225 bra 	$L__BB4_226;

	setp.eq.s32 	%p226, %r75, 0;
	mov.f32 	%f263, %f16;
	@%p226 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_214:
	setp.gt.s32 	%p205, %r75, 10;
	@%p205 bra 	$L__BB4_220;

	setp.gt.s32 	%p211, %r75, 8;
	@%p211 bra 	$L__BB4_218;

	setp.eq.s32 	%p214, %r75, 7;
	mov.f32 	%f263, %f23;
	@%p214 bra 	$L__BB4_226;

	setp.eq.s32 	%p215, %r75, 8;
	mov.f32 	%f263, %f24;
	@%p215 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_209:
	setp.gt.s32 	%p217, %r75, 4;
	@%p217 bra 	$L__BB4_212;

	setp.eq.s32 	%p220, %r75, 3;
	mov.f32 	%f263, %f19;
	@%p220 bra 	$L__BB4_226;

	setp.eq.s32 	%p221, %r75, 4;
	mov.f32 	%f263, %f20;
	@%p221 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_220:
	setp.gt.s32 	%p206, %r75, 12;
	@%p206 bra 	$L__BB4_223;

	setp.eq.s32 	%p209, %r75, 11;
	mov.f32 	%f263, %f27;
	@%p209 bra 	$L__BB4_226;

	setp.eq.s32 	%p210, %r75, 12;
	mov.f32 	%f263, %f28;
	@%p210 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_207:
	setp.eq.s32 	%p223, %r75, 1;
	mov.f32 	%f263, %f17;
	@%p223 bra 	$L__BB4_226;

	setp.eq.s32 	%p224, %r75, 2;
	mov.f32 	%f263, %f18;
	@%p224 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_218:
	setp.eq.s32 	%p212, %r75, 9;
	mov.f32 	%f263, %f25;
	@%p212 bra 	$L__BB4_226;

	setp.eq.s32 	%p213, %r75, 10;
	mov.f32 	%f263, %f26;
	@%p213 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_212:
	setp.eq.s32 	%p218, %r75, 5;
	mov.f32 	%f263, %f21;
	@%p218 bra 	$L__BB4_226;

	setp.eq.s32 	%p219, %r75, 6;
	mov.f32 	%f263, %f22;
	@%p219 bra 	$L__BB4_226;
	bra.uni 	$L__BB4_225;

$L__BB4_223:
	setp.eq.s32 	%p207, %r75, 13;
	mov.f32 	%f263, %f29;
	@%p207 bra 	$L__BB4_226;

	setp.ne.s32 	%p208, %r75, 14;
	mov.f32 	%f263, %f30;
	@%p208 bra 	$L__BB4_225;
	bra.uni 	$L__BB4_226;

$L__BB4_225:
	mov.f32 	%f263, 0f00000000;

$L__BB4_226:
	fma.rn.ftz.f32 	%f265, %f85, %f263, %f265;
	setp.eq.s32 	%p227, %r42, 2;
	@%p227 bra 	$L__BB4_252;

	ld.global.f32 	%f88, [%rd22+12];
	setp.gt.s32 	%p228, %r75, 5;
	@%p228 bra 	$L__BB4_239;

	setp.gt.s32 	%p240, %r75, 1;
	@%p240 bra 	$L__BB4_234;

	setp.gt.s32 	%p246, %r75, -1;
	@%p246 bra 	$L__BB4_232;

	mov.f32 	%f264, 0f3E906EBB;
	setp.eq.s32 	%p249, %r75, -2;
	@%p249 bra 	$L__BB4_251;

	setp.eq.s32 	%p250, %r75, -1;
	mov.f32 	%f264, %f16;
	@%p250 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_239:
	setp.gt.s32 	%p229, %r75, 9;
	@%p229 bra 	$L__BB4_245;

	setp.gt.s32 	%p264, %r75, 7;
	@%p264 bra 	$L__BB4_243;

	setp.eq.s32 	%p238, %r75, 6;
	mov.f32 	%f264, %f23;
	@%p238 bra 	$L__BB4_251;

	setp.eq.s32 	%p239, %r75, 7;
	mov.f32 	%f264, %f24;
	@%p239 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_234:
	setp.gt.s32 	%p241, %r75, 3;
	@%p241 bra 	$L__BB4_237;

	setp.eq.s32 	%p244, %r75, 2;
	mov.f32 	%f264, %f19;
	@%p244 bra 	$L__BB4_251;

	setp.eq.s32 	%p245, %r75, 3;
	mov.f32 	%f264, %f20;
	@%p245 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_245:
	setp.gt.s32 	%p230, %r75, 11;
	@%p230 bra 	$L__BB4_248;

	setp.eq.s32 	%p233, %r75, 10;
	mov.f32 	%f264, %f27;
	@%p233 bra 	$L__BB4_251;

	setp.eq.s32 	%p234, %r75, 11;
	mov.f32 	%f264, %f28;
	@%p234 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_232:
	setp.eq.s32 	%p247, %r75, 0;
	mov.f32 	%f264, %f17;
	@%p247 bra 	$L__BB4_251;

	setp.eq.s32 	%p248, %r75, 1;
	mov.f32 	%f264, %f18;
	@%p248 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_243:
	setp.eq.s32 	%p236, %r75, 8;
	mov.f32 	%f264, %f25;
	@%p236 bra 	$L__BB4_251;

	setp.eq.s32 	%p237, %r75, 9;
	mov.f32 	%f264, %f26;
	@%p237 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_237:
	setp.eq.s32 	%p242, %r75, 4;
	mov.f32 	%f264, %f21;
	@%p242 bra 	$L__BB4_251;

	setp.eq.s32 	%p243, %r75, 5;
	mov.f32 	%f264, %f22;
	@%p243 bra 	$L__BB4_251;
	bra.uni 	$L__BB4_250;

$L__BB4_248:
	setp.eq.s32 	%p231, %r75, 12;
	mov.f32 	%f264, %f29;
	@%p231 bra 	$L__BB4_251;

	setp.ne.s32 	%p232, %r75, 13;
	mov.f32 	%f264, %f30;
	@%p232 bra 	$L__BB4_250;
	bra.uni 	$L__BB4_251;

$L__BB4_250:
	mov.f32 	%f264, 0f00000000;

$L__BB4_251:
	fma.rn.ftz.f32 	%f265, %f88, %f264, %f265;
	bra.uni 	$L__BB4_252;

$L__BB4_146:
	setp.eq.s32 	%p153, %r178, 1;
	@%p153 bra 	$L__BB4_148;
	bra.uni 	$L__BB4_147;

$L__BB4_148:
	setp.eq.s32 	%p155, %r39, 0;
	setp.lt.u32 	%p156, %r241, 3;
	selp.b32 	%r67, %r241, 0, %p156;
	mov.f32 	%f265, 0f00000000;
	@%p155 bra 	$L__BB4_252;

	setp.lt.u32 	%p157, %r41, 3;
	mov.f32 	%f265, 0f00000000;
	mov.u32 	%r75, 0;
	@%p157 bra 	$L__BB4_176;

	add.s32 	%r242, %r64, %r67;
	mov.f32 	%f265, 0f00000000;
	mov.u32 	%r243, 0;
	mov.u32 	%r75, %r243;

$L__BB4_151:
	add.s32 	%r211, %r242, -9;
	mul.wide.s32 	%rd85, %r211, 4;
	add.s64 	%rd21, %rd15, %rd85;
	ld.global.f32 	%f68, [%rd21];
	setp.gt.s32 	%p158, %r243, 1;
	@%p158 bra 	$L__BB4_154;

	mov.f32 	%f256, 0f3E906EBB;
	setp.eq.s32 	%p161, %r243, 0;
	@%p161 bra 	$L__BB4_157;

	setp.eq.s32 	%p162, %r243, 1;
	mov.f32 	%f256, %f19;
	@%p162 bra 	$L__BB4_157;
	bra.uni 	$L__BB4_156;

$L__BB4_154:
	setp.eq.s32 	%p159, %r243, 3;
	mov.f32 	%f256, %f27;
	@%p159 bra 	$L__BB4_157;

	setp.ne.s32 	%p160, %r243, 2;
	mov.f32 	%f256, %f23;
	@%p160 bra 	$L__BB4_156;
	bra.uni 	$L__BB4_157;

$L__BB4_156:
	mov.f32 	%f256, 0f00000000;

$L__BB4_157:
	fma.rn.ftz.f32 	%f70, %f68, %f256, %f265;
	ld.global.f32 	%f71, [%rd21+12];
	@%p158 bra 	$L__BB4_160;

	setp.eq.s32 	%p166, %r243, 0;
	mov.f32 	%f257, %f16;
	@%p166 bra 	$L__BB4_163;

	setp.eq.s32 	%p167, %r243, 1;
	mov.f32 	%f257, %f20;
	@%p167 bra 	$L__BB4_163;
	bra.uni 	$L__BB4_162;

$L__BB4_160:
	setp.eq.s32 	%p164, %r243, 2;
	mov.f32 	%f257, %f24;
	@%p164 bra 	$L__BB4_163;

	setp.eq.s32 	%p165, %r243, 3;
	mov.f32 	%f257, %f28;
	@%p165 bra 	$L__BB4_163;

$L__BB4_162:
	mov.f32 	%f257, 0f00000000;

$L__BB4_163:
	fma.rn.ftz.f32 	%f73, %f71, %f257, %f70;
	ld.global.f32 	%f74, [%rd21+24];
	@%p158 bra 	$L__BB4_166;

	setp.eq.s32 	%p171, %r243, 0;
	mov.f32 	%f258, %f17;
	@%p171 bra 	$L__BB4_169;

	setp.eq.s32 	%p172, %r243, 1;
	mov.f32 	%f258, %f21;
	@%p172 bra 	$L__BB4_169;
	bra.uni 	$L__BB4_168;

$L__BB4_166:
	setp.eq.s32 	%p169, %r243, 3;
	mov.f32 	%f258, %f29;
	@%p169 bra 	$L__BB4_169;

	setp.ne.s32 	%p170, %r243, 2;
	mov.f32 	%f258, %f25;
	@%p170 bra 	$L__BB4_168;
	bra.uni 	$L__BB4_169;

$L__BB4_168:
	mov.f32 	%f258, 0f00000000;

$L__BB4_169:
	fma.rn.ftz.f32 	%f76, %f74, %f258, %f73;
	ld.global.f32 	%f77, [%rd21+36];
	@%p158 bra 	$L__BB4_172;

	setp.eq.s32 	%p176, %r243, 0;
	mov.f32 	%f259, %f18;
	@%p176 bra 	$L__BB4_175;

	setp.eq.s32 	%p177, %r243, 1;
	mov.f32 	%f259, %f22;
	@%p177 bra 	$L__BB4_175;
	bra.uni 	$L__BB4_174;

$L__BB4_172:
	setp.eq.s32 	%p174, %r243, 2;
	mov.f32 	%f259, %f26;
	@%p174 bra 	$L__BB4_175;

	setp.eq.s32 	%p175, %r243, 3;
	mov.f32 	%f259, %f30;
	@%p175 bra 	$L__BB4_175;

$L__BB4_174:
	mov.f32 	%f259, 0f00000000;

$L__BB4_175:
	sub.s32 	%r217, %r42, %r39;
	fma.rn.ftz.f32 	%f265, %f77, %f259, %f76;
	add.s32 	%r243, %r243, 1;
	add.s32 	%r242, %r242, 12;
	add.s32 	%r75, %r75, 4;
	add.s32 	%r212, %r217, %r75;
	setp.ne.s32 	%p178, %r212, 0;
	@%p178 bra 	$L__BB4_151;

$L__BB4_176:
	setp.eq.s32 	%p179, %r42, 0;
	@%p179 bra 	$L__BB4_252;

	add.s32 	%r76, %r75, %r63;
	mad.lo.s32 	%r213, %r76, 3, %r67;
	mul.wide.s32 	%rd86, %r213, 4;
	add.s64 	%rd87, %rd15, %rd86;
	ld.global.f32 	%f82, [%rd87];
	setp.gt.s32 	%p180, %r75, 7;
	@%p180 bra 	$L__BB4_189;

	setp.gt.s32 	%p192, %r75, 3;
	@%p192 bra 	$L__BB4_184;

	setp.gt.s32 	%p198, %r75, 1;
	@%p198 bra 	$L__BB4_182;

	mov.f32 	%f262, 0f3E906EBB;
	setp.eq.s32 	%p201, %r75, 0;
	@%p201 bra 	$L__BB4_201;

	setp.eq.s32 	%p202, %r75, 1;
	mov.f32 	%f262, %f16;
	@%p202 bra 	$L__BB4_201;
	bra.uni 	$L__BB4_200;

$L__BB4_147:
	add.s32 	%r220, %r35, -1;
	setp.gt.s32 	%p154, %r35, %r241;
	selp.b32 	%r206, %r241, %r220, %p154;
	add.s32 	%r207, %r206, %r65;
	mul.wide.s32 	%rd83, %r207, 4;
	add.s64 	%rd84, %rd15, %rd83;
	ld.global.f32 	%f265, [%rd84];

$L__BB4_252:
	add.s32 	%r216, %r241, %r17;
	mul.wide.s32 	%rd89, %r216, 4;
	add.s64 	%rd90, %rd16, %rd89;
	ld.global.f32 	%f208, [%rd90];
	fma.rn.ftz.f32 	%f209, %f36, %f265, %f208;
	st.global.f32 	[%rd90], %f209;
	add.s32 	%r241, %r241, 1;
	setp.lt.s32 	%p251, %r241, %r16;
	@%p251 bra 	$L__BB4_146;
	bra.uni 	$L__BB4_253;

$L__BB4_138:
	setp.lt.u32 	%p146, %r38, 3;
	mov.u32 	%r240, 0;
	@%p146 bra 	$L__BB4_141;

	mov.u32 	%r240, 0;
	mov.u32 	%r239, %r45;

$L__BB4_140:
	mul.ftz.f32 	%f231, %f268, %f35;
	mul.ftz.f32 	%f230, %f231, 0f00000000;
	setp.eq.s32 	%p147, %r240, 0;
	selp.f32 	%f177, 0f3F800000, 0f00000000, %p147;
	add.s32 	%r202, %r240, %r17;
	mul.wide.s32 	%rd80, %r202, 4;
	add.s64 	%rd81, %rd16, %rd80;
	ld.global.f32 	%f178, [%rd81];
	fma.rn.ftz.f32 	%f179, %f231, %f177, %f178;
	st.global.f32 	[%rd81], %f179;
	ld.global.f32 	%f180, [%rd81+4];
	add.ftz.f32 	%f181, %f230, %f180;
	st.global.f32 	[%rd81+4], %f181;
	ld.global.f32 	%f182, [%rd81+8];
	add.ftz.f32 	%f183, %f230, %f182;
	st.global.f32 	[%rd81+8], %f183;
	ld.global.f32 	%f184, [%rd81+12];
	add.ftz.f32 	%f185, %f230, %f184;
	st.global.f32 	[%rd81+12], %f185;
	add.s32 	%r240, %r240, 4;
	add.s32 	%r239, %r239, -4;
	setp.ne.s32 	%p148, %r239, 0;
	@%p148 bra 	$L__BB4_140;

$L__BB4_141:
	setp.eq.s32 	%p149, %r43, 0;
	@%p149 bra 	$L__BB4_253;

	setp.eq.s32 	%p150, %r43, 1;
	setp.eq.s32 	%p151, %r240, 0;
	selp.f32 	%f186, 0f3F800000, 0f00000000, %p151;
	add.s32 	%r203, %r240, %r17;
	mul.wide.s32 	%rd82, %r203, 4;
	add.s64 	%rd20, %rd16, %rd82;
	ld.global.f32 	%f187, [%rd20];
	fma.rn.ftz.f32 	%f188, %f36, %f186, %f187;
	st.global.f32 	[%rd20], %f188;
	@%p150 bra 	$L__BB4_253;

	setp.eq.s32 	%p152, %r43, 2;
	ld.global.f32 	%f189, [%rd20+4];
	mul.ftz.f32 	%f65, %f36, 0f00000000;
	add.ftz.f32 	%f190, %f65, %f189;
	st.global.f32 	[%rd20+4], %f190;
	@%p152 bra 	$L__BB4_253;

	ld.global.f32 	%f191, [%rd20+8];
	add.ftz.f32 	%f192, %f65, %f191;
	st.global.f32 	[%rd20+8], %f192;

$L__BB4_253:
	add.s32 	%r218, %r234, %r3;
	cvt.s64.s32 	%rd115, %r218;
	shl.b64 	%rd114, %rd115, 2;
	add.ftz.f32 	%f267, %f267, %f36;
	add.s64 	%rd92, %rd2, %rd114;
	ld.global.f32 	%f210, [%rd92];
	fma.rn.ftz.f32 	%f269, %f36, %f210, %f269;
	mov.f32 	%f211, 0f3F800000;
	sub.ftz.f32 	%f212, %f211, %f35;
	mul.ftz.f32 	%f268, %f268, %f212;

$L__BB4_254:
	ld.const.u32 	%r221, [params+272];
	add.s32 	%r234, %r234, 1;
	setp.lt.s32 	%p252, %r234, %r221;
	@%p252 bra 	$L__BB4_27;

$L__BB4_255:
	ld.const.u64 	%rd116, [params+320];
	setp.eq.s64 	%p261, %rd116, 0;
	setp.lt.s32 	%p253, %r16, 3;
	or.pred  	%p255, %p253, %p261;
	@%p255 bra 	$L__BB4_259;

	ld.const.u64 	%rd117, [params+64];
	setp.eq.s64 	%p262, %rd117, 0;
	@%p262 bra 	$L__BB4_258;

	ld.const.u64 	%rd118, [params+64];
	cvta.to.global.u64 	%rd93, %rd118;
	add.s64 	%rd94, %rd93, %rd12;
	ld.global.u8 	%rs2, [%rd94];
	setp.eq.s16 	%p257, %rs2, 0;
	@%p257 bra 	$L__BB4_259;

$L__BB4_258:
	ld.const.u64 	%rd119, [params+320];
	ld.const.f32 	%f213, [params+212];
	cvta.to.global.u64 	%rd95, %rd119;
	mul.wide.s32 	%rd96, %r17, 4;
	add.s64 	%rd97, %rd95, %rd96;
	ld.global.f32 	%f214, [%rd97];
	fma.rn.ftz.f32 	%f215, %f268, %f213, %f214;
	st.global.f32 	[%rd97], %f215;
	ld.const.v2.f32 	{%f216, %f217}, [params+216];
	ld.global.f32 	%f220, [%rd97+4];
	fma.rn.ftz.f32 	%f221, %f268, %f216, %f220;
	st.global.f32 	[%rd97+4], %f221;
	ld.global.f32 	%f222, [%rd97+8];
	fma.rn.ftz.f32 	%f223, %f268, %f217, %f222;
	st.global.f32 	[%rd97+8], %f223;

$L__BB4_259:
	ld.const.u64 	%rd98, [params+312];
	cvta.to.global.u64 	%rd99, %rd98;
	shl.b64 	%rd100, %rd12, 2;
	add.s64 	%rd101, %rd99, %rd100;
	st.global.f32 	[%rd101], %f266;
	ld.const.u64 	%rd102, [params+328];
	cvta.to.global.u64 	%rd103, %rd102;
	add.s64 	%rd104, %rd103, %rd100;
	st.global.f32 	[%rd104], %f267;
	ld.const.u64 	%rd105, [params+336];
	cvta.to.global.u64 	%rd106, %rd105;
	add.s64 	%rd107, %rd106, %rd100;
	st.global.f32 	[%rd107], %f268;
	setp.leu.ftz.f32 	%p258, %f267, 0f00000000;
	mov.f32 	%f274, 0f7F800000;
	@%p258 bra 	$L__BB4_261;

	div.approx.ftz.f32 	%f274, %f269, %f267;

$L__BB4_261:
	ld.const.u64 	%rd108, [params+344];
	cvta.to.global.u64 	%rd109, %rd108;
	add.s64 	%rd111, %rd109, %rd100;
	st.global.f32 	[%rd111], %f274;
	ld.const.u64 	%rd23, [params+264];
	setp.eq.s64 	%p259, %rd23, 0;
	@%p259 bra 	$L__BB4_263;

	setp.gt.ftz.f32 	%p260, %f267, 0f00000000;
	selp.u16 	%rs3, 1, 0, %p260;
	cvta.to.global.u64 	%rd112, %rd23;
	add.s64 	%rd113, %rd112, %rd12;
	st.global.u8 	[%rd113], %rs3;

$L__BB4_263:
	ret;

}

)PTX_CHUNK"
;
static const size_t surfel_trace_ptx_size = 60307;
