# Copyright Xingyu Chen.
# Implements shared Python support for runtime Dr.Jit.

import os as _os
import pathlib as _pathlib
import sys as _sys

import drjit as _drjit

if _sys.platform == "win32" and hasattr(_os, "add_dll_directory"):
    _os.add_dll_directory(str(_pathlib.Path(_drjit.__file__).resolve().parent))

from rayd.drjit._C import *  # noqa: F401,F403
from rayd._impl.capabilities_jit import api_manifest, backend_capabilities

# Explicit public surface. `from ._C import *` above is the import mechanism;
# this list is the contract. It equals every name bound by NB_MODULE(_C, m) in
# src/bindings/module_jit.cpp plus the two `_capabilities` helpers, and is
# recomputed from that source by tests/test_public_api_manifest.py and
# cross-checked against the built extension by tests/test_namespace_isolation.py.
__all__ = [
    "AccumGrid",
    "AccumOptions",
    "AccumResult",
    "AccumResultAD",
    "AxialEdgeVisibility",
    "AxialEdgeVisibilityAD",
    "DfrAccum",
    "DfrAccumAD",
    "DfrCoherentAccum",
    "DfrCoherentAccumAD",
    "DfrCoherentCandidatePairs",
    "DfrCoherentCandidatePairsAD",
    "DfrCoherentEdge",
    "DfrCoherentEdgeAD",
    "DfrCoherentOptions",
    "DfrCoherentUtdStates",
    "DfrCoherentUtdStatesAD",
    "DfrGrid",
    "DfrMaterial",
    "DfrMaterialAD",
    "DfrOptions",
    "DfrPathOptions",
    "DfrPaths",
    "DfrPathsAD",
    "DfrStates",
    "DfrStatesAD",
    "Intersection",
    "IntersectionAD",
    "Material",
    "MaterialAD",
    "Mesh",
    "NearestEdgesTopK",
    "NearestEdgesTopKAD",
    "NearestPointEdge",
    "NearestPointEdgeAD",
    "NearestRayEdge",
    "NearestRayEdgeAD",
    "RAYD_DFR_DIRECT",
    "RAYD_DFR_HASH",
    "RAYD_DFR_KELLER",
    "RAYD_DFR_MATCHED_ISO",
    "RAYD_DFR_SOBOL",
    "RAYD_DFR_SUFFIX_REFL",
    "REFLECTION_EXPORT_COUNT_ONLY",
    "REFLECTION_EXPORT_FULL",
    "REFLECTION_EXPORT_MINIMAL",
    "Ray",
    "RayAD",
    "RayFlags",
    "ReflEpc",
    "ReflEpcAD",
    "ReflEpcField",
    "ReflEpcFieldAD",
    "ReflEpcFieldOptions",
    "ReflEpcFieldOptionsAD",
    "ReflEpcOptions",
    "ReflectionBounce",
    "ReflectionBounceAD",
    "ReflectionChain",
    "ReflectionChainAD",
    "ReflectionTrace",
    "ReflectionTraceAD",
    "ReflectionTraceOptions",
    "Scene",
    "SceneEdgeBVHStats",
    "SceneEdgeInfo",
    "SceneEdgeTopology",
    "SceneGeometry",
    "SceneSyncProfile",
    "SecondaryEdgeInfo",
    "SegmentChainVisibility",
    "SegmentChainVisibilityAD",
    "SegmentPairVisibility",
    "SegmentPairVisibilityAD",
    "SegmentVisibility",
    "SegmentVisibilityAD",
    "SurfelAppearance",
    "SurfelCloud",
    "SurfelColorModel",
    "SurfelComposite",
    "SurfelCompositeAD",
    "SurfelGeometry",
    "SurfelIntersection",
    "SurfelIntersectionAD",
    "SurfelPrimitiveMode",
    "SurfelRender",
    "SurfelRenderAD",
    "SurfelRenderMode",
    "SurfelRenderOptions",
    "SurfelScene",
    "SurfelTraceOptions",
    "WedgeEvents",
    "WedgeEventsAD",
    "api_manifest",
    "backend_capabilities",
    "current_device",
    "device_count",
    "native_launch_audit",
    "native_launch_audit_clear",
    "optix_available",
    "set_device",
]
