// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char reflection_accumulation_ptx[] =
R"PTX_CHUNK(//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__closesthit__reflection_accumulation
.const .align 8 .b8 params[616];

.visible .entry __closesthit__reflection_accumulation()
{
	.reg .f32 	%f<4>;
	.reg .b32 	%r<15>;


	// begin inline asm
	call (%f1), _optix_get_ray_tmax, ();
	// end inline asm
	mov.b32 	%r6, %f1;
	// begin inline asm
	call (%f2, %f3), _optix_get_triangle_barycentrics, ();
	// end inline asm
	mov.b32 	%r8, %f2;
	mov.b32 	%r10, %f3;
	// begin inline asm
	call (%r1), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r2), _optix_read_instance_id, ();
	// end inline asm
	mov.u32 	%r3, 0;
	mov.u32 	%r5, 1;
	// begin inline asm
	call _optix_set_payload, (%r3, %r5);
	// end inline asm
	// begin inline asm
	call _optix_set_payload, (%r5, %r6);
	// end inline asm
	mov.u32 	%r7, 2;
	// begin inline asm
	call _optix_set_payload, (%r7, %r8);
	// end inline asm
	mov.u32 	%r9, 3;
	// begin inline asm
	call _optix_set_payload, (%r9, %r10);
	// end inline asm
	mov.u32 	%r11, 4;
	// begin inline asm
	call _optix_set_payload, (%r11, %r1);
	// end inline asm
	mov.u32 	%r13, 5;
	// begin inline asm
	call _optix_set_payload, (%r13, %r2);
	// end inline asm
	ret;

}
	// .globl	__miss__reflection_accumulation
.visible .entry __miss__reflection_accumulation()
{
	.reg .b32 	%r<3>;


	mov.u32 	%r2, 0;
	// begin inline asm
	call _optix_set_payload, (%r2, %r2);
	// end inline asm
	ret;

}
	// .globl	__raygen__reflection_accumulation
.visible .entry __raygen__reflection_accumulation()
{
	.reg .pred 	%p<160>;
	.reg .b16 	%rs<9>;
	.reg .f32 	%f<979>;
	.reg .b32 	%r<409>;
	.reg .f64 	%fd<47>;
	.reg .b64 	%rd<286>;


	// begin inline asm
	call (%r112), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r113, [params+200];
	setp.ge.u32 	%p3, %r112, %r113;
	@%p3 bra 	$L__BB2_111;

	ld.const.u64 	%rd1, [params+192];
	setp.eq.s64 	%p4, %rd1, 0;
	@%p4 bra 	$L__BB2_3;

	cvta.to.global.u64 	%rd69, %rd1;
	cvt.u64.u32 	%rd70, %r112;
	add.s64 	%rd71, %rd69, %rd70;
	ld.global.u8 	%rs3, [%rd71];
	setp.eq.s16 	%p5, %rs3, 0;
	@%p5 bra 	$L__BB2_111;

$L__BB2_3:
	ld.const.u64 	%rd72, [params+136];
	cvta.to.global.u64 	%rd73, %rd72;
	mul.wide.u32 	%rd74, %r112, 4;
	add.s64 	%rd75, %rd73, %rd74;
	ld.const.u64 	%rd76, [params+144];
	cvta.to.global.u64 	%rd77, %rd76;
	add.s64 	%rd78, %rd77, %rd74;
	ld.const.u64 	%rd79, [params+152];
	cvta.to.global.u64 	%rd80, %rd79;
	add.s64 	%rd81, %rd80, %rd74;
	ld.global.f32 	%f927, [%rd81];
	ld.global.f32 	%f926, [%rd78];
	ld.global.f32 	%f925, [%rd75];
	ld.const.u64 	%rd82, [params+160];
	cvta.to.global.u64 	%rd83, %rd82;
	add.s64 	%rd84, %rd83, %rd74;
	ld.const.u64 	%rd85, [params+168];
	cvta.to.global.u64 	%rd86, %rd85;
	add.s64 	%rd87, %rd86, %rd74;
	ld.const.u64 	%rd88, [params+176];
	cvta.to.global.u64 	%rd89, %rd88;
	add.s64 	%rd90, %rd89, %rd74;
	ld.global.f32 	%f315, [%rd84];
	ld.global.f32 	%f316, [%rd87];
	mul.ftz.f32 	%f317, %f316, %f316;
	fma.rn.ftz.f32 	%f318, %f315, %f315, %f317;
	ld.global.f32 	%f319, [%rd90];
	fma.rn.ftz.f32 	%f320, %f319, %f319, %f318;
	mov.f32 	%f321, 0f2B8CBCCC;
	max.ftz.f32 	%f322, %f320, %f321;
	rsqrt.approx.ftz.f32 	%f323, %f322;
	mul.ftz.f32 	%f7, %f315, %f323;
	mul.ftz.f32 	%f8, %f316, %f323;
	mul.ftz.f32 	%f9, %f319, %f323;
	ld.const.u64 	%rd91, [params+208];
	cvta.to.global.u64 	%rd92, %rd91;
	add.s64 	%rd93, %rd92, %rd74;
	ld.const.u64 	%rd94, [params+216];
	cvta.to.global.u64 	%rd95, %rd94;
	add.s64 	%rd96, %rd95, %rd74;
	ld.const.u64 	%rd97, [params+224];
	cvta.to.global.u64 	%rd98, %rd97;
	add.s64 	%rd99, %rd98, %rd74;
	ld.global.f32 	%f921, [%rd99];
	ld.global.f32 	%f920, [%rd96];
	ld.global.f32 	%f919, [%rd93];
	ld.const.u64 	%rd100, [params+232];
	cvta.to.global.u64 	%rd101, %rd100;
	add.s64 	%rd102, %rd101, %rd74;
	ld.const.u64 	%rd103, [params+240];
	cvta.to.global.u64 	%rd104, %rd103;
	add.s64 	%rd105, %rd104, %rd74;
	ld.const.u64 	%rd106, [params+248];
	cvta.to.global.u64 	%rd107, %rd106;
	add.s64 	%rd108, %rd107, %rd74;
	ld.global.f32 	%f13, [%rd102];
	ld.global.f32 	%f14, [%rd105];
	mul.ftz.f32 	%f324, %f8, %f14;
	fma.rn.ftz.f32 	%f325, %f7, %f13, %f324;
	ld.global.f32 	%f15, [%rd108];
	fma.rn.ftz.f32 	%f326, %f9, %f15, %f325;
	mul.ftz.f32 	%f327, %f7, %f326;
	mul.ftz.f32 	%f328, %f8, %f326;
	mul.ftz.f32 	%f329, %f9, %f326;
	sub.ftz.f32 	%f16, %f13, %f327;
	sub.ftz.f32 	%f17, %f14, %f328;
	sub.ftz.f32 	%f18, %f15, %f329;
	mul.ftz.f32 	%f330, %f17, %f17;
	fma.rn.ftz.f32 	%f331, %f16, %f16, %f330;
	fma.rn.ftz.f32 	%f19, %f18, %f18, %f331;
	setp.gtu.ftz.f32 	%p6, %f19, 0f2B8CBCCC;
	@%p6 bra 	$L__BB2_7;
	bra.uni 	$L__BB2_4;

$L__BB2_7:
	max.ftz.f32 	%f369, %f19, %f321;
	rsqrt.approx.ftz.f32 	%f370, %f369;
	mul.ftz.f32 	%f932, %f18, %f370;
	mul.ftz.f32 	%f930, %f17, %f370;
	mul.ftz.f32 	%f928, %f16, %f370;
	bra.uni 	$L__BB2_8;

$L__BB2_4:
	mul.ftz.f32 	%f332, %f8, %f8;
	fma.rn.ftz.f32 	%f333, %f7, %f7, %f332;
	fma.rn.ftz.f32 	%f334, %f9, %f9, %f333;
	max.ftz.f32 	%f336, %f334, %f321;
	rsqrt.approx.ftz.f32 	%f337, %f336;
	mul.ftz.f32 	%f20, %f7, %f337;
	mul.ftz.f32 	%f21, %f8, %f337;
	mul.ftz.f32 	%f22, %f9, %f337;
	mul.ftz.f32 	%f338, %f14, %f21;
	fma.rn.ftz.f32 	%f339, %f13, %f20, %f338;
	fma.rn.ftz.f32 	%f340, %f15, %f22, %f339;
	mul.ftz.f32 	%f341, %f20, %f340;
	mul.ftz.f32 	%f342, %f21, %f340;
	mul.ftz.f32 	%f343, %f22, %f340;
	sub.ftz.f32 	%f23, %f13, %f341;
	sub.ftz.f32 	%f24, %f14, %f342;
	sub.ftz.f32 	%f25, %f15, %f343;
	mul.ftz.f32 	%f344, %f24, %f24;
	fma.rn.ftz.f32 	%f345, %f23, %f23, %f344;
	fma.rn.ftz.f32 	%f26, %f25, %f25, %f345;
	setp.gt.ftz.f32 	%p7, %f26, 0f2B8CBCCC;
	@%p7 bra 	$L__BB2_6;
	bra.uni 	$L__BB2_5;

$L__BB2_6:
	mov.f32 	%f365, 0f2B8CBCCC;
	max.ftz.f32 	%f366, %f26, %f365;
	rsqrt.approx.ftz.f32 	%f367, %f366;
	mul.ftz.f32 	%f932, %f25, %f367;
	mul.ftz.f32 	%f930, %f24, %f367;
	mul.ftz.f32 	%f928, %f23, %f367;
	bra.uni 	$L__BB2_8;

$L__BB2_5:
	abs.ftz.f32 	%f346, %f22;
	setp.lt.ftz.f32 	%p8, %f346, 0f3F666666;
	selp.f32 	%f347, 0f3F800000, 0f00000000, %p8;
	selp.f32 	%f348, 0f00000000, 0f3F800000, %p8;
	mov.f32 	%f349, 0f00000000;
	mul.ftz.f32 	%f350, %f21, %f348;
	fma.rn.ftz.f32 	%f351, %f20, 0f00000000, %f350;
	fma.rn.ftz.f32 	%f352, %f22, %f347, %f351;
	mul.ftz.f32 	%f353, %f20, %f352;
	mul.ftz.f32 	%f354, %f21, %f352;
	mul.ftz.f32 	%f355, %f22, %f352;
	sub.ftz.f32 	%f356, %f349, %f353;
	sub.ftz.f32 	%f357, %f348, %f354;
	sub.ftz.f32 	%f358, %f347, %f355;
	mul.ftz.f32 	%f359, %f357, %f357;
	fma.rn.ftz.f32 	%f360, %f356, %f356, %f359;
	fma.rn.ftz.f32 	%f361, %f358, %f358, %f360;
	mov.f32 	%f362, 0f2B8CBCCC;
	max.ftz.f32 	%f363, %f361, %f362;
	rsqrt.approx.ftz.f32 	%f364, %f363;
	mul.ftz.f32 	%f932, %f364, %f358;
	mul.ftz.f32 	%f930, %f364, %f357;
	mul.ftz.f32 	%f928, %f364, %f356;

$L__BB2_8:
	ld.const.u32 	%r2, [params+256];
	setp.lt.s32 	%p9, %r2, 0;
	@%p9 bra 	$L__BB2_111;

	ld.const.u64 	%rd2, [params];
	ld.const.u64 	%rd3, [params+184];
	ld.const.u64 	%rd4, [params+8];
	ld.const.v2.u32 	{%r115, %r116}, [params+128];
	ld.const.v2.u32 	{%r117, %r118}, [params+288];
	ld.const.u64 	%rd109, [params+120];
	cvta.to.global.u64 	%rd5, %rd109;
	ld.const.v2.f32 	{%f375, %f376}, [params+296];
	ld.const.u64 	%rd110, [params+24];
	cvta.to.global.u64 	%rd6, %rd110;
	ld.const.u64 	%rd111, [params+48];
	cvta.to.global.u64 	%rd7, %rd111;
	ld.const.u64 	%rd112, [params+72];
	cvta.to.global.u64 	%rd8, %rd112;
	ld.const.u64 	%rd113, [params+32];
	cvta.to.global.u64 	%rd9, %rd113;
	ld.const.u64 	%rd114, [params+56];
	cvta.to.global.u64 	%rd10, %rd114;
	ld.const.u64 	%rd115, [params+80];
	cvta.to.global.u64 	%rd11, %rd115;
	ld.const.u64 	%rd116, [params+40];
	cvta.to.global.u64 	%rd12, %rd116;
	ld.const.u64 	%rd117, [params+64];
	cvta.to.global.u64 	%rd13, %rd117;
	ld.const.u64 	%rd118, [params+88];
	cvta.to.global.u64 	%rd14, %rd118;
	ld.const.u64 	%rd119, [params+96];
	cvta.to.global.u64 	%rd15, %rd119;
	ld.const.u64 	%rd120, [params+104];
	cvta.to.global.u64 	%rd16, %rd120;
	ld.const.u64 	%rd121, [params+112];
	cvta.to.global.u64 	%rd17, %rd121;
	ld.const.v2.f32 	{%f377, %f378}, [params+264];
	ld.const.v2.f32 	{%f379, %f380}, [params+304];
	ld.const.v2.u32 	{%r119, %r120}, [params+312];
	ld.const.u32 	%r10, [params+320];
	ld.const.v2.u32 	{%r121, %r122}, [params+368];
	mov.u32 	%r380, 0;
	ld.const.u64 	%rd18, [params+360];
	ld.const.f32 	%f56, [params+260];
	ld.const.v2.u32 	{%r124, %r125}, [params+272];
	ld.const.u64 	%rd122, [params+328];
	cvta.to.global.u64 	%rd19, %rd122;
	ld.const.u64 	%rd123, [params+336];
	cvta.to.global.u64 	%rd20, %rd123;
	ld.const.u64 	%rd124, [params+352];
	cvta.to.global.u64 	%rd21, %rd124;
	ld.const.u64 	%rd125, [params+344];
	cvta.to.global.u64 	%rd22, %rd125;
	setp.eq.s32 	%p10, %r122, 0;
	ld.const.u64 	%rd126, [params+456];
	setp.eq.s64 	%p11, %rd126, 0;
	or.pred  	%p1, %p10, %p11;
	ld.const.v2.u32 	{%r126, %r127}, [params+280];
	ld.const.v2.u32 	{%r128, %r129}, [params+376];
	ld.const.u32 	%r130, [params+384];
	setp.gt.s32 	%p12, %r130, 1;
	selp.b32 	%r18, %r130, 1, %p12;
	setp.ne.s32 	%p13, %r128, 0;
	and.pred  	%p2, %p12, %p13;
	cvta.to.global.u64 	%rd23, %rd126;
	cvt.rn.f32.s32 	%f57, %r18;
	ld.const.u64 	%rd127, [params+464];
	cvta.to.global.u64 	%rd24, %rd127;
	ld.const.u64 	%rd128, [params+472];
	cvta.to.global.u64 	%rd25, %rd128;
	ld.const.u64 	%rd129, [params+480];
	cvta.to.global.u64 	%rd26, %rd129;
	ld.const.u64 	%rd130, [params+488];
	cvta.to.global.u64 	%rd27, %rd130;
	ld.const.u64 	%rd131, [params+496];
	cvta.to.global.u64 	%rd28, %rd131;
	ld.const.u64 	%rd132, [params+504];
	cvta.to.global.u64 	%rd29, %rd132;
	ld.const.u64 	%rd133, [params+512];
	cvta.to.global.u64 	%rd30, %rd133;
	ld.const.u64 	%rd134, [params+520];
	cvta.to.global.u64 	%rd31, %rd134;
	ld.const.u64 	%rd135, [params+528];
	cvta.to.global.u64 	%rd32, %rd135;
	ld.const.u64 	%rd136, [params+536];
	cvta.to.global.u64 	%rd33, %rd136;
	ld.const.u64 	%rd137, [params+544];
	cvta.to.global.u64 	%rd34, %rd137;
	ld.const.u64 	%rd138, [params+552];
	cvta.to.global.u64 	%rd35, %rd138;
	ld.const.u64 	%rd139, [params+560];
	cvta.to.global.u64 	%rd36, %rd139;
	ld.const.u64 	%rd140, [params+568];
	cvta.to.global.u64 	%rd37, %rd140;
	ld.const.u64 	%rd141, [params+576];
	cvta.to.global.u64 	%rd38, %rd141;
	ld.const.u64 	%rd142, [params+584];
	cvta.to.global.u64 	%rd39, %rd142;
	ld.const.u64 	%rd143, [params+592];
	cvta.to.global.u64 	%rd40, %rd143;
	ld.const.u64 	%rd144, [params+600];
	cvta.to.global.u64 	%rd41, %rd144;
	ld.const.u64 	%rd145, [params+608];
	cvta.to.global.u64 	%rd42, %rd145;
	ld.const.u64 	%rd146, [params+400];
	cvta.to.global.u64 	%rd43, %rd146;
	ld.const.u64 	%rd147, [params+408];
	cvta.to.global.u64 	%rd44, %rd147;
	ld.const.u64 	%rd148, [params+416];
	cvta.to.global.u64 	%rd45, %rd148;
	ld.const.u64 	%rd149, [params+424];
	cvta.to.global.u64 	%rd46, %rd149;
	ld.const.u64 	%rd150, [params+432];
	cvta.to.global.u64 	%rd47, %rd150;
	ld.const.u64 	%rd151, [params+440];
	cvta.to.global.u64 	%rd48, %rd151;
	ld.const.u64 	%rd152, [params+392];
	cvta.to.global.u64 	%rd49, %rd152;
	ld.const.u64 	%rd153, [params+448];
	cvta.to.global.u64 	%rd50, %rd153;
	mov.f32 	%f918, 0f00000000;
	not.pred 	%p145, %p2;
	mov.f32 	%f922, %f7;
	mov.f32 	%f923, %f8;
	mov.f32 	%f924, %f9;
	mov.f32 	%f929, %f918;
	mov.f32 	%f931, %f918;
	mov.f32 	%f933, %f918;

$L__BB2_10:
	setp.ne.s32 	%p14, %r380, 0;
	setp.eq.s64 	%p15, %rd3, 0;
	or.pred  	%p16, %p14, %p15;
	mov.f32 	%f934, 0f4CBEBC20;
	@%p16 bra 	$L__BB2_12;

	cvta.to.global.u64 	%rd154, %rd3;
	add.s64 	%rd156, %rd154, %rd74;
	ld.global.f32 	%f934, [%rd156];

$L__BB2_12:
	abs.ftz.f32 	%f382, %f934;
	setp.geu.ftz.f32 	%p17, %f382, 0f7F800000;
	selp.f32 	%f76, 0f4CBEBC20, %f934, %p17;
	setp.eq.s64 	%p18, %rd2, 0;
	mov.u32 	%r381, 0;
	mov.u32 	%r385, 1287568416;
	mov.u32 	%r382, %r381;
	mov.u32 	%r383, %r381;
	mov.u32 	%r384, %r381;
	mov.u32 	%r386, %r381;
	@%p18 bra 	$L__BB2_14;

	mov.f32 	%f389, 0f3727C5AC;
	mov.f32 	%f391, 0f00000000;
	mov.u32 	%r170, 255;
	mov.u32 	%r173, 1;
	mov.u32 	%r175, 6;
	mov.u32 	%r177, 1287568416;
	mov.u32 	%r207, 0;
	// begin inline asm
	call(%r386,%r385,%r384,%r383,%r382,%r381,%r143,%r144,%r145,%r146,%r147,%r148,%r149,%r150,%r151,%r152,%r153,%r154,%r155,%r156,%r157,%r158,%r159,%r160,%r161,%r162,%r163,%r164,%r165,%r166,%r167,%r168),_optix_trace_typed_32,(%r207,%rd2,%f925,%f926,%f927,%f922,%f923,%f924,%f389,%f76,%f391,%r170,%r173,%r207,%r173,%r207,%r175,%r207,%r177,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207,%r207);
	// end inline asm

$L__BB2_14:
	ld.const.u32 	%r379, [params+16];
	setp.eq.s32 	%p19, %r379, 0;
	@%p19 bra 	$L__BB2_21;

	setp.eq.s64 	%p20, %rd4, 0;
	mov.u32 	%r387, 0;
	mov.u32 	%r391, 1287568416;
	mov.u32 	%r388, %r387;
	mov.u32 	%r389, %r387;
	mov.u32 	%r390, %r387;
	mov.u32 	%r392, %r387;
	@%p20 bra 	$L__BB2_17;

	mov.f32 	%f398, 0f3727C5AC;
	mov.f32 	%f400, 0f00000000;
	mov.u32 	%r247, 255;
	mov.u32 	%r250, 1;
	mov.u32 	%r252, 6;
	mov.u32 	%r254, 1287568416;
	mov.u32 	%r284, 0;
	// begin inline asm
	call(%r392,%r391,%r390,%r389,%r388,%r387,%r220,%r221,%r222,%r223,%r224,%r225,%r226,%r227,%r228,%r229,%r230,%r231,%r232,%r233,%r234,%r235,%r236,%r237,%r238,%r239,%r240,%r241,%r242,%r243,%r244,%r245),_optix_trace_typed_32,(%r284,%rd4,%f925,%f926,%f927,%f922,%f923,%f924,%f398,%f76,%f400,%r247,%r250,%r284,%r250,%r284,%r252,%r284,%r254,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284,%r284);
	// end inline asm

$L__BB2_17:
	setp.eq.s32 	%p21, %r386, 0;
	mov.u32 	%r393, %r392;
	mov.u32 	%r394, %r391;
	mov.u32 	%r395, %r390;
	mov.u32 	%r396, %r389;
	mov.u32 	%r397, %r388;
	mov.u32 	%r398, %r387;
	@%p21 bra 	$L__BB2_22;

	setp.eq.s32 	%p22, %r392, 0;
	mov.u32 	%r393, %r386;
	mov.u32 	%r394, %r385;
	mov.u32 	%r395, %r384;
	mov.u32 	%r396, %r383;
	mov.u32 	%r397, %r382;
	mov.u32 	%r398, %r381;
	@%p22 bra 	$L__BB2_22;

	mov.b32 	%f401, %r391;
	mov.b32 	%f402, %r385;
	setp.lt.ftz.f32 	%p23, %f401, %f402;
	mov.u32 	%r393, %r386;
	mov.u32 	%r394, %r385;
	mov.u32 	%r395, %r384;
	mov.u32 	%r396, %r383;
	mov.u32 	%r397, %r382;
	mov.u32 	%r398, %r381;
	@%p23 bra 	$L__BB2_20;
	bra.uni 	$L__BB2_22;

$L__BB2_20:
	mov.u32 	%r393, %r392;
	mov.u32 	%r394, %r391;
	mov.u32 	%r395, %r390;
	mov.u32 	%r396, %r389;
	mov.u32 	%r397, %r388;
	mov.u32 	%r398, %r387;
	bra.uni 	$L__BB2_22;

$L__BB2_21:
	mov.u32 	%r393, %r386;
	mov.u32 	%r394, %r385;
	mov.u32 	%r395, %r384;
	mov.u32 	%r396, %r383;
	mov.u32 	%r397, %r382;
	mov.u32 	%r398, %r381;

$L__BB2_22:
	setp.eq.s32 	%p24, %r393, 0;
	mov.b32 	%f403, %r394;
	selp.f32 	%f77, 0f4CBEBC20, %f403, %p24;
	setp.eq.s32 	%p25, %r380, 0;
	@%p25 bra 	$L__BB2_65;

	mul.ftz.f32 	%f404, %f928, %f928;
	fma.rn.ftz.f32 	%f405, %f929, %f929, %f404;
	mul.ftz.f32 	%f406, %f930, %f930;
	fma.rn.ftz.f32 	%f407, %f931, %f931, %f406;
	add.ftz.f32 	%f408, %f407, %f405;
	mul.ftz.f32 	%f409, %f932, %f932;
	fma.rn.ftz.f32 	%f410, %f933, %f933, %f409;
	add.ftz.f32 	%f411, %f410, %f408;
	setp.le.ftz.f32 	%p26, %f411, 0f00000000;
	@%p26 bra 	$L__BB2_65;

	setp.eq.s32 	%p27, %r118, 1;
	setp.eq.s32 	%p28, %r118, 0;
	selp.f32 	%f412, %f923, %f924, %p27;
	selp.f32 	%f81, %f922, %f412, %p28;
	abs.ftz.f32 	%f82, %f81;
	setp.le.ftz.f32 	%p29, %f82, 0f358637BD;
	@%p29 bra 	$L__BB2_65;

	setp.ge.ftz.f32 	%p32, %f81, 0f00000000;
	selp.f32 	%f413, 0f358637BD, 0fB58637BD, %p32;
	add.ftz.f32 	%f414, %f81, %f413;
	selp.f32 	%f415, %f926, %f927, %p27;
	selp.f32 	%f416, %f925, %f415, %p28;
	sub.ftz.f32 	%f417, %f375, %f416;
	div.approx.ftz.f32 	%f86, %f417, %f414;
	setp.leu.ftz.f32 	%p33, %f86, 0f3727C5AC;
	setp.geu.ftz.f32 	%p34, %f86, %f77;
	or.pred  	%p35, %p34, %p33;
	@%p35 bra 	$L__BB2_65;

	fma.rn.ftz.f32 	%f87, %f922)PTX_CHUNK"
R"PTX_CHUNK(, %f86, %f925;
	fma.rn.ftz.f32 	%f88, %f923, %f86, %f926;
	fma.rn.ftz.f32 	%f935, %f924, %f86, %f927;
	mov.f32 	%f936, %f88;
	@%p28 bra 	$L__BB2_29;

	setp.ne.s32 	%p37, %r118, 1;
	mov.f32 	%f936, %f87;
	@%p37 bra 	$L__BB2_28;
	bra.uni 	$L__BB2_29;

$L__BB2_28:
	mov.f32 	%f935, %f88;
	mov.f32 	%f936, %f87;

$L__BB2_29:
	setp.lt.ftz.f32 	%p38, %f936, %f376;
	setp.ge.ftz.f32 	%p39, %f936, %f379;
	or.pred  	%p40, %p38, %p39;
	setp.lt.ftz.f32 	%p41, %f935, %f380;
	or.pred  	%p42, %p40, %p41;
	mov.b32 	%f418, %r119;
	setp.ge.ftz.f32 	%p43, %f935, %f418;
	or.pred  	%p44, %p42, %p43;
	setp.lt.s32 	%p45, %r120, 1;
	sub.ftz.f32 	%f419, %f379, %f376;
	setp.le.ftz.f32 	%p46, %f419, 0f00000000;
	sub.ftz.f32 	%f420, %f418, %f380;
	setp.le.ftz.f32 	%p47, %f420, 0f00000000;
	or.pred  	%p48, %p46, %p47;
	or.pred  	%p49, %p45, %p48;
	setp.lt.s32 	%p50, %r10, 1;
	or.pred  	%p51, %p50, %p49;
	or.pred  	%p52, %p44, %p51;
	@%p52 bra 	$L__BB2_65;

	@%p28 bra 	$L__BB2_33;

	mov.f32 	%f937, %f936;
	mov.f32 	%f938, %f935;
	mov.f32 	%f939, %f375;
	@%p27 bra 	$L__BB2_32;
	bra.uni 	$L__BB2_34;

$L__BB2_32:
	mov.f32 	%f937, %f936;
	mov.f32 	%f938, %f375;
	mov.f32 	%f939, %f935;
	bra.uni 	$L__BB2_34;

$L__BB2_33:
	mov.f32 	%f937, %f375;
	mov.f32 	%f938, %f936;
	mov.f32 	%f939, %f935;

$L__BB2_34:
	cvt.rn.f32.s32 	%f914, %r10;
	cvt.rn.f32.s32 	%f913, %r120;
	sub.ftz.f32 	%f424, %f936, %f376;
	div.approx.ftz.f32 	%f425, %f424, %f419;
	mul.ftz.f32 	%f426, %f425, %f913;
	cvt.rzi.ftz.s32.f32 	%r286, %f426;
	max.s32 	%r287, %r286, 0;
	add.s32 	%r288, %r120, -1;
	sub.ftz.f32 	%f429, %f935, %f380;
	div.approx.ftz.f32 	%f430, %f429, %f420;
	mul.ftz.f32 	%f431, %f430, %f914;
	cvt.rzi.ftz.s32.f32 	%r289, %f431;
	max.s32 	%r290, %r289, 0;
	add.s32 	%r291, %r10, -1;
	sub.ftz.f32 	%f432, %f937, %f919;
	sub.ftz.f32 	%f433, %f938, %f920;
	sub.ftz.f32 	%f434, %f939, %f921;
	mul.ftz.f32 	%f435, %f433, %f433;
	fma.rn.ftz.f32 	%f436, %f432, %f432, %f435;
	fma.rn.ftz.f32 	%f437, %f434, %f434, %f436;
	mov.f32 	%f438, 0f00000000;
	max.ftz.f32 	%f439, %f437, %f438;
	sqrt.approx.ftz.f32 	%f107, %f439;
	mov.f32 	%f440, 0f358637BD;
	max.ftz.f32 	%f441, %f107, %f440;
	mul.ftz.f32 	%f442, %f441, 0f41490FDB;
	div.approx.ftz.f32 	%f443, %f56, %f442;
	mov.b32 	%f444, %r124;
	max.ftz.f32 	%f445, %f444, %f440;
	div.approx.ftz.f32 	%f446, %f378, %f445;
	mul.ftz.f32 	%f447, %f107, %f446;
	mul.ftz.f32 	%f448, %f107, %f447;
	max.ftz.f32 	%f449, %f82, %f440;
	div.approx.ftz.f32 	%f450, %f448, %f449;
	max.ftz.f32 	%f451, %f450, %f438;
	sqrt.approx.ftz.f32 	%f452, %f451;
	mul.ftz.f32 	%f108, %f443, %f452;
	abs.ftz.f32 	%f453, %f377;
	setp.gt.ftz.f32 	%p55, %f453, 0f358637BD;
	min.s32 	%r292, %r290, %r291;
	min.s32 	%r293, %r287, %r288;
	mad.lo.s32 	%r81, %r292, %r120, %r293;
	mov.f32 	%f940, %f377;
	@%p55 bra 	$L__BB2_36;

	max.ftz.f32 	%f455, %f56, %f440;
	mov.f32 	%f456, 0f40C90FDB;
	div.approx.ftz.f32 	%f940, %f456, %f455;

$L__BB2_36:
	cvt.ftz.f64.f32 	%fd14, %f107;
	cvt.ftz.f64.f32 	%fd15, %f940;
	mul.f64 	%fd1, %fd14, %fd15;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r82}, %fd1;
	}
	and.b32  	%r294, %r82, 2147483647;
	{
	.reg .b32 %temp;
	mov.b64 	{%r295, %temp}, %fd1;
	}
	mov.f64 	%fd16, 0d401921FB54442D18;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r296}, %fd16;
	}
	and.b32  	%r297, %r296, 2147483647;
	mov.b64 	%fd43, {%r295, %r294};
	{
	.reg .b32 %temp;
	mov.b64 	{%r298, %temp}, %fd16;
	}
	mov.b64 	%fd44, {%r298, %r297};
	setp.gt.u32 	%p56, %r294, 2146435071;
	setp.gt.u32 	%p57, %r297, 2146435071;
	or.pred  	%p58, %p56, %p57;
	@%p58 bra 	$L__BB2_53;
	bra.uni 	$L__BB2_37;

$L__BB2_53:
	setp.le.f64 	%p93, %fd43, 0d7FF0000000000000;
	setp.le.f64 	%p94, %fd44, 0d7FF0000000000000;
	and.pred  	%p95, %p93, %p94;
	@%p95 bra 	$L__BB2_55;
	bra.uni 	$L__BB2_54;

$L__BB2_55:
	setp.eq.f64 	%p96, %fd43, 0d7FF0000000000000;
	selp.f64 	%fd46, 0dFFF8000000000000, %fd1, %p96;
	bra.uni 	$L__BB2_56;

$L__BB2_37:
	setp.eq.f64 	%p59, %fd44, 0d0000000000000000;
	mov.f64 	%fd46, 0dFFF8000000000000;
	@%p59 bra 	$L__BB2_56;

	setp.ltu.f64 	%p60, %fd43, %fd44;
	mov.f64 	%fd46, %fd1;
	@%p60 bra 	$L__BB2_56;

	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r299}, %fd43;
	}
	shr.u32 	%r399, %r299, 20;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r300}, %fd44;
	}
	shr.u32 	%r400, %r300, 20;
	setp.ne.s32 	%p61, %r399, 0;
	@%p61 bra 	$L__BB2_41;

	mul.f64 	%fd43, %fd43, 0d4350000000000000;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r301}, %fd43;
	}
	shr.u32 	%r302, %r301, 20;
	add.s32 	%r399, %r302, -54;

$L__BB2_41:
	setp.ne.s32 	%p62, %r400, 0;
	@%p62 bra 	$L__BB2_43;

	mul.f64 	%fd44, %fd44, 0d4350000000000000;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r303}, %fd44;
	}
	shr.u32 	%r304, %r303, 20;
	add.s32 	%r400, %r304, -54;

$L__BB2_43:
	mov.b64 	%rd160, %fd43;
	and.b64  	%rd161, %rd160, 4503599627370495;
	or.b64  	%rd282, %rd161, 4503599627370496;
	mov.b64 	%rd162, %fd44;
	and.b64  	%rd163, %rd162, 4503599627370495;
	or.b64  	%rd52, %rd163, 4503599627370496;
	sub.s32 	%r406, %r399, %r400;
	not.b32 	%r305, %r399;
	add.s32 	%r306, %r400, %r305;
	max.s32 	%r307, %r306, -1;
	add.s32 	%r90, %r307, %r399;
	mov.u32 	%r308, 2;
	sub.s32 	%r309, %r308, %r400;
	add.s32 	%r310, %r309, %r90;
	and.b32  	%r402, %r310, 3;
	setp.eq.s32 	%p63, %r402, 0;
	@%p63 bra 	$L__BB2_45;

$L__BB2_44:
	.pragma "nounroll";
	sub.s64 	%rd164, %rd282, %rd52;
	mov.b64 	%fd18, %rd164;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r311}, %fd18;
	}
	setp.lt.s32 	%p64, %r311, 0;
	selp.b64 	%rd285, %rd282, %rd164, %p64;
	shl.b64 	%rd282, %rd285, 1;
	add.s32 	%r406, %r406, -1;
	add.s32 	%r402, %r402, -1;
	setp.ne.s32 	%p65, %r402, 0;
	@%p65 bra 	$L__BB2_44;

$L__BB2_45:
	mov.u32 	%r312, 1;
	sub.s32 	%r313, %r312, %r400;
	add.s32 	%r314, %r313, %r90;
	setp.lt.u32 	%p66, %r314, 3;
	@%p66 bra 	$L__BB2_50;

	not.b32 	%r315, %r406;
	max.s32 	%r316, %r315, -4;
	add.s32 	%r317, %r406, %r316;
	add.s32 	%r97, %r317, 4;
	shr.u32 	%r318, %r97, 2;
	add.s32 	%r319, %r318, 1;
	and.b32  	%r405, %r319, 3;
	setp.eq.s32 	%p67, %r405, 0;
	@%p67 bra 	$L__BB2_48;

$L__BB2_47:
	.pragma "nounroll";
	sub.s64 	%rd166, %rd282, %rd52;
	mov.b64 	%fd19, %rd166;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r320}, %fd19;
	}
	setp.lt.s32 	%p68, %r320, 0;
	selp.b64 	%rd167, %rd282, %rd166, %p68;
	shl.b64 	%rd168, %rd167, 1;
	sub.s64 	%rd169, %rd168, %rd52;
	mov.b64 	%fd20, %rd169;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r321}, %fd20;
	}
	setp.lt.s32 	%p69, %r321, 0;
	selp.b64 	%rd170, %rd168, %rd169, %p69;
	shl.b64 	%rd171, %rd170, 1;
	sub.s64 	%rd172, %rd171, %rd52;
	mov.b64 	%fd21, %rd172;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r322}, %fd21;
	}
	setp.lt.s32 	%p70, %r322, 0;
	selp.b64 	%rd173, %rd171, %rd172, %p70;
	shl.b64 	%rd174, %rd173, 1;
	sub.s64 	%rd175, %rd174, %rd52;
	mov.b64 	%fd22, %rd175;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r323}, %fd22;
	}
	setp.lt.s32 	%p71, %r323, 0;
	selp.b64 	%rd285, %rd174, %rd175, %p71;
	shl.b64 	%rd282, %rd285, 1;
	add.s32 	%r406, %r406, -4;
	add.s32 	%r405, %r405, -1;
	setp.ne.s32 	%p72, %r405, 0;
	@%p72 bra 	$L__BB2_47;

$L__BB2_48:
	setp.lt.u32 	%p73, %r97, 12;
	@%p73 bra 	$L__BB2_50;

$L__BB2_49:
	sub.s64 	%rd176, %rd282, %rd52;
	mov.b64 	%fd23, %rd176;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r324}, %fd23;
	}
	setp.lt.s32 	%p74, %r324, 0;
	selp.b64 	%rd177, %rd282, %rd176, %p74;
	shl.b64 	%rd178, %rd177, 1;
	sub.s64 	%rd179, %rd178, %rd52;
	mov.b64 	%fd24, %rd179;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r325}, %fd24;
	}
	setp.lt.s32 	%p75, %r325, 0;
	selp.b64 	%rd180, %rd178, %rd179, %p75;
	shl.b64 	%rd181, %rd180, 1;
	sub.s64 	%rd182, %rd181, %rd52;
	mov.b64 	%fd25, %rd182;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r326}, %fd25;
	}
	setp.lt.s32 	%p76, %r326, 0;
	selp.b64 	%rd183, %rd181, %rd182, %p76;
	shl.b64 	%rd184, %rd183, 1;
	sub.s64 	%rd185, %rd184, %rd52;
	mov.b64 	%fd26, %rd185;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r327}, %fd26;
	}
	setp.lt.s32 	%p77, %r327, 0;
	selp.b64 	%rd186, %rd184, %rd185, %p77;
	shl.b64 	%rd187, %rd186, 1;
	sub.s64 	%rd188, %rd187, %rd52;
	mov.b64 	%fd27, %rd188;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r328}, %fd27;
	}
	setp.lt.s32 	%p78, %r328, 0;
	selp.b64 	%rd189, %rd187, %rd188, %p78;
	shl.b64 	%rd190, %rd189, 1;
	sub.s64 	%rd191, %rd190, %rd52;
	mov.b64 	%fd28, %rd191;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r329}, %fd28;
	}
	setp.lt.s32 	%p79, %r329, 0;
	selp.b64 	%rd192, %rd190, %rd191, %p79;
	shl.b64 	%rd193, %rd192, 1;
	sub.s64 	%rd194, %rd193, %rd52;
	mov.b64 	%fd29, %rd194;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r330}, %fd29;
	}
	setp.lt.s32 	%p80, %r330, 0;
	selp.b64 	%rd195, %rd193, %rd194, %p80;
	shl.b64 	%rd196, %rd195, 1;
	sub.s64 	%rd197, %rd196, %rd52;
	mov.b64 	%fd30, %rd197;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r331}, %fd30;
	}
	setp.lt.s32 	%p81, %r331, 0;
	selp.b64 	%rd198, %rd196, %rd197, %p81;
	shl.b64 	%rd199, %rd198, 1;
	sub.s64 	%rd200, %rd199, %rd52;
	mov.b64 	%fd31, %rd200;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r332}, %fd31;
	}
	setp.lt.s32 	%p82, %r332, 0;
	selp.b64 	%rd201, %rd199, %rd200, %p82;
	shl.b64 	%rd202, %rd201, 1;
	sub.s64 	%rd203, %rd202, %rd52;
	mov.b64 	%fd32, %rd203;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r333}, %fd32;
	}
	setp.lt.s32 	%p83, %r333, 0;
	selp.b64 	%rd204, %rd202, %rd203, %p83;
	shl.b64 	%rd205, %rd204, 1;
	sub.s64 	%rd206, %rd205, %rd52;
	mov.b64 	%fd33, %rd206;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r334}, %fd33;
	}
	setp.lt.s32 	%p84, %r334, 0;
	selp.b64 	%rd207, %rd205, %rd206, %p84;
	shl.b64 	%rd208, %rd207, 1;
	sub.s64 	%rd209, %rd208, %rd52;
	mov.b64 	%fd34, %rd209;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r335}, %fd34;
	}
	setp.lt.s32 	%p85, %r335, 0;
	selp.b64 	%rd210, %rd208, %rd209, %p85;
	shl.b64 	%rd211, %rd210, 1;
	sub.s64 	%rd212, %rd211, %rd52;
	mov.b64 	%fd35, %rd212;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r336}, %fd35;
	}
	setp.lt.s32 	%p86, %r336, 0;
	selp.b64 	%rd213, %rd211, %rd212, %p86;
	shl.b64 	%rd214, %rd213, 1;
	sub.s64 	%rd215, %rd214, %rd52;
	mov.b64 	%fd36, %rd215;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r337}, %fd36;
	}
	setp.lt.s32 	%p87, %r337, 0;
	selp.b64 	%rd216, %rd214, %rd215, %p87;
	shl.b64 	%rd217, %rd216, 1;
	sub.s64 	%rd218, %rd217, %rd52;
	mov.b64 	%fd37, %rd218;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r338}, %fd37;
	}
	setp.lt.s32 	%p88, %r338, 0;
	selp.b64 	%rd219, %rd217, %rd218, %p88;
	shl.b64 	%rd220, %rd219, 1;
	sub.s64 	%rd221, %rd220, %rd52;
	mov.b64 	%fd38, %rd221;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r339}, %fd38;
	}
	setp.lt.s32 	%p89, %r339, 0;
	selp.b64 	%rd285, %rd220, %rd221, %p89;
	shl.b64 	%rd282, %rd285, 1;
	add.s32 	%r105, %r406, -16;
	setp.gt.s32 	%p90, %r406, 15;
	mov.u32 	%r406, %r105;
	@%p90 bra 	$L__BB2_49;

$L__BB2_50:
	and.b64  	%rd67, %rd285, 9223372036854775807;
	setp.eq.s64 	%p91, %rd67, 0;
	mov.f64 	%fd45, 0d0000000000000000;
	@%p91 bra 	$L__BB2_52;

	mov.b64 	%fd40, %rd67;
	mul.f64 	%fd41, %fd40, 0d4350000000000000;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r340}, %fd41;
	}
	shr.u32 	%r341, %r340, 20;
	mov.u32 	%r342, 55;
	sub.s32 	%r343, %r342, %r341;
	sub.s32 	%r344, %r400, %r343;
	shl.b64 	%rd222, %rd67, %r343;
	setp.lt.s32 	%p92, %r344, 1;
	mov.u32 	%r345, 1;
	sub.s32 	%r346, %r345, %r344;
	shr.u64 	%rd223, %rd222, %r346;
	add.s32 	%r347, %r344, -1;
	cvt.u64.u32 	%rd224, %r347;
	shl.b64 	%rd225, %rd224, 52;
	add.s64 	%rd226, %rd225, %rd222;
	selp.b64 	%rd227, %rd223, %rd226, %p92;
	mov.b64 	%fd45, %rd227;

$L__BB2_52:
	and.b32  	%r348, %r82, -2147483648;
	{
	.reg .b32 %temp;
	mov.b64 	{%temp, %r349}, %fd45;
	}
	or.b32  	%r350, %r349, %r348;
	{
	.reg .b32 %temp;
	mov.b64 	{%r351, %temp}, %fd45;
	}
	mov.b64 	%fd46, {%r351, %r350};
	bra.uni 	$L__BB2_56;

$L__BB2_54:
	mov.f64 	%fd42, 0d401921FB54442D18;
	add.rn.f64 	%fd46, %fd1, %fd42;

$L__BB2_56:
	cvt.rn.ftz.f32.f64 	%f457, %fd46;
	sin.approx.ftz.f32 	%f458, %f457;
	cos.approx.ftz.f32 	%f459, %f457;
	mul.ftz.f32 	%f460, %f108, %f459;
	mul.ftz.f32 	%f461, %f108, %f458;
	mul.ftz.f32 	%f462, %f929, %f461;
	fma.rn.ftz.f32 	%f112, %f928, %f460, %f462;
	mul.ftz.f32 	%f463, %f928, %f461;
	mul.ftz.f32 	%f464, %f929, %f460;
	sub.ftz.f32 	%f113, %f464, %f463;
	mul.ftz.f32 	%f465, %f931, %f461;
	fma.rn.ftz.f32 	%f114, %f930, %f460, %f465;
	mul.ftz.f32 	%f466, %f930, %f461;
	mul.ftz.f32 	%f467, %f931, %f460;
	sub.ftz.f32 	%f115, %f467, %f466;
	mul.ftz.f32 	%f468, %f933, %f461;
	fma.rn.ftz.f32 	%f116, %f932, %f460, %f468;
	mul.ftz.f32 	%f469, %f932, %f461;
	mul.ftz.f32 	%f470, %f933, %f460;
	sub.ftz.f32 	%f117, %f470, %f469;
	abs.ftz.f32 	%f471, %f112;
	setp.geu.ftz.f32 	%p97, %f471, 0f7F800000;
	@%p97 bra 	$L__BB2_65;

	abs.ftz.f32 	%f472, %f113;
	setp.geu.ftz.f32 	%p98, %f472, 0f7F800000;
	@%p98 bra 	$L__BB2_65;

	abs.ftz.f32 	%f473, %f114;
	setp.geu.ftz.f32 	%p99, %f473, 0f7F800000;
	@%p99 bra 	$L__BB2_65;

	abs.ftz.f32 	%f474, %f115;
	setp.geu.ftz.f32 	%p100, %f474, 0f7F800000;
	@%p100 bra 	$L__BB2_65;

	abs.ftz.f32 	%f475, %f116;
	setp.geu.ftz.f32 	%p101, %f475, 0f7F800000;
	@%p101 bra 	$L__BB2_65;

	abs.ftz.f32 	%f476, %f117;
	setp.geu.ftz.f32 	%p102, %f476, 0f7F800000;
	@%p102 bra 	$L__BB2_65;

	mul.ftz.f32 	%f477, %f113, %f113;
	fma.rn.ftz.f32 	%f478, %f112, %f112, %f477;
	mul.ftz.f32 	%f479, %f115, %f115;
	fma.rn.ftz.f32 	%f480, %f114, %f114, %f479;
	add.ftz.f32 	%f481, %f478, %f480;
	mul.ftz.f32 	%f482, %f117, %f117;
	fma.rn.ftz.f32 	%f483, %f116, %f116, %f482;
	add.ftz.f32 	%f118, %f483, %f481;
	setp.leu.ftz.f32 	%p103, %f118, 0f00000000;
	@%p103 bra 	$L__BB2_65;

	abs.ftz.f32 	%f484, %f118;
	setp.geu.ftz.f32 	%p104, %f484, 0f7F800000;
	@%p104 bra 	$L__BB2_65;

	mul.wide.s32 	%rd228, %r81, 4;
	add.s64 	%rd229, %rd43, %rd228;
	atom.global.add.f32 	%f485, [%rd229], %f112;
	add.s64 	%rd230, %rd44, %rd228;
	atom.global.add.f32 	%f486, [%rd230], %f113;
	add.s64 	%rd231, %rd45, %rd228;
	atom.global.add.f32 	%f487, [%rd231], %f114;
	add.s64 	%rd232, %rd46, %rd228;
	atom.global.add.f32 	%f488, [%rd232], %f115;
	add.s64 	%rd233, %rd47, %rd228;
	atom.global.add.f32 	%f489, [%rd233], %f116;
	add.s64 	%rd234, %rd48, %rd228;
	atom.global.add.f32 	%f490, [%rd234], %f117;
	add.s64 	%rd235, %rd49, %rd228;
	atom.global.add.f32 	%f491, [%rd235], %f118;
	atom.global.add.u32 	%r352, [%rd50], 1;

$L__BB2_65:
	setp.ge.s32 	%p106, %r380, %r2;
	or.pred  	%p107, %p24, %p106;
	@%p107 bra 	$L__BB2_111;

	setp.lt.s32 	%p108, %r398, 0;
	mov.u32 	%r408, 0;
	setp.ge.s32 	%p109, %r398, %r115;
	or.pred  	%p110, %p108, %p109;
	@%p110 bra 	$L__BB2_68;

	mul.wide.s32 	%rd236, %r398, 4;
	add.s64 	%rd237, %rd5, %rd236;
	ld.global.u32 	%r408, [%rd237];

$L__BB2_68:
	fma.rn.ftz.f32 	%f941, %f922, %f77, %f925;
	fma.rn.ftz.f32 	%f942, %f923, %f77, %f926;
	fma.rn.ftz.f32 	%f943, %f924, %f77, %f927;
	add.s32 	%r109, %r408, %r397;
	setp.lt.s32 	%p111, %r109, 0;
	setp.ge.s32 	%p112, %r109, %r116;
	mov.f32 	%f946, 0f3F800000;
	mov.f32 	%f944, 0f00000000;
	or.pred  	%p113, %p111, %p112;
	mov.f32 	%f945, %f944;
	@%p113 bra 	$L__BB2_70;

	mov.b32 	%f495, %r395;
	mov.b32 	%f496, %r396;
	mul.wide.s32 	%rd238, %r109, 4;
	add.s64 	%rd239, %rd6, %rd238;
	add.s64 	%rd240, %rd7, %rd238;
	ld.global.f32 	%f497, [%rd240];
	ld.global.f32 	%f498, [%rd239];
	fma.rn.ftz.f32 	%f499, %f497, %f495, %f498;
	add.s64 	%rd241, %rd8, %rd238;
	ld.global.f32 	%f500, [%rd241];
	add.s64 	%rd242, %rd9, %rd238;
	add.s64 	%rd243, %rd10, %rd238;
	ld.global.f32 	%f501, [%rd243];
	ld.global.f32 	%f502, [%rd242];
	fma.rn.ftz.f32 	%f503, %f501, %f495, %f502;
	add.s64 	%rd244, %rd11, %rd238;
	ld.global.f32 	%f504, [%rd244];
	add.s64 	%rd245, %rd12, %rd238;
	add.s64 	%rd246, %rd13, %rd238;
	ld.global.f32 	%f505, [%rd246];
	ld.global.f32 	%f506, [%rd245];
	fma.rn.ftz.f32 	%f507, %f505, %f495, %f506;
	add.s64 	%rd247, %rd14, %rd238;
	ld.global.f32 	%f508, [%rd247];
	fma.rn.ftz.f32 	%f943, %f508, %f496, %f507;
	fma.rn.ftz.f32 	%f942, %f504, %f496, %f503;
	fma.rn.ftz.f32 	%f941, %f500, %f496, %f499;
	add.s64 	%rd248, %rd15, %rd238;
	add.s64 	%rd249, %rd16, %rd238;
	add.s64 	%rd250, %rd17, %rd238;
	ld.global.f32 	%f509, [%rd248];
	ld.global.f32 	%f510, [%rd249];
	mul.ftz.f32 )PTX_CHUNK"
R"PTX_CHUNK(	%f511, %f510, %f510;
	fma.rn.ftz.f32 	%f512, %f509, %f509, %f511;
	ld.global.f32 	%f513, [%rd250];
	fma.rn.ftz.f32 	%f514, %f513, %f513, %f512;
	mov.f32 	%f515, 0f2B8CBCCC;
	max.ftz.f32 	%f516, %f514, %f515;
	rsqrt.approx.ftz.f32 	%f517, %f516;
	mul.ftz.f32 	%f946, %f513, %f517;
	mul.ftz.f32 	%f945, %f510, %f517;
	mul.ftz.f32 	%f944, %f509, %f517;

$L__BB2_70:
	mul.ftz.f32 	%f518, %f923, %f945;
	fma.rn.ftz.f32 	%f519, %f922, %f944, %f518;
	fma.rn.ftz.f32 	%f520, %f924, %f946, %f519;
	setp.gt.ftz.f32 	%p114, %f520, 0f00000000;
	neg.ftz.f32 	%f521, %f944;
	neg.ftz.f32 	%f522, %f945;
	neg.ftz.f32 	%f523, %f946;
	selp.f32 	%f137, %f523, %f946, %p114;
	selp.f32 	%f138, %f522, %f945, %p114;
	selp.f32 	%f139, %f521, %f944, %p114;
	mul.ftz.f32 	%f524, %f928, %f928;
	fma.rn.ftz.f32 	%f525, %f929, %f929, %f524;
	mul.ftz.f32 	%f526, %f930, %f930;
	fma.rn.ftz.f32 	%f527, %f931, %f931, %f526;
	add.ftz.f32 	%f528, %f527, %f525;
	mul.ftz.f32 	%f529, %f932, %f932;
	fma.rn.ftz.f32 	%f530, %f933, %f933, %f529;
	add.ftz.f32 	%f531, %f530, %f528;
	mul.ftz.f32 	%f972, %f531, %f378;
	mul.ftz.f32 	%f532, %f923, %f923;
	fma.rn.ftz.f32 	%f533, %f922, %f922, %f532;
	fma.rn.ftz.f32 	%f534, %f924, %f924, %f533;
	mov.f32 	%f535, 0f2B8CBCCC;
	max.ftz.f32 	%f536, %f534, %f535;
	rsqrt.approx.ftz.f32 	%f537, %f536;
	mul.ftz.f32 	%f141, %f922, %f537;
	mul.ftz.f32 	%f142, %f923, %f537;
	mul.ftz.f32 	%f143, %f924, %f537;
	mul.ftz.f32 	%f538, %f138, %f138;
	fma.rn.ftz.f32 	%f539, %f139, %f139, %f538;
	fma.rn.ftz.f32 	%f540, %f137, %f137, %f539;
	max.ftz.f32 	%f541, %f540, %f535;
	rsqrt.approx.ftz.f32 	%f542, %f541;
	mul.ftz.f32 	%f144, %f139, %f542;
	mul.ftz.f32 	%f145, %f138, %f542;
	mul.ftz.f32 	%f146, %f137, %f542;
	mul.ftz.f32 	%f543, %f142, %f145;
	fma.rn.ftz.f32 	%f544, %f141, %f144, %f543;
	fma.rn.ftz.f32 	%f147, %f143, %f146, %f544;
	add.ftz.f32 	%f545, %f147, %f147;
	mul.ftz.f32 	%f546, %f144, %f545;
	mul.ftz.f32 	%f547, %f145, %f545;
	mul.ftz.f32 	%f548, %f146, %f545;
	sub.ftz.f32 	%f549, %f141, %f546;
	sub.ftz.f32 	%f550, %f142, %f547;
	sub.ftz.f32 	%f551, %f143, %f548;
	mul.ftz.f32 	%f552, %f550, %f550;
	fma.rn.ftz.f32 	%f553, %f549, %f549, %f552;
	fma.rn.ftz.f32 	%f554, %f551, %f551, %f553;
	max.ftz.f32 	%f555, %f554, %f535;
	rsqrt.approx.ftz.f32 	%f556, %f555;
	mul.ftz.f32 	%f148, %f556, %f549;
	mul.ftz.f32 	%f149, %f556, %f550;
	mul.ftz.f32 	%f150, %f556, %f551;
	mul.ftz.f32 	%f557, %f143, %f145;
	mul.ftz.f32 	%f558, %f142, %f146;
	sub.ftz.f32 	%f151, %f557, %f558;
	mul.ftz.f32 	%f559, %f141, %f146;
	mul.ftz.f32 	%f560, %f143, %f144;
	sub.ftz.f32 	%f152, %f559, %f560;
	mul.ftz.f32 	%f561, %f142, %f144;
	mul.ftz.f32 	%f562, %f141, %f145;
	sub.ftz.f32 	%f153, %f561, %f562;
	mul.ftz.f32 	%f563, %f152, %f152;
	fma.rn.ftz.f32 	%f564, %f151, %f151, %f563;
	fma.rn.ftz.f32 	%f154, %f153, %f153, %f564;
	setp.gtu.ftz.f32 	%p115, %f154, 0f2B8CBCCC;
	@%p115 bra 	$L__BB2_74;
	bra.uni 	$L__BB2_71;

$L__BB2_74:
	max.ftz.f32 	%f602, %f154, %f535;
	rsqrt.approx.ftz.f32 	%f603, %f602;
	mul.ftz.f32 	%f949, %f153, %f603;
	mul.ftz.f32 	%f948, %f152, %f603;
	mul.ftz.f32 	%f947, %f151, %f603;
	bra.uni 	$L__BB2_75;

$L__BB2_71:
	mul.ftz.f32 	%f565, %f142, %f142;
	fma.rn.ftz.f32 	%f566, %f141, %f141, %f565;
	fma.rn.ftz.f32 	%f567, %f143, %f143, %f566;
	max.ftz.f32 	%f569, %f567, %f535;
	rsqrt.approx.ftz.f32 	%f570, %f569;
	mul.ftz.f32 	%f155, %f141, %f570;
	mul.ftz.f32 	%f156, %f142, %f570;
	mul.ftz.f32 	%f157, %f143, %f570;
	mul.ftz.f32 	%f571, %f145, %f156;
	fma.rn.ftz.f32 	%f572, %f144, %f155, %f571;
	fma.rn.ftz.f32 	%f573, %f146, %f157, %f572;
	mul.ftz.f32 	%f574, %f155, %f573;
	mul.ftz.f32 	%f575, %f156, %f573;
	mul.ftz.f32 	%f576, %f157, %f573;
	sub.ftz.f32 	%f158, %f144, %f574;
	sub.ftz.f32 	%f159, %f145, %f575;
	sub.ftz.f32 	%f160, %f146, %f576;
	mul.ftz.f32 	%f577, %f159, %f159;
	fma.rn.ftz.f32 	%f578, %f158, %f158, %f577;
	fma.rn.ftz.f32 	%f161, %f160, %f160, %f578;
	setp.gt.ftz.f32 	%p116, %f161, 0f2B8CBCCC;
	@%p116 bra 	$L__BB2_73;
	bra.uni 	$L__BB2_72;

$L__BB2_73:
	mov.f32 	%f598, 0f2B8CBCCC;
	max.ftz.f32 	%f599, %f161, %f598;
	rsqrt.approx.ftz.f32 	%f600, %f599;
	mul.ftz.f32 	%f949, %f160, %f600;
	mul.ftz.f32 	%f948, %f159, %f600;
	mul.ftz.f32 	%f947, %f158, %f600;
	bra.uni 	$L__BB2_75;

$L__BB2_72:
	abs.ftz.f32 	%f579, %f157;
	setp.lt.ftz.f32 	%p117, %f579, 0f3F666666;
	selp.f32 	%f580, 0f3F800000, 0f00000000, %p117;
	selp.f32 	%f581, 0f00000000, 0f3F800000, %p117;
	mov.f32 	%f582, 0f00000000;
	mul.ftz.f32 	%f583, %f156, %f581;
	fma.rn.ftz.f32 	%f584, %f155, 0f00000000, %f583;
	fma.rn.ftz.f32 	%f585, %f157, %f580, %f584;
	mul.ftz.f32 	%f586, %f155, %f585;
	mul.ftz.f32 	%f587, %f156, %f585;
	mul.ftz.f32 	%f588, %f157, %f585;
	sub.ftz.f32 	%f589, %f582, %f586;
	sub.ftz.f32 	%f590, %f581, %f587;
	sub.ftz.f32 	%f591, %f580, %f588;
	mul.ftz.f32 	%f592, %f590, %f590;
	fma.rn.ftz.f32 	%f593, %f589, %f589, %f592;
	fma.rn.ftz.f32 	%f594, %f591, %f591, %f593;
	mov.f32 	%f595, 0f2B8CBCCC;
	max.ftz.f32 	%f596, %f594, %f595;
	rsqrt.approx.ftz.f32 	%f597, %f596;
	mul.ftz.f32 	%f949, %f597, %f591;
	mul.ftz.f32 	%f948, %f597, %f590;
	mul.ftz.f32 	%f947, %f597, %f589;

$L__BB2_75:
	mul.ftz.f32 	%f604, %f143, %f948;
	mul.ftz.f32 	%f605, %f142, %f949;
	sub.ftz.f32 	%f182, %f604, %f605;
	mul.ftz.f32 	%f606, %f141, %f949;
	mul.ftz.f32 	%f607, %f143, %f947;
	sub.ftz.f32 	%f184, %f606, %f607;
	mul.ftz.f32 	%f608, %f142, %f947;
	mul.ftz.f32 	%f609, %f141, %f948;
	sub.ftz.f32 	%f185, %f608, %f609;
	mul.ftz.f32 	%f610, %f184, %f184;
	fma.rn.ftz.f32 	%f611, %f182, %f182, %f610;
	fma.rn.ftz.f32 	%f186, %f185, %f185, %f611;
	setp.gtu.ftz.f32 	%p118, %f186, 0f2B8CBCCC;
	@%p118 bra 	$L__BB2_79;
	bra.uni 	$L__BB2_76;

$L__BB2_79:
	mov.f32 	%f648, 0f2B8CBCCC;
	max.ftz.f32 	%f649, %f186, %f648;
	rsqrt.approx.ftz.f32 	%f650, %f649;
	mul.ftz.f32 	%f952, %f185, %f650;
	mul.ftz.f32 	%f951, %f184, %f650;
	mul.ftz.f32 	%f950, %f182, %f650;
	bra.uni 	$L__BB2_80;

$L__BB2_76:
	mul.ftz.f32 	%f612, %f142, %f142;
	fma.rn.ftz.f32 	%f613, %f141, %f141, %f612;
	fma.rn.ftz.f32 	%f614, %f143, %f143, %f613;
	mov.f32 	%f615, 0f2B8CBCCC;
	max.ftz.f32 	%f616, %f614, %f615;
	rsqrt.approx.ftz.f32 	%f617, %f616;
	mul.ftz.f32 	%f187, %f141, %f617;
	mul.ftz.f32 	%f188, %f142, %f617;
	mul.ftz.f32 	%f189, %f143, %f617;
	mul.ftz.f32 	%f618, %f145, %f188;
	fma.rn.ftz.f32 	%f619, %f144, %f187, %f618;
	fma.rn.ftz.f32 	%f620, %f146, %f189, %f619;
	mul.ftz.f32 	%f621, %f187, %f620;
	mul.ftz.f32 	%f622, %f188, %f620;
	mul.ftz.f32 	%f623, %f189, %f620;
	sub.ftz.f32 	%f190, %f144, %f621;
	sub.ftz.f32 	%f191, %f145, %f622;
	sub.ftz.f32 	%f192, %f146, %f623;
	mul.ftz.f32 	%f624, %f191, %f191;
	fma.rn.ftz.f32 	%f625, %f190, %f190, %f624;
	fma.rn.ftz.f32 	%f193, %f192, %f192, %f625;
	setp.gt.ftz.f32 	%p119, %f193, 0f2B8CBCCC;
	@%p119 bra 	$L__BB2_78;
	bra.uni 	$L__BB2_77;

$L__BB2_78:
	max.ftz.f32 	%f646, %f193, %f615;
	rsqrt.approx.ftz.f32 	%f647, %f646;
	mul.ftz.f32 	%f952, %f192, %f647;
	mul.ftz.f32 	%f951, %f191, %f647;
	mul.ftz.f32 	%f950, %f190, %f647;
	bra.uni 	$L__BB2_80;

$L__BB2_77:
	abs.ftz.f32 	%f626, %f189;
	setp.lt.ftz.f32 	%p120, %f626, 0f3F666666;
	selp.f32 	%f627, 0f3F800000, 0f00000000, %p120;
	selp.f32 	%f628, 0f00000000, 0f3F800000, %p120;
	mov.f32 	%f629, 0f00000000;
	mul.ftz.f32 	%f630, %f188, %f628;
	fma.rn.ftz.f32 	%f631, %f187, 0f00000000, %f630;
	fma.rn.ftz.f32 	%f632, %f189, %f627, %f631;
	mul.ftz.f32 	%f633, %f187, %f632;
	mul.ftz.f32 	%f634, %f188, %f632;
	mul.ftz.f32 	%f635, %f189, %f632;
	sub.ftz.f32 	%f636, %f629, %f633;
	sub.ftz.f32 	%f637, %f628, %f634;
	sub.ftz.f32 	%f638, %f627, %f635;
	mul.ftz.f32 	%f639, %f637, %f637;
	fma.rn.ftz.f32 	%f640, %f636, %f636, %f639;
	fma.rn.ftz.f32 	%f641, %f638, %f638, %f640;
	max.ftz.f32 	%f643, %f641, %f615;
	rsqrt.approx.ftz.f32 	%f644, %f643;
	mul.ftz.f32 	%f952, %f644, %f638;
	mul.ftz.f32 	%f951, %f644, %f637;
	mul.ftz.f32 	%f950, %f644, %f636;

$L__BB2_80:
	mul.ftz.f32 	%f651, %f149, %f949;
	mul.ftz.f32 	%f652, %f150, %f948;
	sub.ftz.f32 	%f212, %f652, %f651;
	mul.ftz.f32 	%f653, %f150, %f947;
	mul.ftz.f32 	%f654, %f148, %f949;
	sub.ftz.f32 	%f213, %f654, %f653;
	mul.ftz.f32 	%f655, %f148, %f948;
	mul.ftz.f32 	%f656, %f149, %f947;
	sub.ftz.f32 	%f214, %f656, %f655;
	mul.ftz.f32 	%f657, %f213, %f213;
	fma.rn.ftz.f32 	%f658, %f212, %f212, %f657;
	fma.rn.ftz.f32 	%f215, %f214, %f214, %f658;
	setp.gtu.ftz.f32 	%p121, %f215, 0f2B8CBCCC;
	@%p121 bra 	$L__BB2_84;
	bra.uni 	$L__BB2_81;

$L__BB2_84:
	mov.f32 	%f695, 0f2B8CBCCC;
	max.ftz.f32 	%f696, %f215, %f695;
	rsqrt.approx.ftz.f32 	%f697, %f696;
	mul.ftz.f32 	%f955, %f214, %f697;
	mul.ftz.f32 	%f954, %f213, %f697;
	mul.ftz.f32 	%f953, %f212, %f697;
	bra.uni 	$L__BB2_85;

$L__BB2_81:
	mul.ftz.f32 	%f659, %f149, %f149;
	fma.rn.ftz.f32 	%f660, %f148, %f148, %f659;
	fma.rn.ftz.f32 	%f661, %f150, %f150, %f660;
	mov.f32 	%f662, 0f2B8CBCCC;
	max.ftz.f32 	%f663, %f661, %f662;
	rsqrt.approx.ftz.f32 	%f664, %f663;
	mul.ftz.f32 	%f216, %f148, %f664;
	mul.ftz.f32 	%f217, %f149, %f664;
	mul.ftz.f32 	%f218, %f150, %f664;
	mul.ftz.f32 	%f665, %f145, %f217;
	fma.rn.ftz.f32 	%f666, %f144, %f216, %f665;
	fma.rn.ftz.f32 	%f667, %f146, %f218, %f666;
	mul.ftz.f32 	%f668, %f216, %f667;
	mul.ftz.f32 	%f669, %f217, %f667;
	mul.ftz.f32 	%f670, %f218, %f667;
	sub.ftz.f32 	%f219, %f144, %f668;
	sub.ftz.f32 	%f220, %f145, %f669;
	sub.ftz.f32 	%f221, %f146, %f670;
	mul.ftz.f32 	%f671, %f220, %f220;
	fma.rn.ftz.f32 	%f672, %f219, %f219, %f671;
	fma.rn.ftz.f32 	%f222, %f221, %f221, %f672;
	setp.gt.ftz.f32 	%p122, %f222, 0f2B8CBCCC;
	@%p122 bra 	$L__BB2_83;
	bra.uni 	$L__BB2_82;

$L__BB2_83:
	max.ftz.f32 	%f693, %f222, %f662;
	rsqrt.approx.ftz.f32 	%f694, %f693;
	mul.ftz.f32 	%f955, %f221, %f694;
	mul.ftz.f32 	%f954, %f220, %f694;
	mul.ftz.f32 	%f953, %f219, %f694;
	bra.uni 	$L__BB2_85;

$L__BB2_82:
	abs.ftz.f32 	%f673, %f218;
	setp.lt.ftz.f32 	%p123, %f673, 0f3F666666;
	selp.f32 	%f674, 0f3F800000, 0f00000000, %p123;
	selp.f32 	%f675, 0f00000000, 0f3F800000, %p123;
	mov.f32 	%f676, 0f00000000;
	mul.ftz.f32 	%f677, %f217, %f675;
	fma.rn.ftz.f32 	%f678, %f216, 0f00000000, %f677;
	fma.rn.ftz.f32 	%f679, %f218, %f674, %f678;
	mul.ftz.f32 	%f680, %f216, %f679;
	mul.ftz.f32 	%f681, %f217, %f679;
	mul.ftz.f32 	%f682, %f218, %f679;
	sub.ftz.f32 	%f683, %f676, %f680;
	sub.ftz.f32 	%f684, %f675, %f681;
	sub.ftz.f32 	%f685, %f674, %f682;
	mul.ftz.f32 	%f686, %f684, %f684;
	fma.rn.ftz.f32 	%f687, %f683, %f683, %f686;
	fma.rn.ftz.f32 	%f688, %f685, %f685, %f687;
	max.ftz.f32 	%f690, %f688, %f662;
	rsqrt.approx.ftz.f32 	%f691, %f690;
	mul.ftz.f32 	%f955, %f691, %f685;
	mul.ftz.f32 	%f954, %f691, %f684;
	mul.ftz.f32 	%f953, %f691, %f683;

$L__BB2_85:
	setp.le.s32 	%p124, %r121, %r109;
	or.pred  	%p126, %p111, %p124;
	setp.eq.s64 	%p127, %rd18, 0;
	or.pred  	%p128, %p126, %p127;
	mov.u16 	%rs8, 0;
	mov.f32 	%f962, 0f00000000;
	mov.f32 	%f963, 0f00000000;
	mov.f32 	%f964, 0f00000000;
	mov.f32 	%f978, 0f00000000;
	mov.f32 	%f965, %f978;
	@%p128 bra 	$L__BB2_97;

	cvt.s64.s32 	%rd68, %r109;
	cvta.to.global.u64 	%rd251, %rd18;
	add.s64 	%rd252, %rd251, %rd68;
	ld.global.u8 	%rs6, [%rd252];
	setp.eq.s16 	%p129, %rs6, 0;
	@%p129 bra 	$L__BB2_97;

	mov.f32 	%f708, 0f358637BD;
	max.ftz.f32 	%f709, %f56, %f708;
	mov.f32 	%f710, 0f4EE08C7C;
	div.approx.ftz.f32 	%f711, %f710, %f709;
	max.ftz.f32 	%f712, %f711, %f708;
	shl.b64 	%rd253, %rd68, 2;
	add.s64 	%rd254, %rd22, %rd253;
	ld.global.f32 	%f241, [%rd254];
	add.s64 	%rd255, %rd19, %rd253;
	ld.global.f32 	%f713, [%rd255];
	max.ftz.f32 	%f242, %f713, %f708;
	add.s64 	%rd256, %rd20, %rd253;
	ld.global.f32 	%f714, [%rd256];
	mov.f32 	%f707, 0f00000000;
	max.ftz.f32 	%f715, %f714, %f707;
	add.s64 	%rd257, %rd21, %rd253;
	ld.global.f32 	%f716, [%rd257];
	max.ftz.f32 	%f243, %f716, %f708;
	neg.ftz.f32 	%f717, %f715;
	mul.ftz.f32 	%f718, %f712, 0f2D1BC3B8;
	div.approx.ftz.f32 	%f244, %f717, %f718;
	abs.ftz.f32 	%f719, %f147;
	abs.ftz.f32 	%f720, %f719;
	max.ftz.f32 	%f721, %f720, %f708;
	mov.f32 	%f722, 0f3F800000;
	min.ftz.f32 	%f245, %f721, %f722;
	mul.ftz.f32 	%f723, %f245, %f245;
	sub.ftz.f32 	%f724, %f722, %f723;
	max.ftz.f32 	%f725, %f707, %f724;
	mul.ftz.f32 	%f726, %f242, %f243;
	mul.ftz.f32 	%f727, %f244, 0f00000000;
	sub.ftz.f32 	%f728, %f726, %f727;
	mul.ftz.f32 	%f729, %f243, %f244;
	fma.rn.ftz.f32 	%f246, %f242, 0f00000000, %f729;
	sub.ftz.f32 	%f247, %f728, %f725;
	abs.ftz.f32 	%f730, %f247;
	abs.ftz.f32 	%f731, %f246;
	mov.b32 	%r354, %f731;
	mov.b32 	%r355, %f730;
	min.s32 	%r356, %r354, %r355;
	mov.b32 	%f732, %r356;
	max.s32 	%r357, %r354, %r355;
	mov.b32 	%f733, %r357;
	and.b32  	%r358, %r357, -33554432;
	mov.u32 	%r359, 2122317824;
	sub.s32 	%r360, %r359, %r358;
	mov.b32 	%f734, %r360;
	mul.ftz.f32 	%f735, %f732, %f734;
	mul.ftz.f32 	%f736, %f733, %f734;
	mul.ftz.f32 	%f737, %f735, %f735;
	fma.rn.ftz.f32 	%f738, %f736, %f736, %f737;
	sqrt.approx.ftz.f32 	%f739, %f738;
	or.b32  	%r361, %r358, 8388608;
	mov.b32 	%f740, %r361;
	mul.ftz.f32 	%f741, %f739, %f740;
	setp.eq.ftz.f32 	%p130, %f732, 0f00000000;
	selp.f32 	%f742, %f733, %f741, %p130;
	setp.eq.ftz.f32 	%p131, %f732, 0f7F800000;
	selp.f32 	%f248, 0f7F800000, %f742, %p131;
	setp.le.ftz.f32 	%p132, %f248, 0f00000000;
	mov.f32 	%f956, %f707;
	mov.f32 	%f957, %f707;
	@%p132 bra 	$L__BB2_89;

	add.ftz.f32 	%f743, %f247, %f248;
	mul.ftz.f32 	%f744, %f743, 0f3F000000;
	mov.f32 	%f745, 0f00000000;
	max.ftz.f32 	%f746, %f745, %f744;
	sub.ftz.f32 	%f747, %f248, %f247;
	mul.ftz.f32 	%f748, %f747, 0f3F000000;
	max.ftz.f32 	%f749, %f745, %f748;
	sqrt.approx.ftz.f32 	%f750, %f749;
	copysign.f32 	%f957, %f246, %f750;
	sqrt.approx.ftz.f32 	%f956, %f746;

$L__BB2_89:
	mul.ftz.f32 	%f751, %f243, %f245;
	sub.ftz.f32 	%f752, %f751, %f956;
	sub.ftz.f32 	%f754, %f707, %f957;
	add.ftz.f32 	%f755, %f751, %f956;
	add.ftz.f32 	%f756, %f957, 0f00000000;
	mul.ftz.f32 	%f757, %f756, %f756;
	fma.rn.ftz.f32 	%f758, %f755, %f755, %f757;
	mov.f32 	%f759, 0f1E3CE508;
	max.ftz.f32 	%f760, %f758, %f759;
	mul.ftz.f32 	%f761, %f754, %f756;
	fma.rn.ftz.f32 	%f762, %f752, %f755, %f761;
	div.approx.ftz.f32 	%f763, %f762, %f760;
	mul.ftz.f32 	%f764, %f754, %f755;
	mul.ftz.f32 	%f765, %f752, %f756;
	sub.ftz.f32 	%f766, %f764, %f765;
	div.approx.ftz.f32 	%f767, %f766, %f760;
	mul.ftz.f32 	%f964, %f241, %f763;
	mul.ftz.f32 	%f965, %f241, %f767;
	mul.ftz.f32 	%f768, %f242, %f245;
	sub.ftz.f32 	%f769, %f768, %f956;
	mul.ftz.f32 	%f770, %f244, %f245;
	sub.ftz.f32 	%f771, %f770, %f957;
	add.ftz.f32 	%f772, %f768, %f956;
	add.ftz.f32 	%f773, %f770, %f957;
	mul.ftz.f32 	%f774, %f773, %f773;
	fma.rn.ftz.f32 	%f775, %f772, %f772, %f774;
	max.ftz.f32 	%f776, %f775, %f759;
	mul.ftz.f32 	%f777, %f771, %f773;
	fma.rn.ftz.f32 	%f778, %f769, %f772, %f777;
	div.approx.ftz.f32 	%f779, %f778, %f776;
	mul.ftz.f32 	%f780, %f771, %f772;
	mul.ftz.f32 	%f781, %f769, %f773;
	sub.ftz.f32 	%f782, %f780, %f781;
	div.approx.ftz.f32 	%f783, %f782, %f776;
	mul.ftz.f32 	%f962, %f241, %f779;
	mul.ftz.f32 	%f963, %f241, %f783;
	abs.ftz.f32 	%f784, %f964;
	setp.geu.ftz.f32 	%p133, %f784, 0f7F800000;
	@%p133 bra 	$L__BB2_91;

	abs.ftz.f32 	%f785, %f965;
	setp.lt.ftz.f32 	%p134, %f785, 0f7F800000;
	@%p134 bra 	$L__BB2_92;

$L__BB2_91:
	mov.f32 	%f964, 0f00000000;
	mov.f32 	%f965, %f964;

$L__BB2_92:
	abs.ftz.f32 	%f788, %f962;
	setp.geu.ftz.f32 	%p135, %f788, 0f7F800000;
	@%p135 bra 	$L__BB2_94;

	abs.ftz.f32 	%f789, %f963;
	setp.lt.ftz.f32 	%p136, %f789, 0f7F800000;
	@%p136 bra 	$L__BB2_95;

$L__BB2_94:
	mov.f32 	%f962, 0f00000000;
	mov.f32 	%f963, %f962;

$L__BB2_95:
	mul.ftz.f32 	%f792, %f965, %f965;
	fma.rn.ftz.f32 	%f793, %f964, %f964, %f792;
	setp.gt.ftz.f32 	%p137, %f793, 0f00000000;
	mov.u16 	%rs8, 1;
	@%p137 bra 	$L__BB2_97;

	mul.ftz.f32 	%f794, %f963, %f963;
	fma.rn.ftz.f32 	%f795, %f962, %f962, %f794;
	setp.gt.ftz.f32 	%p138, %f795, 0f00000000;
	selp.u16 	%rs8, 1, 0, %p138;

$L__BB2_97:
	setp.eq.s16 	%p139, %rs8, 0;
	mov.f32 	%f977, %f978;
	mov.f32 	%f976, %f978;
	mov.f32 	%f975, %f978;
	mov.f32 	%f974, %f978;
	mov.f32 	%f973, %f978;
	@%p139 bra 	$L__BB2_99;

	mul.ftz.f32 	%f802, )PTX_CHUNK"
R"PTX_CHUNK(%f930, %f948;
	fma.rn.ftz.f32 	%f803, %f928, %f947, %f802;
	mul.ftz.f32 	%f804, %f931, %f948;
	fma.rn.ftz.f32 	%f805, %f929, %f947, %f804;
	fma.rn.ftz.f32 	%f806, %f932, %f949, %f803;
	fma.rn.ftz.f32 	%f807, %f933, %f949, %f805;
	mul.ftz.f32 	%f808, %f930, %f951;
	mul.ftz.f32 	%f809, %f931, %f951;
	fma.rn.ftz.f32 	%f810, %f928, %f950, %f808;
	fma.rn.ftz.f32 	%f811, %f929, %f950, %f809;
	fma.rn.ftz.f32 	%f812, %f932, %f952, %f810;
	fma.rn.ftz.f32 	%f813, %f933, %f952, %f811;
	mul.ftz.f32 	%f814, %f806, %f964;
	mul.ftz.f32 	%f815, %f807, %f965;
	sub.ftz.f32 	%f816, %f814, %f815;
	mul.ftz.f32 	%f817, %f806, %f965;
	fma.rn.ftz.f32 	%f818, %f807, %f964, %f817;
	mul.ftz.f32 	%f819, %f947, %f816;
	mul.ftz.f32 	%f820, %f947, %f818;
	mul.ftz.f32 	%f821, %f948, %f816;
	mul.ftz.f32 	%f822, %f948, %f818;
	mul.ftz.f32 	%f823, %f949, %f816;
	mul.ftz.f32 	%f824, %f949, %f818;
	mul.ftz.f32 	%f825, %f812, %f962;
	mul.ftz.f32 	%f826, %f813, %f963;
	sub.ftz.f32 	%f827, %f825, %f826;
	mul.ftz.f32 	%f828, %f812, %f963;
	fma.rn.ftz.f32 	%f829, %f813, %f962, %f828;
	fma.rn.ftz.f32 	%f973, %f955, %f829, %f824;
	fma.rn.ftz.f32 	%f974, %f955, %f827, %f823;
	fma.rn.ftz.f32 	%f975, %f954, %f829, %f822;
	fma.rn.ftz.f32 	%f976, %f954, %f827, %f821;
	fma.rn.ftz.f32 	%f977, %f953, %f829, %f820;
	fma.rn.ftz.f32 	%f978, %f953, %f827, %f819;

$L__BB2_99:
	mul.ftz.f32 	%f830, %f977, %f977;
	fma.rn.ftz.f32 	%f831, %f978, %f978, %f830;
	mul.ftz.f32 	%f832, %f975, %f975;
	fma.rn.ftz.f32 	%f833, %f976, %f976, %f832;
	add.ftz.f32 	%f834, %f831, %f833;
	mul.ftz.f32 	%f835, %f973, %f973;
	fma.rn.ftz.f32 	%f836, %f974, %f974, %f835;
	add.ftz.f32 	%f283, %f836, %f834;
	setp.le.ftz.f32 	%p140, %f283, 0f00000000;
	@%p140 bra 	$L__BB2_111;

	setp.ne.s32 	%p159, %r380, 0;
	setp.eq.s32 	%p142, %r128, 0;
	and.pred  	%p143, %p159, %p142;
	or.pred  	%p144, %p1, %p143;
	@%p144 bra 	$L__BB2_106;

	@%p145 bra 	$L__BB2_104;

	rem.u32 	%r362, %r125, %r18;
	add.s32 	%r363, %r362, %r380;
	max.s32 	%r364, %r2, 1;
	mad.lo.s32 	%r365, %r364, %r112, %r363;
	rem.u32 	%r366, %r365, %r18;
	setp.ne.s32 	%p146, %r366, 0;
	@%p146 bra 	$L__BB2_106;

	mul.ftz.f32 	%f972, %f972, %f57;

$L__BB2_104:
	atom.global.add.u32 	%r110, [%rd23], 1;
	setp.lt.s32 	%p147, %r110, 0;
	setp.ge.s32 	%p148, %r110, %r129;
	or.pred  	%p149, %p147, %p148;
	@%p149 bra 	$L__BB2_106;

	mul.wide.s32 	%rd258, %r110, 4;
	add.s64 	%rd259, %rd24, %rd258;
	st.global.u32 	[%rd259], %r112;
	add.s64 	%rd260, %rd25, %rd258;
	st.global.f32 	[%rd260], %f941;
	add.s64 	%rd261, %rd26, %rd258;
	st.global.f32 	[%rd261], %f942;
	add.s64 	%rd262, %rd27, %rd258;
	st.global.f32 	[%rd262], %f943;
	add.s64 	%rd263, %rd28, %rd258;
	st.global.f32 	[%rd263], %f139;
	add.s64 	%rd264, %rd29, %rd258;
	st.global.f32 	[%rd264], %f138;
	add.s64 	%rd265, %rd30, %rd258;
	st.global.f32 	[%rd265], %f137;
	add.s64 	%rd266, %rd31, %rd258;
	st.global.u32 	[%rd266], %r109;
	add.s64 	%rd267, %rd32, %rd258;
	st.global.f32 	[%rd267], %f922;
	add.s64 	%rd268, %rd33, %rd258;
	st.global.f32 	[%rd268], %f923;
	add.s64 	%rd269, %rd34, %rd258;
	st.global.f32 	[%rd269], %f924;
	add.s64 	%rd270, %rd35, %rd258;
	st.global.f32 	[%rd270], %f919;
	add.s64 	%rd271, %rd36, %rd258;
	st.global.f32 	[%rd271], %f920;
	add.s64 	%rd272, %rd37, %rd258;
	st.global.f32 	[%rd272], %f921;
	add.s64 	%rd273, %rd38, %rd258;
	st.global.f32 	[%rd273], %f972;
	add.s64 	%rd274, %rd39, %rd258;
	st.global.f32 	[%rd274], %f7;
	add.s64 	%rd275, %rd40, %rd258;
	st.global.f32 	[%rd275], %f8;
	add.s64 	%rd276, %rd41, %rd258;
	st.global.f32 	[%rd276], %f9;
	add.s64 	%rd277, %rd42, %rd258;
	st.global.u32 	[%rd277], %r380;

$L__BB2_106:
	sub.ftz.f32 	%f837, %f919, %f941;
	sub.ftz.f32 	%f838, %f920, %f942;
	mul.ftz.f32 	%f839, %f838, %f138;
	fma.rn.ftz.f32 	%f840, %f837, %f139, %f839;
	sub.ftz.f32 	%f841, %f921, %f943;
	fma.rn.ftz.f32 	%f842, %f841, %f137, %f840;
	add.ftz.f32 	%f843, %f842, %f842;
	mul.ftz.f32 	%f844, %f139, %f843;
	mul.ftz.f32 	%f845, %f138, %f843;
	mul.ftz.f32 	%f846, %f137, %f843;
	sub.ftz.f32 	%f921, %f921, %f846;
	sub.ftz.f32 	%f920, %f920, %f845;
	sub.ftz.f32 	%f919, %f919, %f844;
	add.ftz.f32 	%f918, %f918, %f77;
	abs.ftz.f32 	%f847, %f943;
	abs.ftz.f32 	%f848, %f942;
	max.ftz.f32 	%f849, %f848, %f847;
	abs.ftz.f32 	%f850, %f941;
	max.ftz.f32 	%f851, %f850, %f849;
	add.ftz.f32 	%f852, %f851, 0f3F800000;
	mul.ftz.f32 	%f853, %f852, 0f3727C5AC;
	mul.ftz.f32 	%f854, %f138, %f149;
	fma.rn.ftz.f32 	%f855, %f139, %f148, %f854;
	fma.rn.ftz.f32 	%f856, %f137, %f150, %f855;
	setp.ge.ftz.f32 	%p150, %f856, 0f00000000;
	mul.ftz.f32 	%f857, %f852, 0fB727C5AC;
	selp.f32 	%f858, %f853, %f857, %p150;
	fma.rn.ftz.f32 	%f927, %f137, %f858, %f943;
	fma.rn.ftz.f32 	%f926, %f138, %f858, %f942;
	fma.rn.ftz.f32 	%f925, %f139, %f858, %f941;
	add.s32 	%r380, %r380, 1;
	setp.lt.s32 	%p151, %r380, %r126;
	setp.lt.s32 	%p152, %r126, 1;
	mov.b32 	%f859, %r127;
	setp.geu.ftz.f32 	%p153, %f859, 0f3F800000;
	or.pred  	%p154, %p152, %p153;
	or.pred  	%p155, %p151, %p154;
	@%p155 bra 	$L__BB2_109;

	mov.f32 	%f860, 0f322BCC77;
	max.ftz.f32 	%f861, %f283, %f860;
	max.ftz.f32 	%f863, %f859, %f860;
	min.ftz.f32 	%f302, %f861, %f863;
	mul.lo.s32 	%r367, %r380, -1640531527;
	xor.b32  	%r368, %r367, %r112;
	xor.b32  	%r369, %r368, %r125;
	shr.u32 	%r370, %r369, 16;
	xor.b32  	%r371, %r370, %r369;
	mul.lo.s32 	%r372, %r371, 2146121005;
	shr.u32 	%r373, %r372, 15;
	xor.b32  	%r374, %r373, %r372;
	mul.lo.s32 	%r375, %r374, -2073254261;
	shr.u32 	%r376, %r375, 16;
	and.b32  	%r377, %r375, 16777215;
	xor.b32  	%r378, %r376, %r377;
	cvt.rn.f32.u32 	%f864, %r378;
	mul.ftz.f32 	%f865, %f864, 0f33800000;
	setp.ge.ftz.f32 	%p156, %f865, %f302;
	@%p156 bra 	$L__BB2_111;

	max.ftz.f32 	%f867, %f302, %f860;
	rsqrt.approx.ftz.f32 	%f868, %f867;
	mul.ftz.f32 	%f978, %f978, %f868;
	mul.ftz.f32 	%f977, %f977, %f868;
	mul.ftz.f32 	%f976, %f976, %f868;
	mul.ftz.f32 	%f975, %f975, %f868;
	mul.ftz.f32 	%f974, %f974, %f868;
	mul.ftz.f32 	%f973, %f973, %f868;

$L__BB2_109:
	mov.b32 	%f869, %r117;
	setp.leu.ftz.f32 	%p157, %f869, 0f00000000;
	mov.f32 	%f922, %f148;
	mov.f32 	%f923, %f149;
	mov.f32 	%f924, %f150;
	mov.f32 	%f928, %f978;
	mov.f32 	%f929, %f977;
	mov.f32 	%f930, %f976;
	mov.f32 	%f931, %f975;
	mov.f32 	%f932, %f974;
	mov.f32 	%f933, %f973;
	@%p157 bra 	$L__BB2_10;

	mov.f32 	%f870, 0f358637BD;
	max.ftz.f32 	%f871, %f918, %f870;
	mul.ftz.f32 	%f872, %f871, 0f41490FDB;
	div.approx.ftz.f32 	%f873, %f56, %f872;
	mul.ftz.f32 	%f874, %f978, %f978;
	fma.rn.ftz.f32 	%f875, %f977, %f977, %f874;
	mul.ftz.f32 	%f876, %f976, %f976;
	fma.rn.ftz.f32 	%f877, %f975, %f975, %f876;
	add.ftz.f32 	%f878, %f877, %f875;
	mul.ftz.f32 	%f879, %f974, %f974;
	fma.rn.ftz.f32 	%f880, %f973, %f973, %f879;
	add.ftz.f32 	%f881, %f880, %f878;
	mul.ftz.f32 	%f882, %f881, %f873;
	mul.ftz.f32 	%f883, %f873, %f882;
	setp.gtu.ftz.f32 	%p158, %f883, %f869;
	mov.f32 	%f922, %f148;
	mov.f32 	%f923, %f149;
	mov.f32 	%f924, %f150;
	mov.f32 	%f928, %f978;
	mov.f32 	%f929, %f977;
	mov.f32 	%f930, %f976;
	mov.f32 	%f931, %f975;
	mov.f32 	%f932, %f974;
	mov.f32 	%f933, %f973;
	@%p158 bra 	$L__BB2_10;

$L__BB2_111:
	ret;

}

)PTX_CHUNK"
;
static const size_t reflection_accumulation_ptx_size = 55111;
