// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char diffraction_accumulation_ptx[] =
R"PTX_CHUNK(//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__closesthit__diffraction_accumulation
.const .align 8 .b8 params[504];

.visible .entry __closesthit__diffraction_accumulation()
{
	.reg .f32 	%f<2>;
	.reg .b32 	%r<11>;


	// begin inline asm
	call (%f1), _optix_get_ray_tmax, ();
	// end inline asm
	mov.b32 	%r6, %f1;
	// begin inline asm
	call (%r1), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r2), _optix_read_instance_id, ();
	// end inline asm
	mov.u32 	%r3, 0;
	mov.u32 	%r5, 1;
	// begin inline asm
	call _optix_set_payload, (%r3, %r5);
	// end inline asm
	// begin inline asm
	call _optix_set_payload, (%r5, %r6);
	// end inline asm
	mov.u32 	%r7, 2;
	// begin inline asm
	call _optix_set_payload, (%r7, %r1);
	// end inline asm
	mov.u32 	%r9, 3;
	// begin inline asm
	call _optix_set_payload, (%r9, %r2);
	// end inline asm
	ret;

}
	// .globl	__miss__diffraction_accumulation
.visible .entry __miss__diffraction_accumulation()
{
	.reg .b32 	%r<3>;


	mov.u32 	%r2, 0;
	// begin inline asm
	call _optix_set_payload, (%r2, %r2);
	// end inline asm
	ret;

}
	// .globl	__raygen__diffraction_order1_accumulation
.visible .entry __raygen__diffraction_order1_accumulation()
{
	.reg .pred 	%p<79>;
	.reg .b16 	%rs<4>;
	.reg .f32 	%f<350>;
	.reg .b32 	%r<480>;
	.reg .b64 	%rd<105>;


	// begin inline asm
	call (%r105), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r106, [params+20];
	setp.ge.u32 	%p1, %r105, %r106;
	ld.const.u32 	%r2, [params+32];
	setp.lt.s32 	%p2, %r2, 1;
	or.pred  	%p3, %p1, %p2;
	ld.const.v2.u32 	{%r107, %r108}, [params+296];
	setp.lt.s32 	%p4, %r107, 1;
	or.pred  	%p5, %p3, %p4;
	setp.lt.s32 	%p6, %r108, 1;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	$L__BB2_62;

	ld.const.v2.u32 	{%r109, %r110}, [params+376];
	and.b32  	%r113, %r110, 1;
	neg.s32 	%r114, %r113;
	ld.const.u32 	%r115, [params+372];
	and.b32  	%r5, %r114, %r115;
	shl.b32 	%r116, %r110, 30;
	shr.s32 	%r117, %r116, 31;
	and.b32  	%r118, %r117, %r109;
	add.s32 	%r6, %r5, %r118;
	setp.lt.s32 	%p8, %r6, 1;
	@%p8 bra 	$L__BB2_62;

	setp.ge.s32 	%p9, %r105, %r5;
	setp.ge.s32 	%p10, %r105, %r6;
	and.pred  	%p11, %p10, %p9;
	@%p11 bra 	$L__BB2_62;
	bra.uni 	$L__BB2_3;

$L__BB2_62:
	ret;

$L__BB2_3:
	rem.u32 	%r7, %r105, %r2;
	ld.const.u64 	%rd1, [params+24];
	setp.eq.s64 	%p12, %rd1, 0;
	@%p12 bra 	$L__BB2_5;

	cvta.to.global.u64 	%rd15, %rd1;
	cvt.s64.s32 	%rd16, %r7;
	add.s64 	%rd17, %rd15, %rd16;
	ld.global.u8 	%rs1, [%rd17];
	setp.eq.s16 	%p13, %rs1, 0;
	@%p13 bra 	$L__BB2_62;

$L__BB2_5:
	cvt.s64.s32 	%rd2, %r7;
	div.u32 	%r119, %r105, %r2;
	mul.lo.s32 	%r120, %r108, %r107;
	rem.u32 	%r466, %r119, %r120;
	ld.const.u32 	%r9, [params+364];
	xor.b32  	%r121, %r9, %r105;
	shr.u32 	%r122, %r121, 16;
	xor.b32  	%r123, %r122, %r121;
	mul.lo.s32 	%r124, %r123, 2146121005;
	shr.u32 	%r125, %r124, 15;
	xor.b32  	%r126, %r125, %r124;
	mul.lo.s32 	%r127, %r126, -2073254261;
	shr.u32 	%r128, %r127, 16;
	and.b32  	%r129, %r127, 16777215;
	xor.b32  	%r130, %r128, %r129;
	cvt.rn.f32.u32 	%f97, %r130;
	mul.ftz.f32 	%f98, %f97, 0f33800000;
	ld.const.u64 	%rd18, [params+96];
	cvta.to.global.u64 	%rd19, %rd18;
	mul.wide.s32 	%rd20, %r7, 4;
	add.s64 	%rd3, %rd19, %rd20;
	ld.const.u64 	%rd21, [params+104];
	cvta.to.global.u64 	%rd22, %rd21;
	add.s64 	%rd4, %rd22, %rd20;
	ld.global.f32 	%f99, [%rd4];
	ld.global.f32 	%f100, [%rd3];
	sub.ftz.f32 	%f101, %f99, %f100;
	fma.rn.ftz.f32 	%f102, %f101, %f98, %f100;
	ld.const.u64 	%rd23, [params+48];
	cvta.to.global.u64 	%rd24, %rd23;
	ld.const.u64 	%rd25, [params+56];
	cvta.to.global.u64 	%rd26, %rd25;
	ld.const.u64 	%rd27, [params+64];
	cvta.to.global.u64 	%rd28, %rd27;
	add.s64 	%rd29, %rd24, %rd20;
	add.s64 	%rd30, %rd26, %rd20;
	add.s64 	%rd31, %rd28, %rd20;
	ld.const.u64 	%rd32, [params+72];
	cvta.to.global.u64 	%rd33, %rd32;
	ld.const.u64 	%rd34, [params+80];
	cvta.to.global.u64 	%rd35, %rd34;
	ld.const.u64 	%rd36, [params+88];
	cvta.to.global.u64 	%rd37, %rd36;
	add.s64 	%rd38, %rd33, %rd20;
	add.s64 	%rd39, %rd35, %rd20;
	add.s64 	%rd40, %rd37, %rd20;
	ld.global.f32 	%f103, [%rd38];
	ld.global.f32 	%f104, [%rd39];
	mul.ftz.f32 	%f105, %f104, %f104;
	fma.rn.ftz.f32 	%f106, %f103, %f103, %f105;
	ld.global.f32 	%f107, [%rd40];
	fma.rn.ftz.f32 	%f108, %f107, %f107, %f106;
	mov.f32 	%f109, 0f2B8CBCCC;
	max.ftz.f32 	%f110, %f108, %f109;
	rsqrt.approx.ftz.f32 	%f111, %f110;
	mul.ftz.f32 	%f1, %f103, %f111;
	mul.ftz.f32 	%f2, %f104, %f111;
	mul.ftz.f32 	%f3, %f107, %f111;
	ld.global.f32 	%f112, [%rd29];
	fma.rn.ftz.f32 	%f4, %f102, %f1, %f112;
	ld.global.f32 	%f113, [%rd30];
	fma.rn.ftz.f32 	%f5, %f102, %f2, %f113;
	ld.global.f32 	%f114, [%rd31];
	fma.rn.ftz.f32 	%f6, %f102, %f3, %f114;
	ld.const.u64 	%rd41, [params+184];
	cvta.to.global.u64 	%rd42, %rd41;
	ld.const.u64 	%rd43, [params+192];
	cvta.to.global.u64 	%rd44, %rd43;
	ld.const.u64 	%rd45, [params+200];
	cvta.to.global.u64 	%rd46, %rd45;
	add.s64 	%rd5, %rd42, %rd20;
	ld.global.f32 	%f7, [%rd5];
	add.s64 	%rd6, %rd44, %rd20;
	ld.global.f32 	%f8, [%rd6];
	add.s64 	%rd7, %rd46, %rd20;
	ld.global.f32 	%f9, [%rd7];
	div.s32 	%r131, %r466, %r107;
	mul.lo.s32 	%r132, %r131, %r107;
	sub.s32 	%r133, %r466, %r132;
	cvt.rn.f32.s32 	%f115, %r133;
	add.ftz.f32 	%f116, %f115, 0f3F000000;
	cvt.rn.f32.s32 	%f10, %r107;
	mov.f32 	%f117, 0f3F800000;
	max.ftz.f32 	%f118, %f10, %f117;
	div.approx.ftz.f32 	%f119, %f116, %f118;
	cvt.rn.f32.s32 	%f120, %r131;
	add.ftz.f32 	%f121, %f120, 0f3F000000;
	cvt.rn.f32.s32 	%f11, %r108;
	max.ftz.f32 	%f122, %f11, %f117;
	div.approx.ftz.f32 	%f123, %f121, %f122;
	ld.const.v2.f32 	{%f124, %f125}, [params+280];
	sub.ftz.f32 	%f14, %f125, %f124;
	fma.rn.ftz.f32 	%f15, %f119, %f14, %f124;
	ld.const.v2.f32 	{%f126, %f127}, [params+288];
	sub.ftz.f32 	%f18, %f127, %f126;
	fma.rn.ftz.f32 	%f19, %f123, %f18, %f126;
	ld.const.u32 	%r10, [params+272];
	setp.eq.s32 	%p14, %r10, 0;
	@%p14 bra 	$L__BB2_8;

	setp.eq.s32 	%p15, %r10, 1;
	ld.const.f32 	%f339, [params+276];
	mov.f32 	%f340, %f15;
	mov.f32 	%f341, %f19;
	mov.f32 	%f342, %f339;
	@%p15 bra 	$L__BB2_7;
	bra.uni 	$L__BB2_9;

$L__BB2_7:
	mov.f32 	%f340, %f15;
	mov.f32 	%f341, %f339;
	mov.f32 	%f342, %f19;
	bra.uni 	$L__BB2_9;

$L__BB2_8:
	ld.const.f32 	%f339, [params+276];
	mov.f32 	%f340, %f339;
	mov.f32 	%f341, %f15;
	mov.f32 	%f342, %f19;

$L__BB2_9:
	setp.lt.s32 	%p16, %r105, %r5;
	@%p16 bra 	$L__BB2_18;
	bra.uni 	$L__BB2_10;

$L__BB2_18:
	sub.ftz.f32 	%f68, %f4, %f7;
	sub.ftz.f32 	%f69, %f5, %f8;
	mul.ftz.f32 	%f235, %f69, %f69;
	fma.rn.ftz.f32 	%f236, %f68, %f68, %f235;
	sub.ftz.f32 	%f70, %f6, %f9;
	fma.rn.ftz.f32 	%f237, %f70, %f70, %f236;
	mov.f32 	%f238, 0f00000000;
	max.ftz.f32 	%f239, %f237, %f238;
	sqrt.approx.ftz.f32 	%f71, %f239;
	setp.le.ftz.f32 	%p36, %f71, 0f3727C5AC;
	@%p36 bra 	$L__BB2_31;

	rcp.approx.ftz.f32 	%f240, %f71;
	mul.ftz.f32 	%f72, %f68, %f240;
	mul.ftz.f32 	%f73, %f69, %f240;
	mul.ftz.f32 	%f74, %f70, %f240;
	fma.rn.ftz.f32 	%f75, %f72, 0f38D1B717, %f7;
	fma.rn.ftz.f32 	%f76, %f73, 0f38D1B717, %f8;
	fma.rn.ftz.f32 	%f77, %f74, 0f38D1B717, %f9;
	add.ftz.f32 	%f241, %f71, 0fB951B717;
	max.ftz.f32 	%f78, %f241, %f238;
	ld.const.u64 	%rd8, [params];
	setp.eq.s64 	%p37, %rd8, 0;
	setp.le.ftz.f32 	%p38, %f78, 0f3727C5AC;
	or.pred  	%p39, %p38, %p37;
	mov.u32 	%r471, 0;
	mov.u32 	%r467, 1287568416;
	@%p39 bra 	$L__BB2_21;

	mov.f32 	%f249, 0f3727C5AC;
	mov.f32 	%f251, 0f00000000;
	mov.u32 	%r192, 255;
	mov.u32 	%r195, 1;
	mov.u32 	%r197, 4;
	mov.u32 	%r199, 1287568416;
	mov.u32 	%r229, 0;
	// begin inline asm
	call(%r471,%r467,%r161,%r162,%r163,%r164,%r165,%r166,%r167,%r168,%r169,%r170,%r171,%r172,%r173,%r174,%r175,%r176,%r177,%r178,%r179,%r180,%r181,%r182,%r183,%r184,%r185,%r186,%r187,%r188,%r189,%r190),_optix_trace_typed_32,(%r229,%rd8,%f75,%f76,%f77,%f72,%f73,%f74,%f249,%f78,%f251,%r192,%r195,%r229,%r195,%r229,%r197,%r229,%r199,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229,%r229);
	// end inline asm

$L__BB2_21:
	ld.const.u32 	%r230, [params+16];
	setp.eq.s32 	%p40, %r230, 0;
	@%p40 bra 	$L__BB2_30;

	ld.const.u64 	%rd9, [params+8];
	setp.eq.s64 	%p42, %rd9, 0;
	or.pred  	%p43, %p38, %p42;
	mov.u32 	%r470, 0;
	mov.u32 	%r469, 1287568416;
	@%p43 bra 	$L__BB2_24;

	mov.f32 	%f258, 0f3727C5AC;
	mov.f32 	%f260, 0f00000000;
	mov.u32 	%r268, 255;
	mov.u32 	%r271, 1;
	mov.u32 	%r273, 4;
	mov.u32 	%r275, 1287568416;
	mov.u32 	%r305, 0;
	// begin inline asm
	call(%r470,%r469,%r237,%r238,%r239,%r240,%r241,%r242,%r243,%r244,%r245,%r246,%r247,%r248,%r249,%r250,%r251,%r252,%r253,%r254,%r255,%r256,%r257,%r258,%r259,%r260,%r261,%r262,%r263,%r264,%r265,%r266),_optix_trace_typed_32,(%r305,%rd9,%f75,%f76,%f77,%f72,%f73,%f74,%f258,%f78,%f260,%r268,%r271,%r305,%r271,%r305,%r273,%r305,%r275,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305,%r305);
	// end inline asm

$L__BB2_24:
	setp.eq.s32 	%p44, %r471, 0;
	@%p44 bra 	$L__BB2_29;

	setp.eq.s32 	%p45, %r470, 0;
	@%p45 bra 	$L__BB2_30;

	mov.b32 	%f261, %r467;
	mov.b32 	%f262, %r469;
	setp.le.ftz.f32 	%p46, %f261, %f262;
	selp.b32 	%r471, %r471, %r470, %p46;
	bra.uni 	$L__BB2_30;

$L__BB2_10:
	ld.const.u64 	%rd47, [params+216];
	cvta.to.global.u64 	%rd48, %rd47;
	ld.const.u64 	%rd49, [params+224];
	cvta.to.global.u64 	%rd50, %rd49;
	ld.const.u64 	%rd51, [params+232];
	cvta.to.global.u64 	%rd52, %rd51;
	shl.b64 	%rd53, %rd2, 2;
	add.s64 	%rd54, %rd48, %rd53;
	add.s64 	%rd55, %rd50, %rd53;
	add.s64 	%rd56, %rd52, %rd53;
	ld.global.f32 	%f130, [%rd54];
	ld.global.f32 	%f131, [%rd55];
	mul.ftz.f32 	%f132, %f131, %f131;
	fma.rn.ftz.f32 	%f133, %f130, %f130, %f132;
	ld.global.f32 	%f134, [%rd56];
	fma.rn.ftz.f32 	%f135, %f134, %f134, %f133;
	mov.f32 	%f136, 0f2B8CBCCC;
	max.ftz.f32 	%f137, %f135, %f136;
	rsqrt.approx.ftz.f32 	%f138, %f137;
	mul.ftz.f32 	%f139, %f130, %f138;
	mul.ftz.f32 	%f140, %f131, %f138;
	mul.ftz.f32 	%f141, %f134, %f138;
	mul.ftz.f32 	%f142, %f2, %f140;
	fma.rn.ftz.f32 	%f143, %f1, %f139, %f142;
	fma.rn.ftz.f32 	%f41, %f3, %f141, %f143;
	mul.ftz.f32 	%f144, %f1, %f41;
	mul.ftz.f32 	%f145, %f2, %f41;
	mul.ftz.f32 	%f146, %f3, %f41;
	sub.ftz.f32 	%f42, %f139, %f144;
	sub.ftz.f32 	%f43, %f140, %f145;
	sub.ftz.f32 	%f44, %f141, %f146;
	mul.ftz.f32 	%f147, %f43, %f43;
	fma.rn.ftz.f32 	%f148, %f42, %f42, %f147;
	fma.rn.ftz.f32 	%f45, %f44, %f44, %f148;
	setp.gt.ftz.f32 	%p17, %f45, 0f2B8CBCCC;
	@%p17 bra 	$L__BB2_12;
	bra.uni 	$L__BB2_11;

$L__BB2_12:
	max.ftz.f32 	%f169, %f45, %f136;
	rsqrt.approx.ftz.f32 	%f170, %f169;
	mul.ftz.f32 	%f345, %f44, %f170;
	mul.ftz.f32 	%f344, %f43, %f170;
	mul.ftz.f32 	%f343, %f42, %f170;
	bra.uni 	$L__BB2_13;

$L__BB2_11:
	abs.ftz.f32 	%f149, %f3;
	setp.lt.ftz.f32 	%p18, %f149, 0f3F666666;
	selp.f32 	%f150, 0f3F800000, 0f00000000, %p18;
	selp.f32 	%f151, 0f00000000, 0f3F800000, %p18;
	mov.f32 	%f152, 0f00000000;
	mul.ftz.f32 	%f153, %f2, %f151;
	fma.rn.ftz.f32 	%f154, %f1, 0f00000000, %f153;
	fma.rn.ftz.f32 	%f155, %f3, %f150, %f154;
	mul.ftz.f32 	%f156, %f1, %f155;
	mul.ftz.f32 	%f157, %f2, %f155;
	mul.ftz.f32 	%f158, %f3, %f155;
	sub.ftz.f32 	%f159, %f152, %f156;
	sub.ftz.f32 	%f160, %f151, %f157;
	sub.ftz.f32 	%f161, %f150, %f158;
	mul.ftz.f32 	%f162, %f160, %f160;
	fma.rn.ftz.f32 	%f163, %f159, %f159, %f162;
	fma.rn.ftz.f32 	%f164, %f161, %f161, %f163;
	max.ftz.f32 	%f166, %f164, %f136;
	rsqrt.approx.ftz.f32 	%f167, %f166;
	mul.ftz.f32 	%f345, %f167, %f161;
	mul.ftz.f32 	%f344, %f167, %f160;
	mul.ftz.f32 	%f343, %f167, %f159;

$L__BB2_13:
	ld.const.u32 	%r465, [params+364];
	mov.f32 	%f171, 0fBF800000;
	max.ftz.f32 	%f172, %f41, %f171;
	mov.f32 	%f173, 0f3F800000;
	min.ftz.f32 	%f174, %f172, %f173;
	mul.ftz.f32 	%f175, %f174, %f174;
	sub.ftz.f32 	%f176, %f173, %f175;
	mov.f32 	%f177, 0f00000000;
	max.ftz.f32 	%f178, %f176, %f177;
	sqrt.approx.ftz.f32 	%f179, %f178;
	mul.ftz.f32 	%f180, %f2, %f345;
	mul.ftz.f32 	%f181, %f3, %f344;
	sub.ftz.f32 	%f182, %f180, %f181;
	mul.ftz.f32 	%f183, %f3, %f343;
	mul.ftz.f32 	%f184, %f1, %f345;
	sub.ftz.f32 	%f185, %f183, %f184;
	mul.ftz.f32 	%f186, %f1, %f344;
	mul.ftz.f32 	%f187, %f2, %f343;
	sub.ftz.f32 	%f188, %f186, %f187;
	mul.ftz.f32 	%f189, %f185, %f185;
	fma.rn.ftz.f32 	%f190, %f182, %f182, %f189;
	fma.rn.ftz.f32 	%f191, %f188, %f188, %f190;
	mov.f32 	%f192, 0f2B8CBCCC;
	max.ftz.f32 	%f193, %f191, %f192;
	rsqrt.approx.ftz.f32 	%f194, %f193;
	mul.ftz.f32 	%f195, %f194, %f182;
	mul.ftz.f32 	%f196, %f194, %f185;
	mul.ftz.f32 	%f197, %f194, %f188;
	xor.b32  	%r134, %r105, %r465;
	xor.b32  	%r135, %r134, -1640531527;
	shr.u32 	%r136, %r135, 16;
	xor.b32  	%r137, %r136, %r135;
	mul.lo.s32 	%r138, %r137, 2146121005;
	shr.u32 	%r139, %r138, 15;
	xor.b32  	%r140, %r139, %r138;
	mul.lo.s32 	%r141, %r140, -2073254261;
	shr.u32 	%r142, %r141, 16;
	and.b32  	%r143, %r141, 16777215;
	xor.b32  	%r144, %r142, %r143;
	cvt.rn.f32.u32 	%f198, %r144;
	mul.ftz.f32 	%f199, %f198, 0f33800000;
	mul.ftz.f32 	%f200, %f199, 0f40C90FDB;
	sin.approx.ftz.f32 	%f201, %f200;
	cos.approx.ftz.f32 	%f202, %f200;
	mul.ftz.f32 	%f203, %f343, %f202;
	mul.ftz.f32 	%f204, %f344, %f202;
	mul.ftz.f32 	%f205, %f345, %f202;
	fma.rn.ftz.f32 	%f206, %f195, %f201, %f203;
	fma.rn.ftz.f32 	%f207, %f196, %f201, %f204;
	fma.rn.ftz.f32 	%f208, %f197, %f201, %f205;
	mul.ftz.f32 	%f209, %f179, %f206;
	mul.ftz.f32 	%f210, %f179, %f207;
	mul.ftz.f32 	%f211, %f179, %f208;
	fma.rn.ftz.f32 	%f212, %f1, %f174, %f209;
	fma.rn.ftz.f32 	%f213, %f2, %f174, %f210;
	fma.rn.ftz.f32 	%f214, %f3, %f174, %f211;
	mul.ftz.f32 	%f215, %f213, %f213;
	fma.rn.ftz.f32 	%f216, %f212, %f212, %f215;
	fma.rn.ftz.f32 	%f217, %f214, %f214, %f216;
	max.ftz.f32 	%f218, %f217, %f192;
	rsqrt.approx.ftz.f32 	%f219, %f218;
	mul.ftz.f32 	%f55, %f219, %f212;
	mul.ftz.f32 	%f56, %f219, %f213;
	mul.ftz.f32 	%f57, %f219, %f214;
	setp.eq.s32 	%p19, %r10, 1;
	selp.f32 	%f220, %f56, %f57, %p19;
	selp.f32 	%f58, %f55, %f220, %p14;
	abs.ftz.f32 	%f221, %f58;
	setp.le.ftz.f32 	%p21, %f221, 0f358637BD;
	@%p21 bra 	$L__BB2_27;

	selp.f32 	%f222, %f5, %f6, %p19;
	selp.f32 	%f223, %f4, %f222, %p14;
	sub.ftz.f32 	%f224, %f339, %f223;
	div.approx.ftz.f32 	%f59, %f224, %f58;
	setp.leu.ftz.f32 	%p24, %f59, 0f38D1B717;
	@%p24 bra 	$L__BB2_27;

	abs.ftz.f32 	%f225, %f59;
	setp.geu.ftz.f32 	%p25, %f225, 0f7F800000;
	@%p25 bra 	$L__BB2_27;

	fma.rn.ftz.f32 	%f340, %f55, %f59, %f4;
	fma.rn.ftz.f32 	%f341, %f56, %f59, %f5;
	fma.rn.ftz.f32 	%f342, %f57, %f59, %f6;
	selp.f32 	%f63, %f341, %f340, %p14;
	setp.lt.u32 	%p27, %r10, 2;
	selp.f32 	%f64, %f342, %f341, %p27;
	setp.lt.ftz.f32 	%p28, %f63, %f124;
	setp.ge.ftz.f32 	%p29, %f63, %f125;
	or.pred  	%p30, %p29, %p28;
	setp.lt.ftz.f32 	%p31, %f64, %f126;
	or.pred  	%p32, %p30, %p31;
	setp.ge.ftz.f32 	%p33, %f64, %f127;
	or.pred  	%p34, %p33, %p32;
	@%p34 bra 	$L__BB2_27;

	sub.ftz.f32 	%f226, %f63, %f124;
	mov.f32 	%f227, 0f358637BD;
	max.ftz.f32 	%f228, %f14, %f227;
	div.approx.ftz.f32 	%f229, %f226, %f228;
	max.ftz.f32 	%f230, %f18, %f227;
	sub.ftz.f32 	%f231, %f64, %f126;
	div.approx.ftz.f32 	%f232, %f231, %f230;
	mul.ftz.f32 	%f233, %f229, %f10;
	cvt.rzi.ftz.s32.f32 	%r145, %f233;
	max.s32 	%r146, %r145, 0;
	add.s32 	%r147, %r107, -1;
	min.s32 	%r148, %r146, %r147;
	mul.ftz.f32 	%f234, %f232, %f11;
	cvt.rzi.ftz.s32.f32 	%r149, %f234;
	max.s32 	%r150, %r149, 0;
	add.s32 	%r151, %r108, -1;
	min.s32 	%r152, %r150, %r151;
	mad.lo.s32 	%r466, %r152, %r107, %r148;
	bra.uni 	$L__BB2_18;

$L__BB2_27:
	ld.const.u32 	%r153, [params+396];
	setp.eq.s32 	%p35, %r153, 0;
	@%p35 bra 	$L__BB2_62;

	ld.const.u64 	%rd57, [params+488];
	cvta.to.global.u64 	%rd58, %rd57;
	atom.global.add.u32 	%r154, [%rd58], 1;
	bra.uni 	$L__BB2_62;

$L__BB2_29:
	mov.u32 	%r471, %r4)PTX_CHUNK"
R"PTX_CHUNK(70;

$L__BB2_30:
	setp.ne.s32 	%p47, %r471, 0;
	@%p47 bra 	$L__BB2_42;

$L__BB2_31:
	sub.ftz.f32 	%f79, %f340, %f4;
	mul.ftz.f32 	%f263, %f79, %f79;
	sub.ftz.f32 	%f80, %f341, %f5;
	fma.rn.ftz.f32 	%f264, %f80, %f80, %f263;
	sub.ftz.f32 	%f81, %f342, %f6;
	fma.rn.ftz.f32 	%f265, %f81, %f81, %f264;
	max.ftz.f32 	%f267, %f265, %f238;
	sqrt.approx.ftz.f32 	%f82, %f267;
	setp.le.ftz.f32 	%p48, %f82, 0f3727C5AC;
	@%p48 bra 	$L__BB2_44;

	rcp.approx.ftz.f32 	%f268, %f82;
	mul.ftz.f32 	%f83, %f79, %f268;
	mul.ftz.f32 	%f84, %f80, %f268;
	mul.ftz.f32 	%f85, %f81, %f268;
	fma.rn.ftz.f32 	%f86, %f83, 0f38D1B717, %f4;
	fma.rn.ftz.f32 	%f87, %f84, 0f38D1B717, %f5;
	fma.rn.ftz.f32 	%f88, %f85, 0f38D1B717, %f6;
	add.ftz.f32 	%f269, %f82, 0fB951B717;
	mov.f32 	%f270, 0f00000000;
	max.ftz.f32 	%f89, %f269, %f270;
	ld.const.u64 	%rd10, [params];
	setp.eq.s64 	%p49, %rd10, 0;
	setp.le.ftz.f32 	%p50, %f89, 0f3727C5AC;
	or.pred  	%p51, %p50, %p49;
	mov.u32 	%r477, 0;
	mov.u32 	%r474, 1287568416;
	@%p51 bra 	$L__BB2_34;

	mov.f32 	%f277, 0f3727C5AC;
	mov.u32 	%r343, 255;
	mov.u32 	%r346, 1;
	mov.u32 	%r348, 4;
	mov.u32 	%r350, 1287568416;
	mov.u32 	%r380, 0;
	// begin inline asm
	call(%r477,%r474,%r312,%r313,%r314,%r315,%r316,%r317,%r318,%r319,%r320,%r321,%r322,%r323,%r324,%r325,%r326,%r327,%r328,%r329,%r330,%r331,%r332,%r333,%r334,%r335,%r336,%r337,%r338,%r339,%r340,%r341),_optix_trace_typed_32,(%r380,%rd10,%f86,%f87,%f88,%f83,%f84,%f85,%f277,%f89,%f270,%r343,%r346,%r380,%r346,%r380,%r348,%r380,%r350,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380,%r380);
	// end inline asm

$L__BB2_34:
	ld.const.u32 	%r381, [params+16];
	setp.eq.s32 	%p52, %r381, 0;
	@%p52 bra 	$L__BB2_41;

	ld.const.u64 	%rd11, [params+8];
	setp.eq.s64 	%p54, %rd11, 0;
	or.pred  	%p55, %p50, %p54;
	mov.u32 	%r475, 0;
	mov.u32 	%r476, 1287568416;
	@%p55 bra 	$L__BB2_37;

	mov.f32 	%f286, 0f3727C5AC;
	mov.f32 	%f288, 0f00000000;
	mov.u32 	%r419, 255;
	mov.u32 	%r422, 1;
	mov.u32 	%r424, 4;
	mov.u32 	%r426, 1287568416;
	mov.u32 	%r456, 0;
	// begin inline asm
	call(%r475,%r476,%r388,%r389,%r390,%r391,%r392,%r393,%r394,%r395,%r396,%r397,%r398,%r399,%r400,%r401,%r402,%r403,%r404,%r405,%r406,%r407,%r408,%r409,%r410,%r411,%r412,%r413,%r414,%r415,%r416,%r417),_optix_trace_typed_32,(%r456,%rd11,%f86,%f87,%f88,%f83,%f84,%f85,%f286,%f89,%f288,%r419,%r422,%r456,%r422,%r456,%r424,%r456,%r426,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456,%r456);
	// end inline asm

$L__BB2_37:
	setp.eq.s32 	%p56, %r477, 0;
	@%p56 bra 	$L__BB2_40;

	setp.eq.s32 	%p57, %r475, 0;
	@%p57 bra 	$L__BB2_41;

	mov.b32 	%f289, %r474;
	mov.b32 	%f290, %r476;
	setp.le.ftz.f32 	%p58, %f289, %f290;
	selp.b32 	%r477, %r477, %r475, %p58;
	bra.uni 	$L__BB2_41;

$L__BB2_40:
	mov.u32 	%r477, %r475;

$L__BB2_41:
	setp.eq.s32 	%p59, %r477, 0;
	@%p59 bra 	$L__BB2_44;

$L__BB2_42:
	ld.const.u32 	%r457, [params+396];
	setp.eq.s32 	%p60, %r457, 0;
	@%p60 bra 	$L__BB2_62;

	ld.const.u64 	%rd63, [params+480];
	cvta.to.global.u64 	%rd64, %rd63;
	atom.global.add.u32 	%r458, [%rd64], 1;
	bra.uni 	$L__BB2_62;

$L__BB2_44:
	ld.global.f32 	%f292, [%rd5];
	sub.ftz.f32 	%f293, %f4, %f292;
	ld.global.f32 	%f294, [%rd6];
	sub.ftz.f32 	%f295, %f5, %f294;
	ld.global.f32 	%f296, [%rd7];
	sub.ftz.f32 	%f297, %f6, %f296;
	mul.ftz.f32 	%f298, %f295, %f295;
	fma.rn.ftz.f32 	%f299, %f293, %f293, %f298;
	fma.rn.ftz.f32 	%f300, %f297, %f297, %f299;
	mov.f32 	%f301, 0f00000000;
	max.ftz.f32 	%f302, %f300, %f301;
	sqrt.approx.ftz.f32 	%f303, %f302;
	mov.f32 	%f304, 0f358637BD;
	max.ftz.f32 	%f90, %f303, %f304;
	max.ftz.f32 	%f91, %f82, %f304;
	ld.global.f32 	%f305, [%rd3];
	ld.global.f32 	%f306, [%rd4];
	sub.ftz.f32 	%f92, %f306, %f305;
	ld.const.u64 	%rd65, [params+176];
	cvta.to.global.u64 	%rd66, %rd65;
	shl.b64 	%rd67, %rd2, 2;
	add.s64 	%rd68, %rd66, %rd67;
	ld.global.f32 	%f93, [%rd68];
	ld.const.u64 	%rd12, [params+336];
	setp.eq.s64 	%p61, %rd12, 0;
	ld.const.u32 	%r101, [params+352];
	setp.lt.s32 	%p62, %r101, 1;
	or.pred  	%p63, %p61, %p62;
	mov.f32 	%f291, 0f3F800000;
	mov.f32 	%f349, %f291;
	@%p63 bra 	$L__BB2_53;

	ld.const.u64 	%rd69, [params+160];
	cvta.to.global.u64 	%rd70, %rd69;
	add.s64 	%rd72, %rd70, %rd67;
	ld.global.u32 	%r479, [%rd72];
	setp.lt.s32 	%p64, %r479, 0;
	setp.ge.s32 	%p65, %r479, %r101;
	or.pred  	%p66, %p64, %p65;
	@%p66 bra 	$L__BB2_48;

	ld.const.u64 	%rd13, [params+344];
	setp.eq.s64 	%p67, %rd13, 0;
	@%p67 bra 	$L__BB2_49;

	cvta.to.global.u64 	%rd73, %rd13;
	cvt.s64.s32 	%rd74, %r479;
	add.s64 	%rd75, %rd73, %rd74;
	ld.global.u8 	%rs2, [%rd75];
	setp.ne.s16 	%p68, %rs2, 0;
	@%p68 bra 	$L__BB2_49;

$L__BB2_48:
	ld.const.u64 	%rd76, [params+168];
	cvta.to.global.u64 	%rd77, %rd76;
	add.s64 	%rd79, %rd77, %rd67;
	ld.global.u32 	%r479, [%rd79];

$L__BB2_49:
	setp.ge.s32 	%p69, %r479, %r101;
	setp.lt.s32 	%p70, %r479, 0;
	or.pred  	%p71, %p70, %p69;
	mov.f32 	%f349, %f291;
	@%p71 bra 	$L__BB2_53;

	ld.const.u64 	%rd14, [params+344];
	setp.eq.s64 	%p72, %rd14, 0;
	@%p72 bra 	$L__BB2_52;

	cvta.to.global.u64 	%rd80, %rd14;
	cvt.s64.s32 	%rd81, %r479;
	add.s64 	%rd82, %rd80, %rd81;
	ld.global.u8 	%rs3, [%rd82];
	setp.eq.s16 	%p73, %rs3, 0;
	mov.f32 	%f349, %f291;
	@%p73 bra 	$L__BB2_53;

$L__BB2_52:
	cvta.to.global.u64 	%rd83, %rd12;
	mul.wide.s32 	%rd84, %r479, 4;
	add.s64 	%rd85, %rd83, %rd84;
	ld.global.f32 	%f309, [%rd85];
	mov.f32 	%f310, 0f00000000;
	max.ftz.f32 	%f349, %f309, %f310;

$L__BB2_53:
	cvt.rn.f32.s32 	%f311, %r6;
	max.ftz.f32 	%f313, %f311, %f291;
	rcp.approx.ftz.f32 	%f314, %f313;
	ld.const.u64 	%rd86, [params+208];
	cvta.to.global.u64 	%rd87, %rd86;
	add.s64 	%rd89, %rd87, %rd67;
	ld.global.f32 	%f315, [%rd89];
	mul.ftz.f32 	%f316, %f349, %f315;
	max.ftz.f32 	%f318, %f92, %f301;
	mul.ftz.f32 	%f319, %f318, %f316;
	ld.const.f32 	%f320, [params+304];
	mul.ftz.f32 	%f321, %f320, %f319;
	mov.f32 	%f322, 0f3F490FDB;
	max.ftz.f32 	%f323, %f93, %f322;
	mov.f32 	%f324, 0f40C90FDB;
	div.approx.ftz.f32 	%f325, %f323, %f324;
	mov.f32 	%f326, 0f40000000;
	min.ftz.f32 	%f327, %f325, %f326;
	mul.ftz.f32 	%f328, %f327, %f321;
	mul.ftz.f32 	%f329, %f314, %f328;
	mul.ftz.f32 	%f330, %f90, %f90;
	mul.ftz.f32 	%f331, %f330, %f91;
	mul.ftz.f32 	%f332, %f91, %f331;
	div.approx.ftz.f32 	%f96, %f329, %f332;
	setp.leu.ftz.f32 	%p74, %f96, 0f00000000;
	@%p74 bra 	$L__BB2_60;

	abs.ftz.f32 	%f333, %f96;
	setp.geu.ftz.f32 	%p75, %f333, 0f7F800000;
	@%p75 bra 	$L__BB2_60;
	bra.uni 	$L__BB2_55;

$L__BB2_60:
	ld.const.u32 	%r463, [params+396];
	setp.eq.s32 	%p78, %r463, 0;
	@%p78 bra 	$L__BB2_62;

	ld.const.u64 	%rd103, [params+488];
	cvta.to.global.u64 	%rd104, %rd103;
	atom.global.add.u32 	%r464, [%rd104], 1;
	bra.uni 	$L__BB2_62;

$L__BB2_55:
	ld.const.u64 	%rd90, [params+400];
	cvta.to.global.u64 	%rd91, %rd90;
	mul.wide.s32 	%rd92, %r466, 4;
	add.s64 	%rd93, %rd91, %rd92;
	atom.global.add.f32 	%f334, [%rd93], %f96;
	ld.const.u64 	%rd94, [params+408];
	cvta.to.global.u64 	%rd95, %rd94;
	add.s64 	%rd96, %rd95, %rd92;
	mov.f32 	%f335, 0f00000000;
	max.ftz.f32 	%f336, %f96, %f335;
	sqrt.approx.ftz.f32 	%f337, %f336;
	atom.global.add.f32 	%f338, [%rd96], %f337;
	@%p16 bra 	$L__BB2_57;
	bra.uni 	$L__BB2_56;

$L__BB2_57:
	ld.const.u64 	%rd99, [params+456];
	cvta.to.global.u64 	%rd100, %rd99;
	atom.global.add.u32 	%r460, [%rd100], 1;
	bra.uni 	$L__BB2_58;

$L__BB2_56:
	ld.const.u64 	%rd97, [params+464];
	cvta.to.global.u64 	%rd98, %rd97;
	atom.global.add.u32 	%r459, [%rd98], 1;

$L__BB2_58:
	ld.const.u32 	%r461, [params+392];
	setp.eq.s32 	%p77, %r461, 0;
	@%p77 bra 	$L__BB2_62;

	ld.const.u64 	%rd101, [params+496];
	cvta.to.global.u64 	%rd102, %rd101;
	atom.global.add.u32 	%r462, [%rd102], 1;
	bra.uni 	$L__BB2_62;

}

)PTX_CHUNK"
;
static const size_t diffraction_accumulation_ptx_size = 23910;
