// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char diffraction_accumulation_ptx[] =
R"PTX_CHUNK(//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__closesthit__diffraction_accumulation
.const .align 8 .b8 params[680];

.visible .entry __closesthit__diffraction_accumulation()
{
	.reg .f32 	%f<2>;
	.reg .b32 	%r<11>;


	// begin inline asm
	call (%f1), _optix_get_ray_tmax, ();
	// end inline asm
	mov.b32 	%r6, %f1;
	// begin inline asm
	call (%r1), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r2), _optix_read_instance_id, ();
	// end inline asm
	mov.u32 	%r3, 0;
	mov.u32 	%r5, 1;
	// begin inline asm
	call _optix_set_payload, (%r3, %r5);
	// end inline asm
	// begin inline asm
	call _optix_set_payload, (%r5, %r6);
	// end inline asm
	mov.u32 	%r7, 2;
	// begin inline asm
	call _optix_set_payload, (%r7, %r1);
	// end inline asm
	mov.u32 	%r9, 3;
	// begin inline asm
	call _optix_set_payload, (%r9, %r2);
	// end inline asm
	ret;

}
	// .globl	__miss__diffraction_accumulation
.visible .entry __miss__diffraction_accumulation()
{
	.reg .b32 	%r<3>;


	mov.u32 	%r2, 0;
	// begin inline asm
	call _optix_set_payload, (%r2, %r2);
	// end inline asm
	ret;

}
	// .globl	__raygen__diffraction_order1_accumulation
.visible .entry __raygen__diffraction_order1_accumulation()
{
	.reg .pred 	%p<79>;
	.reg .b16 	%rs<4>;
	.reg .f32 	%f<350>;
	.reg .b32 	%r<481>;
	.reg .b64 	%rd<103>;


	// begin inline asm
	call (%r106), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r107, [params+20];
	setp.ge.u32 	%p1, %r106, %r107;
	ld.const.u32 	%r2, [params+32];
	setp.lt.s32 	%p2, %r2, 1;
	or.pred  	%p3, %p1, %p2;
	ld.const.v2.u32 	{%r108, %r109}, [params+456];
	setp.lt.s32 	%p4, %r108, 1;
	or.pred  	%p5, %p3, %p4;
	setp.lt.s32 	%p6, %r109, 1;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	$L__BB2_61;

	ld.const.u32 	%r110, [params+544];
	and.b32  	%r111, %r110, 1;
	neg.s32 	%r112, %r111;
	ld.const.v2.u32 	{%r113, %r114}, [params+536];
	and.b32  	%r5, %r112, %r113;
	shl.b32 	%r117, %r110, 30;
	shr.s32 	%r118, %r117, 31;
	and.b32  	%r119, %r118, %r114;
	add.s32 	%r6, %r5, %r119;
	setp.lt.s32 	%p8, %r6, 1;
	@%p8 bra 	$L__BB2_61;

	setp.ge.s32 	%p9, %r106, %r5;
	setp.ge.s32 	%p10, %r106, %r6;
	and.pred  	%p11, %p10, %p9;
	@%p11 bra 	$L__BB2_61;
	bra.uni 	$L__BB2_3;

$L__BB2_61:
	ret;

$L__BB2_3:
	rem.u32 	%r7, %r106, %r2;
	ld.const.u64 	%rd1, [params+24];
	setp.eq.s64 	%p12, %rd1, 0;
	@%p12 bra 	$L__BB2_5;

	cvta.to.global.u64 	%rd15, %rd1;
	cvt.s64.s32 	%rd16, %r7;
	add.s64 	%rd17, %rd15, %rd16;
	ld.global.u8 	%rs1, [%rd17];
	setp.eq.s16 	%p13, %rs1, 0;
	@%p13 bra 	$L__BB2_61;

$L__BB2_5:
	cvt.s64.s32 	%rd2, %r7;
	div.u32 	%r120, %r106, %r2;
	mul.lo.s32 	%r121, %r109, %r108;
	rem.u32 	%r467, %r120, %r121;
	ld.const.u32 	%r9, [params+524];
	xor.b32  	%r122, %r9, %r106;
	shr.u32 	%r123, %r122, 16;
	xor.b32  	%r124, %r123, %r122;
	mul.lo.s32 	%r125, %r124, 2146121005;
	shr.u32 	%r126, %r125, 15;
	xor.b32  	%r127, %r126, %r125;
	mul.lo.s32 	%r128, %r127, -2073254261;
	shr.u32 	%r129, %r128, 16;
	and.b32  	%r130, %r128, 16777215;
	xor.b32  	%r131, %r129, %r130;
	cvt.rn.f32.u32 	%f97, %r131;
	mul.ftz.f32 	%f98, %f97, 0f33800000;
	ld.const.u64 	%rd18, [params+96];
	cvta.to.global.u64 	%rd19, %rd18;
	mul.wide.s32 	%rd20, %r7, 4;
	add.s64 	%rd3, %rd19, %rd20;
	ld.const.u64 	%rd21, [params+104];
	cvta.to.global.u64 	%rd22, %rd21;
	add.s64 	%rd4, %rd22, %rd20;
	ld.global.f32 	%f99, [%rd4];
	ld.global.f32 	%f100, [%rd3];
	sub.ftz.f32 	%f101, %f99, %f100;
	fma.rn.ftz.f32 	%f102, %f101, %f98, %f100;
	ld.const.u64 	%rd23, [params+48];
	cvta.to.global.u64 	%rd24, %rd23;
	ld.const.u64 	%rd25, [params+56];
	cvta.to.global.u64 	%rd26, %rd25;
	ld.const.u64 	%rd27, [params+64];
	cvta.to.global.u64 	%rd28, %rd27;
	add.s64 	%rd29, %rd24, %rd20;
	add.s64 	%rd30, %rd26, %rd20;
	add.s64 	%rd31, %rd28, %rd20;
	ld.const.u64 	%rd32, [params+72];
	cvta.to.global.u64 	%rd33, %rd32;
	ld.const.u64 	%rd34, [params+80];
	cvta.to.global.u64 	%rd35, %rd34;
	ld.const.u64 	%rd36, [params+88];
	cvta.to.global.u64 	%rd37, %rd36;
	add.s64 	%rd38, %rd33, %rd20;
	add.s64 	%rd39, %rd35, %rd20;
	add.s64 	%rd40, %rd37, %rd20;
	ld.global.f32 	%f103, [%rd38];
	ld.global.f32 	%f104, [%rd39];
	mul.ftz.f32 	%f105, %f104, %f104;
	fma.rn.ftz.f32 	%f106, %f103, %f103, %f105;
	ld.global.f32 	%f107, [%rd40];
	fma.rn.ftz.f32 	%f108, %f107, %f107, %f106;
	mov.f32 	%f109, 0f2B8CBCCC;
	max.ftz.f32 	%f110, %f108, %f109;
	rsqrt.approx.ftz.f32 	%f111, %f110;
	mul.ftz.f32 	%f1, %f103, %f111;
	mul.ftz.f32 	%f2, %f104, %f111;
	mul.ftz.f32 	%f3, %f107, %f111;
	ld.global.f32 	%f112, [%rd29];
	fma.rn.ftz.f32 	%f4, %f102, %f1, %f112;
	ld.global.f32 	%f113, [%rd30];
	fma.rn.ftz.f32 	%f5, %f102, %f2, %f113;
	ld.global.f32 	%f114, [%rd31];
	fma.rn.ftz.f32 	%f6, %f102, %f3, %f114;
	ld.const.u64 	%rd41, [params+184];
	cvta.to.global.u64 	%rd42, %rd41;
	ld.const.u64 	%rd43, [params+192];
	cvta.to.global.u64 	%rd44, %rd43;
	ld.const.u64 	%rd45, [params+200];
	cvta.to.global.u64 	%rd46, %rd45;
	add.s64 	%rd5, %rd42, %rd20;
	ld.global.f32 	%f7, [%rd5];
	add.s64 	%rd6, %rd44, %rd20;
	ld.global.f32 	%f8, [%rd6];
	add.s64 	%rd7, %rd46, %rd20;
	ld.global.f32 	%f9, [%rd7];
	div.s32 	%r132, %r467, %r108;
	mul.lo.s32 	%r133, %r132, %r108;
	sub.s32 	%r134, %r467, %r133;
	cvt.rn.f32.s32 	%f115, %r134;
	add.ftz.f32 	%f116, %f115, 0f3F000000;
	cvt.rn.f32.s32 	%f10, %r108;
	mov.f32 	%f117, 0f3F800000;
	max.ftz.f32 	%f118, %f10, %f117;
	div.approx.ftz.f32 	%f119, %f116, %f118;
	cvt.rn.f32.s32 	%f120, %r132;
	add.ftz.f32 	%f121, %f120, 0f3F000000;
	cvt.rn.f32.s32 	%f11, %r109;
	max.ftz.f32 	%f122, %f11, %f117;
	div.approx.ftz.f32 	%f123, %f121, %f122;
	ld.const.v2.f32 	{%f124, %f125}, [params+440];
	sub.ftz.f32 	%f14, %f125, %f124;
	fma.rn.ftz.f32 	%f15, %f119, %f14, %f124;
	ld.const.v2.f32 	{%f126, %f127}, [params+448];
	sub.ftz.f32 	%f18, %f127, %f126;
	fma.rn.ftz.f32 	%f19, %f123, %f18, %f126;
	ld.const.u32 	%r10, [params+432];
	setp.eq.s32 	%p14, %r10, 0;
	@%p14 bra 	$L__BB2_8;

	setp.eq.s32 	%p15, %r10, 1;
	ld.const.f32 	%f339, [params+436];
	mov.f32 	%f340, %f15;
	mov.f32 	%f341, %f19;
	mov.f32 	%f342, %f339;
	@%p15 bra 	$L__BB2_7;
	bra.uni 	$L__BB2_9;

$L__BB2_7:
	mov.f32 	%f340, %f15;
	mov.f32 	%f341, %f339;
	mov.f32 	%f342, %f19;
	bra.uni 	$L__BB2_9;

$L__BB2_8:
	ld.const.f32 	%f339, [params+436];
	mov.f32 	%f340, %f339;
	mov.f32 	%f341, %f15;
	mov.f32 	%f342, %f19;

$L__BB2_9:
	setp.lt.s32 	%p16, %r106, %r5;
	@%p16 bra 	$L__BB2_18;
	bra.uni 	$L__BB2_10;

$L__BB2_18:
	sub.ftz.f32 	%f68, %f4, %f7;
	sub.ftz.f32 	%f69, %f5, %f8;
	mul.ftz.f32 	%f235, %f69, %f69;
	fma.rn.ftz.f32 	%f236, %f68, %f68, %f235;
	sub.ftz.f32 	%f70, %f6, %f9;
	fma.rn.ftz.f32 	%f237, %f70, %f70, %f236;
	mov.f32 	%f238, 0f00000000;
	max.ftz.f32 	%f239, %f237, %f238;
	sqrt.approx.ftz.f32 	%f71, %f239;
	setp.le.ftz.f32 	%p36, %f71, 0f3727C5AC;
	@%p36 bra 	$L__BB2_31;

	rcp.approx.ftz.f32 	%f240, %f71;
	mul.ftz.f32 	%f72, %f68, %f240;
	mul.ftz.f32 	%f73, %f69, %f240;
	mul.ftz.f32 	%f74, %f70, %f240;
	fma.rn.ftz.f32 	%f75, %f72, 0f38D1B717, %f7;
	fma.rn.ftz.f32 	%f76, %f73, 0f38D1B717, %f8;
	fma.rn.ftz.f32 	%f77, %f74, 0f38D1B717, %f9;
	add.ftz.f32 	%f241, %f71, 0fB951B717;
	max.ftz.f32 	%f78, %f241, %f238;
	ld.const.u64 	%rd8, [params];
	setp.eq.s64 	%p37, %rd8, 0;
	setp.le.ftz.f32 	%p38, %f78, 0f3727C5AC;
	or.pred  	%p39, %p38, %p37;
	mov.u32 	%r472, 0;
	mov.u32 	%r468, 1287568416;
	@%p39 bra 	$L__BB2_21;

	mov.f32 	%f249, 0f3727C5AC;
	mov.f32 	%f251, 0f00000000;
	mov.u32 	%r193, 255;
	mov.u32 	%r196, 1;
	mov.u32 	%r198, 4;
	mov.u32 	%r200, 1287568416;
	mov.u32 	%r230, 0;
	// begin inline asm
	call(%r472,%r468,%r162,%r163,%r164,%r165,%r166,%r167,%r168,%r169,%r170,%r171,%r172,%r173,%r174,%r175,%r176,%r177,%r178,%r179,%r180,%r181,%r182,%r183,%r184,%r185,%r186,%r187,%r188,%r189,%r190,%r191),_optix_trace_typed_32,(%r230,%rd8,%f75,%f76,%f77,%f72,%f73,%f74,%f249,%f78,%f251,%r193,%r196,%r230,%r196,%r230,%r198,%r230,%r200,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230,%r230);
	// end inline asm

$L__BB2_21:
	ld.const.u32 	%r231, [params+16];
	setp.eq.s32 	%p40, %r231, 0;
	@%p40 bra 	$L__BB2_30;

	ld.const.u64 	%rd9, [params+8];
	setp.eq.s64 	%p42, %rd9, 0;
	or.pred  	%p43, %p38, %p42;
	mov.u32 	%r471, 0;
	mov.u32 	%r470, 1287568416;
	@%p43 bra 	$L__BB2_24;

	mov.f32 	%f258, 0f3727C5AC;
	mov.f32 	%f260, 0f00000000;
	mov.u32 	%r269, 255;
	mov.u32 	%r272, 1;
	mov.u32 	%r274, 4;
	mov.u32 	%r276, 1287568416;
	mov.u32 	%r306, 0;
	// begin inline asm
	call(%r471,%r470,%r238,%r239,%r240,%r241,%r242,%r243,%r244,%r245,%r246,%r247,%r248,%r249,%r250,%r251,%r252,%r253,%r254,%r255,%r256,%r257,%r258,%r259,%r260,%r261,%r262,%r263,%r264,%r265,%r266,%r267),_optix_trace_typed_32,(%r306,%rd9,%f75,%f76,%f77,%f72,%f73,%f74,%f258,%f78,%f260,%r269,%r272,%r306,%r272,%r306,%r274,%r306,%r276,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306,%r306);
	// end inline asm

$L__BB2_24:
	setp.eq.s32 	%p44, %r472, 0;
	@%p44 bra 	$L__BB2_29;

	setp.eq.s32 	%p45, %r471, 0;
	@%p45 bra 	$L__BB2_30;

	mov.b32 	%f261, %r468;
	mov.b32 	%f262, %r470;
	setp.le.ftz.f32 	%p46, %f261, %f262;
	selp.b32 	%r472, %r472, %r471, %p46;
	bra.uni 	$L__BB2_30;

$L__BB2_10:
	ld.const.u64 	%rd47, [params+216];
	cvta.to.global.u64 	%rd48, %rd47;
	ld.const.u64 	%rd49, [params+224];
	cvta.to.global.u64 	%rd50, %rd49;
	ld.const.u64 	%rd51, [params+232];
	cvta.to.global.u64 	%rd52, %rd51;
	shl.b64 	%rd53, %rd2, 2;
	add.s64 	%rd54, %rd48, %rd53;
	add.s64 	%rd55, %rd50, %rd53;
	add.s64 	%rd56, %rd52, %rd53;
	ld.global.f32 	%f130, [%rd54];
	ld.global.f32 	%f131, [%rd55];
	mul.ftz.f32 	%f132, %f131, %f131;
	fma.rn.ftz.f32 	%f133, %f130, %f130, %f132;
	ld.global.f32 	%f134, [%rd56];
	fma.rn.ftz.f32 	%f135, %f134, %f134, %f133;
	mov.f32 	%f136, 0f2B8CBCCC;
	max.ftz.f32 	%f137, %f135, %f136;
	rsqrt.approx.ftz.f32 	%f138, %f137;
	mul.ftz.f32 	%f139, %f130, %f138;
	mul.ftz.f32 	%f140, %f131, %f138;
	mul.ftz.f32 	%f141, %f134, %f138;
	mul.ftz.f32 	%f142, %f2, %f140;
	fma.rn.ftz.f32 	%f143, %f1, %f139, %f142;
	fma.rn.ftz.f32 	%f41, %f3, %f141, %f143;
	mul.ftz.f32 	%f144, %f1, %f41;
	mul.ftz.f32 	%f145, %f2, %f41;
	mul.ftz.f32 	%f146, %f3, %f41;
	sub.ftz.f32 	%f42, %f139, %f144;
	sub.ftz.f32 	%f43, %f140, %f145;
	sub.ftz.f32 	%f44, %f141, %f146;
	mul.ftz.f32 	%f147, %f43, %f43;
	fma.rn.ftz.f32 	%f148, %f42, %f42, %f147;
	fma.rn.ftz.f32 	%f45, %f44, %f44, %f148;
	setp.gt.ftz.f32 	%p17, %f45, 0f2B8CBCCC;
	@%p17 bra 	$L__BB2_12;
	bra.uni 	$L__BB2_11;

$L__BB2_12:
	max.ftz.f32 	%f169, %f45, %f136;
	rsqrt.approx.ftz.f32 	%f170, %f169;
	mul.ftz.f32 	%f345, %f44, %f170;
	mul.ftz.f32 	%f344, %f43, %f170;
	mul.ftz.f32 	%f343, %f42, %f170;
	bra.uni 	$L__BB2_13;

$L__BB2_11:
	abs.ftz.f32 	%f149, %f3;
	setp.lt.ftz.f32 	%p18, %f149, 0f3F666666;
	selp.f32 	%f150, 0f3F800000, 0f00000000, %p18;
	selp.f32 	%f151, 0f00000000, 0f3F800000, %p18;
	mov.f32 	%f152, 0f00000000;
	mul.ftz.f32 	%f153, %f2, %f151;
	fma.rn.ftz.f32 	%f154, %f1, 0f00000000, %f153;
	fma.rn.ftz.f32 	%f155, %f3, %f150, %f154;
	mul.ftz.f32 	%f156, %f1, %f155;
	mul.ftz.f32 	%f157, %f2, %f155;
	mul.ftz.f32 	%f158, %f3, %f155;
	sub.ftz.f32 	%f159, %f152, %f156;
	sub.ftz.f32 	%f160, %f151, %f157;
	sub.ftz.f32 	%f161, %f150, %f158;
	mul.ftz.f32 	%f162, %f160, %f160;
	fma.rn.ftz.f32 	%f163, %f159, %f159, %f162;
	fma.rn.ftz.f32 	%f164, %f161, %f161, %f163;
	max.ftz.f32 	%f166, %f164, %f136;
	rsqrt.approx.ftz.f32 	%f167, %f166;
	mul.ftz.f32 	%f345, %f167, %f161;
	mul.ftz.f32 	%f344, %f167, %f160;
	mul.ftz.f32 	%f343, %f167, %f159;

$L__BB2_13:
	ld.const.u32 	%r466, [params+524];
	mov.f32 	%f171, 0fBF800000;
	max.ftz.f32 	%f172, %f41, %f171;
	mov.f32 	%f173, 0f3F800000;
	min.ftz.f32 	%f174, %f172, %f173;
	mul.ftz.f32 	%f175, %f174, %f174;
	sub.ftz.f32 	%f176, %f173, %f175;
	mov.f32 	%f177, 0f00000000;
	max.ftz.f32 	%f178, %f176, %f177;
	sqrt.approx.ftz.f32 	%f179, %f178;
	mul.ftz.f32 	%f180, %f2, %f345;
	mul.ftz.f32 	%f181, %f3, %f344;
	sub.ftz.f32 	%f182, %f180, %f181;
	mul.ftz.f32 	%f183, %f3, %f343;
	mul.ftz.f32 	%f184, %f1, %f345;
	sub.ftz.f32 	%f185, %f183, %f184;
	mul.ftz.f32 	%f186, %f1, %f344;
	mul.ftz.f32 	%f187, %f2, %f343;
	sub.ftz.f32 	%f188, %f186, %f187;
	mul.ftz.f32 	%f189, %f185, %f185;
	fma.rn.ftz.f32 	%f190, %f182, %f182, %f189;
	fma.rn.ftz.f32 	%f191, %f188, %f188, %f190;
	mov.f32 	%f192, 0f2B8CBCCC;
	max.ftz.f32 	%f193, %f191, %f192;
	rsqrt.approx.ftz.f32 	%f194, %f193;
	mul.ftz.f32 	%f195, %f194, %f182;
	mul.ftz.f32 	%f196, %f194, %f185;
	mul.ftz.f32 	%f197, %f194, %f188;
	xor.b32  	%r135, %r106, %r466;
	xor.b32  	%r136, %r135, -1640531527;
	shr.u32 	%r137, %r136, 16;
	xor.b32  	%r138, %r137, %r136;
	mul.lo.s32 	%r139, %r138, 2146121005;
	shr.u32 	%r140, %r139, 15;
	xor.b32  	%r141, %r140, %r139;
	mul.lo.s32 	%r142, %r141, -2073254261;
	shr.u32 	%r143, %r142, 16;
	and.b32  	%r144, %r142, 16777215;
	xor.b32  	%r145, %r143, %r144;
	cvt.rn.f32.u32 	%f198, %r145;
	mul.ftz.f32 	%f199, %f198, 0f33800000;
	mul.ftz.f32 	%f200, %f199, 0f40C90FDB;
	sin.approx.ftz.f32 	%f201, %f200;
	cos.approx.ftz.f32 	%f202, %f200;
	mul.ftz.f32 	%f203, %f343, %f202;
	mul.ftz.f32 	%f204, %f344, %f202;
	mul.ftz.f32 	%f205, %f345, %f202;
	fma.rn.ftz.f32 	%f206, %f195, %f201, %f203;
	fma.rn.ftz.f32 	%f207, %f196, %f201, %f204;
	fma.rn.ftz.f32 	%f208, %f197, %f201, %f205;
	mul.ftz.f32 	%f209, %f179, %f206;
	mul.ftz.f32 	%f210, %f179, %f207;
	mul.ftz.f32 	%f211, %f179, %f208;
	fma.rn.ftz.f32 	%f212, %f1, %f174, %f209;
	fma.rn.ftz.f32 	%f213, %f2, %f174, %f210;
	fma.rn.ftz.f32 	%f214, %f3, %f174, %f211;
	mul.ftz.f32 	%f215, %f213, %f213;
	fma.rn.ftz.f32 	%f216, %f212, %f212, %f215;
	fma.rn.ftz.f32 	%f217, %f214, %f214, %f216;
	max.ftz.f32 	%f218, %f217, %f192;
	rsqrt.approx.ftz.f32 	%f219, %f218;
	mul.ftz.f32 	%f55, %f219, %f212;
	mul.ftz.f32 	%f56, %f219, %f213;
	mul.ftz.f32 	%f57, %f219, %f214;
	setp.eq.s32 	%p19, %r10, 1;
	selp.f32 	%f220, %f56, %f57, %p19;
	selp.f32 	%f58, %f55, %f220, %p14;
	abs.ftz.f32 	%f221, %f58;
	setp.le.ftz.f32 	%p21, %f221, 0f358637BD;
	@%p21 bra 	$L__BB2_27;

	selp.f32 	%f222, %f5, %f6, %p19;
	selp.f32 	%f223, %f4, %f222, %p14;
	sub.ftz.f32 	%f224, %f339, %f223;
	div.approx.ftz.f32 	%f59, %f224, %f58;
	setp.leu.ftz.f32 	%p24, %f59, 0f38D1B717;
	@%p24 bra 	$L__BB2_27;

	abs.ftz.f32 	%f225, %f59;
	setp.geu.ftz.f32 	%p25, %f225, 0f7F800000;
	@%p25 bra 	$L__BB2_27;

	fma.rn.ftz.f32 	%f340, %f55, %f59, %f4;
	fma.rn.ftz.f32 	%f341, %f56, %f59, %f5;
	fma.rn.ftz.f32 	%f342, %f57, %f59, %f6;
	selp.f32 	%f63, %f341, %f340, %p14;
	setp.lt.u32 	%p27, %r10, 2;
	selp.f32 	%f64, %f342, %f341, %p27;
	setp.lt.ftz.f32 	%p28, %f63, %f124;
	setp.ge.ftz.f32 	%p29, %f63, %f125;
	or.pred  	%p30, %p29, %p28;
	setp.lt.ftz.f32 	%p31, %f64, %f126;
	or.pred  	%p32, %p30, %p31;
	setp.ge.ftz.f32 	%p33, %f64, %f127;
	or.pred  	%p34, %p33, %p32;
	@%p34 bra 	$L__BB2_27;

	sub.ftz.f32 	%f226, %f63, %f124;
	mov.f32 	%f227, 0f358637BD;
	max.ftz.f32 	%f228, %f14, %f227;
	div.approx.ftz.f32 	%f229, %f226, %f228;
	max.ftz.f32 	%f230, %f18, %f227;
	sub.ftz.f32 	%f231, %f64, %f126;
	div.approx.ftz.f32 	%f232, %f231, %f230;
	mul.ftz.f32 	%f233, %f229, %f10;
	cvt.rzi.ftz.s32.f32 	%r146, %f233;
	max.s32 	%r147, %r146, 0;
	add.s32 	%r148, %r108, -1;
	min.s32 	%r149, %r147, %r148;
	mul.ftz.f32 	%f234, %f232, %f11;
	cvt.rzi.ftz.s32.f32 	%r150, %f234;
	max.s32 	%r151, %r150, 0;
	add.s32 	%r152, %r109, -1;
	min.s32 	%r153, %r151, %r152;
	mad.lo.s32 	%r467, %r153, %r108, %r149;
	bra.uni 	$L__BB2_18;

$L__BB2_27:
	ld.const.u32 	%r154, [params+560];
	setp.eq.s32 	%p35, %r154, 0;
	@%p35 bra 	$L__BB2_61;

	ld.const.u64 	%rd57, [params+664];
	cvta.to.global.u64 	%rd58, %rd57;
	atom.global.add.u32 	%r155, [%rd58], 1;
	bra.uni 	$L__BB2_61;

$L__BB2_29:
	mov.u32 	%r472, %r4)PTX_CHUNK"
R"PTX_CHUNK(71;

$L__BB2_30:
	setp.ne.s32 	%p47, %r472, 0;
	@%p47 bra 	$L__BB2_42;

$L__BB2_31:
	sub.ftz.f32 	%f79, %f340, %f4;
	mul.ftz.f32 	%f263, %f79, %f79;
	sub.ftz.f32 	%f80, %f341, %f5;
	fma.rn.ftz.f32 	%f264, %f80, %f80, %f263;
	sub.ftz.f32 	%f81, %f342, %f6;
	fma.rn.ftz.f32 	%f265, %f81, %f81, %f264;
	max.ftz.f32 	%f267, %f265, %f238;
	sqrt.approx.ftz.f32 	%f82, %f267;
	setp.le.ftz.f32 	%p48, %f82, 0f3727C5AC;
	@%p48 bra 	$L__BB2_44;

	rcp.approx.ftz.f32 	%f268, %f82;
	mul.ftz.f32 	%f83, %f79, %f268;
	mul.ftz.f32 	%f84, %f80, %f268;
	mul.ftz.f32 	%f85, %f81, %f268;
	fma.rn.ftz.f32 	%f86, %f83, 0f38D1B717, %f4;
	fma.rn.ftz.f32 	%f87, %f84, 0f38D1B717, %f5;
	fma.rn.ftz.f32 	%f88, %f85, 0f38D1B717, %f6;
	add.ftz.f32 	%f269, %f82, 0fB951B717;
	mov.f32 	%f270, 0f00000000;
	max.ftz.f32 	%f89, %f269, %f270;
	ld.const.u64 	%rd10, [params];
	setp.eq.s64 	%p49, %rd10, 0;
	setp.le.ftz.f32 	%p50, %f89, 0f3727C5AC;
	or.pred  	%p51, %p50, %p49;
	mov.u32 	%r478, 0;
	mov.u32 	%r475, 1287568416;
	@%p51 bra 	$L__BB2_34;

	mov.f32 	%f277, 0f3727C5AC;
	mov.u32 	%r344, 255;
	mov.u32 	%r347, 1;
	mov.u32 	%r349, 4;
	mov.u32 	%r351, 1287568416;
	mov.u32 	%r381, 0;
	// begin inline asm
	call(%r478,%r475,%r313,%r314,%r315,%r316,%r317,%r318,%r319,%r320,%r321,%r322,%r323,%r324,%r325,%r326,%r327,%r328,%r329,%r330,%r331,%r332,%r333,%r334,%r335,%r336,%r337,%r338,%r339,%r340,%r341,%r342),_optix_trace_typed_32,(%r381,%rd10,%f86,%f87,%f88,%f83,%f84,%f85,%f277,%f89,%f270,%r344,%r347,%r381,%r347,%r381,%r349,%r381,%r351,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381,%r381);
	// end inline asm

$L__BB2_34:
	ld.const.u32 	%r382, [params+16];
	setp.eq.s32 	%p52, %r382, 0;
	@%p52 bra 	$L__BB2_41;

	ld.const.u64 	%rd11, [params+8];
	setp.eq.s64 	%p54, %rd11, 0;
	or.pred  	%p55, %p50, %p54;
	mov.u32 	%r476, 0;
	mov.u32 	%r477, 1287568416;
	@%p55 bra 	$L__BB2_37;

	mov.f32 	%f286, 0f3727C5AC;
	mov.f32 	%f288, 0f00000000;
	mov.u32 	%r420, 255;
	mov.u32 	%r423, 1;
	mov.u32 	%r425, 4;
	mov.u32 	%r427, 1287568416;
	mov.u32 	%r457, 0;
	// begin inline asm
	call(%r476,%r477,%r389,%r390,%r391,%r392,%r393,%r394,%r395,%r396,%r397,%r398,%r399,%r400,%r401,%r402,%r403,%r404,%r405,%r406,%r407,%r408,%r409,%r410,%r411,%r412,%r413,%r414,%r415,%r416,%r417,%r418),_optix_trace_typed_32,(%r457,%rd11,%f86,%f87,%f88,%f83,%f84,%f85,%f286,%f89,%f288,%r420,%r423,%r457,%r423,%r457,%r425,%r457,%r427,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457,%r457);
	// end inline asm

$L__BB2_37:
	setp.eq.s32 	%p56, %r478, 0;
	@%p56 bra 	$L__BB2_40;

	setp.eq.s32 	%p57, %r476, 0;
	@%p57 bra 	$L__BB2_41;

	mov.b32 	%f289, %r475;
	mov.b32 	%f290, %r477;
	setp.le.ftz.f32 	%p58, %f289, %f290;
	selp.b32 	%r478, %r478, %r476, %p58;
	bra.uni 	$L__BB2_41;

$L__BB2_40:
	mov.u32 	%r478, %r476;

$L__BB2_41:
	setp.eq.s32 	%p59, %r478, 0;
	@%p59 bra 	$L__BB2_44;

$L__BB2_42:
	ld.const.u32 	%r458, [params+560];
	setp.eq.s32 	%p60, %r458, 0;
	@%p60 bra 	$L__BB2_61;

	ld.const.u64 	%rd63, [params+648];
	cvta.to.global.u64 	%rd64, %rd63;
	atom.global.add.u32 	%r459, [%rd64], 1;
	bra.uni 	$L__BB2_61;

$L__BB2_44:
	ld.global.f32 	%f292, [%rd5];
	sub.ftz.f32 	%f293, %f4, %f292;
	ld.global.f32 	%f294, [%rd6];
	sub.ftz.f32 	%f295, %f5, %f294;
	ld.global.f32 	%f296, [%rd7];
	sub.ftz.f32 	%f297, %f6, %f296;
	mul.ftz.f32 	%f298, %f295, %f295;
	fma.rn.ftz.f32 	%f299, %f293, %f293, %f298;
	fma.rn.ftz.f32 	%f300, %f297, %f297, %f299;
	mov.f32 	%f301, 0f00000000;
	max.ftz.f32 	%f302, %f300, %f301;
	sqrt.approx.ftz.f32 	%f303, %f302;
	mov.f32 	%f304, 0f358637BD;
	max.ftz.f32 	%f90, %f303, %f304;
	max.ftz.f32 	%f91, %f82, %f304;
	ld.global.f32 	%f305, [%rd3];
	ld.global.f32 	%f306, [%rd4];
	sub.ftz.f32 	%f92, %f306, %f305;
	ld.const.u64 	%rd65, [params+176];
	cvta.to.global.u64 	%rd66, %rd65;
	shl.b64 	%rd67, %rd2, 2;
	add.s64 	%rd68, %rd66, %rd67;
	ld.global.f32 	%f93, [%rd68];
	ld.const.u64 	%rd69, [params+160];
	cvta.to.global.u64 	%rd70, %rd69;
	add.s64 	%rd71, %rd70, %rd67;
	ld.global.u32 	%r101, [%rd71];
	ld.const.u64 	%rd72, [params+168];
	cvta.to.global.u64 	%rd73, %rd72;
	add.s64 	%rd74, %rd73, %rd67;
	ld.global.u32 	%r102, [%rd74];
	ld.const.u64 	%rd12, [params+496];
	setp.eq.s64 	%p61, %rd12, 0;
	ld.const.u32 	%r103, [params+512];
	setp.lt.s32 	%p62, %r103, 1;
	or.pred  	%p63, %p61, %p62;
	mov.f32 	%f291, 0f3F800000;
	mov.f32 	%f349, %f291;
	@%p63 bra 	$L__BB2_52;

	setp.lt.s32 	%p64, %r101, 0;
	setp.le.s32 	%p65, %r103, %r101;
	or.pred  	%p66, %p64, %p65;
	mov.u32 	%r480, %r102;
	@%p66 bra 	$L__BB2_48;

	ld.const.u64 	%rd13, [params+504];
	setp.eq.s64 	%p67, %rd13, 0;
	mov.u32 	%r480, %r101;
	@%p67 bra 	$L__BB2_48;

	cvta.to.global.u64 	%rd75, %rd13;
	cvt.s64.s32 	%rd76, %r101;
	add.s64 	%rd77, %rd75, %rd76;
	ld.global.u8 	%rs2, [%rd77];
	setp.eq.s16 	%p68, %rs2, 0;
	selp.b32 	%r480, %r102, %r101, %p68;

$L__BB2_48:
	setp.ge.s32 	%p69, %r480, %r103;
	setp.lt.s32 	%p70, %r480, 0;
	or.pred  	%p71, %p70, %p69;
	mov.f32 	%f349, %f291;
	@%p71 bra 	$L__BB2_52;

	ld.const.u64 	%rd14, [params+504];
	setp.eq.s64 	%p72, %rd14, 0;
	@%p72 bra 	$L__BB2_51;

	cvta.to.global.u64 	%rd78, %rd14;
	cvt.s64.s32 	%rd79, %r480;
	add.s64 	%rd80, %rd78, %rd79;
	ld.global.u8 	%rs3, [%rd80];
	setp.eq.s16 	%p73, %rs3, 0;
	mov.f32 	%f349, %f291;
	@%p73 bra 	$L__BB2_52;

$L__BB2_51:
	cvta.to.global.u64 	%rd81, %rd12;
	mul.wide.s32 	%rd82, %r480, 4;
	add.s64 	%rd83, %rd81, %rd82;
	ld.global.f32 	%f309, [%rd83];
	mov.f32 	%f310, 0f00000000;
	max.ftz.f32 	%f349, %f309, %f310;

$L__BB2_52:
	cvt.rn.f32.s32 	%f311, %r6;
	max.ftz.f32 	%f313, %f311, %f291;
	rcp.approx.ftz.f32 	%f314, %f313;
	ld.const.u64 	%rd84, [params+208];
	cvta.to.global.u64 	%rd85, %rd84;
	add.s64 	%rd87, %rd85, %rd67;
	ld.global.f32 	%f315, [%rd87];
	mul.ftz.f32 	%f316, %f349, %f315;
	max.ftz.f32 	%f318, %f92, %f301;
	mul.ftz.f32 	%f319, %f318, %f316;
	ld.const.f32 	%f320, [params+464];
	mul.ftz.f32 	%f321, %f320, %f319;
	mov.f32 	%f322, 0f3F490FDB;
	max.ftz.f32 	%f323, %f93, %f322;
	mov.f32 	%f324, 0f40C90FDB;
	div.approx.ftz.f32 	%f325, %f323, %f324;
	mov.f32 	%f326, 0f40000000;
	min.ftz.f32 	%f327, %f325, %f326;
	mul.ftz.f32 	%f328, %f327, %f321;
	mul.ftz.f32 	%f329, %f314, %f328;
	mul.ftz.f32 	%f330, %f90, %f90;
	mul.ftz.f32 	%f331, %f330, %f91;
	mul.ftz.f32 	%f332, %f91, %f331;
	div.approx.ftz.f32 	%f96, %f329, %f332;
	setp.leu.ftz.f32 	%p74, %f96, 0f00000000;
	@%p74 bra 	$L__BB2_59;

	abs.ftz.f32 	%f333, %f96;
	setp.geu.ftz.f32 	%p75, %f333, 0f7F800000;
	@%p75 bra 	$L__BB2_59;
	bra.uni 	$L__BB2_54;

$L__BB2_59:
	ld.const.u32 	%r464, [params+560];
	setp.eq.s32 	%p78, %r464, 0;
	@%p78 bra 	$L__BB2_61;

	ld.const.u64 	%rd101, [params+664];
	cvta.to.global.u64 	%rd102, %rd101;
	atom.global.add.u32 	%r465, [%rd102], 1;
	bra.uni 	$L__BB2_61;

$L__BB2_54:
	ld.const.u64 	%rd88, [params+568];
	cvta.to.global.u64 	%rd89, %rd88;
	mul.wide.s32 	%rd90, %r467, 4;
	add.s64 	%rd91, %rd89, %rd90;
	atom.global.add.f32 	%f334, [%rd91], %f96;
	ld.const.u64 	%rd92, [params+576];
	cvta.to.global.u64 	%rd93, %rd92;
	add.s64 	%rd94, %rd93, %rd90;
	mov.f32 	%f335, 0f00000000;
	max.ftz.f32 	%f336, %f96, %f335;
	sqrt.approx.ftz.f32 	%f337, %f336;
	atom.global.add.f32 	%f338, [%rd94], %f337;
	@%p16 bra 	$L__BB2_56;
	bra.uni 	$L__BB2_55;

$L__BB2_56:
	ld.const.u64 	%rd97, [params+624];
	cvta.to.global.u64 	%rd98, %rd97;
	atom.global.add.u32 	%r461, [%rd98], 1;
	bra.uni 	$L__BB2_57;

$L__BB2_55:
	ld.const.u64 	%rd95, [params+632];
	cvta.to.global.u64 	%rd96, %rd95;
	atom.global.add.u32 	%r460, [%rd96], 1;

$L__BB2_57:
	ld.const.u32 	%r462, [params+556];
	setp.eq.s32 	%p77, %r462, 0;
	@%p77 bra 	$L__BB2_61;

	ld.const.u64 	%rd99, [params+672];
	cvta.to.global.u64 	%rd100, %rd99;
	atom.global.add.u32 	%r463, [%rd100], 1;
	bra.uni 	$L__BB2_61;

}
	// .globl	__raygen__diffraction_chain_accumulation
.visible .entry __raygen__diffraction_chain_accumulation()
{
	.reg .pred 	%p<154>;
	.reg .b16 	%rs<27>;
	.reg .f32 	%f<604>;
	.reg .b32 	%r<966>;
	.reg .b64 	%rd<221>;


	// begin inline asm
	call (%r212), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r213, [params+20];
	setp.ge.u32 	%p2, %r212, %r213;
	ld.const.u32 	%r2, [params+32];
	setp.lt.s32 	%p3, %r2, 1;
	or.pred  	%p4, %p2, %p3;
	ld.const.u32 	%r3, [params+272];
	setp.lt.s32 	%p5, %r3, 1;
	or.pred  	%p6, %p4, %p5;
	ld.const.v2.u32 	{%r214, %r215}, [params+456];
	setp.lt.s32 	%p7, %r214, 1;
	or.pred  	%p8, %p6, %p7;
	setp.lt.s32 	%p9, %r215, 1;
	or.pred  	%p10, %p8, %p9;
	@%p10 bra 	$L__BB3_123;

	ld.const.u32 	%r6, [params+532];
	or.b32  	%r216, %r6, 1;
	setp.ne.s32 	%p11, %r216, 3;
	@%p11 bra 	$L__BB3_123;

	ld.const.u32 	%r7, [params+544];
	and.b32  	%r217, %r7, 3;
	setp.eq.s32 	%p12, %r217, 0;
	@%p12 bra 	$L__BB3_123;

	and.b32  	%r218, %r7, 1;
	neg.s32 	%r219, %r218;
	ld.const.v2.u32 	{%r220, %r221}, [params+536];
	and.b32  	%r8, %r219, %r220;
	shl.b32 	%r224, %r7, 30;
	shr.s32 	%r225, %r224, 31;
	and.b32  	%r9, %r225, %r221;
	add.s32 	%r226, %r8, %r9;
	setp.lt.s32 	%p13, %r226, 1;
	setp.ge.s32 	%p14, %r212, %r226;
	or.pred  	%p15, %p13, %p14;
	@%p15 bra 	$L__BB3_123;
	bra.uni 	$L__BB3_4;

$L__BB3_123:
	ret;

$L__BB3_4:
	rem.u32 	%r10, %r212, %r2;
	ld.const.u32 	%r11, [params+524];
	mul.lo.s32 	%r227, %r11, -1640531527;
	xor.b32  	%r228, %r212, %r227;
	xor.b32  	%r229, %r228, 1374496523;
	shr.u32 	%r230, %r229, 16;
	xor.b32  	%r231, %r230, %r229;
	mul.lo.s32 	%r232, %r231, 2146121005;
	shr.u32 	%r233, %r232, 15;
	xor.b32  	%r234, %r233, %r232;
	mul.lo.s32 	%r235, %r234, -2073254261;
	shr.u32 	%r236, %r235, 16;
	xor.b32  	%r237, %r236, %r235;
	rem.u32 	%r12, %r237, %r3;
	ld.const.u64 	%rd1, [params+24];
	setp.eq.s64 	%p16, %rd1, 0;
	@%p16 bra 	$L__BB3_6;

	cvta.to.global.u64 	%rd39, %rd1;
	cvt.s64.s32 	%rd40, %r10;
	add.s64 	%rd41, %rd39, %rd40;
	ld.global.u8 	%rs9, [%rd41];
	setp.eq.s16 	%p17, %rs9, 0;
	@%p17 bra 	$L__BB3_123;

$L__BB3_6:
	ld.const.u64 	%rd2, [params+280];
	setp.eq.s64 	%p18, %rd2, 0;
	@%p18 bra 	$L__BB3_8;

	cvta.to.global.u64 	%rd42, %rd2;
	cvt.s64.s32 	%rd43, %r12;
	add.s64 	%rd44, %rd42, %rd43;
	ld.global.u8 	%rs10, [%rd44];
	setp.eq.s16 	%p19, %rs10, 0;
	@%p19 bra 	$L__BB3_123;

$L__BB3_8:
	setp.ne.s32 	%p20, %r6, 3;
	mov.u32 	%r937, -1;
	mov.u32 	%r936, %r937;
	@%p20 bra 	$L__BB3_11;

	mul.lo.s32 	%r239, %r11, -2048144789;
	xor.b32  	%r240, %r212, %r239;
	xor.b32  	%r241, %r240, -1028477387;
	shr.u32 	%r242, %r241, 16;
	xor.b32  	%r243, %r242, %r241;
	mul.lo.s32 	%r244, %r243, 2146121005;
	shr.u32 	%r245, %r244, 15;
	xor.b32  	%r246, %r245, %r244;
	mul.lo.s32 	%r247, %r246, -2073254261;
	shr.u32 	%r248, %r247, 16;
	xor.b32  	%r249, %r248, %r247;
	rem.u32 	%r936, %r249, %r3;
	@%p18 bra 	$L__BB3_11;

	cvta.to.global.u64 	%rd45, %rd2;
	cvt.s64.s32 	%rd46, %r936;
	add.s64 	%rd47, %rd45, %rd46;
	ld.global.u8 	%rs11, [%rd47];
	setp.eq.s16 	%p22, %rs11, 0;
	@%p22 bra 	$L__BB3_123;

$L__BB3_11:
	ld.const.u64 	%rd48, [params+40];
	cvta.to.global.u64 	%rd49, %rd48;
	cvt.s64.s32 	%rd3, %r10;
	mul.wide.s32 	%rd50, %r10, 4;
	add.s64 	%rd51, %rd49, %rd50;
	ld.global.u32 	%r15, [%rd51];
	ld.const.u64 	%rd52, [params+288];
	cvta.to.global.u64 	%rd4, %rd52;
	cvt.s64.s32 	%rd5, %r12;
	mul.wide.s32 	%rd53, %r12, 4;
	add.s64 	%rd54, %rd4, %rd53;
	ld.global.u32 	%r16, [%rd54];
	@%p20 bra 	$L__BB3_13;

	mul.wide.s32 	%rd55, %r936, 4;
	add.s64 	%rd56, %rd4, %rd55;
	ld.global.u32 	%r937, [%rd56];

$L__BB3_13:
	setp.eq.s32 	%p24, %r15, %r16;
	@%p24 bra 	$L__BB3_121;

	setp.eq.s32 	%p25, %r6, 3;
	setp.eq.s32 	%p26, %r16, %r937;
	setp.eq.s32 	%p27, %r15, %r937;
	or.pred  	%p28, %p27, %p26;
	and.pred  	%p29, %p28, %p25;
	@%p29 bra 	$L__BB3_121;
	bra.uni 	$L__BB3_15;

$L__BB3_121:
	ld.const.u32 	%r924, [params+560];
	setp.eq.s32 	%p153, %r924, 0;
	@%p153 bra 	$L__BB3_123;

	ld.const.u64 	%rd192, [params+664];
	cvta.to.global.u64 	%rd193, %rd192;
	atom.global.add.u32 	%r925, [%rd193], 1;
	bra.uni 	$L__BB3_123;

$L__BB3_15:
	mul.lo.s32 	%r251, %r215, %r214;
	div.u32 	%r252, %r212, %r2;
	rem.u32 	%r938, %r252, %r251;
	xor.b32  	%r253, %r11, %r212;
	shr.u32 	%r254, %r253, 16;
	xor.b32  	%r255, %r254, %r253;
	mul.lo.s32 	%r256, %r255, 2146121005;
	shr.u32 	%r257, %r256, 15;
	xor.b32  	%r258, %r257, %r256;
	mul.lo.s32 	%r259, %r258, -2073254261;
	shr.u32 	%r260, %r259, 16;
	and.b32  	%r261, %r259, 16777215;
	xor.b32  	%r262, %r260, %r261;
	cvt.rn.f32.u32 	%f179, %r262;
	mul.ftz.f32 	%f180, %f179, 0f33800000;
	xor.b32  	%r263, %r253, 1013904242;
	shr.u32 	%r264, %r263, 16;
	xor.b32  	%r265, %r264, %r263;
	mul.lo.s32 	%r266, %r265, 2146121005;
	shr.u32 	%r267, %r266, 15;
	xor.b32  	%r268, %r267, %r266;
	mul.lo.s32 	%r269, %r268, -2073254261;
	shr.u32 	%r270, %r269, 16;
	and.b32  	%r271, %r269, 16777215;
	xor.b32  	%r272, %r270, %r271;
	cvt.rn.f32.u32 	%f181, %r272;
	mul.ftz.f32 	%f182, %f181, 0f33800000;
	ld.const.u64 	%rd57, [params+48];
	cvta.to.global.u64 	%rd58, %rd57;
	ld.const.u64 	%rd59, [params+56];
	cvta.to.global.u64 	%rd60, %rd59;
	ld.const.u64 	%rd61, [params+64];
	cvta.to.global.u64 	%rd62, %rd61;
	shl.b64 	%rd63, %rd3, 2;
	add.s64 	%rd64, %rd58, %rd63;
	add.s64 	%rd65, %rd60, %rd63;
	add.s64 	%rd66, %rd62, %rd63;
	ld.const.u64 	%rd67, [params+72];
	cvta.to.global.u64 	%rd68, %rd67;
	ld.const.u64 	%rd69, [params+80];
	cvta.to.global.u64 	%rd70, %rd69;
	ld.const.u64 	%rd71, [params+88];
	cvta.to.global.u64 	%rd72, %rd71;
	add.s64 	%rd73, %rd68, %rd63;
	add.s64 	%rd74, %rd70, %rd63;
	add.s64 	%rd75, %rd72, %rd63;
	ld.global.f32 	%f183, [%rd73];
	ld.global.f32 	%f184, [%rd74];
	mul.ftz.f32 	%f185, %f184, %f184;
	fma.rn.ftz.f32 	%f186, %f183, %f183, %f185;
	ld.global.f32 	%f187, [%rd75];
	fma.rn.ftz.f32 	%f188, %f187, %f187, %f186;
	mov.f32 	%f189, 0f2B8CBCCC;
	max.ftz.f32 	%f190, %f188, %f189;
	rsqrt.approx.ftz.f32 	%f191, %f190;
	mul.ftz.f32 	%f192, %f183, %f191;
	mul.ftz.f32 	%f193, %f184, %f191;
	mul.ftz.f32 	%f194, %f187, %f191;
	ld.const.u64 	%rd76, [params+96];
	cvta.to.global.u64 	%rd77, %rd76;
	add.s64 	%rd6, %rd77, %rd63;
	ld.const.u64 	%rd78, [params+104];
	cvta.to.global.u64 	%rd79, %rd78;
	add.s64 	%rd7, %rd79, %rd63;
	ld.global.f32 	%f195, [%rd7];
	ld.global.f32 	%f196, [%rd6];
	sub.ftz.f32 	%f197, %f195, %f196;
	fma.rn.ftz.f32 	%f198, %f180, %f197, %f196;
	ld.global.f32 	%f199, [%rd64];
	fma.rn.ftz.f32 	%f1, %f192, %f198, %f199;
	ld.global.f32 	%f200, [%rd65];
	fma.rn.ftz.f32 	%f2, %f193, %f198, %f200;
	ld.global.f32 	%f201, [%rd66];
	fma.rn.ftz.f32 	%f3, %f194, %f198, %f201;
	ld.const.u64 	%rd80, [params+296];
	cvta.to.global.u64 	%rd8, %rd80;
	ld.const.u64 	%rd81, [params+304];
	cvta.to.global.u64 	%rd9, %rd81;
	ld.const.u64 	%rd82, [params+312];
	cvta.to.global.u64 	%rd10, %rd82;
	shl.b64 	%rd83, %rd5, 2;
	add.s64 	%rd84, %rd8, %rd83;
	add.s64 	%rd85, %rd9, %rd83;
	add.s64 	%rd86, %rd10, %rd83;
	ld.const.u64 	%rd87, [params+320];
	cvta.to.global.u64 	%rd11, %rd87;
	ld.const.u64 	%rd88, [params+328];
	cvta.to.global.u64 	%rd12, %rd88;
	ld.const.u64 	%rd89, [params+336];
	cvta.to.global.u64 	%rd13, %rd89;
	add.s64 	%rd90, %rd11, %rd83;
	add.s64 	%rd91, %rd12, %rd83;
	add.s64 	%rd92, %rd13, %rd83;
	ld.global.f32 	%f202, [%rd90];
	ld.global.f32 	%f203, [%rd91];
	mul.ftz.f32 	%f204, %f203, %f203;
	fma.rn.ftz.f32 	%f205, %f202, %f202, %f204;
	ld.global.f32 	%f206, [%rd92];
	fma.rn.ftz.f32 	%f207, %f206, %f206, %f205;
	max.ftz.f32 	%f208, %f207, %f189;
	rsqrt.approx.ftz.f32 	%f209, %f208;
	mul.ftz.f32 	%f6, %f206, %f209;
	mul.ftz.f32 	%f5, %f203, %f209;
	mul.ftz.f32 	%f4, %f202, %f209;
	ld.const.u64 	%rd93, [params+344];
	cvta.to.global.u64 	%rd14, %rd93;
	add.s64 	%rd15, %rd14, %rd83;
	ld.const.u64 	%rd94, [params+352];
	cvta.to.global.u64 	%rd16, %rd94;
	add.s64 	%rd17, %rd16, %rd83;
	ld.global.f32 	%f210, [%rd17];
	ld.global.f32 	%f211, [%rd15];
	sub.ftz.f32 	%f212, %f210, %f211;
	fma.rn.ftz.f32 	%f213, %f182, %f212, %f211;
	ld.global.f32 	%f214, [%rd8)PTX_CHUNK"
R"PTX_CHUNK(4];
	fma.rn.ftz.f32 	%f7, %f4, %f213, %f214;
	ld.global.f32 	%f215, [%rd85];
	fma.rn.ftz.f32 	%f8, %f5, %f213, %f215;
	ld.global.f32 	%f216, [%rd86];
	fma.rn.ftz.f32 	%f9, %f6, %f213, %f216;
	ld.const.u64 	%rd95, [params+184];
	cvta.to.global.u64 	%rd96, %rd95;
	ld.const.u64 	%rd97, [params+192];
	cvta.to.global.u64 	%rd98, %rd97;
	ld.const.u64 	%rd99, [params+200];
	cvta.to.global.u64 	%rd100, %rd99;
	add.s64 	%rd101, %rd96, %rd63;
	ld.global.f32 	%f10, [%rd101];
	add.s64 	%rd102, %rd98, %rd63;
	ld.global.f32 	%f11, [%rd102];
	add.s64 	%rd103, %rd100, %rd63;
	ld.global.f32 	%f12, [%rd103];
	div.s32 	%r273, %r938, %r214;
	mul.lo.s32 	%r274, %r273, %r214;
	sub.s32 	%r275, %r938, %r274;
	cvt.rn.f32.s32 	%f217, %r275;
	add.ftz.f32 	%f218, %f217, 0f3F000000;
	cvt.rn.f32.s32 	%f13, %r214;
	mov.f32 	%f219, 0f3F800000;
	max.ftz.f32 	%f220, %f13, %f219;
	div.approx.ftz.f32 	%f221, %f218, %f220;
	cvt.rn.f32.s32 	%f222, %r273;
	add.ftz.f32 	%f223, %f222, 0f3F000000;
	cvt.rn.f32.s32 	%f14, %r215;
	max.ftz.f32 	%f224, %f14, %f219;
	div.approx.ftz.f32 	%f225, %f223, %f224;
	ld.const.v2.f32 	{%f226, %f227}, [params+440];
	sub.ftz.f32 	%f17, %f227, %f226;
	fma.rn.ftz.f32 	%f18, %f221, %f17, %f226;
	ld.const.v2.f32 	{%f228, %f229}, [params+448];
	sub.ftz.f32 	%f21, %f229, %f228;
	fma.rn.ftz.f32 	%f22, %f225, %f21, %f228;
	ld.const.u32 	%r20, [params+432];
	setp.eq.s32 	%p30, %r20, 0;
	@%p30 bra 	$L__BB3_18;

	ld.const.u32 	%r927, [params+432];
	setp.eq.s32 	%p31, %r927, 1;
	ld.const.f32 	%f581, [params+436];
	mov.f32 	%f582, %f18;
	mov.f32 	%f583, %f22;
	mov.f32 	%f584, %f581;
	@%p31 bra 	$L__BB3_17;
	bra.uni 	$L__BB3_19;

$L__BB3_17:
	mov.f32 	%f582, %f18;
	mov.f32 	%f583, %f581;
	mov.f32 	%f584, %f22;
	bra.uni 	$L__BB3_19;

$L__BB3_18:
	ld.const.f32 	%f581, [params+436];
	mov.f32 	%f582, %f581;
	mov.f32 	%f583, %f18;
	mov.f32 	%f584, %f22;

$L__BB3_19:
	mul.wide.s32 	%rd104, %r936, 4;
	add.s64 	%rd19, %rd14, %rd104;
	add.s64 	%rd20, %rd16, %rd104;
	mov.f32 	%f585, %f7;
	mov.f32 	%f586, %f8;
	mov.f32 	%f587, %f9;
	mov.f32 	%f588, %f4;
	mov.f32 	%f589, %f5;
	mov.f32 	%f590, %f6;
	@%p20 bra 	$L__BB3_21;

	ld.const.u32 	%r931, [params+524];
	ld.const.u64 	%rd220, [params+320];
	cvta.to.global.u64 	%rd219, %rd220;
	ld.const.u64 	%rd218, [params+312];
	cvta.to.global.u64 	%rd217, %rd218;
	ld.const.u64 	%rd216, [params+304];
	cvta.to.global.u64 	%rd215, %rd216;
	xor.b32  	%r276, %r212, %r931;
	xor.b32  	%r277, %r276, 2027808484;
	shr.u32 	%r278, %r277, 16;
	xor.b32  	%r279, %r278, %r277;
	mul.lo.s32 	%r280, %r279, 2146121005;
	shr.u32 	%r281, %r280, 15;
	xor.b32  	%r282, %r281, %r280;
	mul.lo.s32 	%r283, %r282, -2073254261;
	shr.u32 	%r284, %r283, 16;
	and.b32  	%r285, %r283, 16777215;
	xor.b32  	%r286, %r284, %r285;
	cvt.rn.f32.u32 	%f232, %r286;
	mul.ftz.f32 	%f233, %f232, 0f33800000;
	add.s64 	%rd106, %rd8, %rd104;
	add.s64 	%rd107, %rd215, %rd104;
	add.s64 	%rd108, %rd217, %rd104;
	add.s64 	%rd109, %rd219, %rd104;
	add.s64 	%rd110, %rd12, %rd104;
	add.s64 	%rd111, %rd13, %rd104;
	ld.global.f32 	%f234, [%rd109];
	ld.global.f32 	%f235, [%rd110];
	mul.ftz.f32 	%f236, %f235, %f235;
	fma.rn.ftz.f32 	%f237, %f234, %f234, %f236;
	ld.global.f32 	%f238, [%rd111];
	fma.rn.ftz.f32 	%f239, %f238, %f238, %f237;
	mov.f32 	%f240, 0f2B8CBCCC;
	max.ftz.f32 	%f241, %f239, %f240;
	rsqrt.approx.ftz.f32 	%f242, %f241;
	mul.ftz.f32 	%f588, %f234, %f242;
	mul.ftz.f32 	%f589, %f235, %f242;
	mul.ftz.f32 	%f590, %f238, %f242;
	ld.global.f32 	%f243, [%rd20];
	ld.global.f32 	%f244, [%rd19];
	sub.ftz.f32 	%f245, %f243, %f244;
	fma.rn.ftz.f32 	%f246, %f233, %f245, %f244;
	ld.global.f32 	%f247, [%rd106];
	ld.global.f32 	%f248, [%rd107];
	ld.global.f32 	%f249, [%rd108];
	fma.rn.ftz.f32 	%f587, %f590, %f246, %f249;
	fma.rn.ftz.f32 	%f586, %f589, %f246, %f248;
	fma.rn.ftz.f32 	%f585, %f588, %f246, %f247;

$L__BB3_21:
	selp.f32 	%f57, %f586, %f8, %p25;
	selp.f32 	%f56, %f585, %f7, %p25;
	selp.f32 	%f58, %f587, %f9, %p25;
	selp.f32 	%f60, %f589, %f5, %p25;
	selp.f32 	%f59, %f588, %f4, %p25;
	selp.f32 	%f61, %f590, %f6, %p25;
	setp.lt.s32 	%p34, %r212, %r8;
	@%p34 bra 	$L__BB3_33;
	bra.uni 	$L__BB3_22;

$L__BB3_33:
	sub.ftz.f32 	%f107, %f1, %f10;
	sub.ftz.f32 	%f108, %f2, %f11;
	mul.ftz.f32 	%f352, %f108, %f108;
	fma.rn.ftz.f32 	%f353, %f107, %f107, %f352;
	sub.ftz.f32 	%f109, %f3, %f12;
	fma.rn.ftz.f32 	%f354, %f109, %f109, %f353;
	mov.f32 	%f355, 0f00000000;
	max.ftz.f32 	%f356, %f354, %f355;
	sqrt.approx.ftz.f32 	%f110, %f356;
	setp.le.ftz.f32 	%p55, %f110, 0f3727C5AC;
	mov.u16 	%rs24, 1;
	mov.u16 	%rs23, %rs24;
	@%p55 bra 	$L__BB3_46;

	rcp.approx.ftz.f32 	%f357, %f110;
	mul.ftz.f32 	%f111, %f107, %f357;
	mul.ftz.f32 	%f112, %f108, %f357;
	mul.ftz.f32 	%f113, %f109, %f357;
	fma.rn.ftz.f32 	%f114, %f111, 0f38D1B717, %f10;
	fma.rn.ftz.f32 	%f115, %f112, 0f38D1B717, %f11;
	fma.rn.ftz.f32 	%f116, %f113, 0f38D1B717, %f12;
	add.ftz.f32 	%f358, %f110, 0fB951B717;
	max.ftz.f32 	%f117, %f358, %f355;
	ld.const.u64 	%rd21, [params];
	setp.eq.s64 	%p56, %rd21, 0;
	setp.le.ftz.f32 	%p57, %f117, 0f3727C5AC;
	or.pred  	%p58, %p57, %p56;
	mov.u32 	%r943, 0;
	mov.u32 	%r939, 1287568416;
	@%p58 bra 	$L__BB3_36;

	mov.f32 	%f366, 0f3727C5AC;
	mov.f32 	%f368, 0f00000000;
	mov.u32 	%r346, 255;
	mov.u32 	%r349, 1;
	mov.u32 	%r351, 4;
	mov.u32 	%r353, 1287568416;
	mov.u32 	%r383, 0;
	// begin inline asm
	call(%r943,%r939,%r315,%r316,%r317,%r318,%r319,%r320,%r321,%r322,%r323,%r324,%r325,%r326,%r327,%r328,%r329,%r330,%r331,%r332,%r333,%r334,%r335,%r336,%r337,%r338,%r339,%r340,%r341,%r342,%r343,%r344),_optix_trace_typed_32,(%r383,%rd21,%f114,%f115,%f116,%f111,%f112,%f113,%f366,%f117,%f368,%r346,%r349,%r383,%r349,%r383,%r351,%r383,%r353,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383,%r383);
	// end inline asm

$L__BB3_36:
	ld.const.u32 	%r384, [params+16];
	setp.eq.s32 	%p59, %r384, 0;
	@%p59 bra 	$L__BB3_45;

	ld.const.u64 	%rd22, [params+8];
	setp.eq.s64 	%p61, %rd22, 0;
	or.pred  	%p62, %p57, %p61;
	mov.u32 	%r942, 0;
	mov.u32 	%r941, 1287568416;
	@%p62 bra 	$L__BB3_39;

	mov.f32 	%f375, 0f3727C5AC;
	mov.f32 	%f377, 0f00000000;
	mov.u32 	%r422, 255;
	mov.u32 	%r425, 1;
	mov.u32 	%r427, 4;
	mov.u32 	%r429, 1287568416;
	mov.u32 	%r459, 0;
	// begin inline asm
	call(%r942,%r941,%r391,%r392,%r393,%r394,%r395,%r396,%r397,%r398,%r399,%r400,%r401,%r402,%r403,%r404,%r405,%r406,%r407,%r408,%r409,%r410,%r411,%r412,%r413,%r414,%r415,%r416,%r417,%r418,%r419,%r420),_optix_trace_typed_32,(%r459,%rd22,%f114,%f115,%f116,%f111,%f112,%f113,%f375,%f117,%f377,%r422,%r425,%r459,%r425,%r459,%r427,%r459,%r429,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459,%r459);
	// end inline asm

$L__BB3_39:
	setp.eq.s32 	%p63, %r943, 0;
	@%p63 bra 	$L__BB3_44;

	setp.eq.s32 	%p64, %r942, 0;
	@%p64 bra 	$L__BB3_45;

	mov.b32 	%f378, %r939;
	mov.b32 	%f379, %r941;
	setp.le.ftz.f32 	%p65, %f378, %f379;
	selp.b32 	%r943, %r943, %r942, %p65;
	bra.uni 	$L__BB3_45;

$L__BB3_22:
	@%p25 bra 	$L__BB3_24;
	bra.uni 	$L__BB3_23;

$L__BB3_24:
	sub.ftz.f32 	%f591, %f585, %f7;
	sub.ftz.f32 	%f592, %f586, %f8;
	sub.ftz.f32 	%f593, %f587, %f9;
	bra.uni 	$L__BB3_25;

$L__BB3_23:
	sub.ftz.f32 	%f593, %f9, %f3;
	sub.ftz.f32 	%f592, %f8, %f2;
	sub.ftz.f32 	%f591, %f7, %f1;

$L__BB3_25:
	mul.ftz.f32 	%f250, %f592, %f592;
	fma.rn.ftz.f32 	%f251, %f591, %f591, %f250;
	fma.rn.ftz.f32 	%f252, %f593, %f593, %f251;
	mov.f32 	%f253, 0f2B8CBCCC;
	max.ftz.f32 	%f254, %f252, %f253;
	rsqrt.approx.ftz.f32 	%f255, %f254;
	mul.ftz.f32 	%f256, %f591, %f255;
	mul.ftz.f32 	%f257, %f592, %f255;
	mul.ftz.f32 	%f258, %f593, %f255;
	mul.ftz.f32 	%f259, %f60, %f257;
	fma.rn.ftz.f32 	%f260, %f59, %f256, %f259;
	fma.rn.ftz.f32 	%f77, %f61, %f258, %f260;
	mul.ftz.f32 	%f261, %f59, %f77;
	mul.ftz.f32 	%f262, %f60, %f77;
	mul.ftz.f32 	%f263, %f61, %f77;
	sub.ftz.f32 	%f78, %f256, %f261;
	sub.ftz.f32 	%f79, %f257, %f262;
	sub.ftz.f32 	%f80, %f258, %f263;
	mul.ftz.f32 	%f264, %f79, %f79;
	fma.rn.ftz.f32 	%f265, %f78, %f78, %f264;
	fma.rn.ftz.f32 	%f81, %f80, %f80, %f265;
	setp.gt.ftz.f32 	%p36, %f81, 0f2B8CBCCC;
	@%p36 bra 	$L__BB3_27;
	bra.uni 	$L__BB3_26;

$L__BB3_27:
	max.ftz.f32 	%f286, %f81, %f253;
	rsqrt.approx.ftz.f32 	%f287, %f286;
	mul.ftz.f32 	%f596, %f80, %f287;
	mul.ftz.f32 	%f595, %f79, %f287;
	mul.ftz.f32 	%f594, %f78, %f287;
	bra.uni 	$L__BB3_28;

$L__BB3_26:
	abs.ftz.f32 	%f266, %f61;
	setp.lt.ftz.f32 	%p37, %f266, 0f3F666666;
	selp.f32 	%f267, 0f3F800000, 0f00000000, %p37;
	selp.f32 	%f268, 0f00000000, 0f3F800000, %p37;
	mov.f32 	%f269, 0f00000000;
	mul.ftz.f32 	%f270, %f60, %f268;
	fma.rn.ftz.f32 	%f271, %f59, 0f00000000, %f270;
	fma.rn.ftz.f32 	%f272, %f61, %f267, %f271;
	mul.ftz.f32 	%f273, %f59, %f272;
	mul.ftz.f32 	%f274, %f60, %f272;
	mul.ftz.f32 	%f275, %f61, %f272;
	sub.ftz.f32 	%f276, %f269, %f273;
	sub.ftz.f32 	%f277, %f268, %f274;
	sub.ftz.f32 	%f278, %f267, %f275;
	mul.ftz.f32 	%f279, %f277, %f277;
	fma.rn.ftz.f32 	%f280, %f276, %f276, %f279;
	fma.rn.ftz.f32 	%f281, %f278, %f278, %f280;
	max.ftz.f32 	%f283, %f281, %f253;
	rsqrt.approx.ftz.f32 	%f284, %f283;
	mul.ftz.f32 	%f596, %f284, %f278;
	mul.ftz.f32 	%f595, %f284, %f277;
	mul.ftz.f32 	%f594, %f284, %f276;

$L__BB3_28:
	ld.const.u32 	%r930, [params+524];
	ld.const.u32 	%r929, [params+432];
	ld.const.u32 	%r928, [params+532];
	mov.f32 	%f288, 0fBF800000;
	max.ftz.f32 	%f289, %f77, %f288;
	mov.f32 	%f290, 0f3F800000;
	min.ftz.f32 	%f291, %f289, %f290;
	mul.ftz.f32 	%f292, %f291, %f291;
	sub.ftz.f32 	%f293, %f290, %f292;
	mov.f32 	%f294, 0f00000000;
	max.ftz.f32 	%f295, %f293, %f294;
	sqrt.approx.ftz.f32 	%f296, %f295;
	mul.ftz.f32 	%f297, %f60, %f596;
	mul.ftz.f32 	%f298, %f61, %f595;
	sub.ftz.f32 	%f299, %f297, %f298;
	mul.ftz.f32 	%f300, %f61, %f594;
	mul.ftz.f32 	%f301, %f59, %f596;
	sub.ftz.f32 	%f302, %f300, %f301;
	mul.ftz.f32 	%f303, %f59, %f595;
	mul.ftz.f32 	%f304, %f60, %f594;
	sub.ftz.f32 	%f305, %f303, %f304;
	mul.ftz.f32 	%f306, %f302, %f302;
	fma.rn.ftz.f32 	%f307, %f299, %f299, %f306;
	fma.rn.ftz.f32 	%f308, %f305, %f305, %f307;
	mov.f32 	%f309, 0f2B8CBCCC;
	max.ftz.f32 	%f310, %f308, %f309;
	rsqrt.approx.ftz.f32 	%f311, %f310;
	mul.ftz.f32 	%f312, %f311, %f299;
	mul.ftz.f32 	%f313, %f311, %f302;
	mul.ftz.f32 	%f314, %f311, %f305;
	mad.lo.s32 	%r287, %r928, -1640531527, 1401181199;
	xor.b32  	%r288, %r287, %r212;
	xor.b32  	%r289, %r288, %r930;
	shr.u32 	%r290, %r289, 16;
	xor.b32  	%r291, %r290, %r289;
	mul.lo.s32 	%r292, %r291, 2146121005;
	shr.u32 	%r293, %r292, 15;
	xor.b32  	%r294, %r293, %r292;
	mul.lo.s32 	%r295, %r294, -2073254261;
	shr.u32 	%r296, %r295, 16;
	and.b32  	%r297, %r295, 16777215;
	xor.b32  	%r298, %r296, %r297;
	cvt.rn.f32.u32 	%f315, %r298;
	mul.ftz.f32 	%f316, %f315, 0f33800000;
	mul.ftz.f32 	%f317, %f316, 0f40C90FDB;
	sin.approx.ftz.f32 	%f318, %f317;
	cos.approx.ftz.f32 	%f319, %f317;
	mul.ftz.f32 	%f320, %f594, %f319;
	mul.ftz.f32 	%f321, %f595, %f319;
	mul.ftz.f32 	%f322, %f596, %f319;
	fma.rn.ftz.f32 	%f323, %f312, %f318, %f320;
	fma.rn.ftz.f32 	%f324, %f313, %f318, %f321;
	fma.rn.ftz.f32 	%f325, %f314, %f318, %f322;
	mul.ftz.f32 	%f326, %f296, %f323;
	mul.ftz.f32 	%f327, %f296, %f324;
	mul.ftz.f32 	%f328, %f296, %f325;
	fma.rn.ftz.f32 	%f329, %f59, %f291, %f326;
	fma.rn.ftz.f32 	%f330, %f60, %f291, %f327;
	fma.rn.ftz.f32 	%f331, %f61, %f291, %f328;
	mul.ftz.f32 	%f332, %f330, %f330;
	fma.rn.ftz.f32 	%f333, %f329, %f329, %f332;
	fma.rn.ftz.f32 	%f334, %f331, %f331, %f333;
	max.ftz.f32 	%f335, %f334, %f309;
	rsqrt.approx.ftz.f32 	%f336, %f335;
	mul.ftz.f32 	%f91, %f336, %f329;
	mul.ftz.f32 	%f92, %f336, %f330;
	mul.ftz.f32 	%f93, %f336, %f331;
	setp.eq.s32 	%p38, %r929, 1;
	selp.f32 	%f337, %f92, %f93, %p38;
	selp.f32 	%f94, %f91, %f337, %p30;
	abs.ftz.f32 	%f338, %f94;
	setp.le.ftz.f32 	%p40, %f338, 0f358637BD;
	@%p40 bra 	$L__BB3_42;

	selp.f32 	%f339, %f57, %f58, %p38;
	selp.f32 	%f340, %f56, %f339, %p30;
	sub.ftz.f32 	%f341, %f581, %f340;
	div.approx.ftz.f32 	%f98, %f341, %f94;
	setp.leu.ftz.f32 	%p43, %f98, 0f38D1B717;
	@%p43 bra 	$L__BB3_42;

	abs.ftz.f32 	%f342, %f98;
	setp.geu.ftz.f32 	%p44, %f342, 0f7F800000;
	@%p44 bra 	$L__BB3_42;

	ld.const.u32 	%r926, [params+432];
	fma.rn.ftz.f32 	%f582, %f91, %f98, %f56;
	fma.rn.ftz.f32 	%f583, %f92, %f98, %f57;
	fma.rn.ftz.f32 	%f584, %f93, %f98, %f58;
	selp.f32 	%f102, %f583, %f582, %p30;
	setp.lt.u32 	%p46, %r926, 2;
	selp.f32 	%f103, %f584, %f583, %p46;
	setp.lt.ftz.f32 	%p47, %f102, %f226;
	setp.ge.ftz.f32 	%p48, %f102, %f227;
	or.pred  	%p49, %p48, %p47;
	setp.lt.ftz.f32 	%p50, %f103, %f228;
	or.pred  	%p51, %p49, %p50;
	setp.ge.ftz.f32 	%p52, %f103, %f229;
	or.pred  	%p53, %p52, %p51;
	@%p53 bra 	$L__BB3_42;

	cvt.rn.f32.s32 	%f579, %r215;
	cvt.rn.f32.s32 	%f578, %r214;
	sub.ftz.f32 	%f577, %f229, %f228;
	sub.ftz.f32 	%f576, %f227, %f226;
	sub.ftz.f32 	%f343, %f102, %f226;
	mov.f32 	%f344, 0f358637BD;
	max.ftz.f32 	%f345, %f576, %f344;
	div.approx.ftz.f32 	%f346, %f343, %f345;
	max.ftz.f32 	%f347, %f577, %f344;
	sub.ftz.f32 	%f348, %f103, %f228;
	div.approx.ftz.f32 	%f349, %f348, %f347;
	mul.ftz.f32 	%f350, %f346, %f578;
	cvt.rzi.ftz.s32.f32 	%r299, %f350;
	max.s32 	%r300, %r299, 0;
	add.s32 	%r301, %r214, -1;
	min.s32 	%r302, %r300, %r301;
	mul.ftz.f32 	%f351, %f349, %f579;
	cvt.rzi.ftz.s32.f32 	%r303, %f351;
	max.s32 	%r304, %r303, 0;
	add.s32 	%r305, %r215, -1;
	min.s32 	%r306, %r304, %r305;
	mad.lo.s32 	%r938, %r306, %r214, %r302;
	bra.uni 	$L__BB3_33;

$L__BB3_42:
	ld.const.u32 	%r307, [params+560];
	setp.eq.s32 	%p54, %r307, 0;
	@%p54 bra 	$L__BB3_123;

	ld.const.u64 	%rd112, [params+664];
	cvta.to.global.u64 	%rd113, %rd112;
	atom.global.add.u32 	%r308, [%rd113], 1;
	bra.uni 	$L__BB3_123;

$L__BB3_44:
	mov.u32 	%r943, %r942;

$L__BB3_45:
	setp.eq.s32 	%p66, %r943, 0;
	selp.u16 	%rs23, 1, 0, %p66;

$L__BB3_46:
	mov.f32 	%f580, 0f00000000;
	sub.ftz.f32 	%f118, %f7, %f1;
	sub.ftz.f32 	%f119, %f8, %f2;
	mul.ftz.f32 	%f380, %f119, %f119;
	fma.rn.ftz.f32 	%f381, %f118, %f118, %f380;
	sub.ftz.f32 	%f120, %f9, %f3;
	fma.rn.ftz.f32 	%f382, %f120, %f120, %f381;
	max.ftz.f32 	%f384, %f382, %f580;
	sqrt.approx.ftz.f32 	%f121, %f384;
	setp.le.ftz.f32 	%p67, %f121, 0f3727C5AC;
	@%p67 bra 	$L__BB3_57;

	rcp.approx.ftz.f32 	%f385, %f121;
	mul.ftz.f32 	%f122, %f118, %f385;
	mul.ftz.f32 	%f123, %f119, %f385;
	mul.ftz.f32 	%f124, %f120, %f385;
	fma.rn.ftz.f32 	%f125, %f122, 0f38D1B717, %f1;
	fma.rn.ftz.f32 	%f126, %f123, 0f38D1B717, %f2;
	fma.rn.ftz.f32 	%f127, %f124, 0f38D1B717, %f3;
	add.ftz.f32 	%f386, %f121, 0fB951B717;
	mov.f32 	%f387, 0f00000000;
	max.ftz.f32 	%f128, %f386, %f387;
	ld.const.u64 	%rd23, [params];
	setp.eq.s64 	%p68, %rd23, 0;
	setp.le.ftz.f32 	%p69, %f128, 0f3727C5AC;
	or.pred  	%p70, %p69, %p68;
	mov.u32 	%r949, 0;
	mov.u32 	%r946, 1287568416;
	@%p70 bra 	$L__BB3_49;

	mov.f32 	%f394, 0f3727C5AC;
	mov.u32 	%r497, 255;
	mov.u32 	%r500, 1;
	mov.u32 	%r502, 4;
	mov.u32 	%r504, 1287568416;
	mov.u32 	%r534, 0;
	// begin inline asm
	call(%r949,%r946,%r466,%r467,%r468,%r469,%r470,%r471,%r472,%r473,%r474,%r475,%r476,%r477,%r478,%r479,%r480,%r481,%r482,%r483,%r484,%r485,%r486,%r487,%r488,%r489,%r490,%r491,%r492,%r493,%r494,%r495),_optix_trace_typed_32,(%r534,%rd23,%f125,%f126,%f127,%f122,%f123,%f124,%f394,%f128,%f387,%r497,%r500,%r534,%r500,%r534,%r502,%r534,%r504,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534,%r534);
	// end inline asm

$L__BB3_49:
	ld.const.u32 	%r535, [params+16];
	setp.eq.s32 	%p71, %r535, 0;
	@%p71 bra 	$L__BB3_56;

	ld.const.u64 	%rd24, [params+8];
	setp.eq.s64 	%p73, %rd24, 0;
	or.pred  	%p74, %p69, %p73;
	mov.u32 	%r947, 0;
	mov.u32 	%r948, 1287568416;
	@%p74 bra 	$L__BB3_52;

	mov.f32 	%f403, 0f3727C5AC;
	mov.f32 	%f405, 0f00000000;
	mov.u32 	%r573, 255;
	mov.u32 	%r576, )PTX_CHUNK"
R"PTX_CHUNK(1;
	mov.u32 	%r578, 4;
	mov.u32 	%r580, 1287568416;
	mov.u32 	%r610, 0;
	// begin inline asm
	call(%r947,%r948,%r542,%r543,%r544,%r545,%r546,%r547,%r548,%r549,%r550,%r551,%r552,%r553,%r554,%r555,%r556,%r557,%r558,%r559,%r560,%r561,%r562,%r563,%r564,%r565,%r566,%r567,%r568,%r569,%r570,%r571),_optix_trace_typed_32,(%r610,%rd24,%f125,%f126,%f127,%f122,%f123,%f124,%f403,%f128,%f405,%r573,%r576,%r610,%r576,%r610,%r578,%r610,%r580,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610,%r610);
	// end inline asm

$L__BB3_52:
	setp.eq.s32 	%p75, %r949, 0;
	@%p75 bra 	$L__BB3_55;

	setp.eq.s32 	%p76, %r947, 0;
	@%p76 bra 	$L__BB3_56;

	mov.b32 	%f406, %r946;
	mov.b32 	%f407, %r948;
	setp.le.ftz.f32 	%p77, %f406, %f407;
	selp.b32 	%r949, %r949, %r947, %p77;
	bra.uni 	$L__BB3_56;

$L__BB3_55:
	mov.u32 	%r949, %r947;

$L__BB3_56:
	setp.eq.s32 	%p78, %r949, 0;
	selp.u16 	%rs24, 1, 0, %p78;

$L__BB3_57:
	mov.u16 	%rs26, 1;
	mov.u16 	%rs25, %rs26;
	@%p20 bra 	$L__BB3_69;

	sub.ftz.f32 	%f129, %f585, %f7;
	sub.ftz.f32 	%f130, %f586, %f8;
	sub.ftz.f32 	%f131, %f587, %f9;
	mul.ftz.f32 	%f408, %f130, %f130;
	fma.rn.ftz.f32 	%f409, %f129, %f129, %f408;
	fma.rn.ftz.f32 	%f410, %f131, %f131, %f409;
	mov.f32 	%f411, 0f00000000;
	max.ftz.f32 	%f412, %f410, %f411;
	sqrt.approx.ftz.f32 	%f132, %f412;
	setp.le.ftz.f32 	%p80, %f132, 0f3727C5AC;
	@%p80 bra 	$L__BB3_69;

	rcp.approx.ftz.f32 	%f413, %f132;
	mul.ftz.f32 	%f133, %f129, %f413;
	mul.ftz.f32 	%f134, %f130, %f413;
	mul.ftz.f32 	%f135, %f131, %f413;
	fma.rn.ftz.f32 	%f136, %f133, 0f38D1B717, %f7;
	fma.rn.ftz.f32 	%f137, %f134, 0f38D1B717, %f8;
	fma.rn.ftz.f32 	%f138, %f135, 0f38D1B717, %f9;
	add.ftz.f32 	%f414, %f132, 0fB951B717;
	max.ftz.f32 	%f139, %f414, %f411;
	ld.const.u64 	%rd25, [params];
	setp.eq.s64 	%p81, %rd25, 0;
	setp.le.ftz.f32 	%p82, %f139, 0f3727C5AC;
	or.pred  	%p83, %p82, %p81;
	mov.u32 	%r955, 0;
	mov.u32 	%r952, 1287568416;
	@%p83 bra 	$L__BB3_61;

	mov.f32 	%f422, 0f3727C5AC;
	mov.f32 	%f424, 0f00000000;
	mov.u32 	%r648, 255;
	mov.u32 	%r651, 1;
	mov.u32 	%r653, 4;
	mov.u32 	%r655, 1287568416;
	mov.u32 	%r685, 0;
	// begin inline asm
	call(%r955,%r952,%r617,%r618,%r619,%r620,%r621,%r622,%r623,%r624,%r625,%r626,%r627,%r628,%r629,%r630,%r631,%r632,%r633,%r634,%r635,%r636,%r637,%r638,%r639,%r640,%r641,%r642,%r643,%r644,%r645,%r646),_optix_trace_typed_32,(%r685,%rd25,%f136,%f137,%f138,%f133,%f134,%f135,%f422,%f139,%f424,%r648,%r651,%r685,%r651,%r685,%r653,%r685,%r655,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685,%r685);
	// end inline asm

$L__BB3_61:
	ld.const.u32 	%r686, [params+16];
	setp.eq.s32 	%p84, %r686, 0;
	@%p84 bra 	$L__BB3_68;

	ld.const.u64 	%rd26, [params+8];
	setp.eq.s64 	%p86, %rd26, 0;
	or.pred  	%p87, %p82, %p86;
	mov.u32 	%r953, 0;
	mov.u32 	%r954, 1287568416;
	@%p87 bra 	$L__BB3_64;

	mov.f32 	%f431, 0f3727C5AC;
	mov.f32 	%f433, 0f00000000;
	mov.u32 	%r724, 255;
	mov.u32 	%r727, 1;
	mov.u32 	%r729, 4;
	mov.u32 	%r731, 1287568416;
	mov.u32 	%r761, 0;
	// begin inline asm
	call(%r953,%r954,%r693,%r694,%r695,%r696,%r697,%r698,%r699,%r700,%r701,%r702,%r703,%r704,%r705,%r706,%r707,%r708,%r709,%r710,%r711,%r712,%r713,%r714,%r715,%r716,%r717,%r718,%r719,%r720,%r721,%r722),_optix_trace_typed_32,(%r761,%rd26,%f136,%f137,%f138,%f133,%f134,%f135,%f431,%f139,%f433,%r724,%r727,%r761,%r727,%r761,%r729,%r761,%r731,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761,%r761);
	// end inline asm

$L__BB3_64:
	setp.eq.s32 	%p88, %r955, 0;
	@%p88 bra 	$L__BB3_67;

	setp.eq.s32 	%p89, %r953, 0;
	@%p89 bra 	$L__BB3_68;

	mov.b32 	%f434, %r952;
	mov.b32 	%f435, %r954;
	setp.le.ftz.f32 	%p90, %f434, %f435;
	selp.b32 	%r955, %r955, %r953, %p90;
	bra.uni 	$L__BB3_68;

$L__BB3_67:
	mov.u32 	%r955, %r953;

$L__BB3_68:
	setp.eq.s32 	%p91, %r955, 0;
	selp.u16 	%rs25, 1, 0, %p91;

$L__BB3_69:
	sub.ftz.f32 	%f141, %f582, %f56;
	sub.ftz.f32 	%f143, %f583, %f57;
	sub.ftz.f32 	%f145, %f584, %f58;
	mul.ftz.f32 	%f436, %f141, %f141;
	fma.rn.ftz.f32 	%f437, %f143, %f143, %f436;
	fma.rn.ftz.f32 	%f438, %f145, %f145, %f437;
	mov.f32 	%f439, 0f00000000;
	max.ftz.f32 	%f440, %f438, %f439;
	sqrt.approx.ftz.f32 	%f146, %f440;
	setp.le.ftz.f32 	%p92, %f146, 0f3727C5AC;
	@%p92 bra 	$L__BB3_80;

	rcp.approx.ftz.f32 	%f441, %f146;
	mul.ftz.f32 	%f147, %f141, %f441;
	mul.ftz.f32 	%f148, %f143, %f441;
	mul.ftz.f32 	%f149, %f145, %f441;
	fma.rn.ftz.f32 	%f150, %f147, 0f38D1B717, %f56;
	fma.rn.ftz.f32 	%f151, %f148, 0f38D1B717, %f57;
	fma.rn.ftz.f32 	%f152, %f149, 0f38D1B717, %f58;
	add.ftz.f32 	%f442, %f146, 0fB951B717;
	max.ftz.f32 	%f153, %f442, %f439;
	ld.const.u64 	%rd27, [params];
	setp.eq.s64 	%p93, %rd27, 0;
	setp.le.ftz.f32 	%p94, %f153, 0f3727C5AC;
	or.pred  	%p95, %p94, %p93;
	mov.u32 	%r961, 0;
	mov.u32 	%r958, 1287568416;
	@%p95 bra 	$L__BB3_72;

	mov.f32 	%f450, 0f3727C5AC;
	mov.f32 	%f452, 0f00000000;
	mov.u32 	%r799, 255;
	mov.u32 	%r802, 1;
	mov.u32 	%r804, 4;
	mov.u32 	%r806, 1287568416;
	mov.u32 	%r836, 0;
	// begin inline asm
	call(%r961,%r958,%r768,%r769,%r770,%r771,%r772,%r773,%r774,%r775,%r776,%r777,%r778,%r779,%r780,%r781,%r782,%r783,%r784,%r785,%r786,%r787,%r788,%r789,%r790,%r791,%r792,%r793,%r794,%r795,%r796,%r797),_optix_trace_typed_32,(%r836,%rd27,%f150,%f151,%f152,%f147,%f148,%f149,%f450,%f153,%f452,%r799,%r802,%r836,%r802,%r836,%r804,%r836,%r806,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836,%r836);
	// end inline asm

$L__BB3_72:
	ld.const.u32 	%r837, [params+16];
	setp.eq.s32 	%p96, %r837, 0;
	@%p96 bra 	$L__BB3_79;

	ld.const.u64 	%rd28, [params+8];
	setp.eq.s64 	%p98, %rd28, 0;
	or.pred  	%p99, %p94, %p98;
	mov.u32 	%r959, 0;
	mov.u32 	%r960, 1287568416;
	@%p99 bra 	$L__BB3_75;

	mov.f32 	%f459, 0f3727C5AC;
	mov.f32 	%f461, 0f00000000;
	mov.u32 	%r875, 255;
	mov.u32 	%r878, 1;
	mov.u32 	%r880, 4;
	mov.u32 	%r882, 1287568416;
	mov.u32 	%r912, 0;
	// begin inline asm
	call(%r959,%r960,%r844,%r845,%r846,%r847,%r848,%r849,%r850,%r851,%r852,%r853,%r854,%r855,%r856,%r857,%r858,%r859,%r860,%r861,%r862,%r863,%r864,%r865,%r866,%r867,%r868,%r869,%r870,%r871,%r872,%r873),_optix_trace_typed_32,(%r912,%rd28,%f150,%f151,%f152,%f147,%f148,%f149,%f459,%f153,%f461,%r875,%r878,%r912,%r878,%r912,%r880,%r912,%r882,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912,%r912);
	// end inline asm

$L__BB3_75:
	setp.eq.s32 	%p100, %r961, 0;
	@%p100 bra 	$L__BB3_78;

	setp.eq.s32 	%p101, %r959, 0;
	@%p101 bra 	$L__BB3_79;

	mov.b32 	%f462, %r958;
	mov.b32 	%f463, %r960;
	setp.le.ftz.f32 	%p102, %f462, %f463;
	selp.b32 	%r961, %r961, %r959, %p102;
	bra.uni 	$L__BB3_79;

$L__BB3_78:
	mov.u32 	%r961, %r959;

$L__BB3_79:
	setp.eq.s32 	%p103, %r961, 0;
	selp.u16 	%rs26, 1, 0, %p103;

$L__BB3_80:
	setp.eq.s16 	%p104, %rs26, 0;
	setp.eq.s16 	%p105, %rs23, 0;
	or.pred  	%p106, %p105, %p104;
	@%p106 bra 	$L__BB3_119;
	bra.uni 	$L__BB3_81;

$L__BB3_119:
	ld.const.u32 	%r922, [params+560];
	setp.eq.s32 	%p152, %r922, 0;
	@%p152 bra 	$L__BB3_123;

	ld.const.u64 	%rd190, [params+648];
	cvta.to.global.u64 	%rd191, %rd190;
	atom.global.add.u32 	%r923, [%rd191], 1;
	bra.uni 	$L__BB3_123;

$L__BB3_81:
	setp.eq.s16 	%p107, %rs24, 0;
	setp.eq.s16 	%p108, %rs25, 0;
	or.pred  	%p109, %p107, %p108;
	mov.f32 	%f600, 0f3F800000;
	@%p109 bra 	$L__BB3_117;
	bra.uni 	$L__BB3_82;

$L__BB3_117:
	ld.const.u32 	%r920, [params+560];
	setp.eq.s32 	%p151, %r920, 0;
	@%p151 bra 	$L__BB3_123;

	ld.const.u64 	%rd188, [params+656];
	cvta.to.global.u64 	%rd189, %rd188;
	atom.global.add.u32 	%r921, [%rd189], 1;
	bra.uni 	$L__BB3_123;

$L__BB3_82:
	cvt.s64.s32 	%rd198, %r10;
	shl.b64 	%rd197, %rd198, 2;
	ld.const.u64 	%rd196, [params+104];
	cvta.to.global.u64 	%rd195, %rd196;
	add.s64 	%rd194, %rd195, %rd197;
	ld.const.u64 	%rd122, [params+208];
	cvta.to.global.u64 	%rd123, %rd122;
	add.s64 	%rd125, %rd123, %rd197;
	ld.global.f32 	%f154, [%rd125];
	ld.const.u64 	%rd126, [params+160];
	cvta.to.global.u64 	%rd127, %rd126;
	add.s64 	%rd128, %rd127, %rd197;
	ld.global.u32 	%r199, [%rd128];
	ld.const.u64 	%rd129, [params+168];
	cvta.to.global.u64 	%rd130, %rd129;
	add.s64 	%rd131, %rd130, %rd197;
	ld.global.u32 	%r200, [%rd131];
	ld.const.u64 	%rd132, [params+176];
	cvta.to.global.u64 	%rd133, %rd132;
	add.s64 	%rd134, %rd133, %rd197;
	mov.f32 	%f465, 0f358637BD;
	max.ftz.f32 	%f155, %f121, %f465;
	ld.global.f32 	%f156, [%rd194];
	ld.global.f32 	%f157, [%rd6];
	ld.global.f32 	%f158, [%rd134];
	ld.const.u64 	%rd29, [params+496];
	setp.eq.s64 	%p110, %rd29, 0;
	ld.const.u32 	%r201, [params+512];
	setp.lt.s32 	%p111, %r201, 1;
	or.pred  	%p1, %p110, %p111;
	@%p1 bra 	$L__BB3_90;

	setp.lt.s32 	%p112, %r199, 0;
	setp.le.s32 	%p113, %r201, %r199;
	or.pred  	%p114, %p112, %p113;
	mov.u32 	%r963, %r200;
	@%p114 bra 	$L__BB3_86;

	ld.const.u64 	%rd30, [params+504];
	setp.eq.s64 	%p115, %rd30, 0;
	mov.u32 	%r963, %r199;
	@%p115 bra 	$L__BB3_86;

	cvta.to.global.u64 	%rd135, %rd30;
	cvt.s64.s32 	%rd136, %r199;
	add.s64 	%rd137, %rd135, %rd136;
	ld.global.u8 	%rs17, [%rd137];
	setp.eq.s16 	%p116, %rs17, 0;
	selp.b32 	%r963, %r200, %r199, %p116;

$L__BB3_86:
	setp.ge.s32 	%p117, %r963, %r201;
	setp.lt.s32 	%p118, %r963, 0;
	or.pred  	%p119, %p118, %p117;
	@%p119 bra 	$L__BB3_90;

	ld.const.u64 	%rd31, [params+504];
	setp.eq.s64 	%p120, %rd31, 0;
	@%p120 bra 	$L__BB3_89;

	cvta.to.global.u64 	%rd138, %rd31;
	cvt.s64.s32 	%rd139, %r963;
	add.s64 	%rd140, %rd138, %rd139;
	ld.global.u8 	%rs18, [%rd140];
	setp.eq.s16 	%p121, %rs18, 0;
	@%p121 bra 	$L__BB3_90;

$L__BB3_89:
	cvta.to.global.u64 	%rd141, %rd29;
	mul.wide.s32 	%rd142, %r963, 4;
	add.s64 	%rd143, %rd141, %rd142;
	ld.global.f32 	%f468, [%rd143];
	mov.f32 	%f469, 0f00000000;
	max.ftz.f32 	%f600, %f468, %f469;

$L__BB3_90:
	cvt.s64.s32 	%rd206, %r12;
	shl.b64 	%rd205, %rd206, 2;
	ld.const.u64 	%rd204, [params+344];
	cvta.to.global.u64 	%rd203, %rd204;
	add.s64 	%rd202, %rd203, %rd205;
	ld.const.u64 	%rd201, [params+352];
	cvta.to.global.u64 	%rd200, %rd201;
	add.s64 	%rd199, %rd200, %rd205;
	max.ftz.f32 	%f472, %f110, %f465;
	mul.ftz.f32 	%f473, %f154, %f600;
	sub.ftz.f32 	%f474, %f156, %f157;
	mov.f32 	%f475, 0f00000000;
	max.ftz.f32 	%f476, %f474, %f475;
	mul.ftz.f32 	%f477, %f476, %f473;
	mov.f32 	%f478, 0f3F490FDB;
	max.ftz.f32 	%f479, %f158, %f478;
	mov.f32 	%f480, 0f40C90FDB;
	div.approx.ftz.f32 	%f481, %f479, %f480;
	mov.f32 	%f482, 0f40000000;
	min.ftz.f32 	%f483, %f481, %f482;
	mul.ftz.f32 	%f484, %f483, %f477;
	mul.ftz.f32 	%f485, %f472, %f472;
	mul.ftz.f32 	%f486, %f485, %f155;
	mul.ftz.f32 	%f487, %f155, %f486;
	div.approx.ftz.f32 	%f161, %f484, %f487;
	selp.f32 	%f488, %f587, %f584, %p25;
	selp.f32 	%f489, %f586, %f583, %p25;
	selp.f32 	%f490, %f585, %f582, %p25;
	ld.const.u64 	%rd144, [params+408];
	cvta.to.global.u64 	%rd32, %rd144;
	add.s64 	%rd146, %rd32, %rd205;
	ld.global.u32 	%r204, [%rd146];
	ld.const.u64 	%rd147, [params+416];
	cvta.to.global.u64 	%rd33, %rd147;
	add.s64 	%rd148, %rd33, %rd205;
	ld.global.u32 	%r205, [%rd148];
	ld.const.u64 	%rd149, [params+424];
	cvta.to.global.u64 	%rd34, %rd149;
	add.s64 	%rd150, %rd34, %rd205;
	sub.ftz.f32 	%f491, %f490, %f7;
	sub.ftz.f32 	%f492, %f489, %f8;
	sub.ftz.f32 	%f493, %f488, %f9;
	mul.ftz.f32 	%f494, %f492, %f492;
	fma.rn.ftz.f32 	%f495, %f491, %f491, %f494;
	fma.rn.ftz.f32 	%f162, %f493, %f493, %f495;
	ld.global.f32 	%f163, [%rd199];
	ld.global.f32 	%f164, [%rd202];
	ld.global.f32 	%f165, [%rd150];
	mov.f32 	%f602, 0f3F800000;
	mov.f32 	%f601, %f602;
	@%p1 bra 	$L__BB3_98;

	setp.lt.s32 	%p123, %r204, 0;
	setp.le.s32 	%p124, %r201, %r204;
	or.pred  	%p125, %p123, %p124;
	mov.u32 	%r964, %r205;
	@%p125 bra 	$L__BB3_94;

	ld.const.u64 	%rd35, [params+504];
	setp.eq.s64 	%p126, %rd35, 0;
	mov.u32 	%r964, %r204;
	@%p126 bra 	$L__BB3_94;

	cvta.to.global.u64 	%rd151, %rd35;
	cvt.s64.s32 	%rd152, %r204;
	add.s64 	%rd153, %rd151, %rd152;
	ld.global.u8 	%rs19, [%rd153];
	setp.eq.s16 	%p127, %rs19, 0;
	selp.b32 	%r964, %r205, %r204, %p127;

$L__BB3_94:
	setp.ge.s32 	%p128, %r964, %r201;
	setp.lt.s32 	%p129, %r964, 0;
	or.pred  	%p130, %p129, %p128;
	mov.f32 	%f601, %f602;
	@%p130 bra 	$L__BB3_98;

	ld.const.u64 	%rd36, [params+504];
	setp.eq.s64 	%p131, %rd36, 0;
	@%p131 bra 	$L__BB3_97;

	cvta.to.global.u64 	%rd154, %rd36;
	cvt.s64.s32 	%rd155, %r964;
	add.s64 	%rd156, %rd154, %rd155;
	ld.global.u8 	%rs20, [%rd156];
	setp.eq.s16 	%p132, %rs20, 0;
	mov.f32 	%f601, %f602;
	@%p132 bra 	$L__BB3_98;

$L__BB3_97:
	cvta.to.global.u64 	%rd157, %rd29;
	mul.wide.s32 	%rd158, %r964, 4;
	add.s64 	%rd159, %rd157, %rd158;
	ld.global.f32 	%f498, [%rd159];
	mov.f32 	%f499, 0f00000000;
	max.ftz.f32 	%f601, %f498, %f499;

$L__BB3_98:
	max.ftz.f32 	%f501, %f162, %f475;
	sqrt.approx.ftz.f32 	%f502, %f501;
	mov.f32 	%f503, 0f358637BD;
	max.ftz.f32 	%f504, %f502, %f503;
	sub.ftz.f32 	%f505, %f163, %f164;
	max.ftz.f32 	%f506, %f505, %f475;
	mul.ftz.f32 	%f507, %f506, %f601;
	max.ftz.f32 	%f509, %f165, %f478;
	div.approx.ftz.f32 	%f511, %f509, %f480;
	min.ftz.f32 	%f513, %f511, %f482;
	mul.ftz.f32 	%f514, %f513, %f507;
	mul.ftz.f32 	%f515, %f155, %f155;
	mul.ftz.f32 	%f516, %f515, %f504;
	mul.ftz.f32 	%f517, %f504, %f516;
	div.approx.ftz.f32 	%f518, %f514, %f517;
	mul.ftz.f32 	%f603, %f161, %f518;
	@%p20 bra 	$L__BB3_108;

	mul.wide.s32 	%rd214, %r936, 4;
	cvt.s64.s32 	%rd213, %r936;
	ld.const.u64 	%rd212, [params+344];
	cvta.to.global.u64 	%rd211, %rd212;
	add.s64 	%rd210, %rd211, %rd214;
	ld.const.u64 	%rd209, [params+352];
	cvta.to.global.u64 	%rd208, %rd209;
	add.s64 	%rd207, %rd208, %rd214;
	shl.b64 	%rd160, %rd213, 2;
	add.s64 	%rd161, %rd32, %rd160;
	ld.global.u32 	%r208, [%rd161];
	add.s64 	%rd162, %rd33, %rd160;
	ld.global.u32 	%r209, [%rd162];
	sub.ftz.f32 	%f520, %f585, %f7;
	sub.ftz.f32 	%f521, %f586, %f8;
	sub.ftz.f32 	%f522, %f587, %f9;
	mul.ftz.f32 	%f523, %f521, %f521;
	fma.rn.ftz.f32 	%f524, %f520, %f520, %f523;
	fma.rn.ftz.f32 	%f169, %f522, %f522, %f524;
	sub.ftz.f32 	%f525, %f582, %f585;
	sub.ftz.f32 	%f526, %f583, %f586;
	sub.ftz.f32 	%f527, %f584, %f587;
	mul.ftz.f32 	%f528, %f525, %f525;
	fma.rn.ftz.f32 	%f529, %f526, %f526, %f528;
	fma.rn.ftz.f32 	%f170, %f527, %f527, %f529;
	ld.global.f32 	%f171, [%rd207];
	ld.global.f32 	%f172, [%rd210];
	add.s64 	%rd163, %rd34, %rd160;
	ld.global.f32 	%f173, [%rd163];
	@%p1 bra 	$L__BB3_107;

	setp.lt.s32 	%p134, %r208, 0;
	setp.le.s32 	%p135, %r201, %r208;
	or.pred  	%p136, %p134, %p135;
	mov.u32 	%r965, %r209;
	@%p136 bra 	$L__BB3_103;

	ld.const.u64 	%rd37, [params+504];
	setp.eq.s64 	%p137, %rd37, 0;
	mov.u32 	%r965, %r208;
	@%p137 bra 	$L__BB3_103;

	cvta.to.global.u64 	%rd164, %rd37;
	cvt.s64.s32 	%rd165, %r208;
	add.s64 	%rd166, %rd164, %rd165;
	ld.global.u8 	%rs21, [%rd166];
	setp.eq.s16 	%p138, %rs21, 0;
	selp.b32 	%r965, %r209, %r208, %p138;

$L__BB3_103:
	setp.ge.s32 	%p139, %r965, %r201;
	setp.lt.s32 	%p140, %r965, 0;
	or.pred  	%p141, %p140, %p139;
	@%p141 bra 	$L__BB3_107;

	ld.const.u64 	%rd38, [params+504];
	setp.eq.s64 	%p142, %rd38, 0;
	@%p142 bra 	$L__BB3_106;

	cvta.to.global.u64 	%rd167, %rd38;
	cvt.s64.s32 	%rd168, %r965;
	add.s64 	%rd169, %rd167, %rd168;
	ld.global.u8 	%rs22, [%rd169];
	setp.eq.s16 	%p143, %rs22, 0;
	@%p143 bra 	$L__BB3_107;

$L__BB3_106:
	cvta.to.global.u64 	%rd170, %rd29;
	mul.wide.s32 	%rd171, %r965, 4;
	add.s64 	%rd172, %rd170, %rd171;
	ld.global.f32 	%f532, [%rd172];
	mov.f32 	%f533, 0f00000000;
	max.ftz.f32 	%f602, %f532, %f533;

$L__BB3_107:
	mov.f32 	%f534, 0f00000000;
	max.ftz.f32 	%f535, %f169, %f534;
	sqrt.approx.ftz.f3)PTX_CHUNK"
R"PTX_CHUNK(2 	%f536, %f535;
	mov.f32 	%f537, 0f358637BD;
	max.ftz.f32 	%f538, %f536, %f537;
	max.ftz.f32 	%f539, %f170, %f534;
	sqrt.approx.ftz.f32 	%f540, %f539;
	max.ftz.f32 	%f541, %f540, %f537;
	sub.ftz.f32 	%f542, %f171, %f172;
	max.ftz.f32 	%f543, %f542, %f534;
	mul.ftz.f32 	%f544, %f543, %f602;
	mov.f32 	%f545, 0f3F490FDB;
	max.ftz.f32 	%f546, %f173, %f545;
	mov.f32 	%f547, 0f40C90FDB;
	div.approx.ftz.f32 	%f548, %f546, %f547;
	mov.f32 	%f549, 0f40000000;
	min.ftz.f32 	%f550, %f548, %f549;
	mul.ftz.f32 	%f551, %f550, %f544;
	mul.ftz.f32 	%f552, %f538, %f538;
	mul.ftz.f32 	%f553, %f552, %f541;
	mul.ftz.f32 	%f554, %f541, %f553;
	div.approx.ftz.f32 	%f555, %f551, %f554;
	mul.ftz.f32 	%f603, %f603, %f555;

$L__BB3_108:
	ld.const.u32 	%r935, [params+544];
	and.b32  	%r934, %r935, 1;
	neg.s32 	%r933, %r934;
	and.b32  	%r932, %r933, %r220;
	ld.const.f32 	%f556, [params+516];
	mul.ftz.f32 	%f557, %f556, 0f3DA2F983;
	mul.ftz.f32 	%f558, %f557, %f557;
	mul.ftz.f32 	%f559, %f558, %f558;
	selp.f32 	%f560, %f559, %f558, %p25;
	selp.b32 	%r913, %r932, %r9, %p34;
	cvt.rn.f32.s32 	%f561, %r913;
	mov.f32 	%f562, 0f3F800000;
	max.ftz.f32 	%f563, %f561, %f562;
	rcp.approx.ftz.f32 	%f564, %f563;
	mul.ftz.f32 	%f565, %f603, %f560;
	ld.const.f32 	%f566, [params+464];
	mul.ftz.f32 	%f567, %f566, %f565;
	mul.ftz.f32 	%f178, %f564, %f567;
	setp.leu.ftz.f32 	%p146, %f178, 0f00000000;
	@%p146 bra 	$L__BB3_115;

	abs.ftz.f32 	%f568, %f178;
	setp.geu.ftz.f32 	%p147, %f568, 0f7F800000;
	@%p147 bra 	$L__BB3_115;
	bra.uni 	$L__BB3_110;

$L__BB3_115:
	ld.const.u32 	%r918, [params+560];
	setp.eq.s32 	%p150, %r918, 0;
	@%p150 bra 	$L__BB3_123;

	ld.const.u64 	%rd186, [params+664];
	cvta.to.global.u64 	%rd187, %rd186;
	atom.global.add.u32 	%r919, [%rd187], 1;
	bra.uni 	$L__BB3_123;

$L__BB3_110:
	ld.const.u64 	%rd173, [params+568];
	cvta.to.global.u64 	%rd174, %rd173;
	mul.wide.s32 	%rd175, %r938, 4;
	add.s64 	%rd176, %rd174, %rd175;
	atom.global.add.f32 	%f569, [%rd176], %f178;
	ld.const.u64 	%rd177, [params+576];
	cvta.to.global.u64 	%rd178, %rd177;
	add.s64 	%rd179, %rd178, %rd175;
	mov.f32 	%f570, 0f00000000;
	max.ftz.f32 	%f571, %f178, %f570;
	sqrt.approx.ftz.f32 	%f572, %f571;
	atom.global.add.f32 	%f573, [%rd179], %f572;
	@%p34 bra 	$L__BB3_112;
	bra.uni 	$L__BB3_111;

$L__BB3_112:
	ld.const.u64 	%rd182, [params+624];
	cvta.to.global.u64 	%rd183, %rd182;
	atom.global.add.u32 	%r915, [%rd183], 1;
	bra.uni 	$L__BB3_113;

$L__BB3_111:
	ld.const.u64 	%rd180, [params+632];
	cvta.to.global.u64 	%rd181, %rd180;
	atom.global.add.u32 	%r914, [%rd181], 1;

$L__BB3_113:
	ld.const.u32 	%r916, [params+556];
	setp.eq.s32 	%p149, %r916, 0;
	@%p149 bra 	$L__BB3_123;

	ld.const.u64 	%rd184, [params+672];
	cvta.to.global.u64 	%rd185, %rd184;
	atom.global.add.u32 	%r917, [%rd185], 1;
	bra.uni 	$L__BB3_123;

}

)PTX_CHUNK"
;
static const size_t diffraction_accumulation_ptx_size = 66811;
