from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Callable

import torch

@dataclass(frozen=True)
class MultiDeviceOptions:
    weights: Sequence[float] | None = ...
    warm_up: bool = ...
    chunk_rays: int | None = ...
    offload: Callable[[int, Any], None] | None = ...
    tape_memory_budget_bytes: int | None = ...
    pipeline: bool = ...
    pipeline_chunks_per_device: int = ...
    min_rays_per_device: int = ...

@dataclass
class ChunkPlan:
    operation: str
    total_rows: int
    chunk_rays: int
    source: str
    row_bytes: int
    budget_bytes: int | None = ...
    chunk_count: int = ...
    measured_row_bytes: float | None = ...

@dataclass
class DeviceCalibration:
    operation: str
    rows: int
    devices: tuple[int, ...] = ...
    seconds: tuple[float, ...] = ...
    weights: tuple[float, ...] = ...
    samples: tuple[tuple[float, ...], ...] = ...
    throughput_weights: tuple[float, ...] = ...
    candidates: tuple[tuple[float, ...], ...] = ...
    candidate_seconds: tuple[float, ...] = ...
    @property
    def rows_per_second(self) -> tuple[float, ...]: ...
    def describe(self) -> str: ...

def calibrate_chunk_size(
    operation: str,
    total_rows: int,
    *,
    row_bytes: int,
    chunk_rays: int | None = ...,
    budget_bytes: int | None = ...,
) -> ChunkPlan: ...
def plan(
    devices: Sequence[int | str | torch.device] | None,
    options: MultiDeviceOptions | None,
    *,
    trace_backend: str,
    edge_bvh_backend: str,
) -> Any: ...
