import torch

from .types import DfrAccum, DfrCoherentAccum, DfrGrid, DfrMaterial, DfrPaths, DfrStates, Intersection, NearestEdgesTopK, NearestPointEdge, NearestRayEdge, ReflEpcField, ReflectionChain

def intersect(scene_handle: int, vertices: torch.Tensor, ray_o: torch.Tensor, ray_d: torch.Tensor, ray_tmax: torch.Tensor, active: torch.Tensor | None, flags: int = ..., mesh_vertices: tuple[torch.Tensor, ...] | None = ...) -> Intersection: ...
def nearest_edge(scene_handle: int, vertices: torch.Tensor, point: torch.Tensor, mesh_vertices: tuple[torch.Tensor, ...] | None = ...) -> NearestPointEdge: ...
def nearest_edges(scene_handle: int, vertices: torch.Tensor, point: torch.Tensor, k: int, active: torch.Tensor | None, mesh_vertices: tuple[torch.Tensor, ...] | None = ...) -> NearestEdgesTopK: ...
def nearest_edge_ray(scene_handle: int, vertices: torch.Tensor, ray_o: torch.Tensor, ray_d: torch.Tensor, ray_tmax: torch.Tensor, active: torch.Tensor | None) -> NearestRayEdge: ...
def visible(scene_handle: int, start: torch.Tensor, end: torch.Tensor, active: torch.Tensor | None) -> torch.Tensor: ...
def trace_reflections(scene_handle: int, vertices: torch.Tensor, ray_o: torch.Tensor, ray_d: torch.Tensor, ray_tmax: torch.Tensor, active: torch.Tensor | None, max_bounces: int, mesh_vertices: tuple[torch.Tensor, ...] | None = ...) -> ReflectionChain: ...
def trace_refl_epc_field(scene_handle: int, vertices: torch.Tensor, source: torch.Tensor, receiver: torch.Tensor, active: torch.Tensor | None, max_bounces: int, mesh_vertices: tuple[torch.Tensor, ...] | None = ...) -> ReflEpcField: ...
def trace_dfr_paths_order1_native(scene_handle: int, tx_positions: torch.Tensor, rx_positions: torch.Tensor, states: DfrStates, material: DfrMaterial, *, active: torch.Tensor, max_paths: int, wavelength: float, tx_polarization: torch.Tensor | None = ...) -> DfrPaths: ...
def accum_dfr_direct_native(scene_handle: int, states: DfrStates, grid: DfrGrid, material: DfrMaterial, *, active: torch.Tensor | None, wavelength: float, direct_samples: int, keller_samples: int = ..., suffix_samples: int = ..., seed: int = ...) -> DfrAccum: ...
def accum_dfr_chain_native(scene_handle: int, initial_states: DfrStates, recursive_states: DfrStates, grid: DfrGrid, material: DfrMaterial, *, active: torch.Tensor | None, recursive_active: torch.Tensor | None, wavelength: float, direct_samples: int, keller_samples: int = ..., suffix_samples: int = ..., seed: int = ..., max_order: int = ...) -> DfrAccum: ...
def accum_dfr_coherent_direct_native(scene_handle: int, states: DfrStates, grid: DfrGrid, material: DfrMaterial, *, active: torch.Tensor | None, wavelength: float, select_diffraction_point: bool = ..., prefilter_visibility: bool = ...) -> DfrCoherentAccum: ...

class NativeOpUnavailable(RuntimeError): ...
