from dataclasses import dataclass
import torch

@dataclass
class Mesh:
    vertices: torch.Tensor
    faces: torch.Tensor
    uv: torch.Tensor | None = ...
    face_uv: torch.Tensor | None = ...
    use_face_normals: bool = ...
    edges_enabled: bool = ...
    to_world_left: torch.Tensor | None = ...
    to_world_right: torch.Tensor | None = ...
