// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char edge_optix_ptx[] =
R"PTX_CHUNK(//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__intersection__edge_point
.const .align 8 .b8 params[184];

.visible .entry __intersection__edge_point()
{
	.reg .pred 	%p<7>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<47>;
	.reg .b32 	%r<7>;
	.reg .b64 	%rd<24>;


	// begin inline asm
	call (%r2), _optix_read_primitive_idx, ();
	// end inline asm
	ld.const.u32 	%r3, [params+64];
	setp.ge.u32 	%p1, %r2, %r3;
	@%p1 bra 	$L__BB0_8;

	ld.const.u64 	%rd1, [params+56];
	setp.eq.s64 	%p2, %rd1, 0;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd2, %rd1;
	cvt.u64.u32 	%rd3, %r2;
	add.s64 	%rd4, %rd2, %rd3;
	ld.global.u8 	%rs1, [%rd4];
	setp.eq.s16 	%p3, %rs1, 0;
	@%p3 bra 	$L__BB0_8;

$L__BB0_3:
	// begin inline asm
	call (%f14), _optix_get_world_ray_origin_x, ();
	// end inline asm
	// begin inline asm
	call (%f15), _optix_get_world_ray_origin_y, ();
	// end inline asm
	// begin inline asm
	call (%f16), _optix_get_world_ray_origin_z, ();
	// end inline asm
	ld.const.u64 	%rd5, [params+8];
	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.u32 	%rd7, %r2, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.f32 	%f4, [%rd8];
	ld.const.u64 	%rd9, [params+16];
	cvta.to.global.u64 	%rd10, %rd9;
	add.s64 	%rd11, %rd10, %rd7;
	ld.global.f32 	%f5, [%rd11];
	ld.const.u64 	%rd12, [params+24];
	cvta.to.global.u64 	%rd13, %rd12;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.f32 	%f6, [%rd14];
	ld.const.u64 	%rd15, [params+32];
	cvta.to.global.u64 	%rd16, %rd15;
	add.s64 	%rd17, %rd16, %rd7;
	ld.const.u64 	%rd18, [params+40];
	cvta.to.global.u64 	%rd19, %rd18;
	add.s64 	%rd20, %rd19, %rd7;
	ld.const.u64 	%rd21, [params+48];
	cvta.to.global.u64 	%rd22, %rd21;
	add.s64 	%rd23, %rd22, %rd7;
	ld.global.f32 	%f7, [%rd17];
	ld.global.f32 	%f8, [%rd20];
	mul.ftz.f32 	%f18, %f8, %f8;
	fma.rn.ftz.f32 	%f19, %f7, %f7, %f18;
	ld.global.f32 	%f9, [%rd23];
	fma.rn.ftz.f32 	%f10, %f9, %f9, %f19;
	setp.leu.ftz.f32 	%p4, %f10, 0f33D6BF95;
	mov.f32 	%f17, 0f00000000;
	mov.f32 	%f46, %f17;
	@%p4 bra 	$L__BB0_5;

	sub.ftz.f32 	%f20, %f14, %f4;
	sub.ftz.f32 	%f21, %f15, %f5;
	mul.ftz.f32 	%f22, %f21, %f8;
	fma.rn.ftz.f32 	%f23, %f20, %f7, %f22;
	sub.ftz.f32 	%f24, %f16, %f6;
	fma.rn.ftz.f32 	%f25, %f24, %f9, %f23;
	div.approx.ftz.f32 	%f26, %f25, %f10;
	mov.f32 	%f27, 0f00000000;
	max.ftz.f32 	%f28, %f26, %f27;
	mov.f32 	%f29, 0f3F800000;
	min.ftz.f32 	%f46, %f28, %f29;

$L__BB0_5:
	fma.rn.ftz.f32 	%f31, %f7, %f46, %f4;
	fma.rn.ftz.f32 	%f32, %f8, %f46, %f5;
	fma.rn.ftz.f32 	%f33, %f9, %f46, %f6;
	sub.ftz.f32 	%f34, %f14, %f31;
	sub.ftz.f32 	%f35, %f15, %f32;
	sub.ftz.f32 	%f36, %f16, %f33;
	mul.ftz.f32 	%f37, %f35, %f35;
	fma.rn.ftz.f32 	%f38, %f34, %f34, %f37;
	fma.rn.ftz.f32 	%f39, %f36, %f36, %f38;
	max.ftz.f32 	%f41, %f39, %f17;
	sqrt.approx.ftz.f32 	%f13, %f41;
	// begin inline asm
	call (%f30), _optix_get_ray_tmax, ();
	// end inline asm
	setp.gtu.ftz.f32 	%p5, %f13, %f30;
	@%p5 bra 	$L__BB0_8;

	ld.const.f32 	%f42, [params+68];
	mov.f32 	%f43, 0f00000000;
	max.ftz.f32 	%f44, %f42, %f43;
	setp.gtu.ftz.f32 	%p6, %f13, %f44;
	@%p6 bra 	$L__BB0_8;

	mov.b32 	%r6, %f46;
	mov.u32 	%r5, 0;
	// begin inline asm
	call (%r4), _optix_report_intersection_1, (%f13, %r5, %r6);
	// end inline asm

$L__BB0_8:
	ret;

}
	// .globl	__intersection__edge_ray
.visible .entry __intersection__edge_ray()
{
	.reg .pred 	%p<28>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<198>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<24>;


	// begin inline asm
	call (%r2), _optix_read_primitive_idx, ();
	// end inline asm
	ld.const.u32 	%r3, [params+64];
	setp.ge.u32 	%p1, %r2, %r3;
	@%p1 bra 	$L__BB1_19;

	ld.const.u64 	%rd1, [params+56];
	setp.eq.s64 	%p2, %rd1, 0;
	@%p2 bra 	$L__BB1_3;

	cvta.to.global.u64 	%rd2, %rd1;
	cvt.u64.u32 	%rd3, %r2;
	add.s64 	%rd4, %rd2, %rd3;
	ld.global.u8 	%rs1, [%rd4];
	setp.eq.s16 	%p3, %rs1, 0;
	@%p3 bra 	$L__BB1_19;

$L__BB1_3:
	// begin inline asm
	call (%f66), _optix_get_ray_tmax, ();
	// end inline asm
	// begin inline asm
	call (%f67), _optix_get_world_ray_origin_x, ();
	// end inline asm
	// begin inline asm
	call (%f68), _optix_get_world_ray_origin_y, ();
	// end inline asm
	// begin inline asm
	call (%f69), _optix_get_world_ray_origin_z, ();
	// end inline asm
	// begin inline asm
	call (%f70), _optix_get_world_ray_direction_x, ();
	// end inline asm
	// begin inline asm
	call (%f71), _optix_get_world_ray_direction_y, ();
	// end inline asm
	// begin inline asm
	call (%f72), _optix_get_world_ray_direction_z, ();
	// end inline asm
	mul.ftz.f32 	%f5, %f66, %f70;
	mul.ftz.f32 	%f6, %f66, %f71;
	mul.ftz.f32 	%f7, %f66, %f72;
	ld.const.u64 	%rd5, [params+8];
	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.u32 	%rd7, %r2, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.const.u64 	%rd9, [params+16];
	cvta.to.global.u64 	%rd10, %rd9;
	add.s64 	%rd11, %rd10, %rd7;
	ld.const.u64 	%rd12, [params+24];
	cvta.to.global.u64 	%rd13, %rd12;
	add.s64 	%rd14, %rd13, %rd7;
	ld.const.u64 	%rd15, [params+32];
	cvta.to.global.u64 	%rd16, %rd15;
	add.s64 	%rd17, %rd16, %rd7;
	ld.const.u64 	%rd18, [params+40];
	cvta.to.global.u64 	%rd19, %rd18;
	add.s64 	%rd20, %rd19, %rd7;
	ld.const.u64 	%rd21, [params+48];
	cvta.to.global.u64 	%rd22, %rd21;
	add.s64 	%rd23, %rd22, %rd7;
	ld.global.f32 	%f8, [%rd8];
	sub.ftz.f32 	%f74, %f67, %f8;
	ld.global.f32 	%f9, [%rd11];
	sub.ftz.f32 	%f75, %f68, %f9;
	ld.global.f32 	%f10, [%rd14];
	sub.ftz.f32 	%f76, %f69, %f10;
	add.ftz.f32 	%f11, %f67, %f5;
	add.ftz.f32 	%f12, %f68, %f6;
	add.ftz.f32 	%f13, %f69, %f7;
	ld.global.f32 	%f14, [%rd17];
	add.ftz.f32 	%f15, %f8, %f14;
	ld.global.f32 	%f16, [%rd20];
	add.ftz.f32 	%f17, %f9, %f16;
	ld.global.f32 	%f18, [%rd23];
	add.ftz.f32 	%f19, %f10, %f18;
	mul.ftz.f32 	%f77, %f6, %f6;
	fma.rn.ftz.f32 	%f78, %f5, %f5, %f77;
	fma.rn.ftz.f32 	%f20, %f7, %f7, %f78;
	mul.ftz.f32 	%f79, %f6, %f16;
	fma.rn.ftz.f32 	%f80, %f5, %f14, %f79;
	fma.rn.ftz.f32 	%f21, %f7, %f18, %f80;
	mul.ftz.f32 	%f81, %f16, %f16;
	fma.rn.ftz.f32 	%f82, %f14, %f14, %f81;
	fma.rn.ftz.f32 	%f22, %f18, %f18, %f82;
	mul.ftz.f32 	%f83, %f6, %f75;
	fma.rn.ftz.f32 	%f84, %f5, %f74, %f83;
	fma.rn.ftz.f32 	%f23, %f7, %f76, %f84;
	mul.ftz.f32 	%f85, %f75, %f16;
	fma.rn.ftz.f32 	%f86, %f74, %f14, %f85;
	fma.rn.ftz.f32 	%f24, %f76, %f18, %f86;
	mul.ftz.f32 	%f87, %f20, %f22;
	mul.ftz.f32 	%f88, %f21, %f21;
	sub.ftz.f32 	%f25, %f87, %f88;
	setp.leu.ftz.f32 	%p4, %f22, 0f33D6BF95;
	mov.f32 	%f186, 0f00000000;
	mov.f32 	%f185, %f186;
	@%p4 bra 	$L__BB1_5;

	div.approx.ftz.f32 	%f89, %f24, %f22;
	mov.f32 	%f90, 0f00000000;
	max.ftz.f32 	%f91, %f89, %f90;
	mov.f32 	%f92, 0f3F800000;
	min.ftz.f32 	%f185, %f91, %f92;

$L__BB1_5:
	fma.rn.ftz.f32 	%f193, %f7, 0f00000000, %f69;
	fma.rn.ftz.f32 	%f192, %f6, 0f00000000, %f68;
	fma.rn.ftz.f32 	%f191, %f5, 0f00000000, %f67;
	fma.rn.ftz.f32 	%f94, %f14, %f185, %f8;
	fma.rn.ftz.f32 	%f95, %f16, %f185, %f9;
	fma.rn.ftz.f32 	%f96, %f18, %f185, %f10;
	sub.ftz.f32 	%f97, %f191, %f94;
	sub.ftz.f32 	%f98, %f192, %f95;
	sub.ftz.f32 	%f99, %f193, %f96;
	mul.ftz.f32 	%f100, %f98, %f98;
	fma.rn.ftz.f32 	%f101, %f97, %f97, %f100;
	fma.rn.ftz.f32 	%f31, %f99, %f99, %f101;
	@%p4 bra 	$L__BB1_7;

	sub.ftz.f32 	%f102, %f11, %f8;
	sub.ftz.f32 	%f103, %f12, %f9;
	mul.ftz.f32 	%f104, %f103, %f16;
	fma.rn.ftz.f32 	%f105, %f102, %f14, %f104;
	sub.ftz.f32 	%f106, %f13, %f10;
	fma.rn.ftz.f32 	%f107, %f106, %f18, %f105;
	div.approx.ftz.f32 	%f108, %f107, %f22;
	mov.f32 	%f109, 0f00000000;
	max.ftz.f32 	%f110, %f108, %f109;
	mov.f32 	%f111, 0f3F800000;
	min.ftz.f32 	%f186, %f110, %f111;

$L__BB1_7:
	setp.lt.ftz.f32 	%p6, %f31, 0f7F7FFFFF;
	min.ftz.f32 	%f113, %f31, 0f7F7FFFFF;
	fma.rn.ftz.f32 	%f114, %f14, %f186, %f8;
	fma.rn.ftz.f32 	%f115, %f16, %f186, %f9;
	fma.rn.ftz.f32 	%f116, %f18, %f186, %f10;
	sub.ftz.f32 	%f117, %f11, %f114;
	sub.ftz.f32 	%f118, %f12, %f115;
	sub.ftz.f32 	%f119, %f13, %f116;
	mul.ftz.f32 	%f120, %f118, %f118;
	fma.rn.ftz.f32 	%f121, %f117, %f117, %f120;
	fma.rn.ftz.f32 	%f122, %f119, %f119, %f121;
	setp.lt.ftz.f32 	%p7, %f122, %f113;
	selp.f32 	%f34, %f122, %f113, %p7;
	selp.f32 	%f35, 0f3F800000, 0f00000000, %p7;
	mov.f32 	%f194, 0f00000000;
	selp.f32 	%f123, %f185, 0f00000000, %p6;
	selp.f32 	%f36, %f186, %f123, %p7;
	setp.leu.ftz.f32 	%p8, %f20, 0f33D6BF95;
	mov.f32 	%f187, %f191;
	mov.f32 	%f188, %f192;
	mov.f32 	%f189, %f193;
	mov.f32 	%f190, %f194;
	@%p8 bra 	$L__BB1_9;

	sub.ftz.f32 	%f124, %f8, %f67;
	sub.ftz.f32 	%f125, %f9, %f68;
	mul.ftz.f32 	%f126, %f6, %f125;
	fma.rn.ftz.f32 	%f127, %f5, %f124, %f126;
	sub.ftz.f32 	%f128, %f10, %f69;
	fma.rn.ftz.f32 	%f129, %f7, %f128, %f127;
	div.approx.ftz.f32 	%f130, %f129, %f20;
	mov.f32 	%f131, 0f00000000;
	max.ftz.f32 	%f132, %f130, %f131;
	mov.f32 	%f133, 0f3F800000;
	min.ftz.f32 	%f190, %f132, %f133;
	fma.rn.ftz.f32 	%f189, %f7, %f190, %f69;
	fma.rn.ftz.f32 	%f188, %f6, %f190, %f68;
	fma.rn.ftz.f32 	%f187, %f5, %f190, %f67;

$L__BB1_9:
	fma.rn.ftz.f32 	%f135, %f14, 0f00000000, %f8;
	fma.rn.ftz.f32 	%f136, %f16, 0f00000000, %f9;
	fma.rn.ftz.f32 	%f137, %f18, 0f00000000, %f10;
	sub.ftz.f32 	%f138, %f187, %f135;
	sub.ftz.f32 	%f139, %f188, %f136;
	sub.ftz.f32 	%f140, %f189, %f137;
	mul.ftz.f32 	%f141, %f139, %f139;
	fma.rn.ftz.f32 	%f142, %f138, %f138, %f141;
	fma.rn.ftz.f32 	%f143, %f140, %f140, %f142;
	setp.lt.ftz.f32 	%p9, %f143, %f34;
	selp.f32 	%f45, %f143, %f34, %p9;
	selp.f32 	%f46, %f190, %f35, %p9;
	selp.f32 	%f47, 0f00000000, %f36, %p9;
	@%p8 bra 	$L__BB1_11;

	sub.ftz.f32 	%f144, %f15, %f67;
	sub.ftz.f32 	%f145, %f17, %f68;
	mul.ftz.f32 	%f146, %f6, %f145;
	fma.rn.ftz.f32 	%f147, %f5, %f144, %f146;
	sub.ftz.f32 	%f148, %f19, %f69;
	fma.rn.ftz.f32 	%f149, %f7, %f148, %f147;
	div.approx.ftz.f32 	%f150, %f149, %f20;
	mov.f32 	%f151, 0f00000000;
	max.ftz.f32 	%f152, %f150, %f151;
	mov.f32 	%f153, 0f3F800000;
	min.ftz.f32 	%f194, %f152, %f153;
	fma.rn.ftz.f32 	%f193, %f7, %f194, %f69;
	fma.rn.ftz.f32 	%f192, %f6, %f194, %f68;
	fma.rn.ftz.f32 	%f191, %f5, %f194, %f67;

$L__BB1_11:
	sub.ftz.f32 	%f154, %f191, %f15;
	sub.ftz.f32 	%f155, %f192, %f17;
	sub.ftz.f32 	%f156, %f193, %f19;
	mul.ftz.f32 	%f157, %f155, %f155;
	fma.rn.ftz.f32 	%f158, %f154, %f154, %f157;
	fma.rn.ftz.f32 	%f159, %f156, %f156, %f158;
	setp.lt.ftz.f32 	%p11, %f159, %f45;
	selp.f32 	%f195, %f159, %f45, %p11;
	selp.f32 	%f196, %f194, %f46, %p11;
	selp.f32 	%f197, 0f3F800000, %f47, %p11;
	or.pred  	%p14, %p8, %p4;
	@%p14 bra 	$L__BB1_16;

	abs.ftz.f32 	%f160, %f25;
	setp.leu.ftz.f32 	%p15, %f160, 0f33D6BF95;
	@%p15 bra 	$L__BB1_16;

	mul.ftz.f32 	%f161, %f21, %f24;
	mul.ftz.f32 	%f162, %f23, %f22;
	sub.ftz.f32 	%f163, %f161, %f162;
	div.approx.ftz.f32 	%f59, %f163, %f25;
	mul.ftz.f32 	%f164, %f23, %f21;
	mul.ftz.f32 	%f165, %f20, %f24;
	sub.ftz.f32 	%f166, %f165, %f164;
	div.approx.ftz.f32 	%f60, %f166, %f25;
	setp.ltu.ftz.f32 	%p16, %f59, 0f00000000;
	setp.gtu.ftz.f32 	%p17, %f59, 0f3F800000;
	or.pred  	%p18, %p16, %p17;
	setp.ltu.ftz.f32 	%p19, %f60, 0f00000000;
	or.pred  	%p20, %p18, %p19;
	setp.gtu.ftz.f32 	%p21, %f60, 0f3F800000;
	or.pred  	%p22, %p21, %p20;
	@%p22 bra 	$L__BB1_16;

	fma.rn.ftz.f32 	%f167, %f5, %f59, %f67;
	fma.rn.ftz.f32 	%f168, %f6, %f59, %f68;
	fma.rn.ftz.f32 	%f169, %f7, %f59, %f69;
	fma.rn.ftz.f32 	%f170, %f14, %f60, %f8;
	fma.rn.ftz.f32 	%f171, %f16, %f60, %f9;
	fma.rn.ftz.f32 	%f172, %f18, %f60, %f10;
	sub.ftz.f32 	%f173, %f167, %f170;
	sub.ftz.f32 	%f174, %f168, %f171;
	sub.ftz.f32 	%f175, %f169, %f172;
	mul.ftz.f32 	%f176, %f174, %f174;
	fma.rn.ftz.f32 	%f177, %f173, %f173, %f176;
	fma.rn.ftz.f32 	%f61, %f175, %f175, %f177;
	setp.geu.ftz.f32 	%p23, %f61, %f195;
	@%p23 bra 	$L__BB1_16;

	mov.f32 	%f195, %f61;
	mov.f32 	%f196, %f59;
	mov.f32 	%f197, %f60;

$L__BB1_16:
	// begin inline asm
	call (%f178), _optix_get_ray_tmin, ();
	// end inline asm
	mul.ftz.f32 	%f65, %f66, %f196;
	setp.ltu.ftz.f32 	%p24, %f65, %f178;
	setp.gtu.ftz.f32 	%p25, %f65, %f66;
	or.pred  	%p26, %p25, %p24;
	@%p26 bra 	$L__BB1_19;

	mov.f32 	%f179, 0f00000000;
	max.ftz.f32 	%f180, %f195, %f179;
	sqrt.approx.ftz.f32 	%f181, %f180;
	ld.const.f32 	%f182, [params+68];
	max.ftz.f32 	%f183, %f182, %f179;
	setp.gtu.ftz.f32 	%p27, %f181, %f183;
	@%p27 bra 	$L__BB1_19;

	mov.b32 	%r6, %f195;
	mov.b32 	%r8, %f197;
	mov.b32 	%r7, %f65;
	mov.u32 	%r5, 0;
	// begin inline asm
	call (%r4), _optix_report_intersection_3, (%f65, %r5, %r6, %r7, %r8);
	// end inline asm

$L__BB1_19:
	ret;

}
	// .globl	__intersection__edge_topk_point
.visible .entry __intersection__edge_topk_point()
{
	.reg .pred 	%p<6>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<45>;
	.reg .b32 	%r<8>;
	.reg .b64 	%rd<24>;


	// begin inline asm
	call (%r2), _optix_read_primitive_idx, ();
	// end inline asm
	ld.const.u32 	%r3, [params+64];
	setp.ge.u32 	%p1, %r2, %r3;
	@%p1 bra 	$L__BB2_7;

	ld.const.u64 	%rd1, [params+56];
	setp.eq.s64 	%p2, %rd1, 0;
	@%p2 bra 	$L__BB2_3;

	cvta.to.global.u64 	%rd2, %rd1;
	cvt.u64.u32 	%rd3, %r2;
	add.s64 	%rd4, %rd2, %rd3;
	ld.global.u8 	%rs1, [%rd4];
	setp.eq.s16 	%p3, %rs1, 0;
	@%p3 bra 	$L__BB2_7;

$L__BB2_3:
	// begin inline asm
	call (%f14), _optix_get_world_ray_origin_x, ();
	// end inline asm
	// begin inline asm
	call (%f15), _optix_get_world_ray_origin_y, ();
	// end inline asm
	// begin inline asm
	call (%f16), _optix_get_world_ray_origin_z, ();
	// end inline asm
	ld.const.u64 	%rd5, [params+8];
	cvta.to.global.u64 	%rd6, %rd5;
	mul.wide.u32 	%rd7, %r2, 4;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.f32 	%f4, [%rd8];
	ld.const.u64 	%rd9, [params+16];
	cvta.to.global.u64 	%rd10, %rd9;
	add.s64 	%rd11, %rd10, %rd7;
	ld.global.f32 	%f5, [%rd11];
	ld.const.u64 	%rd12, [params+24];
	cvta.to.global.u64 	%rd13, %rd12;
	add.s64 	%rd14, %rd13, %rd7;
	ld.global.f32 	%f6, [%rd14];
	ld.const.u64 	%rd15, [params+32];
	cvta.to.global.u64 	%rd16, %rd15;
	add.s64 	%rd17, %rd16, %rd7;
	ld.const.u64 	%rd18, [params+40];
	cvta.to.global.u64 	%rd19, %rd18;
	add.s64 	%rd20, %rd19, %rd7;
	ld.const.u64 	%rd21, [params+48];
	cvta.to.global.u64 	%rd22, %rd21;
	add.s64 	%rd23, %rd22, %rd7;
	ld.global.f32 	%f7, [%rd17];
	ld.global.f32 	%f8, [%rd20];
	mul.ftz.f32 	%f18, %f8, %f8;
	fma.rn.ftz.f32 	%f19, %f7, %f7, %f18;
	ld.global.f32 	%f9, [%rd23];
	fma.rn.ftz.f32 	%f10, %f9, %f9, %f19;
	setp.leu.ftz.f32 	%p4, %f10, 0f33D6BF95;
	mov.f32 	%f17, 0f00000000;
	mov.f32 	%f44, %f17;
	@%p4 bra 	$L__BB2_5;

	sub.ftz.f32 	%f20, %f14, %f4;
	sub.ftz.f32 	%f21, %f15, %f5;
	mul.ftz.f32 	%f22, %f21, %f8;
	fma.rn.ftz.f32 	%f23, %f20, %f7, %f22;
	sub.ftz.f32 	%f24, %f16, %f6;
	fma.rn.ftz.f32 	%f25, %f24, %f9, %f23;
	div.approx.ftz.f32 	%f26, %f25, %f10;
	mov.f32 	%f27, 0f00000000;
	max.ftz.f32 	%f28, %f26, %f27;
	mov.f32 	%f29, 0f3F800000;
	min.ftz.f32 	%f44, %f28, %f29;

$L__BB2_5:
	fma.rn.ftz.f32 	%f30, %f7, %f44, %f4;
	fma.rn.ftz.f32 	%f31, %f8, %f44, %f5;
	fma.rn.ftz.f32 	%f32, %f9, %f44, %f6;
	sub.ftz.f32 	%f33, %f14, %f30;
	sub.ftz.f32 	%f34, %f15, %f31;
	sub.ftz.f32 	%f35, %f16, %f32;
	mul.ftz.f32 	%f36, %f34, %f34;
	fma.rn.ftz.f32 	%f37, %f33, %f33, %f36;
	fma.rn.ftz.f32 	%f13, %f35, %f35, %f37;
	max.ftz.f32 	%f39, %f13, %f17;
	sqrt.approx.ftz.f32 	%f40, %f39;
	ld.const.f32 	%f41, [params+68];
	max.ftz.f32 	%f42, %f41, %f17;
	setp.gtu.ftz.f32 	%p5, %f40, %f42;
	@%p5 bra 	$L__BB2_7;

	mov.b32 	%r6, %f13;
	mov.b32 	%r7, %f44;
	mov.f32 	%f43, 0f36A7C5AC;
	mov.u32 	%r5, 0;
	// begin inline asm
	call (%r4), _optix_report_intersection_2, (%f43, %r5, %r6, %r7);
	// end inline asm

$L__BB2_7:
	ret;

}
	// .globl	__closesthit__edge_point
.visible .entry __closesthit__edge_point()
{
	.reg .f32 	%f<3>;
	.reg .b32 	%r<11>;


	// begin inline asm
	call (%f1), _optix_get_ray_tmax, ();
	// end inline asm
	// begin inline asm
	call (%r1), _optix_read_primitive_idx, ();
	// end inline asm
	mov.u32 	%r2, 0;
	// begin inline asm
	call _optix_set_payload, (%r2, %r1);
	// end inline asm
	mul.ftz.f32 	%f2, %f1, %f1;
	mov.b32 	%r5, %f2;
	mov.u32 	%r10, 1;
	// begin inline asm
	call _optix_set_payload, (%r10, %r5);
	// end inline asm
)PTX_CHUNK"
R"PTX_CHUNK(	// begin inline asm
	call (%r6), _optix_get_attribute_0, ();
	// end inline asm
	mov.u32 	%r7, 2;
	// begin inline asm
	call _optix_set_payload, (%r7, %r6);
	// end inline asm
	mov.u32 	%r9, 3;
	// begin inline asm
	call _optix_set_payload, (%r9, %r10);
	// end inline asm
	ret;

}
	// .globl	__anyhit__edge_ray
.visible .entry __anyhit__edge_ray()
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<18>;


	// begin inline asm
	call (%r2), _optix_get_attribute_0, ();
	// end inline asm
	mov.b32 	%f1, %r2;
	mov.u32 	%r4, 1;
	// begin inline asm
	call (%r3), _optix_get_payload, (%r4);
	// end inline asm
	mov.b32 	%f2, %r3;
	setp.geu.ftz.f32 	%p1, %f1, %f2;
	@%p1 bra 	$L__BB4_2;

	// begin inline asm
	call (%r5), _optix_read_primitive_idx, ();
	// end inline asm
	mov.u32 	%r6, 0;
	// begin inline asm
	call _optix_set_payload, (%r6, %r5);
	// end inline asm
	// begin inline asm
	call _optix_set_payload, (%r4, %r2);
	// end inline asm
	// begin inline asm
	call (%r10), _optix_get_attribute_1, ();
	// end inline asm
	mov.u32 	%r11, 2;
	// begin inline asm
	call _optix_set_payload, (%r11, %r10);
	// end inline asm
	// begin inline asm
	call (%r13), _optix_get_attribute_2, ();
	// end inline asm
	mov.u32 	%r14, 3;
	// begin inline asm
	call _optix_set_payload, (%r14, %r13);
	// end inline asm
	mov.u32 	%r16, 4;
	// begin inline asm
	call _optix_set_payload, (%r16, %r4);
	// end inline asm

$L__BB4_2:
	// begin inline asm
	call _optix_ignore_intersection, ();
	// end inline asm
	ret;

}
	// .globl	__anyhit__edge_topk_point
.visible .entry __anyhit__edge_topk_point()
{
	.reg .pred 	%p<50>;
	.reg .b16 	%rs<3>;
	.reg .f32 	%f<9>;
	.reg .b32 	%r<181>;
	.reg .b64 	%rd<23>;


	ld.const.u32 	%r174, [params+140];
	setp.lt.s32 	%p3, %r174, 9;
	@%p3 bra 	$L__BB5_9;
	bra.uni 	$L__BB5_1;

$L__BB5_9:
	// begin inline asm
	call (%r46), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r47), _optix_get_attribute_0, ();
	// end inline asm
	mov.b32 	%f2, %r47;
	add.s32 	%r48, %r174, -1;
	setp.gt.u32 	%p8, %r48, 7;
	@%p8 bra 	$L__BB5_83;

	setp.gt.s32 	%p9, %r174, 3;
	@%p9 bra 	$L__BB5_15;
	bra.uni 	$L__BB5_11;

$L__BB5_15:
	setp.gt.s32 	%p10, %r174, 5;
	@%p10 bra 	$L__BB5_19;

	setp.eq.s32 	%p13, %r174, 4;
	@%p13 bra 	$L__BB5_23;

	setp.eq.s32 	%p14, %r174, 5;
	@%p14 bra 	$L__BB5_18;
	bra.uni 	$L__BB5_26;

$L__BB5_18:
	mov.u32 	%r54, 12;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r54);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_1:
	// begin inline asm
	call (%r38), _optix_get_launch_index_x, ();
	// end inline asm
	// begin inline asm
	call (%r39), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r40), _optix_get_attribute_0, ();
	// end inline asm
	mov.b32 	%f1, %r40;
	// begin inline asm
	call (%r41), _optix_get_attribute_1, ();
	// end inline asm
	add.s32 	%r6, %r174, -1;
	setp.gt.u32 	%p4, %r6, 15;
	@%p4 bra 	$L__BB5_83;

	ld.const.u64 	%rd13, [params+152];
	cvta.to.global.u64 	%rd1, %rd13;
	mad.lo.s32 	%r42, %r174, %r38, %r6;
	mul.wide.s32 	%rd14, %r42, 4;
	add.s64 	%rd15, %rd1, %rd14;
	ld.global.f32 	%f3, [%rd15];
	setp.le.ftz.f32 	%p5, %f3, %f1;
	@%p5 bra 	$L__BB5_83;

	ld.const.u64 	%rd16, [params+144];
	cvta.to.global.u64 	%rd2, %rd16;
	ld.const.u64 	%rd17, [params+168];
	cvta.to.global.u64 	%rd3, %rd17;
	ld.const.u64 	%rd18, [params+176];
	cvta.to.global.u64 	%rd19, %rd18;
	add.s32 	%r43, %r38, 1;
	mad.lo.s32 	%r44, %r174, %r43, -2;
	cvt.s64.s32 	%rd20, %r44;
	add.s64 	%rd22, %rd19, %rd20;
	mul.wide.s32 	%rd21, %r44, 4;
	bra.uni 	$L__BB5_4;

$L__BB5_8:
	ld.global.f32 	%f5, [%rd8];
	st.global.f32 	[%rd8+4], %f5;
	ld.global.u32 	%r45, [%rd9];
	st.global.u32 	[%rd9+4], %r45;
	ld.global.f32 	%f6, [%rd10];
	st.global.f32 	[%rd10+4], %f6;
	ld.global.u8 	%rs2, [%rd22];
	st.global.u8 	[%rd22+1], %rs2;
	add.s64 	%rd22, %rd22, -1;
	add.s64 	%rd21, %rd21, -4;
	add.s32 	%r174, %r174, -1;

$L__BB5_4:
	add.s64 	%rd8, %rd1, %rd21;
	setp.lt.s32 	%p7, %r174, 2;
	mov.pred 	%p49, 0;
	@%p7 bra 	$L__BB5_6;

	ld.global.f32 	%f4, [%rd8];
	setp.gt.ftz.f32 	%p49, %f4, %f1;

$L__BB5_6:
	add.s64 	%rd9, %rd2, %rd21;
	add.s64 	%rd10, %rd3, %rd21;
	@%p49 bra 	$L__BB5_8;

	st.global.u32 	[%rd8+4], %r40;
	st.global.u32 	[%rd9+4], %r39;
	st.global.u32 	[%rd10+4], %r41;
	mov.u16 	%rs1, 1;
	st.global.u8 	[%rd22+1], %rs1;
	bra.uni 	$L__BB5_83;

$L__BB5_11:
	setp.eq.s32 	%p15, %r174, 1;
	@%p15 bra 	$L__BB5_25;

	setp.eq.s32 	%p16, %r174, 2;
	@%p16 bra 	$L__BB5_24;

	setp.eq.s32 	%p17, %r174, 3;
	@%p17 bra 	$L__BB5_14;
	bra.uni 	$L__BB5_26;

$L__BB5_14:
	mov.u32 	%r58, 10;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r58);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_19:
	setp.eq.s32 	%p11, %r174, 6;
	@%p11 bra 	$L__BB5_22;

	setp.ne.s32 	%p12, %r174, 7;
	@%p12 bra 	$L__BB5_26;

	mov.u32 	%r50, 14;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r50);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_23:
	mov.u32 	%r56, 11;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r56);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_25:
	mov.u32 	%r62, 8;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r62);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_22:
	mov.u32 	%r52, 13;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r52);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_26:
	mov.u32 	%r64, 15;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r64);
	// end inline asm
	bra.uni 	$L__BB5_27;

$L__BB5_24:
	mov.u32 	%r60, 9;
	// begin inline asm
	call (%r175), _optix_get_payload, (%r60);
	// end inline asm

$L__BB5_27:
	mov.b32 	%f7, %r175;
	setp.le.ftz.f32 	%p18, %f7, %f2;
	@%p18 bra 	$L__BB5_83;

	setp.lt.s32 	%p19, %r174, 2;
	mov.u32 	%r180, 1;
	@%p19 bra 	$L__BB5_66;

$L__BB5_29:
	mov.u32 	%r180, %r174;
	add.s32 	%r174, %r180, -1;
	setp.gt.s32 	%p20, %r180, 4;
	@%p20 bra 	$L__BB5_34;
	bra.uni 	$L__BB5_30;

$L__BB5_34:
	setp.gt.s32 	%p21, %r180, 6;
	@%p21 bra 	$L__BB5_38;

	setp.eq.s32 	%p24, %r180, 5;
	@%p24 bra 	$L__BB5_42;

	setp.eq.s32 	%p25, %r180, 6;
	@%p25 bra 	$L__BB5_37;
	bra.uni 	$L__BB5_45;

$L__BB5_37:
	mov.u32 	%r71, 12;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r71);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_30:
	setp.eq.s32 	%p26, %r180, 2;
	@%p26 bra 	$L__BB5_44;

	setp.eq.s32 	%p27, %r180, 3;
	@%p27 bra 	$L__BB5_43;

	setp.eq.s32 	%p28, %r180, 4;
	@%p28 bra 	$L__BB5_33;
	bra.uni 	$L__BB5_45;

$L__BB5_33:
	mov.u32 	%r75, 10;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r75);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_38:
	setp.eq.s32 	%p22, %r180, 7;
	@%p22 bra 	$L__BB5_41;

	setp.ne.s32 	%p23, %r180, 8;
	@%p23 bra 	$L__BB5_45;

	mov.u32 	%r67, 14;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r67);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_42:
	mov.u32 	%r73, 11;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r73);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_44:
	mov.u32 	%r79, 8;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r79);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_43:
	mov.u32 	%r77, 9;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r77);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_41:
	mov.u32 	%r69, 13;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r69);
	// end inline asm
	bra.uni 	$L__BB5_46;

$L__BB5_45:
	mov.u32 	%r81, 15;
	// begin inline asm
	call (%r177), _optix_get_payload, (%r81);
	// end inline asm

$L__BB5_46:
	mov.b32 	%f8, %r177;
	setp.leu.ftz.f32 	%p29, %f8, %f2;
	@%p29 bra 	$L__BB5_66;

	@%p20 bra 	$L__BB5_52;
	bra.uni 	$L__BB5_48;

$L__BB5_52:
	setp.gt.s32 	%p31, %r180, 6;
	@%p31 bra 	$L__BB5_56;

	setp.eq.s32 	%p34, %r180, 5;
	@%p34 bra 	$L__BB5_60;

	setp.eq.s32 	%p35, %r180, 6;
	@%p35 bra 	$L__BB5_55;
	bra.uni 	$L__BB5_63;

$L__BB5_55:
	mov.u32 	%r95, 4;
	// begin inline asm
	call (%r94), _optix_get_payload, (%r95);
	// end inline asm
	mov.u32 	%r97, 12;
	// begin inline asm
	call (%r96), _optix_get_payload, (%r97);
	// end inline asm
	mov.u32 	%r98, 5;
	// begin inline asm
	call _optix_set_payload, (%r98, %r94);
	// end inline asm
	mov.u32 	%r100, 13;
	// begin inline asm
	call _optix_set_payload, (%r100, %r96);
	// end inline asm
	bra.uni 	$L__BB5_65;

$L__BB5_48:
	setp.eq.s32 	%p36, %r180, 2;
	@%p36 bra 	$L__BB5_62;

	setp.eq.s32 	%p37, %r180, 3;
	@%p37 bra 	$L__BB5_61;

	setp.eq.s32 	%p38, %r180, 4;
	@%p38 bra 	$L__BB5_51;
	bra.uni 	$L__BB5_63;

$L__BB5_51:
	mov.u32 	%r111, 2;
	// begin inline asm
	call (%r110), _optix_get_payload, (%r111);
	// end inline asm
	mov.u32 	%r113, 10;
	// begin inline asm
	call (%r112), _optix_get_payload, (%r113);
	// end inline asm
	mov.u32 	%r114, 3;
	// begin inline asm
	call _optix_set_payload, (%r114, %r110);
	// end inline asm
	mov.u32 	%r116, 11;
	// begin inline asm
	call _optix_set_payload, (%r116, %r112);
	// end inline asm
	bra.uni 	$L__BB5_65;

$L__BB5_56:
	setp.eq.s32 	%p32, %r180, 7;
	@%p32 bra 	$L__BB5_59;

	setp.ne.s32 	%p33, %r180, 8;
	@%p33 bra 	$L__BB5_63;

	mov.u32 	%r83, 6;
	// begin inline asm
	call (%r179), _optix_get_payload, (%r83);
	// end inline asm
	mov.u32 	%r85, 14;
	// begin inline asm
	call (%r178), _optix_get_payload, (%r85);
	// end inline asm
	bra.uni 	$L__BB5_64;

$L__BB5_60:
	mov.u32 	%r103, 3;
	// begin inline asm
	call (%r102), _optix_get_payload, (%r103);
	// end inline asm
	mov.u32 	%r105, 11;
	// begin inline asm
	call (%r104), _optix_get_payload, (%r105);
	// end inline asm
	mov.u32 	%r106, 4;
	// begin inline asm
	call _optix_set_payload, (%r106, %r102);
	// end inline asm
	mov.u32 	%r108, 12;
	// begin inline asm
	call _optix_set_payload, (%r108, %r104);
	// end inline asm
	bra.uni 	$L__BB5_65;

$L__BB5_62:
	mov.u32 	%r127, 0;
	// begin inline asm
	call (%r126), _optix_get_payload, (%r127);
	// end inline asm
	mov.u32 	%r129, 8;
	// begin inline asm
	call (%r128), _optix_get_payload, (%r129);
	// end inline asm
	mov.u32 	%r130, 1;
	// begin inline asm
	call _optix_set_payload, (%r130, %r126);
	// end inline asm
	mov.u32 	%r132, 9;
	// begin inline asm
	call _optix_set_payload, (%r132, %r128);
	// end inline asm
	bra.uni 	$L__BB5_65;

$L__BB5_61:
	mov.u32 	%r119, 1;
	// begin inline asm
	call (%r118), _optix_get_payload, (%r119);
	// end inline asm
	mov.u32 	%r121, 9;
	// begin inline asm
	call (%r120), _optix_get_payload, (%r121);
	// end inline asm
	mov.u32 	%r122, 2;
	// begin inline asm
	call _optix_set_payload, (%r122, %r118);
	// end inline asm
	mov.u32 	%r124, 10;
	// begin inline asm
	call _optix_set_payload, (%r124, %r120);
	// end inline asm
	bra.uni 	$L__BB5_65;

$L__BB5_59:
	mov.u32 	%r87, 5;
	// begin inline asm
	call (%r86), _optix_get_payload, (%r87);
	// end inline asm
	mov.u32 	%r89, 13;
	// begin inline asm
	call (%r88), _optix_get_payload, (%r89);
	// end inline asm
	mov.u32 	%r90, 6;
	// begin inline asm
	call _optix_set_payload, (%r90, %r86);
	// end inline asm
	mov.u32 	%r92, 14;
	// begin inline asm
	call _optix_set_payload, (%r92, %r88);
	// end inline asm
	bra.uni 	$L__BB5_65;

$L__BB5_63:
	mov.u32 	%r135, 7;
	// begin inline asm
	call (%r179), _optix_get_payload, (%r135);
	// end inline asm
	mov.u32 	%r137, 15;
	// begin inline asm
	call (%r178), _optix_get_payload, (%r137);
	// end inline asm

$L__BB5_64:
	mov.u32 	%r138, 7;
	// begin inline asm
	call _optix_set_payload, (%r138, %r179);
	// end inline asm
	mov.u32 	%r140, 15;
	// begin inline asm
	call _optix_set_payload, (%r140, %r178);
	// end inline asm

$L__BB5_65:
	setp.gt.s32 	%p39, %r180, 2;
	mov.u32 	%r180, %r174;
	@%p39 bra 	$L__BB5_29;

$L__BB5_66:
	setp.gt.s32 	%p40, %r180, 3;
	@%p40 bra 	$L__BB5_71;
	bra.uni 	$L__BB5_67;

$L__BB5_71:
	setp.gt.s32 	%p41, %r180, 5;
	@%p41 bra 	$L__BB5_75;

	setp.eq.s32 	%p44, %r180, 4;
	@%p44 bra 	$L__BB5_79;

	setp.eq.s32 	%p45, %r180, 5;
	@%p45 bra 	$L__BB5_74;
	bra.uni 	$L__BB5_82;

$L__BB5_74:
	mov.u32 	%r150, 4;
	// begin inline asm
	call _optix_set_payload, (%r150, %r46);
	// end inline asm
	mov.u32 	%r152, 12;
	// begin inline asm
	call _optix_set_payload, (%r152, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_67:
	setp.eq.s32 	%p46, %r180, 1;
	@%p46 bra 	$L__BB5_81;

	setp.eq.s32 	%p47, %r180, 2;
	@%p47 bra 	$L__BB5_80;

	setp.eq.s32 	%p48, %r180, 3;
	@%p48 bra 	$L__BB5_70;
	bra.uni 	$L__BB5_82;

$L__BB5_70:
	mov.u32 	%r158, 2;
	// begin inline asm
	call _optix_set_payload, (%r158, %r46);
	// end inline asm
	mov.u32 	%r160, 10;
	// begin inline asm
	call _optix_set_payload, (%r160, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_75:
	setp.eq.s32 	%p42, %r180, 6;
	@%p42 bra 	$L__BB5_78;

	setp.ne.s32 	%p43, %r180, 7;
	@%p43 bra 	$L__BB5_82;

	mov.u32 	%r142, 6;
	// begin inline asm
	call _optix_set_payload, (%r142, %r46);
	// end inline asm
	mov.u32 	%r144, 14;
	// begin inline asm
	call _optix_set_payload, (%r144, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_79:
	mov.u32 	%r154, 3;
	// begin inline asm
	call _optix_set_payload, (%r154, %r46);
	// end inline asm
	mov.u32 	%r156, 11;
	// begin inline asm
	call _optix_set_payload, (%r156, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_81:
	mov.u32 	%r166, 0;
	// begin inline asm
	call _optix_set_payload, (%r166, %r46);
	// end inline asm
	mov.u32 	%r168, 8;
	// begin inline asm
	call _optix_set_payload, (%r168, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_78:
	mov.u32 	%r146, 5;
	// begin inline asm
	call _optix_set_payload, (%r146, %r46);
	// end inline asm
	mov.u32 	%r148, 13;
	// begin inline asm
	call _optix_set_payload, (%r148, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_82:
	mov.u32 	%r170, 7;
	// begin inline asm
	call _optix_set_payload, (%r170, %r46);
	// end inline asm
	mov.u32 	%r172, 15;
	// begin inline asm
	call _optix_set_payload, (%r172, %r47);
	// end inline asm
	bra.uni 	$L__BB5_83;

$L__BB5_80:
	mov.u32 	%r162, 1;
	// begin inline asm
	call _optix_set_payload, (%r162, %r46);
	// end inline asm
	mov.u32 	%r164, 9;
	// begin inline asm
	call _optix_set_payload, (%r164, %r47);
	// end inline asm

$L__BB5_83:
	// begin inline asm
	call _optix_ignore_intersection, ();
	// end inline asm
	ret;

}
	// .globl	__miss__edge_query
.visible .entry __miss__edge_query()
{



	ret;

}
	// .globl	__raygen__edge_point
.visible .entry __raygen__edge_point()
{
	.reg .pred 	%p<20>;
	.reg .b16 	%rs<5>;
	.reg .f32 	%f<11>;
	.reg .b32 	%r<119>;
	.reg .b64 	%rd<75>;


	// begin inline asm
	call (%r35), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r36, [params+136];
	setp.ge.u32 	%p1, %r35, %r36;
	@%p1 bra 	$L__BB7_3;

	ld.const.u64 	%rd1, [params+128];
	setp.eq.s64 	%p2, %rd1, 0;
	@%p2 bra 	$L__BB7_7;

	cvta.to.global.u64 	%rd13, %rd1;
	cvt.u64.u32 	%rd14, %r35;
	add.s64 	%rd15, %rd13, %rd14;
	ld.global.u8 	%rs1, [%rd15];
	setp.eq.s16 	%p3, %rs1, 0;
	ld.const.u64 	%rd74, [params];
	setp.eq.s64 	%p4, %rd74, 0;
	or.pred  	%p5, %p3, %p4;
	ld.const.u32 	%r37, [params+64];
	setp.lt.s32 	%p6, %r37, 1;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	$L__BB7_3;
	bra.uni 	$L__BB7_8;

$L__BB7_3:
	ld.const.u64 	%rd58, [params+144];
	cvta.to.global.u64 	%rd59, %rd58;
	cvt.u64.u32 	%rd10, %r35;
	mul.wide.u32 	%rd60, %r35, 4;
	add.s64 	%rd61, %rd59, %rd60;
	mov.u32 	%r115, -1;
	st.global.u32 	[%rd61], %r115;
	ld.const.u64 	%rd62, [params+152];
	cvta.to.global.u64 	%rd63, %rd62;
	add.s64 	%rd64, %rd63, %rd60;
	mov.u32 	%r116, 2139095039;
	st.global.u32 	[%rd64], %r116;
	ld.const.u64 	%rd11, [params+160];
	setp.eq.s64 	%p18, %rd11, 0;
	@%p18 bra 	$L__BB7_5;

	cvta.to.global.u64 	%rd65, %rd11;
	shl.b64 	%rd66, %rd10, 2;
	add.s64 	%rd67, %rd65, %rd66;
	mov.u32 	%r117, 0;
	st.global.u32 	[%rd67], %r117;

$L__BB7_5:
	ld.const.u64 	%rd68, [params+168];
	cvta.to.global.u64 	%rd69, %rd68;
	shl.b64 	%rd70, %rd10, 2;
	add.s64 	%rd71, %rd69, %rd70;
	mov.u32 	%r118, 0;
	st.global.u32 	[%rd71], %r118;
	ld.const.u64 	%rd12, [params+176];
	setp.eq.s64 	%p19, %rd12, 0;
	@%p19 bra 	$L__BB7_17;

	cvta.to.global.u64 	%rd72, %rd12;
	)PTX_CHUNK"
R"PTX_CHUNK(add.s64 	%rd73, %rd72, %rd10;
	mov.u16 	%rs4, 0;
	st.global.u8 	[%rd73], %rs4;

$L__BB7_17:
	ret;

$L__BB7_7:
	ld.const.u64 	%rd74, [params];
	setp.eq.s64 	%p8, %rd74, 0;
	ld.const.u32 	%r38, [params+64];
	setp.lt.s32 	%p9, %r38, 1;
	or.pred  	%p10, %p8, %p9;
	@%p10 bra 	$L__BB7_3;

$L__BB7_8:
	ld.const.u64 	%rd17, [params+72];
	cvta.to.global.u64 	%rd18, %rd17;
	cvt.u64.u32 	%rd5, %r35;
	mul.wide.u32 	%rd19, %r35, 4;
	add.s64 	%rd20, %rd18, %rd19;
	ld.global.f32 	%f1, [%rd20];
	ld.const.u64 	%rd21, [params+80];
	cvta.to.global.u64 	%rd22, %rd21;
	add.s64 	%rd23, %rd22, %rd19;
	ld.global.f32 	%f2, [%rd23];
	ld.const.u64 	%rd24, [params+88];
	cvta.to.global.u64 	%rd25, %rd24;
	add.s64 	%rd26, %rd25, %rd19;
	ld.global.f32 	%f3, [%rd26];
	ld.const.f32 	%f10, [params+68];
	mov.f32 	%f9, 0f00000000;
	max.ftz.f32 	%f8, %f10, %f9;
	mov.f32 	%f6, 0fBF800000;
	mov.u32 	%r72, 255;
	mov.u32 	%r75, 1;
	mov.u32 	%r77, 4;
	mov.u32 	%r78, -1;
	mov.u32 	%r79, 2139095039;
	mov.u32 	%r109, 0;
	// begin inline asm
	call(%r39,%r40,%r41,%r42,%r43,%r44,%r45,%r46,%r47,%r48,%r49,%r50,%r51,%r52,%r53,%r54,%r55,%r56,%r57,%r58,%r59,%r60,%r61,%r62,%r63,%r64,%r65,%r66,%r67,%r68,%r69,%r70),_optix_trace_typed_32,(%r109,%rd74,%f1,%f2,%f3,%f9,%f9,%f6,%f9,%f8,%f9,%r72,%r75,%r109,%r75,%r109,%r77,%r78,%r79,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109);
	// end inline asm
	setp.eq.s32 	%p11, %r42, 0;
	setp.eq.s32 	%p12, %r39, -1;
	or.pred  	%p13, %p11, %p12;
	@%p13 bra 	$L__BB7_13;
	bra.uni 	$L__BB7_9;

$L__BB7_13:
	ld.const.u64 	%rd42, [params+144];
	cvta.to.global.u64 	%rd43, %rd42;
	shl.b64 	%rd44, %rd5, 2;
	add.s64 	%rd45, %rd43, %rd44;
	st.global.u32 	[%rd45], %r78;
	ld.const.u64 	%rd46, [params+152];
	cvta.to.global.u64 	%rd47, %rd46;
	add.s64 	%rd48, %rd47, %rd44;
	st.global.u32 	[%rd48], %r79;
	ld.const.u64 	%rd8, [params+160];
	setp.eq.s64 	%p16, %rd8, 0;
	@%p16 bra 	$L__BB7_15;

	cvta.to.global.u64 	%rd49, %rd8;
	add.s64 	%rd51, %rd49, %rd44;
	mov.u32 	%r113, 0;
	st.global.u32 	[%rd51], %r113;

$L__BB7_15:
	ld.const.u64 	%rd52, [params+168];
	cvta.to.global.u64 	%rd53, %rd52;
	add.s64 	%rd55, %rd53, %rd44;
	mov.u32 	%r114, 0;
	st.global.u32 	[%rd55], %r114;
	ld.const.u64 	%rd9, [params+176];
	setp.eq.s64 	%p17, %rd9, 0;
	@%p17 bra 	$L__BB7_17;

	cvta.to.global.u64 	%rd56, %rd9;
	add.s64 	%rd57, %rd56, %rd5;
	mov.u16 	%rs3, 0;
	st.global.u8 	[%rd57], %rs3;
	bra.uni 	$L__BB7_17;

$L__BB7_9:
	ld.const.u64 	%rd27, [params+144];
	cvta.to.global.u64 	%rd28, %rd27;
	shl.b64 	%rd29, %rd5, 2;
	add.s64 	%rd30, %rd28, %rd29;
	st.global.u32 	[%rd30], %r39;
	ld.const.u64 	%rd31, [params+152];
	cvta.to.global.u64 	%rd32, %rd31;
	add.s64 	%rd33, %rd32, %rd29;
	st.global.u32 	[%rd33], %r40;
	ld.const.u64 	%rd34, [params+168];
	cvta.to.global.u64 	%rd35, %rd34;
	add.s64 	%rd36, %rd35, %rd29;
	st.global.u32 	[%rd36], %r41;
	ld.const.u64 	%rd6, [params+160];
	setp.eq.s64 	%p14, %rd6, 0;
	@%p14 bra 	$L__BB7_11;

	cvta.to.global.u64 	%rd37, %rd6;
	add.s64 	%rd39, %rd37, %rd29;
	mov.u32 	%r110, 0;
	st.global.u32 	[%rd39], %r110;

$L__BB7_11:
	ld.const.u64 	%rd7, [params+176];
	setp.eq.s64 	%p15, %rd7, 0;
	@%p15 bra 	$L__BB7_17;

	cvta.to.global.u64 	%rd40, %rd7;
	add.s64 	%rd41, %rd40, %rd5;
	mov.u16 	%rs2, 1;
	st.global.u8 	[%rd41], %rs2;
	bra.uni 	$L__BB7_17;

}
	// .globl	__raygen__edge_ray
.visible .entry __raygen__edge_ray()
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<5>;
	.reg .f32 	%f<19>;
	.reg .b32 	%r<118>;
	.reg .b64 	%rd<87>;


	// begin inline asm
	call (%r35), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r36, [params+136];
	setp.ge.u32 	%p1, %r35, %r36;
	@%p1 bra 	$L__BB8_3;

	ld.const.u64 	%rd1, [params+128];
	setp.eq.s64 	%p2, %rd1, 0;
	@%p2 bra 	$L__BB8_7;

	cvta.to.global.u64 	%rd13, %rd1;
	cvt.u64.u32 	%rd14, %r35;
	add.s64 	%rd15, %rd13, %rd14;
	ld.global.u8 	%rs1, [%rd15];
	setp.eq.s16 	%p3, %rs1, 0;
	ld.const.u64 	%rd86, [params];
	setp.eq.s64 	%p4, %rd86, 0;
	or.pred  	%p5, %p3, %p4;
	ld.const.u32 	%r37, [params+64];
	setp.lt.s32 	%p6, %r37, 1;
	or.pred  	%p7, %p5, %p6;
	@%p7 bra 	$L__BB8_3;
	bra.uni 	$L__BB8_8;

$L__BB8_3:
	ld.const.u64 	%rd70, [params+144];
	cvta.to.global.u64 	%rd71, %rd70;
	cvt.u64.u32 	%rd10, %r35;
	mul.wide.u32 	%rd72, %r35, 4;
	add.s64 	%rd73, %rd71, %rd72;
	mov.u32 	%r114, -1;
	st.global.u32 	[%rd73], %r114;
	ld.const.u64 	%rd74, [params+152];
	cvta.to.global.u64 	%rd75, %rd74;
	add.s64 	%rd76, %rd75, %rd72;
	mov.u32 	%r115, 2139095039;
	st.global.u32 	[%rd76], %r115;
	ld.const.u64 	%rd11, [params+160];
	setp.eq.s64 	%p20, %rd11, 0;
	@%p20 bra 	$L__BB8_5;

	cvta.to.global.u64 	%rd77, %rd11;
	shl.b64 	%rd78, %rd10, 2;
	add.s64 	%rd79, %rd77, %rd78;
	mov.u32 	%r116, 0;
	st.global.u32 	[%rd79], %r116;

$L__BB8_5:
	ld.const.u64 	%rd80, [params+168];
	cvta.to.global.u64 	%rd81, %rd80;
	shl.b64 	%rd82, %rd10, 2;
	add.s64 	%rd83, %rd81, %rd82;
	mov.u32 	%r117, 0;
	st.global.u32 	[%rd83], %r117;
	ld.const.u64 	%rd12, [params+176];
	setp.eq.s64 	%p21, %rd12, 0;
	@%p21 bra 	$L__BB8_19;

	cvta.to.global.u64 	%rd84, %rd12;
	add.s64 	%rd85, %rd84, %rd10;
	mov.u16 	%rs4, 0;
	st.global.u8 	[%rd85], %rs4;

$L__BB8_19:
	ret;

$L__BB8_7:
	ld.const.u64 	%rd86, [params];
	setp.eq.s64 	%p8, %rd86, 0;
	ld.const.u32 	%r38, [params+64];
	setp.lt.s32 	%p9, %r38, 1;
	or.pred  	%p10, %p8, %p9;
	@%p10 bra 	$L__BB8_3;

$L__BB8_8:
	ld.const.u64 	%rd5, [params+120];
	setp.eq.s64 	%p11, %rd5, 0;
	mov.f32 	%f18, 0f4CBEBC20;
	mov.f32 	%f17, %f18;
	@%p11 bra 	$L__BB8_10;

	cvta.to.global.u64 	%rd16, %rd5;
	mul.wide.u32 	%rd17, %r35, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.f32 	%f17, [%rd18];

$L__BB8_10:
	setp.leu.ftz.f32 	%p12, %f17, 0f00000000;
	@%p12 bra 	$L__BB8_12;

	abs.ftz.f32 	%f7, %f17;
	setp.neu.ftz.f32 	%p13, %f7, 0f7F800000;
	selp.f32 	%f18, %f17, 0f4CBEBC20, %p13;

$L__BB8_12:
	ld.const.u64 	%rd20, [params+72];
	cvta.to.global.u64 	%rd21, %rd20;
	cvt.u64.u32 	%rd6, %r35;
	mul.wide.u32 	%rd22, %r35, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.f32 	%f8, [%rd23];
	ld.const.u64 	%rd24, [params+80];
	cvta.to.global.u64 	%rd25, %rd24;
	add.s64 	%rd26, %rd25, %rd22;
	ld.global.f32 	%f9, [%rd26];
	ld.const.u64 	%rd27, [params+88];
	cvta.to.global.u64 	%rd28, %rd27;
	add.s64 	%rd29, %rd28, %rd22;
	ld.global.f32 	%f10, [%rd29];
	ld.const.u64 	%rd30, [params+96];
	cvta.to.global.u64 	%rd31, %rd30;
	add.s64 	%rd32, %rd31, %rd22;
	ld.global.f32 	%f11, [%rd32];
	ld.const.u64 	%rd33, [params+104];
	cvta.to.global.u64 	%rd34, %rd33;
	add.s64 	%rd35, %rd34, %rd22;
	ld.global.f32 	%f12, [%rd35];
	ld.const.u64 	%rd36, [params+112];
	cvta.to.global.u64 	%rd37, %rd36;
	add.s64 	%rd38, %rd37, %rd22;
	ld.global.f32 	%f13, [%rd38];
	mov.f32 	%f16, 0f00000000;
	mov.u32 	%r72, 255;
	mov.u32 	%r73, 10;
	mov.u32 	%r75, 1;
	mov.u32 	%r77, 5;
	mov.u32 	%r78, -1;
	mov.u32 	%r79, 2139095039;
	mov.u32 	%r109, 0;
	// begin inline asm
	call(%r39,%r40,%r41,%r42,%r43,%r44,%r45,%r46,%r47,%r48,%r49,%r50,%r51,%r52,%r53,%r54,%r55,%r56,%r57,%r58,%r59,%r60,%r61,%r62,%r63,%r64,%r65,%r66,%r67,%r68,%r69,%r70),_optix_trace_typed_32,(%r109,%rd86,%f8,%f9,%f10,%f11,%f12,%f13,%f16,%f18,%f16,%r72,%r73,%r75,%r75,%r109,%r77,%r78,%r79,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109,%r109);
	// end inline asm
	setp.eq.s32 	%p14, %r43, 0;
	setp.eq.s32 	%p15, %r39, -1;
	or.pred  	%p16, %p14, %p15;
	@%p16 bra 	$L__BB8_15;
	bra.uni 	$L__BB8_13;

$L__BB8_15:
	ld.const.u64 	%rd54, [params+144];
	cvta.to.global.u64 	%rd55, %rd54;
	shl.b64 	%rd56, %rd6, 2;
	add.s64 	%rd57, %rd55, %rd56;
	st.global.u32 	[%rd57], %r78;
	ld.const.u64 	%rd58, [params+152];
	cvta.to.global.u64 	%rd59, %rd58;
	add.s64 	%rd60, %rd59, %rd56;
	st.global.u32 	[%rd60], %r79;
	ld.const.u64 	%rd8, [params+160];
	setp.eq.s64 	%p18, %rd8, 0;
	@%p18 bra 	$L__BB8_17;

	cvta.to.global.u64 	%rd61, %rd8;
	add.s64 	%rd63, %rd61, %rd56;
	mov.u32 	%r112, 0;
	st.global.u32 	[%rd63], %r112;

$L__BB8_17:
	ld.const.u64 	%rd64, [params+168];
	cvta.to.global.u64 	%rd65, %rd64;
	add.s64 	%rd67, %rd65, %rd56;
	mov.u32 	%r113, 0;
	st.global.u32 	[%rd67], %r113;
	ld.const.u64 	%rd9, [params+176];
	setp.eq.s64 	%p19, %rd9, 0;
	@%p19 bra 	$L__BB8_19;

	cvta.to.global.u64 	%rd68, %rd9;
	add.s64 	%rd69, %rd68, %rd6;
	mov.u16 	%rs3, 0;
	st.global.u8 	[%rd69], %rs3;
	bra.uni 	$L__BB8_19;

$L__BB8_13:
	ld.const.u64 	%rd39, [params+144];
	cvta.to.global.u64 	%rd40, %rd39;
	shl.b64 	%rd41, %rd6, 2;
	add.s64 	%rd42, %rd40, %rd41;
	st.global.u32 	[%rd42], %r39;
	ld.const.u64 	%rd43, [params+152];
	cvta.to.global.u64 	%rd44, %rd43;
	add.s64 	%rd45, %rd44, %rd41;
	st.global.u32 	[%rd45], %r40;
	ld.const.u64 	%rd46, [params+160];
	cvta.to.global.u64 	%rd47, %rd46;
	add.s64 	%rd48, %rd47, %rd41;
	st.global.u32 	[%rd48], %r41;
	ld.const.u64 	%rd49, [params+168];
	cvta.to.global.u64 	%rd50, %rd49;
	add.s64 	%rd51, %rd50, %rd41;
	st.global.u32 	[%rd51], %r42;
	ld.const.u64 	%rd7, [params+176];
	setp.eq.s64 	%p17, %rd7, 0;
	@%p17 bra 	$L__BB8_19;

	cvta.to.global.u64 	%rd52, %rd7;
	add.s64 	%rd53, %rd52, %rd6;
	mov.u16 	%rs2, 1;
	st.global.u8 	[%rd53], %rs2;
	bra.uni 	$L__BB8_19;

}
	// .globl	__raygen__edge_topk_point
.visible .entry __raygen__edge_topk_point()
{
	.local .align 16 .b8 	__local_depot9[64];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<43>;
	.reg .b16 	%rs<23>;
	.reg .f32 	%f<42>;
	.reg .b32 	%r<226>;
	.reg .b64 	%rd<95>;


	mov.u64 	%SPL, __local_depot9;
	add.u64 	%rd1, %SPL, 0;
	add.u64 	%rd2, %SPL, 32;
	// begin inline asm
	call (%r18), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.v2.u32 	{%r19, %r20}, [params+136];
	setp.ge.u32 	%p1, %r18, %r19;
	add.s32 	%r3, %r20, -1;
	setp.gt.u32 	%p2, %r3, 15;
	or.pred  	%p3, %p2, %p1;
	@%p3 bra 	$L__BB9_52;

	mul.lo.s32 	%r22, %r20, %r18;
	ld.const.u64 	%rd55, [params+144];
	cvta.to.global.u64 	%rd3, %rd55;
	ld.const.u64 	%rd56, [params+152];
	cvta.to.global.u64 	%rd4, %rd56;
	ld.const.u64 	%rd57, [params+168];
	cvta.to.global.u64 	%rd5, %rd57;
	ld.const.u64 	%rd58, [params+176];
	cvta.to.global.u64 	%rd6, %rd58;
	cvt.s64.s32 	%rd7, %r22;
	mul.wide.s32 	%rd59, %r22, 4;
	add.s64 	%rd8, %rd3, %rd59;
	mov.u32 	%r23, -1;
	st.global.u32 	[%rd8], %r23;
	add.s64 	%rd9, %rd4, %rd59;
	mov.u32 	%r24, 2139095039;
	st.global.u32 	[%rd9], %r24;
	add.s64 	%rd10, %rd5, %rd59;
	mov.u32 	%r25, 0;
	st.global.u32 	[%rd10], %r25;
	add.s64 	%rd11, %rd6, %rd7;
	mov.u16 	%rs1, 0;
	st.global.u8 	[%rd11], %rs1;
	setp.lt.s32 	%p4, %r20, 2;
	@%p4 bra 	$L__BB9_3;

	st.global.u32 	[%rd8+4], %r23;
	st.global.u32 	[%rd9+4], %r24;
	st.global.u32 	[%rd10+4], %r25;
	st.global.u8 	[%rd11+1], %rs1;

$L__BB9_3:
	setp.lt.s32 	%p5, %r20, 3;
	@%p5 bra 	$L__BB9_5;

	mov.u32 	%r29, -1;
	st.global.u32 	[%rd8+8], %r29;
	mov.u32 	%r30, 2139095039;
	st.global.u32 	[%rd9+8], %r30;
	mov.u32 	%r31, 0;
	st.global.u32 	[%rd10+8], %r31;
	mov.u16 	%rs3, 0;
	st.global.u8 	[%rd11+2], %rs3;

$L__BB9_5:
	setp.lt.s32 	%p6, %r20, 4;
	@%p6 bra 	$L__BB9_7;

	mov.u32 	%r32, -1;
	st.global.u32 	[%rd8+12], %r32;
	mov.u32 	%r33, 2139095039;
	st.global.u32 	[%rd9+12], %r33;
	mov.u32 	%r34, 0;
	st.global.u32 	[%rd10+12], %r34;
	mov.u16 	%rs4, 0;
	st.global.u8 	[%rd11+3], %rs4;

$L__BB9_7:
	setp.lt.s32 	%p7, %r20, 5;
	@%p7 bra 	$L__BB9_9;

	mov.u32 	%r35, -1;
	st.global.u32 	[%rd8+16], %r35;
	mov.u32 	%r36, 2139095039;
	st.global.u32 	[%rd9+16], %r36;
	mov.u32 	%r37, 0;
	st.global.u32 	[%rd10+16], %r37;
	mov.u16 	%rs5, 0;
	st.global.u8 	[%rd11+4], %rs5;

$L__BB9_9:
	setp.lt.s32 	%p8, %r20, 6;
	@%p8 bra 	$L__BB9_11;

	mov.u32 	%r38, -1;
	st.global.u32 	[%rd8+20], %r38;
	mov.u32 	%r39, 2139095039;
	st.global.u32 	[%rd9+20], %r39;
	mov.u32 	%r40, 0;
	st.global.u32 	[%rd10+20], %r40;
	mov.u16 	%rs6, 0;
	st.global.u8 	[%rd11+5], %rs6;

$L__BB9_11:
	setp.lt.s32 	%p9, %r20, 7;
	@%p9 bra 	$L__BB9_13;

	mov.u32 	%r41, -1;
	st.global.u32 	[%rd8+24], %r41;
	mov.u32 	%r42, 2139095039;
	st.global.u32 	[%rd9+24], %r42;
	mov.u32 	%r43, 0;
	st.global.u32 	[%rd10+24], %r43;
	mov.u16 	%rs7, 0;
	st.global.u8 	[%rd11+6], %rs7;

$L__BB9_13:
	setp.lt.s32 	%p10, %r20, 8;
	@%p10 bra 	$L__BB9_15;

	mov.u32 	%r44, -1;
	st.global.u32 	[%rd8+28], %r44;
	mov.u32 	%r45, 2139095039;
	st.global.u32 	[%rd9+28], %r45;
	mov.u32 	%r46, 0;
	st.global.u32 	[%rd10+28], %r46;
	mov.u16 	%rs8, 0;
	st.global.u8 	[%rd11+7], %rs8;

$L__BB9_15:
	setp.lt.s32 	%p11, %r20, 9;
	@%p11 bra 	$L__BB9_17;

	mov.u32 	%r47, -1;
	st.global.u32 	[%rd8+32], %r47;
	mov.u32 	%r48, 2139095039;
	st.global.u32 	[%rd9+32], %r48;
	mov.u32 	%r49, 0;
	st.global.u32 	[%rd10+32], %r49;
	mov.u16 	%rs9, 0;
	st.global.u8 	[%rd11+8], %rs9;

$L__BB9_17:
	setp.lt.s32 	%p12, %r20, 10;
	@%p12 bra 	$L__BB9_19;

	mov.u32 	%r50, -1;
	st.global.u32 	[%rd8+36], %r50;
	mov.u32 	%r51, 2139095039;
	st.global.u32 	[%rd9+36], %r51;
	mov.u32 	%r52, 0;
	st.global.u32 	[%rd10+36], %r52;
	mov.u16 	%rs10, 0;
	st.global.u8 	[%rd11+9], %rs10;

$L__BB9_19:
	setp.lt.s32 	%p13, %r20, 11;
	@%p13 bra 	$L__BB9_21;

	mov.u32 	%r53, -1;
	st.global.u32 	[%rd8+40], %r53;
	mov.u32 	%r54, 2139095039;
	st.global.u32 	[%rd9+40], %r54;
	mov.u32 	%r55, 0;
	st.global.u32 	[%rd10+40], %r55;
	mov.u16 	%rs11, 0;
	st.global.u8 	[%rd11+10], %rs11;

$L__BB9_21:
	setp.lt.s32 	%p14, %r20, 12;
	@%p14 bra 	$L__BB9_23;

	mov.u32 	%r56, -1;
	st.global.u32 	[%rd8+44], %r56;
	mov.u32 	%r57, 2139095039;
	st.global.u32 	[%rd9+44], %r57;
	mov.u32 	%r58, 0;
	st.global.u32 	[%rd10+44], %r58;
	mov.u16 	%rs12, 0;
	st.global.u8 	[%rd11+11], %rs12;

$L__BB9_23:
	setp.lt.s32 	%p15, %r20, 13;
	@%p15 bra 	$L__BB9_25;

	mov.u32 	%r59, -1;
	st.global.u32 	[%rd8+48], %r59;
	mov.u32 	%r60, 2139095039;
	st.global.u32 	[%rd9+48], %r60;
	mov.u32 	%r61, 0;
	st.global.u32 	[%rd10+48], %r61;
	mov.u16 	%rs13, 0;
	st.global.u8 	[%rd11+12], %rs13;

$L__BB9_25:
	setp.lt.s32 	%p16, %r20, 14;
	@%p16 bra 	$L__BB9_27;

	mov.u32 	%r62, -1;
	st.global.u32 	[%rd8+52], %r62;
	mov.u32 	%r63, 2139095039;
	st.global.u32 	[%rd9+52], %r63;
	mov.u32 	%r64, 0;
	st.global.u32 	[%rd10+52], %r64;
	mov.u16 	%rs14, 0;
	st.global.u8 	[%rd11+13], %rs14;

$L__BB9_27:
	setp.lt.s32 	%p17, %r20, 15;
	@%p17 bra 	$L__BB9_29;

	mov.u32 	%r65, -1;
	st.global.u32 	[%rd8+56], %r65;
	mov.u32 	%r66, 2139095039;
	st.global.u32 	[%rd9+56], %r66;
	mov.u32 	%r67, 0;
	st.global.u32 	[%rd10+56], %r67;
	mov.u16 	%rs15, 0;
	st.global.u8 	[%rd11+14], %rs15;

$L__BB9_29:
	setp.lt.s32 	%p18, %r20, 16;
	@%p18 bra 	$L__BB9_31;

	mov.u32 	%r68, -1;
	st.global.u32 	[%rd8+60], %r68;
	mov.u32 	%r69, 2139095039;
	st.global.u32 	[%rd9+60], %r69;
	mov.u32 	%r70, 0;
	st.global.u32 	[%rd10+60], %r70;
	mov.u16 	%rs16, 0;
	st.global.u8 	[%rd11+15], %rs16;

$L__BB9_31:
	ld.const.u64 	%rd12, [params+128];
	setp.eq.s64 	%p19, %rd12, 0;
	@%p19 bra 	$L__BB9_33;

	cvta.to.global.u64 	%rd60, %rd12;
	cvt.u64.u32 	%rd61, %r18;
	add.s64 	%rd62, %rd60, %rd61;
	ld.global.u8 	%rs17, [%rd62];
	setp.eq.s16 	%p20, %rs17, 0;
	ld.const.u64 	%rd82, [params];
	setp.eq.s64 	%p21, %rd82, 0;
	or.pred  	%p22, %p20, %p21;
	ld.const.u32 	%r71, [params+64];
	setp.lt.s32 	%p23, %r71, 1;
	or.pred  	%p24, %p22, %p23;
	@%p24 bra 	$L__BB9_52;
	bra.uni 	$L__BB9_34;

$L__BB9_33:
	ld.const.u64 	%rd82, [params];
	setp.eq.s64 	%p25, %rd82, 0;
	ld.const.u32 	%r72, [params+64];
	setp.lt.s32 	%p26, %r72, 1;
	or.pred  	%p27, %p25, %p26;
	@%p27 bra 	$L__BB9_52;

$L__BB9_34:
	ld.const.u64 	%rd63, [params+72];
	cvta.to.global.u64 	%rd64, %rd63;
	mul.wide.u32 	%rd65, %r18, 4;
	add.s64 	%rd66, %rd64, %rd65;
	ld.global.f32 	%f1, [%rd66];
	ld.const.u64 	%rd67, [params+80];
	cvta.to.global.u64 	%rd68, %rd67;
	add.s64 	%rd69, %rd68, %rd65;
	ld.global.f32 	%f2, [%rd69];
	ld.const.u64 	%rd70, [params+88];
	cvta.to.global.u64 	%rd71, %rd70;
	add.s64 	%rd72, %rd71, %rd65;
	ld.global.f32 	%f3, [%rd72];
	@%p11 bra 	$L__BB9_36;
	bra.uni 	$L__BB9_35;

$L__BB9_36:
	mov.f32 	%f28, 0fBF800000;
	mov.f32 	%f30, 0f3727C5AC;
	m)PTX_CHUNK"
R"PTX_CHUNK(ov.f32 	%f31, 0f00000000;
	mov.u32 	%r177, 255;
	mov.u32 	%r178, 10;
	mov.u32 	%r179, 2;
	mov.u32 	%r180, 1;
	mov.u32 	%r182, 16;
	mov.u32 	%r190, -1;
	mov.u32 	%r198, 2139095039;
	mov.u32 	%r224, 0;
	// begin inline asm
	call(%r144,%r145,%r146,%r147,%r148,%r149,%r150,%r151,%r152,%r153,%r154,%r155,%r156,%r157,%r158,%r159,%r160,%r161,%r162,%r163,%r164,%r165,%r166,%r167,%r168,%r169,%r170,%r171,%r172,%r173,%r174,%r175),_optix_trace_typed_32,(%r224,%rd82,%f1,%f2,%f3,%f31,%f31,%f28,%f31,%f30,%f31,%r177,%r178,%r179,%r180,%r224,%r182,%r190,%r190,%r190,%r190,%r190,%r190,%r190,%r190,%r198,%r198,%r198,%r198,%r198,%r198,%r198,%r198,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224,%r224);
	// end inline asm
	st.local.v4.u32 	[%rd1], {%r144, %r145, %r146, %r147};
	st.local.v4.u32 	[%rd1+16], {%r148, %r149, %r150, %r151};
	st.local.v4.u32 	[%rd2], {%r152, %r153, %r154, %r155};
	st.local.v4.u32 	[%rd2+16], {%r156, %r157, %r158, %r159};
	and.b32  	%r225, %r20, 3;
	setp.lt.u32 	%p29, %r3, 3;
	@%p29 bra 	$L__BB9_47;

	sub.s32 	%r223, %r20, %r225;
	shl.b64 	%rd75, %rd7, 2;
	add.s64 	%rd76, %rd75, 8;
	add.s64 	%rd86, %rd3, %rd76;
	add.s64 	%rd85, %rd4, %rd76;
	add.s64 	%rd84, %rd5, %rd76;
	add.s64 	%rd83, %rd11, 1;
	mov.u32 	%r224, 0;
	mov.u64 	%rd87, %rd2;
	mov.u64 	%rd88, %rd1;

$L__BB9_38:
	ld.local.u32 	%r8, [%rd88];
	setp.eq.s32 	%p30, %r8, -1;
	st.global.u32 	[%rd86+-8], %r8;
	mov.f32 	%f38, 0f7F7FFFFF;
	mov.f32 	%f37, %f38;
	@%p30 bra 	$L__BB9_40;

	ld.local.f32 	%f37, [%rd87];

$L__BB9_40:
	add.s64 	%rd26, %rd85, -8;
	st.global.f32 	[%rd85+-8], %f37;
	add.s64 	%rd27, %rd84, -8;
	mov.u32 	%r217, 0;
	st.global.u32 	[%rd84+-8], %r217;
	setp.ne.s32 	%p31, %r8, -1;
	selp.u16 	%rs18, 1, 0, %p31;
	add.s64 	%rd28, %rd83, -1;
	st.global.u8 	[%rd83+-1], %rs18;
	ld.local.u32 	%r9, [%rd88+4];
	setp.eq.s32 	%p32, %r9, -1;
	st.global.u32 	[%rd86+-4], %r9;
	@%p32 bra 	$L__BB9_42;

	ld.local.f32 	%f38, [%rd87+4];

$L__BB9_42:
	st.global.f32 	[%rd26+4], %f38;
	st.global.u32 	[%rd27+4], %r217;
	setp.ne.s32 	%p33, %r9, -1;
	selp.u16 	%rs19, 1, 0, %p33;
	st.global.u8 	[%rd28+1], %rs19;
	ld.local.u32 	%r10, [%rd88+8];
	setp.eq.s32 	%p34, %r10, -1;
	st.global.u32 	[%rd86], %r10;
	mov.f32 	%f40, 0f7F7FFFFF;
	mov.f32 	%f39, %f40;
	@%p34 bra 	$L__BB9_44;

	ld.local.f32 	%f39, [%rd87+8];

$L__BB9_44:
	st.global.f32 	[%rd26+8], %f39;
	mov.u32 	%r219, 0;
	st.global.u32 	[%rd27+8], %r219;
	setp.ne.s32 	%p35, %r10, -1;
	selp.u16 	%rs20, 1, 0, %p35;
	st.global.u8 	[%rd28+2], %rs20;
	ld.local.u32 	%r11, [%rd88+12];
	setp.eq.s32 	%p36, %r11, -1;
	st.global.u32 	[%rd86+4], %r11;
	@%p36 bra 	$L__BB9_46;

	ld.local.f32 	%f40, [%rd87+12];

$L__BB9_46:
	add.s64 	%rd88, %rd88, 16;
	st.global.f32 	[%rd26+12], %f40;
	st.global.u32 	[%rd27+12], %r219;
	setp.ne.s32 	%p37, %r11, -1;
	selp.u16 	%rs21, 1, 0, %p37;
	st.global.u8 	[%rd28+3], %rs21;
	add.s32 	%r224, %r224, 4;
	add.s64 	%rd87, %rd87, 16;
	add.s64 	%rd86, %rd86, 16;
	add.s64 	%rd85, %rd85, 16;
	add.s64 	%rd84, %rd84, 16;
	add.s64 	%rd83, %rd83, 4;
	add.s32 	%r223, %r223, -4;
	setp.ne.s32 	%p38, %r223, 0;
	@%p38 bra 	$L__BB9_38;

$L__BB9_47:
	setp.eq.s32 	%p39, %r225, 0;
	@%p39 bra 	$L__BB9_52;

	cvt.s64.s32 	%rd78, %r224;
	add.s64 	%rd79, %rd78, %rd7;
	add.s64 	%rd94, %rd6, %rd79;
	shl.b64 	%rd80, %rd79, 2;
	add.s64 	%rd93, %rd5, %rd80;
	add.s64 	%rd92, %rd4, %rd80;
	add.s64 	%rd91, %rd3, %rd80;
	mul.wide.s32 	%rd81, %r224, 4;
	add.s64 	%rd90, %rd2, %rd81;
	add.s64 	%rd89, %rd1, %rd81;

$L__BB9_49:
	.pragma "nounroll";
	ld.local.u32 	%r16, [%rd89];
	setp.eq.s32 	%p40, %r16, -1;
	st.global.u32 	[%rd91], %r16;
	mov.f32 	%f41, 0f7F7FFFFF;
	@%p40 bra 	$L__BB9_51;

	ld.local.f32 	%f41, [%rd90];

$L__BB9_51:
	st.global.f32 	[%rd92], %f41;
	mov.u32 	%r221, 0;
	st.global.u32 	[%rd93], %r221;
	setp.ne.s32 	%p41, %r16, -1;
	selp.u16 	%rs22, 1, 0, %p41;
	st.global.u8 	[%rd94], %rs22;
	add.s64 	%rd94, %rd94, 1;
	add.s64 	%rd93, %rd93, 4;
	add.s64 	%rd92, %rd92, 4;
	add.s64 	%rd91, %rd91, 4;
	add.s64 	%rd90, %rd90, 4;
	add.s64 	%rd89, %rd89, 4;
	add.s32 	%r225, %r225, -1;
	setp.ne.s32 	%p42, %r225, 0;
	@%p42 bra 	$L__BB9_49;
	bra.uni 	$L__BB9_52;

$L__BB9_35:
	mov.f32 	%f19, 0fBF800000;
	mov.f32 	%f21, 0f3727C5AC;
	mov.f32 	%f22, 0f00000000;
	mov.u32 	%r106, 255;
	mov.u32 	%r107, 10;
	mov.u32 	%r108, 2;
	mov.u32 	%r111, 1;
	mov.u32 	%r143, 0;
	// begin inline asm
	call(%r73,%r74,%r75,%r76,%r77,%r78,%r79,%r80,%r81,%r82,%r83,%r84,%r85,%r86,%r87,%r88,%r89,%r90,%r91,%r92,%r93,%r94,%r95,%r96,%r97,%r98,%r99,%r100,%r101,%r102,%r103,%r104),_optix_trace_typed_32,(%r143,%rd82,%f1,%f2,%f3,%f22,%f22,%f19,%f22,%f21,%f22,%r106,%r107,%r108,%r111,%r143,%r111,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143,%r143);
	// end inline asm

$L__BB9_52:
	ret;

}

)PTX_CHUNK"
;
static const size_t edge_optix_ptx_size = 52898;
