// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char reflection_trace_ptx[] = R"PTX(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__closesthit__reflection
.const .align 8 .b8 params[328];

.visible .entry __closesthit__reflection()
{
	.reg .f32 	%f<4>;
	.reg .b32 	%r<15>;


	// begin inline asm
	call (%f1), _optix_get_ray_tmax, ();
	// end inline asm
	mov.b32 	%r6, %f1;
	// begin inline asm
	call (%f2, %f3), _optix_get_triangle_barycentrics, ();
	// end inline asm
	mov.b32 	%r8, %f2;
	mov.b32 	%r10, %f3;
	// begin inline asm
	call (%r1), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r2), _optix_read_instance_id, ();
	// end inline asm
	mov.u32 	%r3, 0;
	mov.u32 	%r5, 1;
	// begin inline asm
	call _optix_set_payload, (%r3, %r5);
	// end inline asm
	// begin inline asm
	call _optix_set_payload, (%r5, %r6);
	// end inline asm
	mov.u32 	%r7, 2;
	// begin inline asm
	call _optix_set_payload, (%r7, %r8);
	// end inline asm
	mov.u32 	%r9, 3;
	// begin inline asm
	call _optix_set_payload, (%r9, %r10);
	// end inline asm
	mov.u32 	%r11, 4;
	// begin inline asm
	call _optix_set_payload, (%r11, %r1);
	// end inline asm
	mov.u32 	%r13, 5;
	// begin inline asm
	call _optix_set_payload, (%r13, %r2);
	// end inline asm
	ret;

}
	// .globl	__miss__reflection
.visible .entry __miss__reflection()
{
	.reg .b32 	%r<3>;


	mov.u32 	%r2, 0;
	// begin inline asm
	call _optix_set_payload, (%r2, %r2);
	// end inline asm
	ret;

}
	// .globl	__raygen__reflection_trace
.visible .entry __raygen__reflection_trace()
{
	.reg .pred 	%p<22>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<156>;
	.reg .b32 	%r<271>;
	.reg .b64 	%rd<126>;


	// begin inline asm
	call (%r79), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r80, [params+200];
	setp.ge.u32 	%p1, %r79, %r80;
	@%p1 bra 	$L__BB2_27;

	ld.const.u64 	%rd1, [params+192];
	setp.eq.s64 	%p2, %rd1, 0;
	@%p2 bra 	$L__BB2_4;

	cvta.to.global.u64 	%rd34, %rd1;
	cvt.u64.u32 	%rd2, %r79;
	add.s64 	%rd35, %rd34, %rd2;
	ld.global.u8 	%rs1, [%rd35];
	setp.ne.s16 	%p3, %rs1, 0;
	@%p3 bra 	$L__BB2_4;
	bra.uni 	$L__BB2_3;

$L__BB2_4:
	cvt.u64.u32 	%rd3, %r79;
	ld.const.u32 	%r2, [params+204];
	ld.const.u64 	%rd40, [params+136];
	cvta.to.global.u64 	%rd41, %rd40;
	mul.wide.u32 	%rd42, %r79, 4;
	add.s64 	%rd43, %rd41, %rd42;
	ld.const.u64 	%rd44, [params+144];
	cvta.to.global.u64 	%rd45, %rd44;
	add.s64 	%rd46, %rd45, %rd42;
	ld.const.u64 	%rd47, [params+152];
	cvta.to.global.u64 	%rd48, %rd47;
	add.s64 	%rd49, %rd48, %rd42;
	ld.global.f32 	%f139, [%rd43];
	ld.global.f32 	%f140, [%rd46];
	ld.global.f32 	%f141, [%rd49];
	setp.lt.s32 	%p4, %r2, 1;
	mov.u32 	%r270, 0;
	@%p4 bra 	$L__BB2_26;

	ld.const.u64 	%rd50, [params+160];
	ld.const.u64 	%rd51, [params+168];
	ld.const.u64 	%rd52, [params+176];
	cvta.to.global.u64 	%rd53, %rd50;
	shl.b64 	%rd54, %rd3, 2;
	add.s64 	%rd55, %rd53, %rd54;
	cvta.to.global.u64 	%rd56, %rd51;
	add.s64 	%rd57, %rd56, %rd54;
	cvta.to.global.u64 	%rd58, %rd52;
	add.s64 	%rd59, %rd58, %rd54;
	ld.const.u64 	%rd60, [params+184];
	cvta.to.global.u64 	%rd61, %rd60;
	add.s64 	%rd4, %rd61, %rd54;
	ld.const.u64 	%rd5, [params];
	ld.const.u64 	%rd6, [params+8];
	ld.const.v2.u32 	{%r84, %r85}, [params+128];
	mov.u32 	%r270, 0;
	ld.const.u64 	%rd62, [params+120];
	cvta.to.global.u64 	%rd7, %rd62;
	ld.const.u64 	%rd63, [params+24];
	cvta.to.global.u64 	%rd8, %rd63;
	ld.const.u64 	%rd64, [params+32];
	cvta.to.global.u64 	%rd9, %rd64;
	ld.const.u64 	%rd65, [params+40];
	cvta.to.global.u64 	%rd10, %rd65;
	ld.const.u64 	%rd66, [params+48];
	cvta.to.global.u64 	%rd11, %rd66;
	ld.const.u64 	%rd67, [params+56];
	cvta.to.global.u64 	%rd12, %rd67;
	ld.const.u64 	%rd68, [params+64];
	cvta.to.global.u64 	%rd13, %rd68;
	ld.const.u64 	%rd69, [params+72];
	cvta.to.global.u64 	%rd14, %rd69;
	ld.const.u64 	%rd70, [params+80];
	cvta.to.global.u64 	%rd15, %rd70;
	ld.const.u64 	%rd71, [params+88];
	cvta.to.global.u64 	%rd16, %rd71;
	ld.const.u64 	%rd72, [params+96];
	cvta.to.global.u64 	%rd17, %rd72;
	ld.const.u64 	%rd73, [params+104];
	cvta.to.global.u64 	%rd18, %rd73;
	ld.const.u64 	%rd74, [params+112];
	cvta.to.global.u64 	%rd19, %rd74;
	ld.const.u64 	%rd75, [params+216];
	cvta.to.global.u64 	%rd20, %rd75;
	ld.const.u64 	%rd76, [params+224];
	cvta.to.global.u64 	%rd21, %rd76;
	ld.const.u64 	%rd77, [params+232];
	cvta.to.global.u64 	%rd22, %rd77;
	ld.const.u64 	%rd78, [params+240];
	cvta.to.global.u64 	%rd23, %rd78;
	ld.const.u64 	%rd79, [params+248];
	cvta.to.global.u64 	%rd24, %rd79;
	ld.const.u64 	%rd80, [params+256];
	cvta.to.global.u64 	%rd25, %rd80;
	ld.const.u64 	%rd81, [params+264];
	cvta.to.global.u64 	%rd26, %rd81;
	ld.const.u64 	%rd82, [params+272];
	cvta.to.global.u64 	%rd27, %rd82;
	ld.const.u64 	%rd83, [params+280];
	cvta.to.global.u64 	%rd28, %rd83;
	ld.const.u64 	%rd84, [params+288];
	cvta.to.global.u64 	%rd29, %rd84;
	ld.const.u64 	%rd85, [params+296];
	cvta.to.global.u64 	%rd30, %rd85;
	ld.const.u64 	%rd86, [params+304];
	cvta.to.global.u64 	%rd31, %rd86;
	ld.const.u64 	%rd87, [params+312];
	cvta.to.global.u64 	%rd32, %rd87;
	ld.const.u64 	%rd88, [params+320];
	cvta.to.global.u64 	%rd33, %rd88;
	ld.global.f32 	%f138, [%rd59];
	ld.global.f32 	%f137, [%rd57];
	ld.global.f32 	%f136, [%rd55];
	mul.lo.s32 	%r6, %r2, %r79;
	mov.f32 	%f142, %f139;
	mov.f32 	%f143, %f140;
	mov.f32 	%f144, %f141;

$L__BB2_6:
	setp.ne.s32 	%p5, %r270, 0;
	mov.f32 	%f145, 0f4CBEBC20;
	@%p5 bra 	$L__BB2_8;

	ld.global.f32 	%f145, [%rd4];

$L__BB2_8:
	abs.ftz.f32 	%f68, %f145;
	setp.geu.ftz.f32 	%p6, %f68, 0f7F800000;
	selp.f32 	%f21, 0f4CBEBC20, %f145, %p6;
	setp.eq.s64 	%p7, %rd5, 0;
	mov.u32 	%r262, 0;
	mov.u32 	%r258, 1287568416;
	mov.u32 	%r261, %r262;
	mov.u32 	%r260, %r262;
	mov.u32 	%r259, %r262;
	mov.u32 	%r257, %r262;
	@%p7 bra 	$L__BB2_10;

	mov.f32 	%f75, 0f3727C5AC;
	mov.f32 	%f77, 0f00000000;
	mov.u32 	%r125, 255;
	mov.u32 	%r128, 1;
	mov.u32 	%r130, 6;
	mov.u32 	%r132, 1287568416;
	mov.u32 	%r162, 0;
	// begin inline asm
	call(%r257,%r258,%r259,%r260,%r261,%r262,%r98,%r99,%r100,%r101,%r102,%r103,%r104,%r105,%r106,%r107,%r108,%r109,%r110,%r111,%r112,%r113,%r114,%r115,%r116,%r117,%r118,%r119,%r120,%r121,%r122,%r123),_optix_trace_typed_32,(%r162,%rd5,%f139,%f140,%f141,%f136,%f137,%f138,%f75,%f21,%f77,%r125,%r128,%r162,%r128,%r162,%r130,%r162,%r132,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162,%r162);
	// end inline asm

$L__BB2_10:
	ld.const.u32 	%r242, [params+16];
	setp.eq.s32 	%p8, %r242, 0;
	@%p8 bra 	$L__BB2_18;

	setp.eq.s64 	%p9, %rd6, 0;
	mov.u32 	%r251, 0;
	mov.u32 	%r255, 1287568416;
	mov.u32 	%r252, %r251;
	mov.u32 	%r253, %r251;
	mov.u32 	%r254, %r251;
	mov.u32 	%r256, %r251;
	@%p9 bra 	$L__BB2_13;

	mov.f32 	%f84, 0f3727C5AC;
	mov.f32 	%f86, 0f00000000;
	mov.u32 	%r202, 255;
	mov.u32 	%r205, 1;
	mov.u32 	%r207, 6;
	mov.u32 	%r209, 1287568416;
	mov.u32 	%r239, 0;
	// begin inline asm
	call(%r256,%r255,%r254,%r253,%r252,%r251,%r175,%r176,%r177,%r178,%r179,%r180,%r181,%r182,%r183,%r184,%r185,%r186,%r187,%r188,%r189,%r190,%r191,%r192,%r193,%r194,%r195,%r196,%r197,%r198,%r199,%r200),_optix_trace_typed_32,(%r239,%rd6,%f139,%f140,%f141,%f136,%f137,%f138,%f84,%f21,%f86,%r202,%r205,%r239,%r205,%r239,%r207,%r239,%r209,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239,%r239);
	// end inline asm

$L__BB2_13:
	setp.eq.s32 	%p10, %r257, 0;
	@%p10 bra 	$L__BB2_17;

	setp.eq.s32 	%p11, %r256, 0;
	@%p11 bra 	$L__BB2_18;

	mov.b32 	%f87, %r255;
	mov.b32 	%f88, %r258;
	setp.lt.ftz.f32 	%p12, %f87, %f88;
	@%p12 bra 	$L__BB2_16;
	bra.uni 	$L__BB2_18;

$L__BB2_16:
	mov.u32 	%r257, %r256;
	mov.u32 	%r258, %r255;
	mov.u32 	%r259, %r254;
	mov.u32 	%r260, %r253;
	mov.u32 	%r261, %r252;
	mov.u32 	%r262, %r251;
	bra.uni 	$L__BB2_18;

$L__BB2_17:
	mov.u32 	%r257, %r256;
	mov.u32 	%r258, %r255;
	mov.u32 	%r259, %r254;
	mov.u32 	%r260, %r253;
	mov.u32 	%r261, %r252;
	mov.u32 	%r262, %r251;

$L__BB2_18:
	setp.eq.s32 	%p13, %r257, 0;
	@%p13 bra 	$L__BB2_26;

	setp.lt.s32 	%p14, %r262, 0;
	setp.ge.s32 	%p15, %r262, %r84;
	mov.u32 	%r269, 0;
	or.pred  	%p16, %p14, %p15;
	@%p16 bra 	$L__BB2_21;

	mul.wide.s32 	%rd91, %r262, 4;
	add.s64 	%rd92, %rd7, %rd91;
	ld.global.u32 	%r269, [%rd92];

$L__BB2_21:
	mov.b32 	%f92, %r258;
	fma.rn.ftz.f32 	%f148, %f136, %f92, %f139;
	fma.rn.ftz.f32 	%f147, %f137, %f92, %f140;
	fma.rn.ftz.f32 	%f146, %f138, %f92, %f141;
	add.s32 	%r76, %r269, %r261;
	setp.lt.s32 	%p17, %r76, 0;
	setp.ge.s32 	%p18, %r76, %r85;
	mov.f32 	%f154, 0f00000000;
	mov.f32 	%f155, 0f3F800000;
	or.pred  	%p19, %p17, %p18;
	mov.f32 	%f153, %f154;
	@%p19 bra 	$L__BB2_23;

	mov.b32 	%f93, %r259;
	mov.b32 	%f94, %r260;
	mul.wide.s32 	%rd93, %r76, 4;
	add.s64 	%rd94, %rd8, %rd93;
	add.s64 	%rd95, %rd9, %rd93;
	add.s64 	%rd96, %rd10, %rd93;
	add.s64 	%rd97, %rd11, %rd93;
	add.s64 	%rd98, %rd12, %rd93;
	add.s64 	%rd99, %rd13, %rd93;
	add.s64 	%rd100, %rd14, %rd93;
	add.s64 	%rd101, %rd15, %rd93;
	add.s64 	%rd102, %rd16, %rd93;
	ld.global.f32 	%f95, [%rd97];
	ld.global.f32 	%f96, [%rd94];
	fma.rn.ftz.f32 	%f97, %f95, %f93, %f96;
	ld.global.f32 	%f98, [%rd100];
	fma.rn.ftz.f32 	%f148, %f98, %f94, %f97;
	ld.global.f32 	%f99, [%rd98];
	ld.global.f32 	%f100, [%rd95];
	fma.rn.ftz.f32 	%f101, %f99, %f93, %f100;
	ld.global.f32 	%f102, [%rd101];
	fma.rn.ftz.f32 	%f147, %f102, %f94, %f101;
	ld.global.f32 	%f103, [%rd99];
	ld.global.f32 	%f104, [%rd96];
	fma.rn.ftz.f32 	%f105, %f103, %f93, %f104;
	ld.global.f32 	%f106, [%rd102];
	fma.rn.ftz.f32 	%f146, %f106, %f94, %f105;
	add.s64 	%rd103, %rd17, %rd93;
	add.s64 	%rd104, %rd18, %rd93;
	add.s64 	%rd105, %rd19, %rd93;
	ld.global.f32 	%f107, [%rd103];
	ld.global.f32 	%f108, [%rd104];
	mul.ftz.f32 	%f109, %f108, %f108;
	fma.rn.ftz.f32 	%f110, %f107, %f107, %f109;
	ld.global.f32 	%f111, [%rd105];
	fma.rn.ftz.f32 	%f112, %f111, %f111, %f110;
	mov.f32 	%f113, 0f2B8CBCCC;
	max.ftz.f32 	%f114, %f112, %f113;
	rsqrt.approx.ftz.f32 	%f115, %f114;
	mul.ftz.f32 	%f153, %f107, %f115;
	mul.ftz.f32 	%f154, %f108, %f115;
	mul.ftz.f32 	%f155, %f111, %f115;

$L__BB2_23:
	mul.ftz.f32 	%f116, %f136, %f153;
	fma.rn.ftz.f32 	%f117, %f137, %f154, %f116;
	fma.rn.ftz.f32 	%f152, %f138, %f155, %f117;
	setp.leu.ftz.f32 	%p20, %f152, 0f00000000;
	@%p20 bra 	$L__BB2_25;

	neg.ftz.f32 	%f153, %f153;
	neg.ftz.f32 	%f154, %f154;
	neg.ftz.f32 	%f49, %f155;
	mul.ftz.f32 	%f119, %f137, %f154;
	sub.ftz.f32 	%f120, %f119, %f116;
	mul.ftz.f32 	%f121, %f138, %f155;
	sub.ftz.f32 	%f152, %f120, %f121;
	mov.f32 	%f155, %f49;

$L__BB2_25:
	ld.const.u32 	%r243, [params+204];
	sub.ftz.f32 	%f122, %f142, %f148;
	sub.ftz.f32 	%f123, %f143, %f147;
	mul.ftz.f32 	%f124, %f123, %f154;
	fma.rn.ftz.f32 	%f125, %f122, %f153, %f124;
	sub.ftz.f32 	%f126, %f144, %f146;
	fma.rn.ftz.f32 	%f127, %f126, %f155, %f125;
	add.ftz.f32 	%f128, %f127, %f127;
	mul.ftz.f32 	%f129, %f153, %f128;
	mul.ftz.f32 	%f130, %f154, %f128;
	mul.ftz.f32 	%f131, %f155, %f128;
	sub.ftz.f32 	%f142, %f142, %f129;
	sub.ftz.f32 	%f143, %f143, %f130;
	sub.ftz.f32 	%f144, %f144, %f131;
	add.s32 	%r241, %r270, %r6;
	mul.wide.s32 	%rd106, %r241, 4;
	add.s64 	%rd107, %rd20, %rd106;
	st.global.u32 	[%rd107], %r262;
	add.s64 	%rd108, %rd21, %rd106;
	st.global.u32 	[%rd108], %r261;
	add.s64 	%rd109, %rd22, %rd106;
	st.global.u32 	[%rd109], %r258;
	add.s64 	%rd110, %rd23, %rd106;
	st.global.u32 	[%rd110], %r259;
	add.s64 	%rd111, %rd24, %rd106;
	st.global.u32 	[%rd111], %r260;
	add.s64 	%rd112, %rd25, %rd106;
	st.global.f32 	[%rd112], %f148;
	add.s64 	%rd113, %rd26, %rd106;
	st.global.f32 	[%rd113], %f147;
	add.s64 	%rd114, %rd27, %rd106;
	st.global.f32 	[%rd114], %f146;
	add.s64 	%rd115, %rd28, %rd106;
	st.global.f32 	[%rd115], %f153;
	add.s64 	%rd116, %rd29, %rd106;
	st.global.f32 	[%rd116], %f154;
	add.s64 	%rd117, %rd30, %rd106;
	st.global.f32 	[%rd117], %f155;
	add.s64 	%rd118, %rd31, %rd106;
	st.global.f32 	[%rd118], %f142;
	add.s64 	%rd119, %rd32, %rd106;
	st.global.f32 	[%rd119], %f143;
	add.s64 	%rd120, %rd33, %rd106;
	st.global.f32 	[%rd120], %f144;
	add.ftz.f32 	%f132, %f152, %f152;
	mul.ftz.f32 	%f133, %f132, %f153;
	mul.ftz.f32 	%f134, %f132, %f154;
	mul.ftz.f32 	%f135, %f132, %f155;
	sub.ftz.f32 	%f138, %f138, %f135;
	sub.ftz.f32 	%f136, %f136, %f133;
	sub.ftz.f32 	%f137, %f137, %f134;
	fma.rn.ftz.f32 	%f140, %f137, 0f3727C5AC, %f147;
	fma.rn.ftz.f32 	%f139, %f136, 0f3727C5AC, %f148;
	fma.rn.ftz.f32 	%f141, %f138, 0f3727C5AC, %f146;
	add.s32 	%r270, %r270, 1;
	setp.lt.s32 	%p21, %r270, %r243;
	@%p21 bra 	$L__BB2_6;

$L__BB2_26:
	cvt.u64.u32 	%rd125, %r79;
	ld.const.u64 	%rd121, [params+208];
	cvta.to.global.u64 	%rd122, %rd121;
	shl.b64 	%rd123, %rd125, 2;
	add.s64 	%rd124, %rd122, %rd123;
	st.global.u32 	[%rd124], %r270;
	bra.uni 	$L__BB2_27;

$L__BB2_3:
	ld.const.u64 	%rd36, [params+208];
	cvta.to.global.u64 	%rd37, %rd36;
	shl.b64 	%rd38, %rd2, 2;
	add.s64 	%rd39, %rd37, %rd38;
	mov.u32 	%r81, 0;
	st.global.u32 	[%rd39], %r81;

$L__BB2_27:
	ret;

}

)PTX";
static const size_t reflection_trace_ptx_size = 13203;
