// Auto-generated. Do not edit.
#pragma once
#include <cstddef>
static const char reflection_accumulation_ptx[] =
R"PTX_CHUNK(//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_70
.address_size 64

	// .globl	__closesthit__reflection_accumulation
.const .align 8 .b8 params[552];

.visible .entry __closesthit__reflection_accumulation()
{
	.reg .f32 	%f<4>;
	.reg .b32 	%r<15>;


	// begin inline asm
	call (%f1), _optix_get_ray_tmax, ();
	// end inline asm
	mov.b32 	%r6, %f1;
	// begin inline asm
	call (%f2, %f3), _optix_get_triangle_barycentrics, ();
	// end inline asm
	mov.b32 	%r8, %f2;
	mov.b32 	%r10, %f3;
	// begin inline asm
	call (%r1), _optix_read_primitive_idx, ();
	// end inline asm
	// begin inline asm
	call (%r2), _optix_read_instance_id, ();
	// end inline asm
	mov.u32 	%r3, 0;
	mov.u32 	%r5, 1;
	// begin inline asm
	call _optix_set_payload, (%r3, %r5);
	// end inline asm
	// begin inline asm
	call _optix_set_payload, (%r5, %r6);
	// end inline asm
	mov.u32 	%r7, 2;
	// begin inline asm
	call _optix_set_payload, (%r7, %r8);
	// end inline asm
	mov.u32 	%r9, 3;
	// begin inline asm
	call _optix_set_payload, (%r9, %r10);
	// end inline asm
	mov.u32 	%r11, 4;
	// begin inline asm
	call _optix_set_payload, (%r11, %r1);
	// end inline asm
	mov.u32 	%r13, 5;
	// begin inline asm
	call _optix_set_payload, (%r13, %r2);
	// end inline asm
	ret;

}
	// .globl	__miss__reflection_accumulation
.visible .entry __miss__reflection_accumulation()
{
	.reg .b32 	%r<3>;


	mov.u32 	%r2, 0;
	// begin inline asm
	call _optix_set_payload, (%r2, %r2);
	// end inline asm
	ret;

}
	// .globl	__raygen__reflection_accumulation
.visible .entry __raygen__reflection_accumulation()
{
	.reg .pred 	%p<114>;
	.reg .b16 	%rs<9>;
	.reg .f32 	%f<953>;
	.reg .b32 	%r<314>;
	.reg .b64 	%rd<174>;


	// begin inline asm
	call (%r84), _optix_get_launch_index_x, ();
	// end inline asm
	ld.const.u32 	%r85, [params+200];
	setp.ge.u32 	%p4, %r84, %r85;
	@%p4 bra 	$L__BB2_88;

	ld.const.u64 	%rd1, [params+192];
	setp.eq.s64 	%p5, %rd1, 0;
	@%p5 bra 	$L__BB2_3;

	cvta.to.global.u64 	%rd48, %rd1;
	cvt.u64.u32 	%rd49, %r84;
	add.s64 	%rd50, %rd48, %rd49;
	ld.global.u8 	%rs3, [%rd50];
	setp.eq.s16 	%p6, %rs3, 0;
	@%p6 bra 	$L__BB2_88;

$L__BB2_3:
	cvt.u64.u32 	%rd2, %r84;
	ld.const.u64 	%rd51, [params+136];
	cvta.to.global.u64 	%rd52, %rd51;
	mul.wide.u32 	%rd53, %r84, 4;
	add.s64 	%rd54, %rd52, %rd53;
	ld.const.u64 	%rd55, [params+144];
	cvta.to.global.u64 	%rd56, %rd55;
	add.s64 	%rd57, %rd56, %rd53;
	ld.const.u64 	%rd58, [params+152];
	cvta.to.global.u64 	%rd59, %rd58;
	add.s64 	%rd60, %rd59, %rd53;
	ld.global.f32 	%f902, [%rd60];
	ld.global.f32 	%f901, [%rd57];
	ld.global.f32 	%f900, [%rd54];
	ld.const.u64 	%rd61, [params+160];
	cvta.to.global.u64 	%rd62, %rd61;
	add.s64 	%rd63, %rd62, %rd53;
	ld.const.u64 	%rd64, [params+168];
	cvta.to.global.u64 	%rd65, %rd64;
	add.s64 	%rd66, %rd65, %rd53;
	ld.const.u64 	%rd67, [params+176];
	cvta.to.global.u64 	%rd68, %rd67;
	add.s64 	%rd69, %rd68, %rd53;
	ld.global.f32 	%f316, [%rd63];
	ld.global.f32 	%f317, [%rd66];
	mul.ftz.f32 	%f318, %f317, %f317;
	fma.rn.ftz.f32 	%f319, %f316, %f316, %f318;
	ld.global.f32 	%f320, [%rd69];
	fma.rn.ftz.f32 	%f321, %f320, %f320, %f319;
	mov.f32 	%f322, 0f2B8CBCCC;
	max.ftz.f32 	%f323, %f321, %f322;
	rsqrt.approx.ftz.f32 	%f324, %f323;
	mul.ftz.f32 	%f897, %f316, %f324;
	mul.ftz.f32 	%f898, %f317, %f324;
	mul.ftz.f32 	%f899, %f320, %f324;
	ld.const.u64 	%rd70, [params+208];
	cvta.to.global.u64 	%rd71, %rd70;
	add.s64 	%rd72, %rd71, %rd53;
	ld.const.u64 	%rd73, [params+216];
	cvta.to.global.u64 	%rd74, %rd73;
	add.s64 	%rd75, %rd74, %rd53;
	ld.const.u64 	%rd76, [params+224];
	cvta.to.global.u64 	%rd77, %rd76;
	add.s64 	%rd78, %rd77, %rd53;
	ld.global.f32 	%f896, [%rd78];
	ld.global.f32 	%f895, [%rd75];
	ld.global.f32 	%f894, [%rd72];
	ld.const.u64 	%rd79, [params+232];
	cvta.to.global.u64 	%rd80, %rd79;
	add.s64 	%rd81, %rd80, %rd53;
	ld.const.u64 	%rd82, [params+240];
	cvta.to.global.u64 	%rd83, %rd82;
	add.s64 	%rd84, %rd83, %rd53;
	ld.const.u64 	%rd85, [params+248];
	cvta.to.global.u64 	%rd86, %rd85;
	add.s64 	%rd87, %rd86, %rd53;
	ld.global.f32 	%f13, [%rd81];
	ld.global.f32 	%f14, [%rd84];
	mul.ftz.f32 	%f325, %f898, %f14;
	fma.rn.ftz.f32 	%f326, %f897, %f13, %f325;
	ld.global.f32 	%f15, [%rd87];
	fma.rn.ftz.f32 	%f327, %f899, %f15, %f326;
	mul.ftz.f32 	%f328, %f897, %f327;
	mul.ftz.f32 	%f329, %f898, %f327;
	mul.ftz.f32 	%f330, %f899, %f327;
	sub.ftz.f32 	%f16, %f13, %f328;
	sub.ftz.f32 	%f17, %f14, %f329;
	sub.ftz.f32 	%f18, %f15, %f330;
	mul.ftz.f32 	%f331, %f17, %f17;
	fma.rn.ftz.f32 	%f332, %f16, %f16, %f331;
	fma.rn.ftz.f32 	%f19, %f18, %f18, %f332;
	setp.gtu.ftz.f32 	%p7, %f19, 0f2B8CBCCC;
	@%p7 bra 	$L__BB2_7;
	bra.uni 	$L__BB2_4;

$L__BB2_7:
	max.ftz.f32 	%f370, %f19, %f322;
	rsqrt.approx.ftz.f32 	%f371, %f370;
	mul.ftz.f32 	%f907, %f18, %f371;
	mul.ftz.f32 	%f905, %f17, %f371;
	mul.ftz.f32 	%f903, %f16, %f371;
	bra.uni 	$L__BB2_8;

$L__BB2_4:
	mul.ftz.f32 	%f333, %f898, %f898;
	fma.rn.ftz.f32 	%f334, %f897, %f897, %f333;
	fma.rn.ftz.f32 	%f335, %f899, %f899, %f334;
	max.ftz.f32 	%f337, %f335, %f322;
	rsqrt.approx.ftz.f32 	%f338, %f337;
	mul.ftz.f32 	%f20, %f897, %f338;
	mul.ftz.f32 	%f21, %f898, %f338;
	mul.ftz.f32 	%f22, %f899, %f338;
	mul.ftz.f32 	%f339, %f14, %f21;
	fma.rn.ftz.f32 	%f340, %f13, %f20, %f339;
	fma.rn.ftz.f32 	%f341, %f15, %f22, %f340;
	mul.ftz.f32 	%f342, %f20, %f341;
	mul.ftz.f32 	%f343, %f21, %f341;
	mul.ftz.f32 	%f344, %f22, %f341;
	sub.ftz.f32 	%f23, %f13, %f342;
	sub.ftz.f32 	%f24, %f14, %f343;
	sub.ftz.f32 	%f25, %f15, %f344;
	mul.ftz.f32 	%f345, %f24, %f24;
	fma.rn.ftz.f32 	%f346, %f23, %f23, %f345;
	fma.rn.ftz.f32 	%f26, %f25, %f25, %f346;
	setp.gt.ftz.f32 	%p8, %f26, 0f2B8CBCCC;
	@%p8 bra 	$L__BB2_6;
	bra.uni 	$L__BB2_5;

$L__BB2_6:
	mov.f32 	%f366, 0f2B8CBCCC;
	max.ftz.f32 	%f367, %f26, %f366;
	rsqrt.approx.ftz.f32 	%f368, %f367;
	mul.ftz.f32 	%f907, %f25, %f368;
	mul.ftz.f32 	%f905, %f24, %f368;
	mul.ftz.f32 	%f903, %f23, %f368;
	bra.uni 	$L__BB2_8;

$L__BB2_5:
	abs.ftz.f32 	%f347, %f22;
	setp.lt.ftz.f32 	%p9, %f347, 0f3F666666;
	selp.f32 	%f348, 0f3F800000, 0f00000000, %p9;
	selp.f32 	%f349, 0f00000000, 0f3F800000, %p9;
	mov.f32 	%f350, 0f00000000;
	mul.ftz.f32 	%f351, %f21, %f349;
	fma.rn.ftz.f32 	%f352, %f20, 0f00000000, %f351;
	fma.rn.ftz.f32 	%f353, %f22, %f348, %f352;
	mul.ftz.f32 	%f354, %f20, %f353;
	mul.ftz.f32 	%f355, %f21, %f353;
	mul.ftz.f32 	%f356, %f22, %f353;
	sub.ftz.f32 	%f357, %f350, %f354;
	sub.ftz.f32 	%f358, %f349, %f355;
	sub.ftz.f32 	%f359, %f348, %f356;
	mul.ftz.f32 	%f360, %f358, %f358;
	fma.rn.ftz.f32 	%f361, %f357, %f357, %f360;
	fma.rn.ftz.f32 	%f362, %f359, %f359, %f361;
	mov.f32 	%f363, 0f2B8CBCCC;
	max.ftz.f32 	%f364, %f362, %f363;
	rsqrt.approx.ftz.f32 	%f365, %f364;
	mul.ftz.f32 	%f907, %f365, %f359;
	mul.ftz.f32 	%f905, %f365, %f358;
	mul.ftz.f32 	%f903, %f365, %f357;

$L__BB2_8:
	ld.const.u32 	%r2, [params+256];
	setp.lt.s32 	%p10, %r2, 0;
	@%p10 bra 	$L__BB2_88;

	ld.const.u64 	%rd3, [params];
	ld.const.u64 	%rd4, [params+184];
	cvta.to.global.u64 	%rd88, %rd4;
	shl.b64 	%rd89, %rd2, 2;
	add.s64 	%rd5, %rd88, %rd89;
	ld.const.u64 	%rd6, [params+8];
	ld.const.v2.u32 	{%r87, %r88}, [params+128];
	mov.u32 	%r294, 0;
	ld.const.v2.u32 	{%r89, %r90}, [params+288];
	mov.b32 	%f48, %r89;
	ld.const.u64 	%rd90, [params+120];
	cvta.to.global.u64 	%rd7, %rd90;
	ld.const.v2.f32 	{%f376, %f377}, [params+296];
	ld.const.u64 	%rd91, [params+24];
	cvta.to.global.u64 	%rd8, %rd91;
	ld.const.u64 	%rd92, [params+48];
	cvta.to.global.u64 	%rd9, %rd92;
	ld.const.u64 	%rd93, [params+72];
	cvta.to.global.u64 	%rd10, %rd93;
	ld.const.u64 	%rd94, [params+32];
	cvta.to.global.u64 	%rd11, %rd94;
	ld.const.u64 	%rd95, [params+56];
	cvta.to.global.u64 	%rd12, %rd95;
	ld.const.u64 	%rd96, [params+80];
	cvta.to.global.u64 	%rd13, %rd96;
	ld.const.u64 	%rd97, [params+40];
	cvta.to.global.u64 	%rd14, %rd97;
	ld.const.u64 	%rd98, [params+64];
	cvta.to.global.u64 	%rd15, %rd98;
	ld.const.u64 	%rd99, [params+88];
	cvta.to.global.u64 	%rd16, %rd99;
	ld.const.u64 	%rd100, [params+96];
	cvta.to.global.u64 	%rd17, %rd100;
	ld.const.u64 	%rd101, [params+104];
	cvta.to.global.u64 	%rd18, %rd101;
	ld.const.u64 	%rd102, [params+112];
	cvta.to.global.u64 	%rd19, %rd102;
	ld.const.v2.f32 	{%f378, %f379}, [params+304];
	ld.const.v2.u32 	{%r92, %r93}, [params+312];
	mov.b32 	%f53, %r92;
	sub.ftz.f32 	%f54, %f378, %f377;
	sub.ftz.f32 	%f55, %f53, %f379;
	setp.le.ftz.f32 	%p11, %f54, 0f00000000;
	mov.f32 	%f893, 0f00000000;
	setp.le.ftz.f32 	%p12, %f55, 0f00000000;
	or.pred  	%p13, %p11, %p12;
	setp.lt.s32 	%p14, %r93, 1;
	or.pred  	%p15, %p14, %p13;
	ld.const.u32 	%r95, [params+320];
	setp.lt.s32 	%p16, %r95, 1;
	or.pred  	%p1, %p16, %p15;
	ld.const.v2.u32 	{%r96, %r97}, [params+368];
	ld.const.f32 	%f61, [params+260];
	ld.const.v2.f32 	{%f382, %f383}, [params+264];
	ld.const.v2.u32 	{%r99, %r100}, [params+272];
	mov.b32 	%f64, %r99;
	ld.const.u64 	%rd20, [params+360];
	cvta.to.global.u64 	%rd21, %rd20;
	ld.const.u64 	%rd103, [params+328];
	cvta.to.global.u64 	%rd22, %rd103;
	ld.const.u64 	%rd104, [params+336];
	cvta.to.global.u64 	%rd23, %rd104;
	ld.const.u64 	%rd105, [params+344];
	cvta.to.global.u64 	%rd24, %rd105;
	ld.const.u64 	%rd106, [params+352];
	cvta.to.global.u64 	%rd25, %rd106;
	setp.eq.s32 	%p17, %r97, 0;
	ld.const.u64 	%rd107, [params+448];
	setp.eq.s64 	%p18, %rd107, 0;
	or.pred  	%p2, %p17, %p18;
	ld.const.v2.u32 	{%r102, %r103}, [params+280];
	mov.b32 	%f65, %r103;
	setp.lt.s32 	%p19, %r102, 1;
	setp.geu.ftz.f32 	%p20, %f65, 0f3F800000;
	or.pred  	%p3, %p19, %p20;
	ld.const.v2.u32 	{%r105, %r106}, [params+376];
	cvta.to.global.u64 	%rd26, %rd107;
	ld.const.u64 	%rd108, [params+456];
	cvta.to.global.u64 	%rd27, %rd108;
	ld.const.u64 	%rd109, [params+464];
	cvta.to.global.u64 	%rd28, %rd109;
	ld.const.u64 	%rd110, [params+472];
	cvta.to.global.u64 	%rd29, %rd110;
	ld.const.u64 	%rd111, [params+480];
	cvta.to.global.u64 	%rd30, %rd111;
	ld.const.u64 	%rd112, [params+488];
	cvta.to.global.u64 	%rd31, %rd112;
	ld.const.u64 	%rd113, [params+496];
	cvta.to.global.u64 	%rd32, %rd113;
	ld.const.u64 	%rd114, [params+504];
	cvta.to.global.u64 	%rd33, %rd114;
	ld.const.u64 	%rd115, [params+512];
	cvta.to.global.u64 	%rd34, %rd115;
	ld.const.u64 	%rd116, [params+520];
	cvta.to.global.u64 	%rd35, %rd116;
	ld.const.u64 	%rd117, [params+528];
	cvta.to.global.u64 	%rd36, %rd117;
	ld.const.u64 	%rd118, [params+536];
	cvta.to.global.u64 	%rd37, %rd118;
	ld.const.u64 	%rd119, [params+544];
	cvta.to.global.u64 	%rd38, %rd119;
	ld.const.u64 	%rd120, [params+392];
	cvta.to.global.u64 	%rd39, %rd120;
	ld.const.u64 	%rd121, [params+400];
	cvta.to.global.u64 	%rd40, %rd121;
	ld.const.u64 	%rd122, [params+408];
	cvta.to.global.u64 	%rd41, %rd122;
	ld.const.u64 	%rd123, [params+416];
	cvta.to.global.u64 	%rd42, %rd123;
	ld.const.u64 	%rd124, [params+424];
	cvta.to.global.u64 	%rd43, %rd124;
	ld.const.u64 	%rd125, [params+432];
	cvta.to.global.u64 	%rd44, %rd125;
	ld.const.u64 	%rd126, [params+384];
	cvta.to.global.u64 	%rd45, %rd126;
	ld.const.u64 	%rd127, [params+440];
	cvta.to.global.u64 	%rd46, %rd127;
	mov.f32 	%f904, %f893;
	mov.f32 	%f906, %f893;
	mov.f32 	%f908, %f893;

$L__BB2_10:
	ld.const.u64 	%rd173, [params+184];
	setp.ne.s32 	%p21, %r294, 0;
	setp.eq.s64 	%p22, %rd173, 0;
	or.pred  	%p23, %p21, %p22;
	mov.f32 	%f909, 0f4CBEBC20;
	@%p23 bra 	$L__BB2_12;

	ld.global.f32 	%f909, [%rd5];

$L__BB2_12:
	abs.ftz.f32 	%f385, %f909;
	setp.geu.ftz.f32 	%p24, %f385, 0f7F800000;
	selp.f32 	%f84, 0f4CBEBC20, %f909, %p24;
	setp.eq.s64 	%p25, %rd3, 0;
	mov.u32 	%r295, 0;
	mov.u32 	%r299, 1287568416;
	mov.u32 	%r296, %r295;
	mov.u32 	%r297, %r295;
	mov.u32 	%r298, %r295;
	mov.u32 	%r300, %r295;
	@%p25 bra 	$L__BB2_14;

	mov.f32 	%f392, 0f3727C5AC;
	mov.f32 	%f394, 0f00000000;
	mov.u32 	%r146, 255;
	mov.u32 	%r149, 1;
	mov.u32 	%r151, 6;
	mov.u32 	%r153, 1287568416;
	mov.u32 	%r183, 0;
	// begin inline asm
	call(%r300,%r299,%r298,%r297,%r296,%r295,%r119,%r120,%r121,%r122,%r123,%r124,%r125,%r126,%r127,%r128,%r129,%r130,%r131,%r132,%r133,%r134,%r135,%r136,%r137,%r138,%r139,%r140,%r141,%r142,%r143,%r144),_optix_trace_typed_32,(%r183,%rd3,%f900,%f901,%f902,%f897,%f898,%f899,%f392,%f84,%f394,%r146,%r149,%r183,%r149,%r183,%r151,%r183,%r153,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183,%r183);
	// end inline asm

$L__BB2_14:
	ld.const.u32 	%r289, [params+16];
	setp.eq.s32 	%p26, %r289, 0;
	@%p26 bra 	$L__BB2_21;

	setp.eq.s64 	%p27, %rd6, 0;
	mov.u32 	%r301, 0;
	mov.u32 	%r305, 1287568416;
	mov.u32 	%r302, %r301;
	mov.u32 	%r303, %r301;
	mov.u32 	%r304, %r301;
	mov.u32 	%r306, %r301;
	@%p27 bra 	$L__BB2_17;

	mov.f32 	%f401, 0f3727C5AC;
	mov.f32 	%f403, 0f00000000;
	mov.u32 	%r223, 255;
	mov.u32 	%r226, 1;
	mov.u32 	%r228, 6;
	mov.u32 	%r230, 1287568416;
	mov.u32 	%r260, 0;
	// begin inline asm
	call(%r306,%r305,%r304,%r303,%r302,%r301,%r196,%r197,%r198,%r199,%r200,%r201,%r202,%r203,%r204,%r205,%r206,%r207,%r208,%r209,%r210,%r211,%r212,%r213,%r214,%r215,%r216,%r217,%r218,%r219,%r220,%r221),_optix_trace_typed_32,(%r260,%rd6,%f900,%f901,%f902,%f897,%f898,%f899,%f401,%f84,%f403,%r223,%r226,%r260,%r226,%r260,%r228,%r260,%r230,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260,%r260);
	// end inline asm

$L__BB2_17:
	setp.eq.s32 	%p28, %r300, 0;
	mov.u32 	%r307, %r306;
	mov.u32 	%r308, %r305;
	mov.u32 	%r309, %r304;
	mov.u32 	%r310, %r303;
	mov.u32 	%r311, %r302;
	mov.u32 	%r312, %r301;
	@%p28 bra 	$L__BB2_22;

	setp.eq.s32 	%p29, %r306, 0;
	mov.u32 	%r307, %r300;
	mov.u32 	%r308, %r299;
	mov.u32 	%r309, %r298;
	mov.u32 	%r310, %r297;
	mov.u32 	%r311, %r296;
	mov.u32 	%r312, %r295;
	@%p29 bra 	$L__BB2_22;

	mov.b32 	%f404, %r305;
	mov.b32 	%f405, %r299;
	setp.lt.ftz.f32 	%p30, %f404, %f405;
	mov.u32 	%r307, %r300;
	mov.u32 	%r308, %r299;
	mov.u32 	%r309, %r298;
	mov.u32 	%r310, %r297;
	mov.u32 	%r311, %r296;
	mov.u32 	%r312, %r295;
	@%p30 bra 	$L__BB2_20;
	bra.uni 	$L__BB2_22;

$L__BB2_20:
	mov.u32 	%r307, %r306;
	mov.u32 	%r308, %r305;
	mov.u32 	%r309, %r304;
	mov.u32 	%r310, %r303;
	mov.u32 	%r311, %r302;
	mov.u32 	%r312, %r301;
	bra.uni 	$L__BB2_22;

$L__BB2_21:
	mov.u32 	%r307, %r300;
	mov.u32 	%r308, %r299;
	mov.u32 	%r309, %r298;
	mov.u32 	%r310, %r297;
	mov.u32 	%r311, %r296;
	mov.u32 	%r312, %r295;

$L__BB2_22:
	setp.eq.s32 	%p31, %r307, 0;
	mov.b32 	%f406, %r308;
	selp.f32 	%f85, 0f4CBEBC20, %f406, %p31;
	setp.eq.s32 	%p32, %r294, 0;
	@%p32 bra 	$L__BB2_45;

	mul.ftz.f32 	%f407, %f903, %f903;
	fma.rn.ftz.f32 	%f408, %f904, %f904, %f407;
	mul.ftz.f32 	%f409, %f905, %f905;
	fma.rn.ftz.f32 	%f410, %f906, %f906, %f409;
	add.ftz.f32 	%f411, %f410, %f408;
	mul.ftz.f32 	%f412, %f907, %f907;
	fma.rn.ftz.f32 	%f413, %f908, %f908, %f412;
	add.ftz.f32 	%f414, %f413, %f411;
	setp.le.ftz.f32 	%p33, %f414, 0f00000000;
	@%p33 bra 	$L__BB2_45;

	setp.eq.s32 	%p34, %r90, 1;
	selp.f32 	%f415, %f898, %f899, %p34;
	setp.eq.s32 	%p35, %r90, 0;
	selp.f32 	%f89, %f897, %f415, %p35;
	abs.ftz.f32 	%f90, %f89;
	setp.le.ftz.f32 	%p36, %f90, 0f358637BD;
	@%p36 bra 	$L__BB2_45;

	setp.ge.ftz.f32 	%p38, %f89, 0f00000000;
	selp.f32 	%f416, 0f358637BD, 0fB58637BD, %p38;
	add.ftz.f32 	%f417, %f89, %f416;
	selp.f32 	%f418, %f901, %f902, %p34;
	selp.f32 	%f419, %f900, %f418, %p35;
	sub.ftz.f32 	%f420, %f376, %f419;
	div.approx.ftz.f32 	%f94, %f420, %f417;
	setp.leu.ftz.f32 	%p40, %f94, 0f3727C5AC;
	setp.geu.ftz.f32 	%p41, %f94, %f85;
	or.pred  	%p42, %p41, %p40;
	@%p42 bra 	$L__BB2_45;

	fma.rn.ftz.f32 	%f95, %f897, %f94, %f900;
	fma.rn.ftz.f32 	%f96, %f898, %f94, %f901;
	fma.rn.ftz.f32 	%f910, %f899, %f94, %f902;
	mov.f32 	%f911, %f96;
	@%p35 bra 	$L__BB2_29;

	setp.ne.s32 	%p44, %r90, 1;
	mov.f32 	%f911, %f95;
	@%p44 bra 	$L__BB2_)PTX_CHUNK"
R"PTX_CHUNK(28;
	bra.uni 	$L__BB2_29;

$L__BB2_28:
	mov.f32 	%f910, %f96;
	mov.f32 	%f911, %f95;

$L__BB2_29:
	mov.b32 	%f886, %r92;
	setp.ge.ftz.f32 	%p45, %f911, %f378;
	setp.lt.ftz.f32 	%p46, %f911, %f377;
	or.pred  	%p47, %p46, %p45;
	setp.lt.ftz.f32 	%p48, %f910, %f379;
	or.pred  	%p49, %p47, %p48;
	setp.ge.ftz.f32 	%p50, %f910, %f886;
	or.pred  	%p51, %p49, %p50;
	or.pred  	%p52, %p51, %p1;
	@%p52 bra 	$L__BB2_45;

	@%p35 bra 	$L__BB2_33;

	mov.f32 	%f912, %f911;
	mov.f32 	%f913, %f910;
	mov.f32 	%f914, %f376;
	@%p34 bra 	$L__BB2_32;
	bra.uni 	$L__BB2_34;

$L__BB2_32:
	mov.f32 	%f912, %f911;
	mov.f32 	%f913, %f376;
	mov.f32 	%f914, %f910;
	bra.uni 	$L__BB2_34;

$L__BB2_33:
	mov.f32 	%f912, %f376;
	mov.f32 	%f913, %f911;
	mov.f32 	%f914, %f910;

$L__BB2_34:
	ld.const.u32 	%r292, [params+320];
	add.s32 	%r291, %r93, -1;
	add.s32 	%r290, %r292, -1;
	cvt.rn.f32.s32 	%f889, %r292;
	cvt.rn.f32.s32 	%f888, %r93;
	sub.ftz.f32 	%f887, %f378, %f377;
	sub.ftz.f32 	%f423, %f911, %f377;
	div.approx.ftz.f32 	%f424, %f423, %f887;
	mul.ftz.f32 	%f425, %f424, %f888;
	cvt.rzi.ftz.s32.f32 	%r261, %f425;
	max.s32 	%r262, %r261, 0;
	sub.ftz.f32 	%f426, %f910, %f379;
	div.approx.ftz.f32 	%f427, %f426, %f55;
	mul.ftz.f32 	%f428, %f427, %f889;
	cvt.rzi.ftz.s32.f32 	%r263, %f428;
	max.s32 	%r264, %r263, 0;
	sub.ftz.f32 	%f429, %f912, %f894;
	sub.ftz.f32 	%f430, %f913, %f895;
	sub.ftz.f32 	%f431, %f914, %f896;
	mul.ftz.f32 	%f432, %f430, %f430;
	fma.rn.ftz.f32 	%f433, %f429, %f429, %f432;
	fma.rn.ftz.f32 	%f434, %f431, %f431, %f433;
	mov.f32 	%f435, 0f00000000;
	max.ftz.f32 	%f436, %f434, %f435;
	sqrt.approx.ftz.f32 	%f115, %f436;
	mov.f32 	%f437, 0f358637BD;
	max.ftz.f32 	%f438, %f115, %f437;
	mul.ftz.f32 	%f439, %f438, 0f41490FDB;
	div.approx.ftz.f32 	%f440, %f61, %f439;
	max.ftz.f32 	%f441, %f64, %f437;
	div.approx.ftz.f32 	%f442, %f383, %f441;
	mul.ftz.f32 	%f443, %f115, %f442;
	mul.ftz.f32 	%f444, %f115, %f443;
	max.ftz.f32 	%f445, %f90, %f437;
	div.approx.ftz.f32 	%f446, %f444, %f445;
	max.ftz.f32 	%f447, %f446, %f435;
	sqrt.approx.ftz.f32 	%f448, %f447;
	mul.ftz.f32 	%f116, %f440, %f448;
	abs.ftz.f32 	%f449, %f382;
	setp.gt.ftz.f32 	%p55, %f449, 0f358637BD;
	min.s32 	%r265, %r264, %r290;
	min.s32 	%r266, %r262, %r291;
	mad.lo.s32 	%r77, %r265, %r93, %r266;
	mov.f32 	%f915, %f382;
	@%p55 bra 	$L__BB2_36;

	max.ftz.f32 	%f451, %f61, %f437;
	mov.f32 	%f452, 0f40C90FDB;
	div.approx.ftz.f32 	%f915, %f452, %f451;

$L__BB2_36:
	mul.ftz.f32 	%f453, %f115, %f915;
	sin.approx.ftz.f32 	%f454, %f453;
	cos.approx.ftz.f32 	%f455, %f453;
	mul.ftz.f32 	%f456, %f116, %f455;
	mul.ftz.f32 	%f457, %f116, %f454;
	mul.ftz.f32 	%f458, %f904, %f457;
	fma.rn.ftz.f32 	%f119, %f903, %f456, %f458;
	mul.ftz.f32 	%f459, %f903, %f457;
	mul.ftz.f32 	%f460, %f904, %f456;
	sub.ftz.f32 	%f120, %f460, %f459;
	mul.ftz.f32 	%f461, %f906, %f457;
	fma.rn.ftz.f32 	%f121, %f905, %f456, %f461;
	mul.ftz.f32 	%f462, %f905, %f457;
	mul.ftz.f32 	%f463, %f906, %f456;
	sub.ftz.f32 	%f122, %f463, %f462;
	mul.ftz.f32 	%f464, %f908, %f457;
	fma.rn.ftz.f32 	%f123, %f907, %f456, %f464;
	mul.ftz.f32 	%f465, %f907, %f457;
	mul.ftz.f32 	%f466, %f908, %f456;
	sub.ftz.f32 	%f124, %f466, %f465;
	abs.ftz.f32 	%f467, %f119;
	setp.geu.ftz.f32 	%p56, %f467, 0f7F800000;
	@%p56 bra 	$L__BB2_45;

	abs.ftz.f32 	%f468, %f120;
	setp.geu.ftz.f32 	%p57, %f468, 0f7F800000;
	@%p57 bra 	$L__BB2_45;

	abs.ftz.f32 	%f469, %f121;
	setp.geu.ftz.f32 	%p58, %f469, 0f7F800000;
	@%p58 bra 	$L__BB2_45;

	abs.ftz.f32 	%f470, %f122;
	setp.geu.ftz.f32 	%p59, %f470, 0f7F800000;
	@%p59 bra 	$L__BB2_45;

	abs.ftz.f32 	%f471, %f123;
	setp.geu.ftz.f32 	%p60, %f471, 0f7F800000;
	@%p60 bra 	$L__BB2_45;

	abs.ftz.f32 	%f472, %f124;
	setp.geu.ftz.f32 	%p61, %f472, 0f7F800000;
	@%p61 bra 	$L__BB2_45;

	mul.ftz.f32 	%f473, %f120, %f120;
	fma.rn.ftz.f32 	%f474, %f119, %f119, %f473;
	mul.ftz.f32 	%f475, %f122, %f122;
	fma.rn.ftz.f32 	%f476, %f121, %f121, %f475;
	add.ftz.f32 	%f477, %f474, %f476;
	mul.ftz.f32 	%f478, %f124, %f124;
	fma.rn.ftz.f32 	%f479, %f123, %f123, %f478;
	add.ftz.f32 	%f125, %f479, %f477;
	setp.leu.ftz.f32 	%p62, %f125, 0f00000000;
	@%p62 bra 	$L__BB2_45;

	abs.ftz.f32 	%f480, %f125;
	setp.geu.ftz.f32 	%p63, %f480, 0f7F800000;
	@%p63 bra 	$L__BB2_45;

	mul.wide.s32 	%rd130, %r77, 4;
	add.s64 	%rd131, %rd39, %rd130;
	atom.global.add.f32 	%f481, [%rd131], %f119;
	add.s64 	%rd132, %rd40, %rd130;
	atom.global.add.f32 	%f482, [%rd132], %f120;
	add.s64 	%rd133, %rd41, %rd130;
	atom.global.add.f32 	%f483, [%rd133], %f121;
	add.s64 	%rd134, %rd42, %rd130;
	atom.global.add.f32 	%f484, [%rd134], %f122;
	add.s64 	%rd135, %rd43, %rd130;
	atom.global.add.f32 	%f485, [%rd135], %f123;
	add.s64 	%rd136, %rd44, %rd130;
	atom.global.add.f32 	%f486, [%rd136], %f124;
	add.s64 	%rd137, %rd45, %rd130;
	atom.global.add.f32 	%f487, [%rd137], %f125;
	atom.global.add.u32 	%r267, [%rd46], 1;

$L__BB2_45:
	ld.const.u32 	%r293, [params+256];
	setp.ge.s32 	%p65, %r294, %r293;
	or.pred  	%p66, %p31, %p65;
	@%p66 bra 	$L__BB2_88;

	setp.lt.s32 	%p67, %r312, 0;
	setp.ge.s32 	%p68, %r312, %r87;
	mov.u32 	%r313, 0;
	or.pred  	%p69, %p67, %p68;
	@%p69 bra 	$L__BB2_48;

	mul.wide.s32 	%rd138, %r312, 4;
	add.s64 	%rd139, %rd7, %rd138;
	ld.global.u32 	%r313, [%rd139];

$L__BB2_48:
	fma.rn.ftz.f32 	%f916, %f897, %f85, %f900;
	fma.rn.ftz.f32 	%f917, %f898, %f85, %f901;
	fma.rn.ftz.f32 	%f918, %f899, %f85, %f902;
	add.s32 	%r81, %r313, %r311;
	setp.lt.s32 	%p70, %r81, 0;
	setp.ge.s32 	%p71, %r81, %r88;
	mov.f32 	%f921, 0f3F800000;
	mov.f32 	%f919, 0f00000000;
	or.pred  	%p72, %p70, %p71;
	mov.f32 	%f920, %f919;
	@%p72 bra 	$L__BB2_50;

	mov.b32 	%f491, %r309;
	mov.b32 	%f492, %r310;
	mul.wide.s32 	%rd140, %r81, 4;
	add.s64 	%rd141, %rd8, %rd140;
	add.s64 	%rd142, %rd9, %rd140;
	ld.global.f32 	%f493, [%rd142];
	ld.global.f32 	%f494, [%rd141];
	fma.rn.ftz.f32 	%f495, %f493, %f491, %f494;
	add.s64 	%rd143, %rd10, %rd140;
	ld.global.f32 	%f496, [%rd143];
	add.s64 	%rd144, %rd11, %rd140;
	add.s64 	%rd145, %rd12, %rd140;
	ld.global.f32 	%f497, [%rd145];
	ld.global.f32 	%f498, [%rd144];
	fma.rn.ftz.f32 	%f499, %f497, %f491, %f498;
	add.s64 	%rd146, %rd13, %rd140;
	ld.global.f32 	%f500, [%rd146];
	add.s64 	%rd147, %rd14, %rd140;
	add.s64 	%rd148, %rd15, %rd140;
	ld.global.f32 	%f501, [%rd148];
	ld.global.f32 	%f502, [%rd147];
	fma.rn.ftz.f32 	%f503, %f501, %f491, %f502;
	add.s64 	%rd149, %rd16, %rd140;
	ld.global.f32 	%f504, [%rd149];
	fma.rn.ftz.f32 	%f918, %f504, %f492, %f503;
	fma.rn.ftz.f32 	%f917, %f500, %f492, %f499;
	fma.rn.ftz.f32 	%f916, %f496, %f492, %f495;
	add.s64 	%rd150, %rd17, %rd140;
	add.s64 	%rd151, %rd18, %rd140;
	add.s64 	%rd152, %rd19, %rd140;
	ld.global.f32 	%f505, [%rd150];
	ld.global.f32 	%f506, [%rd151];
	mul.ftz.f32 	%f507, %f506, %f506;
	fma.rn.ftz.f32 	%f508, %f505, %f505, %f507;
	ld.global.f32 	%f509, [%rd152];
	fma.rn.ftz.f32 	%f510, %f509, %f509, %f508;
	mov.f32 	%f511, 0f2B8CBCCC;
	max.ftz.f32 	%f512, %f510, %f511;
	rsqrt.approx.ftz.f32 	%f513, %f512;
	mul.ftz.f32 	%f921, %f509, %f513;
	mul.ftz.f32 	%f920, %f506, %f513;
	mul.ftz.f32 	%f919, %f505, %f513;

$L__BB2_50:
	mul.ftz.f32 	%f514, %f898, %f920;
	fma.rn.ftz.f32 	%f515, %f897, %f919, %f514;
	fma.rn.ftz.f32 	%f516, %f899, %f921, %f515;
	setp.gt.ftz.f32 	%p73, %f516, 0f00000000;
	neg.ftz.f32 	%f517, %f919;
	neg.ftz.f32 	%f518, %f920;
	neg.ftz.f32 	%f519, %f921;
	selp.f32 	%f144, %f519, %f921, %p73;
	selp.f32 	%f145, %f518, %f920, %p73;
	selp.f32 	%f146, %f517, %f919, %p73;
	mul.ftz.f32 	%f520, %f898, %f898;
	fma.rn.ftz.f32 	%f521, %f897, %f897, %f520;
	fma.rn.ftz.f32 	%f522, %f899, %f899, %f521;
	mov.f32 	%f523, 0f2B8CBCCC;
	max.ftz.f32 	%f524, %f522, %f523;
	rsqrt.approx.ftz.f32 	%f525, %f524;
	mul.ftz.f32 	%f147, %f897, %f525;
	mul.ftz.f32 	%f148, %f898, %f525;
	mul.ftz.f32 	%f149, %f899, %f525;
	mul.ftz.f32 	%f526, %f145, %f145;
	fma.rn.ftz.f32 	%f527, %f146, %f146, %f526;
	fma.rn.ftz.f32 	%f528, %f144, %f144, %f527;
	max.ftz.f32 	%f529, %f528, %f523;
	rsqrt.approx.ftz.f32 	%f530, %f529;
	mul.ftz.f32 	%f150, %f146, %f530;
	mul.ftz.f32 	%f151, %f145, %f530;
	mul.ftz.f32 	%f152, %f144, %f530;
	mul.ftz.f32 	%f531, %f148, %f151;
	fma.rn.ftz.f32 	%f532, %f147, %f150, %f531;
	fma.rn.ftz.f32 	%f153, %f149, %f152, %f532;
	add.ftz.f32 	%f533, %f153, %f153;
	mul.ftz.f32 	%f534, %f150, %f533;
	mul.ftz.f32 	%f535, %f151, %f533;
	mul.ftz.f32 	%f536, %f152, %f533;
	sub.ftz.f32 	%f537, %f147, %f534;
	sub.ftz.f32 	%f538, %f148, %f535;
	sub.ftz.f32 	%f539, %f149, %f536;
	mul.ftz.f32 	%f540, %f538, %f538;
	fma.rn.ftz.f32 	%f541, %f537, %f537, %f540;
	fma.rn.ftz.f32 	%f542, %f539, %f539, %f541;
	max.ftz.f32 	%f543, %f542, %f523;
	rsqrt.approx.ftz.f32 	%f544, %f543;
	mul.ftz.f32 	%f897, %f544, %f537;
	mul.ftz.f32 	%f898, %f544, %f538;
	mul.ftz.f32 	%f899, %f544, %f539;
	mul.ftz.f32 	%f545, %f149, %f151;
	mul.ftz.f32 	%f546, %f148, %f152;
	sub.ftz.f32 	%f157, %f545, %f546;
	mul.ftz.f32 	%f547, %f147, %f152;
	mul.ftz.f32 	%f548, %f149, %f150;
	sub.ftz.f32 	%f158, %f547, %f548;
	mul.ftz.f32 	%f549, %f148, %f150;
	mul.ftz.f32 	%f550, %f147, %f151;
	sub.ftz.f32 	%f159, %f549, %f550;
	mul.ftz.f32 	%f551, %f158, %f158;
	fma.rn.ftz.f32 	%f552, %f157, %f157, %f551;
	fma.rn.ftz.f32 	%f160, %f159, %f159, %f552;
	setp.gtu.ftz.f32 	%p74, %f160, 0f2B8CBCCC;
	@%p74 bra 	$L__BB2_54;
	bra.uni 	$L__BB2_51;

$L__BB2_54:
	max.ftz.f32 	%f590, %f160, %f523;
	rsqrt.approx.ftz.f32 	%f591, %f590;
	mul.ftz.f32 	%f924, %f159, %f591;
	mul.ftz.f32 	%f923, %f158, %f591;
	mul.ftz.f32 	%f922, %f157, %f591;
	bra.uni 	$L__BB2_55;

$L__BB2_51:
	mul.ftz.f32 	%f553, %f148, %f148;
	fma.rn.ftz.f32 	%f554, %f147, %f147, %f553;
	fma.rn.ftz.f32 	%f555, %f149, %f149, %f554;
	max.ftz.f32 	%f557, %f555, %f523;
	rsqrt.approx.ftz.f32 	%f558, %f557;
	mul.ftz.f32 	%f161, %f147, %f558;
	mul.ftz.f32 	%f162, %f148, %f558;
	mul.ftz.f32 	%f163, %f149, %f558;
	mul.ftz.f32 	%f559, %f151, %f162;
	fma.rn.ftz.f32 	%f560, %f150, %f161, %f559;
	fma.rn.ftz.f32 	%f561, %f152, %f163, %f560;
	mul.ftz.f32 	%f562, %f161, %f561;
	mul.ftz.f32 	%f563, %f162, %f561;
	mul.ftz.f32 	%f564, %f163, %f561;
	sub.ftz.f32 	%f164, %f150, %f562;
	sub.ftz.f32 	%f165, %f151, %f563;
	sub.ftz.f32 	%f166, %f152, %f564;
	mul.ftz.f32 	%f565, %f165, %f165;
	fma.rn.ftz.f32 	%f566, %f164, %f164, %f565;
	fma.rn.ftz.f32 	%f167, %f166, %f166, %f566;
	setp.gt.ftz.f32 	%p75, %f167, 0f2B8CBCCC;
	@%p75 bra 	$L__BB2_53;
	bra.uni 	$L__BB2_52;

$L__BB2_53:
	mov.f32 	%f586, 0f2B8CBCCC;
	max.ftz.f32 	%f587, %f167, %f586;
	rsqrt.approx.ftz.f32 	%f588, %f587;
	mul.ftz.f32 	%f924, %f166, %f588;
	mul.ftz.f32 	%f923, %f165, %f588;
	mul.ftz.f32 	%f922, %f164, %f588;
	bra.uni 	$L__BB2_55;

$L__BB2_52:
	abs.ftz.f32 	%f567, %f163;
	setp.lt.ftz.f32 	%p76, %f567, 0f3F666666;
	selp.f32 	%f568, 0f3F800000, 0f00000000, %p76;
	selp.f32 	%f569, 0f00000000, 0f3F800000, %p76;
	mov.f32 	%f570, 0f00000000;
	mul.ftz.f32 	%f571, %f162, %f569;
	fma.rn.ftz.f32 	%f572, %f161, 0f00000000, %f571;
	fma.rn.ftz.f32 	%f573, %f163, %f568, %f572;
	mul.ftz.f32 	%f574, %f161, %f573;
	mul.ftz.f32 	%f575, %f162, %f573;
	mul.ftz.f32 	%f576, %f163, %f573;
	sub.ftz.f32 	%f577, %f570, %f574;
	sub.ftz.f32 	%f578, %f569, %f575;
	sub.ftz.f32 	%f579, %f568, %f576;
	mul.ftz.f32 	%f580, %f578, %f578;
	fma.rn.ftz.f32 	%f581, %f577, %f577, %f580;
	fma.rn.ftz.f32 	%f582, %f579, %f579, %f581;
	mov.f32 	%f583, 0f2B8CBCCC;
	max.ftz.f32 	%f584, %f582, %f583;
	rsqrt.approx.ftz.f32 	%f585, %f584;
	mul.ftz.f32 	%f924, %f585, %f579;
	mul.ftz.f32 	%f923, %f585, %f578;
	mul.ftz.f32 	%f922, %f585, %f577;

$L__BB2_55:
	mul.ftz.f32 	%f592, %f149, %f923;
	mul.ftz.f32 	%f593, %f148, %f924;
	sub.ftz.f32 	%f188, %f592, %f593;
	mul.ftz.f32 	%f594, %f147, %f924;
	mul.ftz.f32 	%f595, %f149, %f922;
	sub.ftz.f32 	%f190, %f594, %f595;
	mul.ftz.f32 	%f596, %f148, %f922;
	mul.ftz.f32 	%f597, %f147, %f923;
	sub.ftz.f32 	%f191, %f596, %f597;
	mul.ftz.f32 	%f598, %f190, %f190;
	fma.rn.ftz.f32 	%f599, %f188, %f188, %f598;
	fma.rn.ftz.f32 	%f192, %f191, %f191, %f599;
	setp.gtu.ftz.f32 	%p77, %f192, 0f2B8CBCCC;
	@%p77 bra 	$L__BB2_59;
	bra.uni 	$L__BB2_56;

$L__BB2_59:
	mov.f32 	%f636, 0f2B8CBCCC;
	max.ftz.f32 	%f637, %f192, %f636;
	rsqrt.approx.ftz.f32 	%f638, %f637;
	mul.ftz.f32 	%f927, %f191, %f638;
	mul.ftz.f32 	%f926, %f190, %f638;
	mul.ftz.f32 	%f925, %f188, %f638;
	bra.uni 	$L__BB2_60;

$L__BB2_56:
	mul.ftz.f32 	%f600, %f148, %f148;
	fma.rn.ftz.f32 	%f601, %f147, %f147, %f600;
	fma.rn.ftz.f32 	%f602, %f149, %f149, %f601;
	mov.f32 	%f603, 0f2B8CBCCC;
	max.ftz.f32 	%f604, %f602, %f603;
	rsqrt.approx.ftz.f32 	%f605, %f604;
	mul.ftz.f32 	%f193, %f147, %f605;
	mul.ftz.f32 	%f194, %f148, %f605;
	mul.ftz.f32 	%f195, %f149, %f605;
	mul.ftz.f32 	%f606, %f151, %f194;
	fma.rn.ftz.f32 	%f607, %f150, %f193, %f606;
	fma.rn.ftz.f32 	%f608, %f152, %f195, %f607;
	mul.ftz.f32 	%f609, %f193, %f608;
	mul.ftz.f32 	%f610, %f194, %f608;
	mul.ftz.f32 	%f611, %f195, %f608;
	sub.ftz.f32 	%f196, %f150, %f609;
	sub.ftz.f32 	%f197, %f151, %f610;
	sub.ftz.f32 	%f198, %f152, %f611;
	mul.ftz.f32 	%f612, %f197, %f197;
	fma.rn.ftz.f32 	%f613, %f196, %f196, %f612;
	fma.rn.ftz.f32 	%f199, %f198, %f198, %f613;
	setp.gt.ftz.f32 	%p78, %f199, 0f2B8CBCCC;
	@%p78 bra 	$L__BB2_58;
	bra.uni 	$L__BB2_57;

$L__BB2_58:
	max.ftz.f32 	%f634, %f199, %f603;
	rsqrt.approx.ftz.f32 	%f635, %f634;
	mul.ftz.f32 	%f927, %f198, %f635;
	mul.ftz.f32 	%f926, %f197, %f635;
	mul.ftz.f32 	%f925, %f196, %f635;
	bra.uni 	$L__BB2_60;

$L__BB2_57:
	abs.ftz.f32 	%f614, %f195;
	setp.lt.ftz.f32 	%p79, %f614, 0f3F666666;
	selp.f32 	%f615, 0f3F800000, 0f00000000, %p79;
	selp.f32 	%f616, 0f00000000, 0f3F800000, %p79;
	mov.f32 	%f617, 0f00000000;
	mul.ftz.f32 	%f618, %f194, %f616;
	fma.rn.ftz.f32 	%f619, %f193, 0f00000000, %f618;
	fma.rn.ftz.f32 	%f620, %f195, %f615, %f619;
	mul.ftz.f32 	%f621, %f193, %f620;
	mul.ftz.f32 	%f622, %f194, %f620;
	mul.ftz.f32 	%f623, %f195, %f620;
	sub.ftz.f32 	%f624, %f617, %f621;
	sub.ftz.f32 	%f625, %f616, %f622;
	sub.ftz.f32 	%f626, %f615, %f623;
	mul.ftz.f32 	%f627, %f625, %f625;
	fma.rn.ftz.f32 	%f628, %f624, %f624, %f627;
	fma.rn.ftz.f32 	%f629, %f626, %f626, %f628;
	max.ftz.f32 	%f631, %f629, %f603;
	rsqrt.approx.ftz.f32 	%f632, %f631;
	mul.ftz.f32 	%f927, %f632, %f626;
	mul.ftz.f32 	%f926, %f632, %f625;
	mul.ftz.f32 	%f925, %f632, %f624;

$L__BB2_60:
	mul.ftz.f32 	%f639, %f898, %f924;
	mul.ftz.f32 	%f640, %f899, %f923;
	sub.ftz.f32 	%f218, %f640, %f639;
	mul.ftz.f32 	%f641, %f899, %f922;
	mul.ftz.f32 	%f642, %f897, %f924;
	sub.ftz.f32 	%f219, %f642, %f641;
	mul.ftz.f32 	%f643, %f897, %f923;
	mul.ftz.f32 	%f644, %f898, %f922;
	sub.ftz.f32 	%f220, %f644, %f643;
	mul.ftz.f32 	%f645, %f219, %f219;
	fma.rn.ftz.f32 	%f646, %f218, %f218, %f645;
	fma.rn.ftz.f32 	%f221, %f220, %f220, %f646;
	setp.gtu.ftz.f32 	%p80, %f221, 0f2B8CBCCC;
	@%p80 bra 	$L__BB2_64;
	bra.uni 	$L__BB2_61;

$L__BB2_64:
	mov.f32 	%f683, 0f2B8CBCCC;
	max.ftz.f32 	%f684, %f221, %f683;
	rsqrt.approx.ftz.f32 	%f685, %f684;
	mul.ftz.f32 	%f930, %f220, %f685;
	mul.ftz.f32 	%f929, %f219, %f685;
	mul.ftz.f32 	%f928, %f218, %f685;
	bra.uni 	$L__BB2_65;

$L__BB2_61:
	mul.ftz.f32 	%f647, %f898, %f898;
	fma.rn.ftz.f32 	%f648, %f897, %f897, %f647;
	fma.rn.ftz.f32 	%f649, %f899, %f899, %f648;
	mov.f32 	%f650, 0f2B8CBCCC;
	max.ftz.f32 	%f651, %f649, %f650;
	rsqrt.approx.ftz.f32 	%f652, %f651;
	mul.ftz.f32 	%f222, %f897, %f652;
	mul.ftz.f32 	%f223, %f898, %f652;
	mul.ftz.f32 	%f224, %f899, %f652;
	mul.ftz.f32 	%f653, %f151, %f223;
	fma.rn.ftz.f32 	%f654, %f150, %f222, %f653;
	fma.rn.ftz.f32 	%f655, %f152, %f224, %f654;
	mul.ftz.f32 	%f656, %f222, %f655;
	mul.ftz.f32 	%f657, %f223, %f655;
	mul.ftz.f32 	%f658, %f224, %f655;
	sub.ftz.f32 	%f225, %f150, %f656;
	sub.ftz.f32 	%f226, %f151, %f657;
	sub.ftz.f32 	%f227, %f152, %f658;
	mul.ftz.f32 	%f659, %f226, %f226;
	fma.rn.ftz.f32 	%f660, %f225, %f225, %f659;
	fma.rn.ftz.f32 	%f228, %f227, %f227, %f660;
	setp.gt.ftz.f32 	%p81, %f228, 0f2B8CBCCC;
	@%p81 bra 	$L__BB2_63;
	bra.uni 	$L__BB2_62;

$L__BB2_63:
	max.ftz.f32 	%f681, %f228, %f650;
	rsqrt.approx.ftz.f32 	%f682, %f681;
	mul.ftz.f32 	%f930)PTX_CHUNK"
R"PTX_CHUNK(, %f227, %f682;
	mul.ftz.f32 	%f929, %f226, %f682;
	mul.ftz.f32 	%f928, %f225, %f682;
	bra.uni 	$L__BB2_65;

$L__BB2_62:
	abs.ftz.f32 	%f661, %f224;
	setp.lt.ftz.f32 	%p82, %f661, 0f3F666666;
	selp.f32 	%f662, 0f3F800000, 0f00000000, %p82;
	selp.f32 	%f663, 0f00000000, 0f3F800000, %p82;
	mov.f32 	%f664, 0f00000000;
	mul.ftz.f32 	%f665, %f223, %f663;
	fma.rn.ftz.f32 	%f666, %f222, 0f00000000, %f665;
	fma.rn.ftz.f32 	%f667, %f224, %f662, %f666;
	mul.ftz.f32 	%f668, %f222, %f667;
	mul.ftz.f32 	%f669, %f223, %f667;
	mul.ftz.f32 	%f670, %f224, %f667;
	sub.ftz.f32 	%f671, %f664, %f668;
	sub.ftz.f32 	%f672, %f663, %f669;
	sub.ftz.f32 	%f673, %f662, %f670;
	mul.ftz.f32 	%f674, %f672, %f672;
	fma.rn.ftz.f32 	%f675, %f671, %f671, %f674;
	fma.rn.ftz.f32 	%f676, %f673, %f673, %f675;
	max.ftz.f32 	%f678, %f676, %f650;
	rsqrt.approx.ftz.f32 	%f679, %f678;
	mul.ftz.f32 	%f930, %f679, %f673;
	mul.ftz.f32 	%f929, %f679, %f672;
	mul.ftz.f32 	%f928, %f679, %f671;

$L__BB2_65:
	ld.const.u64 	%rd172, [params+360];
	setp.lt.s32 	%p112, %r81, 0;
	setp.le.s32 	%p83, %r96, %r81;
	or.pred  	%p85, %p112, %p83;
	setp.eq.s64 	%p86, %rd172, 0;
	or.pred  	%p87, %p85, %p86;
	mov.u16 	%rs8, 0;
	mov.f32 	%f937, 0f00000000;
	mov.f32 	%f938, 0f00000000;
	mov.f32 	%f939, 0f00000000;
	mov.f32 	%f952, 0f00000000;
	mov.f32 	%f940, %f952;
	@%p87 bra 	$L__BB2_77;

	cvt.s64.s32 	%rd47, %r81;
	add.s64 	%rd153, %rd21, %rd47;
	ld.global.u8 	%rs6, [%rd153];
	setp.eq.s16 	%p88, %rs6, 0;
	@%p88 bra 	$L__BB2_77;

	shl.b64 	%rd154, %rd47, 2;
	add.s64 	%rd155, %rd22, %rd154;
	ld.global.f32 	%f696, [%rd155];
	mov.f32 	%f697, 0f358637BD;
	max.ftz.f32 	%f247, %f696, %f697;
	add.s64 	%rd156, %rd23, %rd154;
	ld.global.f32 	%f698, [%rd156];
	mov.f32 	%f695, 0f00000000;
	max.ftz.f32 	%f699, %f698, %f695;
	add.s64 	%rd157, %rd24, %rd154;
	ld.global.f32 	%f248, [%rd157];
	add.s64 	%rd158, %rd25, %rd154;
	ld.global.f32 	%f700, [%rd158];
	max.ftz.f32 	%f249, %f700, %f697;
	max.ftz.f32 	%f701, %f61, %f697;
	mov.f32 	%f702, 0f4EE08C7C;
	div.approx.ftz.f32 	%f703, %f702, %f701;
	max.ftz.f32 	%f704, %f703, %f697;
	neg.ftz.f32 	%f705, %f699;
	mul.ftz.f32 	%f706, %f704, 0f2D1BC3B8;
	div.approx.ftz.f32 	%f250, %f705, %f706;
	abs.ftz.f32 	%f707, %f153;
	abs.ftz.f32 	%f708, %f707;
	max.ftz.f32 	%f709, %f708, %f697;
	mov.f32 	%f710, 0f3F800000;
	min.ftz.f32 	%f251, %f709, %f710;
	mul.ftz.f32 	%f711, %f251, %f251;
	sub.ftz.f32 	%f712, %f710, %f711;
	max.ftz.f32 	%f713, %f695, %f712;
	mul.ftz.f32 	%f714, %f247, %f249;
	mul.ftz.f32 	%f715, %f250, 0f00000000;
	sub.ftz.f32 	%f716, %f714, %f715;
	mul.ftz.f32 	%f717, %f249, %f250;
	fma.rn.ftz.f32 	%f252, %f247, 0f00000000, %f717;
	sub.ftz.f32 	%f253, %f716, %f713;
	abs.ftz.f32 	%f718, %f253;
	abs.ftz.f32 	%f719, %f252;
	mov.b32 	%r269, %f719;
	mov.b32 	%r270, %f718;
	min.s32 	%r271, %r269, %r270;
	mov.b32 	%f720, %r271;
	max.s32 	%r272, %r269, %r270;
	mov.b32 	%f721, %r272;
	and.b32  	%r273, %r272, -33554432;
	mov.u32 	%r274, 2122317824;
	sub.s32 	%r275, %r274, %r273;
	mov.b32 	%f722, %r275;
	mul.ftz.f32 	%f723, %f720, %f722;
	mul.ftz.f32 	%f724, %f721, %f722;
	mul.ftz.f32 	%f725, %f723, %f723;
	fma.rn.ftz.f32 	%f726, %f724, %f724, %f725;
	sqrt.approx.ftz.f32 	%f727, %f726;
	or.b32  	%r276, %r273, 8388608;
	mov.b32 	%f728, %r276;
	mul.ftz.f32 	%f729, %f727, %f728;
	setp.eq.ftz.f32 	%p89, %f720, 0f00000000;
	selp.f32 	%f730, %f721, %f729, %p89;
	setp.eq.ftz.f32 	%p90, %f720, 0f7F800000;
	selp.f32 	%f254, 0f7F800000, %f730, %p90;
	setp.le.ftz.f32 	%p91, %f254, 0f00000000;
	mov.f32 	%f931, %f695;
	mov.f32 	%f932, %f695;
	@%p91 bra 	$L__BB2_69;

	add.ftz.f32 	%f731, %f253, %f254;
	mul.ftz.f32 	%f732, %f731, 0f3F000000;
	mov.f32 	%f733, 0f00000000;
	max.ftz.f32 	%f734, %f733, %f732;
	sub.ftz.f32 	%f735, %f254, %f253;
	mul.ftz.f32 	%f736, %f735, 0f3F000000;
	max.ftz.f32 	%f737, %f733, %f736;
	sqrt.approx.ftz.f32 	%f738, %f737;
	copysign.f32 	%f932, %f252, %f738;
	sqrt.approx.ftz.f32 	%f931, %f734;

$L__BB2_69:
	mul.ftz.f32 	%f739, %f249, %f251;
	sub.ftz.f32 	%f740, %f739, %f931;
	sub.ftz.f32 	%f742, %f695, %f932;
	add.ftz.f32 	%f743, %f739, %f931;
	add.ftz.f32 	%f744, %f932, 0f00000000;
	mul.ftz.f32 	%f745, %f744, %f744;
	fma.rn.ftz.f32 	%f746, %f743, %f743, %f745;
	mov.f32 	%f747, 0f1E3CE508;
	max.ftz.f32 	%f748, %f746, %f747;
	mul.ftz.f32 	%f749, %f742, %f744;
	fma.rn.ftz.f32 	%f750, %f740, %f743, %f749;
	div.approx.ftz.f32 	%f751, %f750, %f748;
	mul.ftz.f32 	%f752, %f742, %f743;
	mul.ftz.f32 	%f753, %f740, %f744;
	sub.ftz.f32 	%f754, %f752, %f753;
	div.approx.ftz.f32 	%f755, %f754, %f748;
	mul.ftz.f32 	%f939, %f248, %f751;
	mul.ftz.f32 	%f940, %f248, %f755;
	mul.ftz.f32 	%f756, %f247, %f251;
	sub.ftz.f32 	%f757, %f756, %f931;
	mul.ftz.f32 	%f758, %f250, %f251;
	sub.ftz.f32 	%f759, %f758, %f932;
	add.ftz.f32 	%f760, %f756, %f931;
	add.ftz.f32 	%f761, %f758, %f932;
	mul.ftz.f32 	%f762, %f761, %f761;
	fma.rn.ftz.f32 	%f763, %f760, %f760, %f762;
	max.ftz.f32 	%f764, %f763, %f747;
	mul.ftz.f32 	%f765, %f759, %f761;
	fma.rn.ftz.f32 	%f766, %f757, %f760, %f765;
	div.approx.ftz.f32 	%f767, %f766, %f764;
	mul.ftz.f32 	%f768, %f759, %f760;
	mul.ftz.f32 	%f769, %f757, %f761;
	sub.ftz.f32 	%f770, %f768, %f769;
	div.approx.ftz.f32 	%f771, %f770, %f764;
	mul.ftz.f32 	%f937, %f248, %f767;
	mul.ftz.f32 	%f938, %f248, %f771;
	abs.ftz.f32 	%f772, %f939;
	setp.geu.ftz.f32 	%p92, %f772, 0f7F800000;
	@%p92 bra 	$L__BB2_71;

	abs.ftz.f32 	%f773, %f940;
	setp.lt.ftz.f32 	%p93, %f773, 0f7F800000;
	@%p93 bra 	$L__BB2_72;

$L__BB2_71:
	mov.f32 	%f939, 0f00000000;
	mov.f32 	%f940, %f939;

$L__BB2_72:
	abs.ftz.f32 	%f776, %f937;
	setp.geu.ftz.f32 	%p94, %f776, 0f7F800000;
	@%p94 bra 	$L__BB2_74;

	abs.ftz.f32 	%f777, %f938;
	setp.lt.ftz.f32 	%p95, %f777, 0f7F800000;
	@%p95 bra 	$L__BB2_75;

$L__BB2_74:
	mov.f32 	%f937, 0f00000000;
	mov.f32 	%f938, %f937;

$L__BB2_75:
	mul.ftz.f32 	%f780, %f940, %f940;
	fma.rn.ftz.f32 	%f781, %f939, %f939, %f780;
	setp.gt.ftz.f32 	%p96, %f781, 0f00000000;
	mov.u16 	%rs8, 1;
	@%p96 bra 	$L__BB2_77;

	mul.ftz.f32 	%f782, %f938, %f938;
	fma.rn.ftz.f32 	%f783, %f937, %f937, %f782;
	setp.gt.ftz.f32 	%p97, %f783, 0f00000000;
	selp.u16 	%rs8, 1, 0, %p97;

$L__BB2_77:
	setp.eq.s16 	%p98, %rs8, 0;
	mov.f32 	%f951, %f952;
	mov.f32 	%f950, %f952;
	mov.f32 	%f949, %f952;
	mov.f32 	%f948, %f952;
	mov.f32 	%f947, %f952;
	@%p98 bra 	$L__BB2_79;

	mul.ftz.f32 	%f790, %f905, %f923;
	fma.rn.ftz.f32 	%f791, %f903, %f922, %f790;
	mul.ftz.f32 	%f792, %f906, %f923;
	fma.rn.ftz.f32 	%f793, %f904, %f922, %f792;
	fma.rn.ftz.f32 	%f794, %f907, %f924, %f791;
	fma.rn.ftz.f32 	%f795, %f908, %f924, %f793;
	mul.ftz.f32 	%f796, %f905, %f926;
	mul.ftz.f32 	%f797, %f906, %f926;
	fma.rn.ftz.f32 	%f798, %f903, %f925, %f796;
	fma.rn.ftz.f32 	%f799, %f904, %f925, %f797;
	fma.rn.ftz.f32 	%f800, %f907, %f927, %f798;
	fma.rn.ftz.f32 	%f801, %f908, %f927, %f799;
	mul.ftz.f32 	%f802, %f794, %f939;
	mul.ftz.f32 	%f803, %f795, %f940;
	sub.ftz.f32 	%f804, %f802, %f803;
	mul.ftz.f32 	%f805, %f794, %f940;
	fma.rn.ftz.f32 	%f806, %f795, %f939, %f805;
	mul.ftz.f32 	%f807, %f922, %f804;
	mul.ftz.f32 	%f808, %f922, %f806;
	mul.ftz.f32 	%f809, %f923, %f804;
	mul.ftz.f32 	%f810, %f923, %f806;
	mul.ftz.f32 	%f811, %f924, %f804;
	mul.ftz.f32 	%f812, %f924, %f806;
	mul.ftz.f32 	%f813, %f800, %f937;
	mul.ftz.f32 	%f814, %f801, %f938;
	sub.ftz.f32 	%f815, %f813, %f814;
	mul.ftz.f32 	%f816, %f800, %f938;
	fma.rn.ftz.f32 	%f817, %f801, %f937, %f816;
	fma.rn.ftz.f32 	%f947, %f930, %f817, %f812;
	fma.rn.ftz.f32 	%f948, %f930, %f815, %f811;
	fma.rn.ftz.f32 	%f949, %f929, %f817, %f810;
	fma.rn.ftz.f32 	%f950, %f929, %f815, %f809;
	fma.rn.ftz.f32 	%f951, %f928, %f817, %f808;
	fma.rn.ftz.f32 	%f952, %f928, %f815, %f807;

$L__BB2_79:
	mul.ftz.f32 	%f818, %f951, %f951;
	fma.rn.ftz.f32 	%f819, %f952, %f952, %f818;
	mul.ftz.f32 	%f820, %f949, %f949;
	fma.rn.ftz.f32 	%f821, %f950, %f950, %f820;
	add.ftz.f32 	%f822, %f819, %f821;
	mul.ftz.f32 	%f823, %f947, %f947;
	fma.rn.ftz.f32 	%f824, %f948, %f948, %f823;
	add.ftz.f32 	%f289, %f824, %f822;
	setp.le.ftz.f32 	%p99, %f289, 0f00000000;
	@%p99 bra 	$L__BB2_88;

	setp.ne.s32 	%p113, %r294, 0;
	setp.eq.s32 	%p101, %r105, 0;
	and.pred  	%p102, %p113, %p101;
	or.pred  	%p103, %p2, %p102;
	@%p103 bra 	$L__BB2_83;

	atom.global.add.u32 	%r82, [%rd26], 1;
	setp.lt.s32 	%p104, %r82, 0;
	setp.ge.s32 	%p105, %r82, %r106;
	or.pred  	%p106, %p104, %p105;
	@%p106 bra 	$L__BB2_83;

	mul.wide.s32 	%rd159, %r82, 4;
	add.s64 	%rd160, %rd27, %rd159;
	st.global.u32 	[%rd160], %r84;
	add.s64 	%rd161, %rd28, %rd159;
	st.global.f32 	[%rd161], %f916;
	add.s64 	%rd162, %rd29, %rd159;
	st.global.f32 	[%rd162], %f917;
	add.s64 	%rd163, %rd30, %rd159;
	st.global.f32 	[%rd163], %f918;
	add.s64 	%rd164, %rd31, %rd159;
	st.global.f32 	[%rd164], %f146;
	add.s64 	%rd165, %rd32, %rd159;
	st.global.f32 	[%rd165], %f145;
	add.s64 	%rd166, %rd33, %rd159;
	st.global.f32 	[%rd166], %f144;
	add.s64 	%rd167, %rd34, %rd159;
	st.global.u32 	[%rd167], %r81;
	add.s64 	%rd168, %rd35, %rd159;
	st.global.f32 	[%rd168], %f897;
	add.s64 	%rd169, %rd36, %rd159;
	st.global.f32 	[%rd169], %f898;
	add.s64 	%rd170, %rd37, %rd159;
	st.global.f32 	[%rd170], %f899;
	add.s64 	%rd171, %rd38, %rd159;
	st.global.u32 	[%rd171], %r294;

$L__BB2_83:
	sub.ftz.f32 	%f825, %f894, %f916;
	sub.ftz.f32 	%f826, %f895, %f917;
	sub.ftz.f32 	%f827, %f896, %f918;
	mul.ftz.f32 	%f828, %f826, %f145;
	fma.rn.ftz.f32 	%f829, %f825, %f146, %f828;
	fma.rn.ftz.f32 	%f830, %f827, %f144, %f829;
	add.ftz.f32 	%f831, %f830, %f830;
	mul.ftz.f32 	%f832, %f146, %f831;
	mul.ftz.f32 	%f833, %f145, %f831;
	mul.ftz.f32 	%f834, %f144, %f831;
	sub.ftz.f32 	%f896, %f896, %f834;
	sub.ftz.f32 	%f895, %f895, %f833;
	sub.ftz.f32 	%f894, %f894, %f832;
	add.ftz.f32 	%f893, %f893, %f85;
	fma.rn.ftz.f32 	%f902, %f899, 0f3727C5AC, %f918;
	fma.rn.ftz.f32 	%f901, %f898, 0f3727C5AC, %f917;
	fma.rn.ftz.f32 	%f900, %f897, 0f3727C5AC, %f916;
	add.s32 	%r294, %r294, 1;
	setp.lt.s32 	%p107, %r294, %r102;
	or.pred  	%p108, %p107, %p3;
	@%p108 bra 	$L__BB2_86;

	mov.b32 	%f885, %r103;
	mov.f32 	%f835, 0f322BCC77;
	max.ftz.f32 	%f836, %f289, %f835;
	max.ftz.f32 	%f837, %f885, %f835;
	min.ftz.f32 	%f303, %f836, %f837;
	mul.lo.s32 	%r277, %r294, -1640531527;
	xor.b32  	%r278, %r277, %r84;
	xor.b32  	%r279, %r278, %r100;
	shr.u32 	%r280, %r279, 16;
	xor.b32  	%r281, %r280, %r279;
	mul.lo.s32 	%r282, %r281, 2146121005;
	shr.u32 	%r283, %r282, 15;
	xor.b32  	%r284, %r283, %r282;
	mul.lo.s32 	%r285, %r284, -2073254261;
	shr.u32 	%r286, %r285, 16;
	and.b32  	%r287, %r285, 16777215;
	xor.b32  	%r288, %r286, %r287;
	cvt.rn.f32.u32 	%f838, %r288;
	mul.ftz.f32 	%f839, %f838, 0f33800000;
	setp.ge.ftz.f32 	%p109, %f839, %f303;
	@%p109 bra 	$L__BB2_88;

	max.ftz.f32 	%f841, %f303, %f835;
	rsqrt.approx.ftz.f32 	%f842, %f841;
	mul.ftz.f32 	%f952, %f952, %f842;
	mul.ftz.f32 	%f951, %f951, %f842;
	mul.ftz.f32 	%f950, %f950, %f842;
	mul.ftz.f32 	%f949, %f949, %f842;
	mul.ftz.f32 	%f948, %f948, %f842;
	mul.ftz.f32 	%f947, %f947, %f842;

$L__BB2_86:
	setp.leu.ftz.f32 	%p110, %f48, 0f00000000;
	mov.f32 	%f903, %f952;
	mov.f32 	%f904, %f951;
	mov.f32 	%f905, %f950;
	mov.f32 	%f906, %f949;
	mov.f32 	%f907, %f948;
	mov.f32 	%f908, %f947;
	@%p110 bra 	$L__BB2_10;

	mov.f32 	%f843, 0f358637BD;
	max.ftz.f32 	%f844, %f893, %f843;
	mul.ftz.f32 	%f845, %f844, 0f41490FDB;
	div.approx.ftz.f32 	%f846, %f61, %f845;
	mul.ftz.f32 	%f847, %f952, %f952;
	fma.rn.ftz.f32 	%f848, %f951, %f951, %f847;
	mul.ftz.f32 	%f849, %f950, %f950;
	fma.rn.ftz.f32 	%f850, %f949, %f949, %f849;
	add.ftz.f32 	%f851, %f850, %f848;
	mul.ftz.f32 	%f852, %f948, %f948;
	fma.rn.ftz.f32 	%f853, %f947, %f947, %f852;
	add.ftz.f32 	%f854, %f853, %f851;
	mul.ftz.f32 	%f855, %f854, %f846;
	mul.ftz.f32 	%f856, %f846, %f855;
	setp.gtu.ftz.f32 	%p111, %f856, %f48;
	mov.f32 	%f903, %f952;
	mov.f32 	%f904, %f951;
	mov.f32 	%f905, %f950;
	mov.f32 	%f906, %f949;
	mov.f32 	%f907, %f948;
	mov.f32 	%f908, %f947;
	@%p111 bra 	$L__BB2_10;

$L__BB2_88:
	ret;

}

)PTX_CHUNK"
;
static const size_t reflection_accumulation_ptx_size = 43946;
